swizzle_type<0, 0>& xx() noexcept { return *reinterpret_cast<swizzle_type<0, 0>*>(addressof(x)); };
swizzle_type<0, 1>& xy() noexcept { return *reinterpret_cast<swizzle_type<0, 1>*>(addressof(x)); };
swizzle_type<0, 2>& xz() noexcept { return *reinterpret_cast<swizzle_type<0, 2>*>(addressof(x)); };
swizzle_type<1, 0>& yx() noexcept { return *reinterpret_cast<swizzle_type<1, 0>*>(addressof(x)); };
swizzle_type<1, 1>& yy() noexcept { return *reinterpret_cast<swizzle_type<1, 1>*>(addressof(x)); };
swizzle_type<1, 2>& yz() noexcept { return *reinterpret_cast<swizzle_type<1, 2>*>(addressof(x)); };
swizzle_type<2, 0>& zx() noexcept { return *reinterpret_cast<swizzle_type<2, 0>*>(addressof(x)); };
swizzle_type<2, 1>& zy() noexcept { return *reinterpret_cast<swizzle_type<2, 1>*>(addressof(x)); };
swizzle_type<2, 2>& zz() noexcept { return *reinterpret_cast<swizzle_type<2, 2>*>(addressof(x)); };
auto xx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0>*>(addressof(x))); };
auto xy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1>*>(addressof(x))); };
auto xz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2>*>(addressof(x))); };
auto yx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0>*>(addressof(x))); };
auto yy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1>*>(addressof(x))); };
auto yz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2>*>(addressof(x))); };
auto zx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0>*>(addressof(x))); };
auto zy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1>*>(addressof(x))); };
auto zz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2>*>(addressof(x))); };

swizzle_type<0, 0, 0>& xxx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1>& xxy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 0, 2>& xxz() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2>*>(addressof(x)); };
swizzle_type<0, 1, 0>& xyx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1>& xyy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1>*>(addressof(x)); };
swizzle_type<0, 1, 2>& xyz() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2>*>(addressof(x)); };
swizzle_type<0, 2, 0>& xzx() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0>*>(addressof(x)); };
swizzle_type<0, 2, 1>& xzy() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1>*>(addressof(x)); };
swizzle_type<0, 2, 2>& xzz() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2>*>(addressof(x)); };
swizzle_type<1, 0, 0>& yxx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1>& yxy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 0, 2>& yxz() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2>*>(addressof(x)); };
swizzle_type<1, 1, 0>& yyx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1>& yyy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1>*>(addressof(x)); };
swizzle_type<1, 1, 2>& yyz() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2>*>(addressof(x)); };
swizzle_type<1, 2, 0>& yzx() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0>*>(addressof(x)); };
swizzle_type<1, 2, 1>& yzy() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1>*>(addressof(x)); };
swizzle_type<1, 2, 2>& yzz() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2>*>(addressof(x)); };
swizzle_type<2, 0, 0>& zxx() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0>*>(addressof(x)); };
swizzle_type<2, 0, 1>& zxy() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1>*>(addressof(x)); };
swizzle_type<2, 0, 2>& zxz() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2>*>(addressof(x)); };
swizzle_type<2, 1, 0>& zyx() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0>*>(addressof(x)); };
swizzle_type<2, 1, 1>& zyy() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1>*>(addressof(x)); };
swizzle_type<2, 1, 2>& zyz() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2>*>(addressof(x)); };
swizzle_type<2, 2, 0>& zzx() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0>*>(addressof(x)); };
swizzle_type<2, 2, 1>& zzy() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1>*>(addressof(x)); };
swizzle_type<2, 2, 2>& zzz() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2>*>(addressof(x)); };
auto xxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0>*>(addressof(x))); };
auto xxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1>*>(addressof(x))); };
auto xxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2>*>(addressof(x))); };
auto xyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0>*>(addressof(x))); };
auto xyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1>*>(addressof(x))); };
auto xyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2>*>(addressof(x))); };
auto xzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0>*>(addressof(x))); };
auto xzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1>*>(addressof(x))); };
auto xzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2>*>(addressof(x))); };
auto yxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0>*>(addressof(x))); };
auto yxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1>*>(addressof(x))); };
auto yxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2>*>(addressof(x))); };
auto yyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0>*>(addressof(x))); };
auto yyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1>*>(addressof(x))); };
auto yyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2>*>(addressof(x))); };
auto yzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0>*>(addressof(x))); };
auto yzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1>*>(addressof(x))); };
auto yzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2>*>(addressof(x))); };
auto zxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0>*>(addressof(x))); };
auto zxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1>*>(addressof(x))); };
auto zxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2>*>(addressof(x))); };
auto zyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0>*>(addressof(x))); };
auto zyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1>*>(addressof(x))); };
auto zyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2>*>(addressof(x))); };
auto zzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0>*>(addressof(x))); };
auto zzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1>*>(addressof(x))); };
auto zzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2>*>(addressof(x))); };

swizzle_type<0, 0, 0, 0>& xxxx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 0, 1>& xxxy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 0, 0, 2>& xxxz() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 2>*>(addressof(x)); };
swizzle_type<0, 0, 1, 0>& xxyx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1, 1>& xxyy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 1>*>(addressof(x)); };
swizzle_type<0, 0, 1, 2>& xxyz() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 2>*>(addressof(x)); };
swizzle_type<0, 0, 2, 0>& xxzx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 0>*>(addressof(x)); };
swizzle_type<0, 0, 2, 1>& xxzy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 1>*>(addressof(x)); };
swizzle_type<0, 0, 2, 2>& xxzz() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 2>*>(addressof(x)); };
swizzle_type<0, 1, 0, 0>& xyxx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 0>*>(addressof(x)); };
swizzle_type<0, 1, 0, 1>& xyxy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 1>*>(addressof(x)); };
swizzle_type<0, 1, 0, 2>& xyxz() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 2>*>(addressof(x)); };
swizzle_type<0, 1, 1, 0>& xyyx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1, 1>& xyyy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 1>*>(addressof(x)); };
swizzle_type<0, 1, 1, 2>& xyyz() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 2>*>(addressof(x)); };
swizzle_type<0, 1, 2, 0>& xyzx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 0>*>(addressof(x)); };
swizzle_type<0, 1, 2, 1>& xyzy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 1>*>(addressof(x)); };
swizzle_type<0, 1, 2, 2>& xyzz() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 2>*>(addressof(x)); };
swizzle_type<0, 2, 0, 0>& xzxx() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 0>*>(addressof(x)); };
swizzle_type<0, 2, 0, 1>& xzxy() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 1>*>(addressof(x)); };
swizzle_type<0, 2, 0, 2>& xzxz() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 2>*>(addressof(x)); };
swizzle_type<0, 2, 1, 0>& xzyx() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 0>*>(addressof(x)); };
swizzle_type<0, 2, 1, 1>& xzyy() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 1>*>(addressof(x)); };
swizzle_type<0, 2, 1, 2>& xzyz() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 2>*>(addressof(x)); };
swizzle_type<0, 2, 2, 0>& xzzx() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 0>*>(addressof(x)); };
swizzle_type<0, 2, 2, 1>& xzzy() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 1>*>(addressof(x)); };
swizzle_type<0, 2, 2, 2>& xzzz() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 2>*>(addressof(x)); };
swizzle_type<1, 0, 0, 0>& yxxx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 0, 1>& yxxy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 1>*>(addressof(x)); };
swizzle_type<1, 0, 0, 2>& yxxz() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 2>*>(addressof(x)); };
swizzle_type<1, 0, 1, 0>& yxyx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1, 1>& yxyy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 1>*>(addressof(x)); };
swizzle_type<1, 0, 1, 2>& yxyz() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 2>*>(addressof(x)); };
swizzle_type<1, 0, 2, 0>& yxzx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 0>*>(addressof(x)); };
swizzle_type<1, 0, 2, 1>& yxzy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 1>*>(addressof(x)); };
swizzle_type<1, 0, 2, 2>& yxzz() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 2>*>(addressof(x)); };
swizzle_type<1, 1, 0, 0>& yyxx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 1, 0, 1>& yyxy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 1, 0, 2>& yyxz() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 2>*>(addressof(x)); };
swizzle_type<1, 1, 1, 0>& yyyx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1, 1>& yyyy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 1>*>(addressof(x)); };
swizzle_type<1, 1, 1, 2>& yyyz() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 2>*>(addressof(x)); };
swizzle_type<1, 1, 2, 0>& yyzx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 0>*>(addressof(x)); };
swizzle_type<1, 1, 2, 1>& yyzy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 1>*>(addressof(x)); };
swizzle_type<1, 1, 2, 2>& yyzz() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 2>*>(addressof(x)); };
swizzle_type<1, 2, 0, 0>& yzxx() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 0>*>(addressof(x)); };
swizzle_type<1, 2, 0, 1>& yzxy() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 1>*>(addressof(x)); };
swizzle_type<1, 2, 0, 2>& yzxz() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 2>*>(addressof(x)); };
swizzle_type<1, 2, 1, 0>& yzyx() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 0>*>(addressof(x)); };
swizzle_type<1, 2, 1, 1>& yzyy() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 1>*>(addressof(x)); };
swizzle_type<1, 2, 1, 2>& yzyz() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 2>*>(addressof(x)); };
swizzle_type<1, 2, 2, 0>& yzzx() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 0>*>(addressof(x)); };
swizzle_type<1, 2, 2, 1>& yzzy() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 1>*>(addressof(x)); };
swizzle_type<1, 2, 2, 2>& yzzz() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 2>*>(addressof(x)); };
swizzle_type<2, 0, 0, 0>& zxxx() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 0>*>(addressof(x)); };
swizzle_type<2, 0, 0, 1>& zxxy() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 1>*>(addressof(x)); };
swizzle_type<2, 0, 0, 2>& zxxz() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 2>*>(addressof(x)); };
swizzle_type<2, 0, 1, 0>& zxyx() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 0>*>(addressof(x)); };
swizzle_type<2, 0, 1, 1>& zxyy() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 1>*>(addressof(x)); };
swizzle_type<2, 0, 1, 2>& zxyz() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 2>*>(addressof(x)); };
swizzle_type<2, 0, 2, 0>& zxzx() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 0>*>(addressof(x)); };
swizzle_type<2, 0, 2, 1>& zxzy() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 1>*>(addressof(x)); };
swizzle_type<2, 0, 2, 2>& zxzz() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 2>*>(addressof(x)); };
swizzle_type<2, 1, 0, 0>& zyxx() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 0>*>(addressof(x)); };
swizzle_type<2, 1, 0, 1>& zyxy() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 1>*>(addressof(x)); };
swizzle_type<2, 1, 0, 2>& zyxz() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 2>*>(addressof(x)); };
swizzle_type<2, 1, 1, 0>& zyyx() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 0>*>(addressof(x)); };
swizzle_type<2, 1, 1, 1>& zyyy() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 1>*>(addressof(x)); };
swizzle_type<2, 1, 1, 2>& zyyz() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 2>*>(addressof(x)); };
swizzle_type<2, 1, 2, 0>& zyzx() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 0>*>(addressof(x)); };
swizzle_type<2, 1, 2, 1>& zyzy() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 1>*>(addressof(x)); };
swizzle_type<2, 1, 2, 2>& zyzz() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 2>*>(addressof(x)); };
swizzle_type<2, 2, 0, 0>& zzxx() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 0>*>(addressof(x)); };
swizzle_type<2, 2, 0, 1>& zzxy() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 1>*>(addressof(x)); };
swizzle_type<2, 2, 0, 2>& zzxz() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 2>*>(addressof(x)); };
swizzle_type<2, 2, 1, 0>& zzyx() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 0>*>(addressof(x)); };
swizzle_type<2, 2, 1, 1>& zzyy() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 1>*>(addressof(x)); };
swizzle_type<2, 2, 1, 2>& zzyz() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 2>*>(addressof(x)); };
swizzle_type<2, 2, 2, 0>& zzzx() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 0>*>(addressof(x)); };
swizzle_type<2, 2, 2, 1>& zzzy() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 1>*>(addressof(x)); };
swizzle_type<2, 2, 2, 2>& zzzz() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 2>*>(addressof(x)); };
auto xxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 0>*>(addressof(x))); };
auto xxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 1>*>(addressof(x))); };
auto xxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 2>*>(addressof(x))); };
auto xxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 0>*>(addressof(x))); };
auto xxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 1>*>(addressof(x))); };
auto xxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 2>*>(addressof(x))); };
auto xxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 0>*>(addressof(x))); };
auto xxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 1>*>(addressof(x))); };
auto xxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 2>*>(addressof(x))); };
auto xyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 0>*>(addressof(x))); };
auto xyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 1>*>(addressof(x))); };
auto xyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 2>*>(addressof(x))); };
auto xyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 0>*>(addressof(x))); };
auto xyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 1>*>(addressof(x))); };
auto xyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 2>*>(addressof(x))); };
auto xyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 0>*>(addressof(x))); };
auto xyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 1>*>(addressof(x))); };
auto xyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 2>*>(addressof(x))); };
auto xzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 0>*>(addressof(x))); };
auto xzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 1>*>(addressof(x))); };
auto xzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 2>*>(addressof(x))); };
auto xzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 0>*>(addressof(x))); };
auto xzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 1>*>(addressof(x))); };
auto xzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 2>*>(addressof(x))); };
auto xzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 0>*>(addressof(x))); };
auto xzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 1>*>(addressof(x))); };
auto xzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 2>*>(addressof(x))); };
auto yxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 0>*>(addressof(x))); };
auto yxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 1>*>(addressof(x))); };
auto yxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 2>*>(addressof(x))); };
auto yxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 0>*>(addressof(x))); };
auto yxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 1>*>(addressof(x))); };
auto yxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 2>*>(addressof(x))); };
auto yxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 0>*>(addressof(x))); };
auto yxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 1>*>(addressof(x))); };
auto yxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 2>*>(addressof(x))); };
auto yyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 0>*>(addressof(x))); };
auto yyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 1>*>(addressof(x))); };
auto yyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 2>*>(addressof(x))); };
auto yyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 0>*>(addressof(x))); };
auto yyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 1>*>(addressof(x))); };
auto yyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 2>*>(addressof(x))); };
auto yyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 0>*>(addressof(x))); };
auto yyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 1>*>(addressof(x))); };
auto yyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 2>*>(addressof(x))); };
auto yzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 0>*>(addressof(x))); };
auto yzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 1>*>(addressof(x))); };
auto yzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 2>*>(addressof(x))); };
auto yzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 0>*>(addressof(x))); };
auto yzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 1>*>(addressof(x))); };
auto yzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 2>*>(addressof(x))); };
auto yzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 0>*>(addressof(x))); };
auto yzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 1>*>(addressof(x))); };
auto yzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 2>*>(addressof(x))); };
auto zxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 0>*>(addressof(x))); };
auto zxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 1>*>(addressof(x))); };
auto zxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 2>*>(addressof(x))); };
auto zxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 0>*>(addressof(x))); };
auto zxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 1>*>(addressof(x))); };
auto zxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 2>*>(addressof(x))); };
auto zxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 0>*>(addressof(x))); };
auto zxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 1>*>(addressof(x))); };
auto zxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 2>*>(addressof(x))); };
auto zyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 0>*>(addressof(x))); };
auto zyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 1>*>(addressof(x))); };
auto zyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 2>*>(addressof(x))); };
auto zyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 0>*>(addressof(x))); };
auto zyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 1>*>(addressof(x))); };
auto zyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 2>*>(addressof(x))); };
auto zyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 0>*>(addressof(x))); };
auto zyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 1>*>(addressof(x))); };
auto zyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 2>*>(addressof(x))); };
auto zzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 0>*>(addressof(x))); };
auto zzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 1>*>(addressof(x))); };
auto zzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 2>*>(addressof(x))); };
auto zzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 0>*>(addressof(x))); };
auto zzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 1>*>(addressof(x))); };
auto zzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 2>*>(addressof(x))); };
auto zzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 0>*>(addressof(x))); };
auto zzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 1>*>(addressof(x))); };
auto zzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 2>*>(addressof(x))); };
