swizzle_type<0, 0>& xx() noexcept { return *reinterpret_cast<swizzle_type<0, 0>*>(addressof(x)); };
swizzle_type<0, 1>& xy() noexcept { return *reinterpret_cast<swizzle_type<0, 1>*>(addressof(x)); };
swizzle_type<1, 0>& yx() noexcept { return *reinterpret_cast<swizzle_type<1, 0>*>(addressof(x)); };
swizzle_type<1, 1>& yy() noexcept { return *reinterpret_cast<swizzle_type<1, 1>*>(addressof(x)); };
auto xx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0>*>(addressof(x))); };
auto xy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1>*>(addressof(x))); };
auto yx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0>*>(addressof(x))); };
auto yy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1>*>(addressof(x))); };

swizzle_type<0, 0, 0>& xxx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1>& xxy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 1, 0>& xyx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1>& xyy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1>*>(addressof(x)); };
swizzle_type<1, 0, 0>& yxx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1>& yxy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 1, 0>& yyx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1>& yyy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1>*>(addressof(x)); };
auto xxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0>*>(addressof(x))); };
auto xxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1>*>(addressof(x))); };
auto xyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0>*>(addressof(x))); };
auto xyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1>*>(addressof(x))); };
auto yxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0>*>(addressof(x))); };
auto yxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1>*>(addressof(x))); };
auto yyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0>*>(addressof(x))); };
auto yyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1>*>(addressof(x))); };

swizzle_type<0, 0, 0, 0>& xxxx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 0, 1>& xxxy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 0, 1, 0>& xxyx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1, 1>& xxyy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 1>*>(addressof(x)); };
swizzle_type<0, 1, 0, 0>& xyxx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 0>*>(addressof(x)); };
swizzle_type<0, 1, 0, 1>& xyxy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 1>*>(addressof(x)); };
swizzle_type<0, 1, 1, 0>& xyyx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1, 1>& xyyy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 1>*>(addressof(x)); };
swizzle_type<1, 0, 0, 0>& yxxx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 0, 1>& yxxy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 1>*>(addressof(x)); };
swizzle_type<1, 0, 1, 0>& yxyx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1, 1>& yxyy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 1>*>(addressof(x)); };
swizzle_type<1, 1, 0, 0>& yyxx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 1, 0, 1>& yyxy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 1, 1, 0>& yyyx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1, 1>& yyyy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 1>*>(addressof(x)); };
auto xxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 0>*>(addressof(x))); };
auto xxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 1>*>(addressof(x))); };
auto xxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 0>*>(addressof(x))); };
auto xxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 1>*>(addressof(x))); };
auto xyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 0>*>(addressof(x))); };
auto xyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 1>*>(addressof(x))); };
auto xyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 0>*>(addressof(x))); };
auto xyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 1>*>(addressof(x))); };
auto yxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 0>*>(addressof(x))); };
auto yxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 1>*>(addressof(x))); };
auto yxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 0>*>(addressof(x))); };
auto yxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 1>*>(addressof(x))); };
auto yyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 0>*>(addressof(x))); };
auto yyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 1>*>(addressof(x))); };
auto yyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 0>*>(addressof(x))); };
auto yyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 1>*>(addressof(x))); };
