swizzle_type<0, 0>& xx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0>*>(addressof(x)); };
swizzle_type<0, 1>& xy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1>*>(addressof(x)); };
swizzle_type<0, 2>& xz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2>*>(addressof(x)); };
swizzle_type<1, 0>& yx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0>*>(addressof(x)); };
swizzle_type<1, 1>& yy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1>*>(addressof(x)); };
swizzle_type<1, 2>& yz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2>*>(addressof(x)); };
swizzle_type<2, 0>& zx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0>*>(addressof(x)); };
swizzle_type<2, 1>& zy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1>*>(addressof(x)); };
swizzle_type<2, 2>& zz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2>*>(addressof(x)); };
auto xx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0>*>(addressof(x))).decay(); };
auto xy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1>*>(addressof(x))).decay(); };
auto xz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2>*>(addressof(x))).decay(); };
auto yx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0>*>(addressof(x))).decay(); };
auto yy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1>*>(addressof(x))).decay(); };
auto yz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2>*>(addressof(x))).decay(); };
auto zx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0>*>(addressof(x))).decay(); };
auto zy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1>*>(addressof(x))).decay(); };
auto zz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2>*>(addressof(x))).decay(); };

swizzle_type<0, 0, 0>& xxx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1>& xxy_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 0, 2>& xxz_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2>*>(addressof(x)); };
swizzle_type<0, 1, 0>& xyx_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1>& xyy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1>*>(addressof(x)); };
swizzle_type<0, 1, 2>& xyz_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2>*>(addressof(x)); };
swizzle_type<0, 2, 0>& xzx_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0>*>(addressof(x)); };
swizzle_type<0, 2, 1>& xzy_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1>*>(addressof(x)); };
swizzle_type<0, 2, 2>& xzz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2>*>(addressof(x)); };
swizzle_type<1, 0, 0>& yxx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1>& yxy_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 0, 2>& yxz_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2>*>(addressof(x)); };
swizzle_type<1, 1, 0>& yyx_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1>& yyy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1>*>(addressof(x)); };
swizzle_type<1, 1, 2>& yyz_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2>*>(addressof(x)); };
swizzle_type<1, 2, 0>& yzx_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0>*>(addressof(x)); };
swizzle_type<1, 2, 1>& yzy_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1>*>(addressof(x)); };
swizzle_type<1, 2, 2>& yzz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2>*>(addressof(x)); };
swizzle_type<2, 0, 0>& zxx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0>*>(addressof(x)); };
swizzle_type<2, 0, 1>& zxy_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1>*>(addressof(x)); };
swizzle_type<2, 0, 2>& zxz_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2>*>(addressof(x)); };
swizzle_type<2, 1, 0>& zyx_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0>*>(addressof(x)); };
swizzle_type<2, 1, 1>& zyy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1>*>(addressof(x)); };
swizzle_type<2, 1, 2>& zyz_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2>*>(addressof(x)); };
swizzle_type<2, 2, 0>& zzx_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0>*>(addressof(x)); };
swizzle_type<2, 2, 1>& zzy_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1>*>(addressof(x)); };
swizzle_type<2, 2, 2>& zzz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2>*>(addressof(x)); };
auto xxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0>*>(addressof(x))).decay(); };
auto xxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1>*>(addressof(x))).decay(); };
auto xxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2>*>(addressof(x))).decay(); };
auto xyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0>*>(addressof(x))).decay(); };
auto xyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1>*>(addressof(x))).decay(); };
auto xyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2>*>(addressof(x))).decay(); };
auto xzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0>*>(addressof(x))).decay(); };
auto xzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1>*>(addressof(x))).decay(); };
auto xzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2>*>(addressof(x))).decay(); };
auto yxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0>*>(addressof(x))).decay(); };
auto yxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1>*>(addressof(x))).decay(); };
auto yxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2>*>(addressof(x))).decay(); };
auto yyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0>*>(addressof(x))).decay(); };
auto yyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1>*>(addressof(x))).decay(); };
auto yyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2>*>(addressof(x))).decay(); };
auto yzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0>*>(addressof(x))).decay(); };
auto yzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1>*>(addressof(x))).decay(); };
auto yzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2>*>(addressof(x))).decay(); };
auto zxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0>*>(addressof(x))).decay(); };
auto zxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1>*>(addressof(x))).decay(); };
auto zxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2>*>(addressof(x))).decay(); };
auto zyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0>*>(addressof(x))).decay(); };
auto zyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1>*>(addressof(x))).decay(); };
auto zyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2>*>(addressof(x))).decay(); };
auto zzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0>*>(addressof(x))).decay(); };
auto zzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1>*>(addressof(x))).decay(); };
auto zzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2>*>(addressof(x))).decay(); };

swizzle_type<0, 0, 0, 0>& xxxx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 0, 1>& xxxy_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 0, 0, 2>& xxxz_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 2>*>(addressof(x)); };
swizzle_type<0, 0, 1, 0>& xxyx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1, 1>& xxyy_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 1>*>(addressof(x)); };
swizzle_type<0, 0, 1, 2>& xxyz_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 2>*>(addressof(x)); };
swizzle_type<0, 0, 2, 0>& xxzx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 0>*>(addressof(x)); };
swizzle_type<0, 0, 2, 1>& xxzy_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 1>*>(addressof(x)); };
swizzle_type<0, 0, 2, 2>& xxzz_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 2>*>(addressof(x)); };
swizzle_type<0, 1, 0, 0>& xyxx_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 0>*>(addressof(x)); };
swizzle_type<0, 1, 0, 1>& xyxy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 1>*>(addressof(x)); };
swizzle_type<0, 1, 0, 2>& xyxz_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 2>*>(addressof(x)); };
swizzle_type<0, 1, 1, 0>& xyyx_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1, 1>& xyyy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 1>*>(addressof(x)); };
swizzle_type<0, 1, 1, 2>& xyyz_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 2>*>(addressof(x)); };
swizzle_type<0, 1, 2, 0>& xyzx_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 0>*>(addressof(x)); };
swizzle_type<0, 1, 2, 1>& xyzy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 1>*>(addressof(x)); };
swizzle_type<0, 1, 2, 2>& xyzz_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 2>*>(addressof(x)); };
swizzle_type<0, 2, 0, 0>& xzxx_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 0>*>(addressof(x)); };
swizzle_type<0, 2, 0, 1>& xzxy_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 1>*>(addressof(x)); };
swizzle_type<0, 2, 0, 2>& xzxz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 2>*>(addressof(x)); };
swizzle_type<0, 2, 1, 0>& xzyx_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 0>*>(addressof(x)); };
swizzle_type<0, 2, 1, 1>& xzyy_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 1>*>(addressof(x)); };
swizzle_type<0, 2, 1, 2>& xzyz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 2>*>(addressof(x)); };
swizzle_type<0, 2, 2, 0>& xzzx_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 0>*>(addressof(x)); };
swizzle_type<0, 2, 2, 1>& xzzy_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 1>*>(addressof(x)); };
swizzle_type<0, 2, 2, 2>& xzzz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 2>*>(addressof(x)); };
swizzle_type<1, 0, 0, 0>& yxxx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 0, 1>& yxxy_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 1>*>(addressof(x)); };
swizzle_type<1, 0, 0, 2>& yxxz_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 2>*>(addressof(x)); };
swizzle_type<1, 0, 1, 0>& yxyx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1, 1>& yxyy_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 1>*>(addressof(x)); };
swizzle_type<1, 0, 1, 2>& yxyz_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 2>*>(addressof(x)); };
swizzle_type<1, 0, 2, 0>& yxzx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 0>*>(addressof(x)); };
swizzle_type<1, 0, 2, 1>& yxzy_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 1>*>(addressof(x)); };
swizzle_type<1, 0, 2, 2>& yxzz_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 2>*>(addressof(x)); };
swizzle_type<1, 1, 0, 0>& yyxx_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 1, 0, 1>& yyxy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 1, 0, 2>& yyxz_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 2>*>(addressof(x)); };
swizzle_type<1, 1, 1, 0>& yyyx_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1, 1>& yyyy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 1>*>(addressof(x)); };
swizzle_type<1, 1, 1, 2>& yyyz_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 2>*>(addressof(x)); };
swizzle_type<1, 1, 2, 0>& yyzx_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 0>*>(addressof(x)); };
swizzle_type<1, 1, 2, 1>& yyzy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 1>*>(addressof(x)); };
swizzle_type<1, 1, 2, 2>& yyzz_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 2>*>(addressof(x)); };
swizzle_type<1, 2, 0, 0>& yzxx_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 0>*>(addressof(x)); };
swizzle_type<1, 2, 0, 1>& yzxy_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 1>*>(addressof(x)); };
swizzle_type<1, 2, 0, 2>& yzxz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 2>*>(addressof(x)); };
swizzle_type<1, 2, 1, 0>& yzyx_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 0>*>(addressof(x)); };
swizzle_type<1, 2, 1, 1>& yzyy_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 1>*>(addressof(x)); };
swizzle_type<1, 2, 1, 2>& yzyz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 2>*>(addressof(x)); };
swizzle_type<1, 2, 2, 0>& yzzx_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 0>*>(addressof(x)); };
swizzle_type<1, 2, 2, 1>& yzzy_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 1>*>(addressof(x)); };
swizzle_type<1, 2, 2, 2>& yzzz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 2>*>(addressof(x)); };
swizzle_type<2, 0, 0, 0>& zxxx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 0>*>(addressof(x)); };
swizzle_type<2, 0, 0, 1>& zxxy_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 1>*>(addressof(x)); };
swizzle_type<2, 0, 0, 2>& zxxz_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 2>*>(addressof(x)); };
swizzle_type<2, 0, 1, 0>& zxyx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 0>*>(addressof(x)); };
swizzle_type<2, 0, 1, 1>& zxyy_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 1>*>(addressof(x)); };
swizzle_type<2, 0, 1, 2>& zxyz_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 2>*>(addressof(x)); };
swizzle_type<2, 0, 2, 0>& zxzx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 0>*>(addressof(x)); };
swizzle_type<2, 0, 2, 1>& zxzy_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 1>*>(addressof(x)); };
swizzle_type<2, 0, 2, 2>& zxzz_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 2>*>(addressof(x)); };
swizzle_type<2, 1, 0, 0>& zyxx_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 0>*>(addressof(x)); };
swizzle_type<2, 1, 0, 1>& zyxy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 1>*>(addressof(x)); };
swizzle_type<2, 1, 0, 2>& zyxz_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 2>*>(addressof(x)); };
swizzle_type<2, 1, 1, 0>& zyyx_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 0>*>(addressof(x)); };
swizzle_type<2, 1, 1, 1>& zyyy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 1>*>(addressof(x)); };
swizzle_type<2, 1, 1, 2>& zyyz_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 2>*>(addressof(x)); };
swizzle_type<2, 1, 2, 0>& zyzx_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 0>*>(addressof(x)); };
swizzle_type<2, 1, 2, 1>& zyzy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 1>*>(addressof(x)); };
swizzle_type<2, 1, 2, 2>& zyzz_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 2>*>(addressof(x)); };
swizzle_type<2, 2, 0, 0>& zzxx_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 0>*>(addressof(x)); };
swizzle_type<2, 2, 0, 1>& zzxy_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 1>*>(addressof(x)); };
swizzle_type<2, 2, 0, 2>& zzxz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 2>*>(addressof(x)); };
swizzle_type<2, 2, 1, 0>& zzyx_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 0>*>(addressof(x)); };
swizzle_type<2, 2, 1, 1>& zzyy_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 1>*>(addressof(x)); };
swizzle_type<2, 2, 1, 2>& zzyz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 2>*>(addressof(x)); };
swizzle_type<2, 2, 2, 0>& zzzx_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 0>*>(addressof(x)); };
swizzle_type<2, 2, 2, 1>& zzzy_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 1>*>(addressof(x)); };
swizzle_type<2, 2, 2, 2>& zzzz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 2>*>(addressof(x)); };
auto xxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 0>*>(addressof(x))).decay(); };
auto xxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 1>*>(addressof(x))).decay(); };
auto xxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 2>*>(addressof(x))).decay(); };
auto xxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 0>*>(addressof(x))).decay(); };
auto xxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 1>*>(addressof(x))).decay(); };
auto xxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 2>*>(addressof(x))).decay(); };
auto xxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 0>*>(addressof(x))).decay(); };
auto xxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 1>*>(addressof(x))).decay(); };
auto xxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 2>*>(addressof(x))).decay(); };
auto xyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 0>*>(addressof(x))).decay(); };
auto xyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 1>*>(addressof(x))).decay(); };
auto xyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 2>*>(addressof(x))).decay(); };
auto xyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 0>*>(addressof(x))).decay(); };
auto xyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 1>*>(addressof(x))).decay(); };
auto xyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 2>*>(addressof(x))).decay(); };
auto xyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 0>*>(addressof(x))).decay(); };
auto xyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 1>*>(addressof(x))).decay(); };
auto xyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 2>*>(addressof(x))).decay(); };
auto xzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 0>*>(addressof(x))).decay(); };
auto xzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 1>*>(addressof(x))).decay(); };
auto xzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 2>*>(addressof(x))).decay(); };
auto xzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 0>*>(addressof(x))).decay(); };
auto xzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 1>*>(addressof(x))).decay(); };
auto xzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 2>*>(addressof(x))).decay(); };
auto xzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 0>*>(addressof(x))).decay(); };
auto xzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 1>*>(addressof(x))).decay(); };
auto xzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 2>*>(addressof(x))).decay(); };
auto yxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 0>*>(addressof(x))).decay(); };
auto yxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 1>*>(addressof(x))).decay(); };
auto yxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 2>*>(addressof(x))).decay(); };
auto yxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 0>*>(addressof(x))).decay(); };
auto yxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 1>*>(addressof(x))).decay(); };
auto yxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 2>*>(addressof(x))).decay(); };
auto yxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 0>*>(addressof(x))).decay(); };
auto yxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 1>*>(addressof(x))).decay(); };
auto yxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 2>*>(addressof(x))).decay(); };
auto yyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 0>*>(addressof(x))).decay(); };
auto yyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 1>*>(addressof(x))).decay(); };
auto yyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 2>*>(addressof(x))).decay(); };
auto yyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 0>*>(addressof(x))).decay(); };
auto yyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 1>*>(addressof(x))).decay(); };
auto yyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 2>*>(addressof(x))).decay(); };
auto yyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 0>*>(addressof(x))).decay(); };
auto yyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 1>*>(addressof(x))).decay(); };
auto yyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 2>*>(addressof(x))).decay(); };
auto yzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 0>*>(addressof(x))).decay(); };
auto yzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 1>*>(addressof(x))).decay(); };
auto yzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 2>*>(addressof(x))).decay(); };
auto yzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 0>*>(addressof(x))).decay(); };
auto yzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 1>*>(addressof(x))).decay(); };
auto yzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 2>*>(addressof(x))).decay(); };
auto yzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 0>*>(addressof(x))).decay(); };
auto yzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 1>*>(addressof(x))).decay(); };
auto yzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 2>*>(addressof(x))).decay(); };
auto zxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 0>*>(addressof(x))).decay(); };
auto zxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 1>*>(addressof(x))).decay(); };
auto zxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 2>*>(addressof(x))).decay(); };
auto zxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 0>*>(addressof(x))).decay(); };
auto zxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 1>*>(addressof(x))).decay(); };
auto zxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 2>*>(addressof(x))).decay(); };
auto zxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 0>*>(addressof(x))).decay(); };
auto zxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 1>*>(addressof(x))).decay(); };
auto zxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 2>*>(addressof(x))).decay(); };
auto zyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 0>*>(addressof(x))).decay(); };
auto zyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 1>*>(addressof(x))).decay(); };
auto zyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 2>*>(addressof(x))).decay(); };
auto zyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 0>*>(addressof(x))).decay(); };
auto zyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 1>*>(addressof(x))).decay(); };
auto zyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 2>*>(addressof(x))).decay(); };
auto zyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 0>*>(addressof(x))).decay(); };
auto zyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 1>*>(addressof(x))).decay(); };
auto zyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 2>*>(addressof(x))).decay(); };
auto zzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 0>*>(addressof(x))).decay(); };
auto zzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 1>*>(addressof(x))).decay(); };
auto zzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 2>*>(addressof(x))).decay(); };
auto zzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 0>*>(addressof(x))).decay(); };
auto zzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 1>*>(addressof(x))).decay(); };
auto zzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 2>*>(addressof(x))).decay(); };
auto zzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 0>*>(addressof(x))).decay(); };
auto zzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 1>*>(addressof(x))).decay(); };
auto zzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 2>*>(addressof(x))).decay(); };
