swizzle_type<0, 0>& xx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0>*>(addressof(x)); };
swizzle_type<0, 1>& xy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1>*>(addressof(x)); };
swizzle_type<0, 2>& xz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2>*>(addressof(x)); };
swizzle_type<0, 3>& xw_() noexcept { return *reinterpret_cast<swizzle_type<0, 3>*>(addressof(x)); };
swizzle_type<1, 0>& yx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0>*>(addressof(x)); };
swizzle_type<1, 1>& yy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1>*>(addressof(x)); };
swizzle_type<1, 2>& yz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2>*>(addressof(x)); };
swizzle_type<1, 3>& yw_() noexcept { return *reinterpret_cast<swizzle_type<1, 3>*>(addressof(x)); };
swizzle_type<2, 0>& zx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0>*>(addressof(x)); };
swizzle_type<2, 1>& zy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1>*>(addressof(x)); };
swizzle_type<2, 2>& zz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2>*>(addressof(x)); };
swizzle_type<2, 3>& zw_() noexcept { return *reinterpret_cast<swizzle_type<2, 3>*>(addressof(x)); };
swizzle_type<3, 0>& wx_() noexcept { return *reinterpret_cast<swizzle_type<3, 0>*>(addressof(x)); };
swizzle_type<3, 1>& wy_() noexcept { return *reinterpret_cast<swizzle_type<3, 1>*>(addressof(x)); };
swizzle_type<3, 2>& wz_() noexcept { return *reinterpret_cast<swizzle_type<3, 2>*>(addressof(x)); };
swizzle_type<3, 3>& ww_() noexcept { return *reinterpret_cast<swizzle_type<3, 3>*>(addressof(x)); };
auto xx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0>*>(addressof(x))).decay(); };
auto xy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1>*>(addressof(x))).decay(); };
auto xz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2>*>(addressof(x))).decay(); };
auto xw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3>*>(addressof(x))).decay(); };
auto yx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0>*>(addressof(x))).decay(); };
auto yy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1>*>(addressof(x))).decay(); };
auto yz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2>*>(addressof(x))).decay(); };
auto yw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3>*>(addressof(x))).decay(); };
auto zx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0>*>(addressof(x))).decay(); };
auto zy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1>*>(addressof(x))).decay(); };
auto zz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2>*>(addressof(x))).decay(); };
auto zw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3>*>(addressof(x))).decay(); };
auto wx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0>*>(addressof(x))).decay(); };
auto wy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1>*>(addressof(x))).decay(); };
auto wz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2>*>(addressof(x))).decay(); };
auto ww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3>*>(addressof(x))).decay(); };

swizzle_type<0, 0, 0>& xxx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1>& xxy_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 0, 2>& xxz_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2>*>(addressof(x)); };
swizzle_type<0, 0, 3>& xxw_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3>*>(addressof(x)); };
swizzle_type<0, 1, 0>& xyx_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1>& xyy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1>*>(addressof(x)); };
swizzle_type<0, 1, 2>& xyz_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2>*>(addressof(x)); };
swizzle_type<0, 1, 3>& xyw_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3>*>(addressof(x)); };
swizzle_type<0, 2, 0>& xzx_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0>*>(addressof(x)); };
swizzle_type<0, 2, 1>& xzy_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1>*>(addressof(x)); };
swizzle_type<0, 2, 2>& xzz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2>*>(addressof(x)); };
swizzle_type<0, 2, 3>& xzw_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3>*>(addressof(x)); };
swizzle_type<0, 3, 0>& xwx_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0>*>(addressof(x)); };
swizzle_type<0, 3, 1>& xwy_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1>*>(addressof(x)); };
swizzle_type<0, 3, 2>& xwz_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2>*>(addressof(x)); };
swizzle_type<0, 3, 3>& xww_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3>*>(addressof(x)); };
swizzle_type<1, 0, 0>& yxx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1>& yxy_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 0, 2>& yxz_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2>*>(addressof(x)); };
swizzle_type<1, 0, 3>& yxw_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3>*>(addressof(x)); };
swizzle_type<1, 1, 0>& yyx_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1>& yyy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1>*>(addressof(x)); };
swizzle_type<1, 1, 2>& yyz_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2>*>(addressof(x)); };
swizzle_type<1, 1, 3>& yyw_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3>*>(addressof(x)); };
swizzle_type<1, 2, 0>& yzx_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0>*>(addressof(x)); };
swizzle_type<1, 2, 1>& yzy_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1>*>(addressof(x)); };
swizzle_type<1, 2, 2>& yzz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2>*>(addressof(x)); };
swizzle_type<1, 2, 3>& yzw_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3>*>(addressof(x)); };
swizzle_type<1, 3, 0>& ywx_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0>*>(addressof(x)); };
swizzle_type<1, 3, 1>& ywy_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1>*>(addressof(x)); };
swizzle_type<1, 3, 2>& ywz_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2>*>(addressof(x)); };
swizzle_type<1, 3, 3>& yww_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3>*>(addressof(x)); };
swizzle_type<2, 0, 0>& zxx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0>*>(addressof(x)); };
swizzle_type<2, 0, 1>& zxy_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1>*>(addressof(x)); };
swizzle_type<2, 0, 2>& zxz_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2>*>(addressof(x)); };
swizzle_type<2, 0, 3>& zxw_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3>*>(addressof(x)); };
swizzle_type<2, 1, 0>& zyx_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0>*>(addressof(x)); };
swizzle_type<2, 1, 1>& zyy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1>*>(addressof(x)); };
swizzle_type<2, 1, 2>& zyz_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2>*>(addressof(x)); };
swizzle_type<2, 1, 3>& zyw_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3>*>(addressof(x)); };
swizzle_type<2, 2, 0>& zzx_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0>*>(addressof(x)); };
swizzle_type<2, 2, 1>& zzy_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1>*>(addressof(x)); };
swizzle_type<2, 2, 2>& zzz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2>*>(addressof(x)); };
swizzle_type<2, 2, 3>& zzw_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3>*>(addressof(x)); };
swizzle_type<2, 3, 0>& zwx_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0>*>(addressof(x)); };
swizzle_type<2, 3, 1>& zwy_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1>*>(addressof(x)); };
swizzle_type<2, 3, 2>& zwz_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2>*>(addressof(x)); };
swizzle_type<2, 3, 3>& zww_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3>*>(addressof(x)); };
swizzle_type<3, 0, 0>& wxx_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0>*>(addressof(x)); };
swizzle_type<3, 0, 1>& wxy_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1>*>(addressof(x)); };
swizzle_type<3, 0, 2>& wxz_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2>*>(addressof(x)); };
swizzle_type<3, 0, 3>& wxw_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3>*>(addressof(x)); };
swizzle_type<3, 1, 0>& wyx_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0>*>(addressof(x)); };
swizzle_type<3, 1, 1>& wyy_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1>*>(addressof(x)); };
swizzle_type<3, 1, 2>& wyz_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2>*>(addressof(x)); };
swizzle_type<3, 1, 3>& wyw_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3>*>(addressof(x)); };
swizzle_type<3, 2, 0>& wzx_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0>*>(addressof(x)); };
swizzle_type<3, 2, 1>& wzy_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1>*>(addressof(x)); };
swizzle_type<3, 2, 2>& wzz_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2>*>(addressof(x)); };
swizzle_type<3, 2, 3>& wzw_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3>*>(addressof(x)); };
swizzle_type<3, 3, 0>& wwx_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0>*>(addressof(x)); };
swizzle_type<3, 3, 1>& wwy_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1>*>(addressof(x)); };
swizzle_type<3, 3, 2>& wwz_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2>*>(addressof(x)); };
swizzle_type<3, 3, 3>& www_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3>*>(addressof(x)); };
auto xxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0>*>(addressof(x))).decay(); };
auto xxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1>*>(addressof(x))).decay(); };
auto xxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2>*>(addressof(x))).decay(); };
auto xxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3>*>(addressof(x))).decay(); };
auto xyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0>*>(addressof(x))).decay(); };
auto xyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1>*>(addressof(x))).decay(); };
auto xyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2>*>(addressof(x))).decay(); };
auto xyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3>*>(addressof(x))).decay(); };
auto xzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0>*>(addressof(x))).decay(); };
auto xzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1>*>(addressof(x))).decay(); };
auto xzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2>*>(addressof(x))).decay(); };
auto xzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3>*>(addressof(x))).decay(); };
auto xwx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0>*>(addressof(x))).decay(); };
auto xwy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1>*>(addressof(x))).decay(); };
auto xwz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2>*>(addressof(x))).decay(); };
auto xww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3>*>(addressof(x))).decay(); };
auto yxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0>*>(addressof(x))).decay(); };
auto yxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1>*>(addressof(x))).decay(); };
auto yxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2>*>(addressof(x))).decay(); };
auto yxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3>*>(addressof(x))).decay(); };
auto yyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0>*>(addressof(x))).decay(); };
auto yyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1>*>(addressof(x))).decay(); };
auto yyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2>*>(addressof(x))).decay(); };
auto yyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3>*>(addressof(x))).decay(); };
auto yzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0>*>(addressof(x))).decay(); };
auto yzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1>*>(addressof(x))).decay(); };
auto yzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2>*>(addressof(x))).decay(); };
auto yzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3>*>(addressof(x))).decay(); };
auto ywx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0>*>(addressof(x))).decay(); };
auto ywy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1>*>(addressof(x))).decay(); };
auto ywz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2>*>(addressof(x))).decay(); };
auto yww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3>*>(addressof(x))).decay(); };
auto zxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0>*>(addressof(x))).decay(); };
auto zxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1>*>(addressof(x))).decay(); };
auto zxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2>*>(addressof(x))).decay(); };
auto zxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3>*>(addressof(x))).decay(); };
auto zyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0>*>(addressof(x))).decay(); };
auto zyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1>*>(addressof(x))).decay(); };
auto zyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2>*>(addressof(x))).decay(); };
auto zyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3>*>(addressof(x))).decay(); };
auto zzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0>*>(addressof(x))).decay(); };
auto zzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1>*>(addressof(x))).decay(); };
auto zzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2>*>(addressof(x))).decay(); };
auto zzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3>*>(addressof(x))).decay(); };
auto zwx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0>*>(addressof(x))).decay(); };
auto zwy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1>*>(addressof(x))).decay(); };
auto zwz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2>*>(addressof(x))).decay(); };
auto zww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3>*>(addressof(x))).decay(); };
auto wxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0>*>(addressof(x))).decay(); };
auto wxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1>*>(addressof(x))).decay(); };
auto wxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2>*>(addressof(x))).decay(); };
auto wxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3>*>(addressof(x))).decay(); };
auto wyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0>*>(addressof(x))).decay(); };
auto wyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1>*>(addressof(x))).decay(); };
auto wyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2>*>(addressof(x))).decay(); };
auto wyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3>*>(addressof(x))).decay(); };
auto wzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0>*>(addressof(x))).decay(); };
auto wzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1>*>(addressof(x))).decay(); };
auto wzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2>*>(addressof(x))).decay(); };
auto wzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3>*>(addressof(x))).decay(); };
auto wwx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0>*>(addressof(x))).decay(); };
auto wwy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1>*>(addressof(x))).decay(); };
auto wwz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2>*>(addressof(x))).decay(); };
auto www() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3>*>(addressof(x))).decay(); };

swizzle_type<0, 0, 0, 0>& xxxx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 0, 1>& xxxy_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 0, 0, 2>& xxxz_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 2>*>(addressof(x)); };
swizzle_type<0, 0, 0, 3>& xxxw_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 3>*>(addressof(x)); };
swizzle_type<0, 0, 1, 0>& xxyx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1, 1>& xxyy_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 1>*>(addressof(x)); };
swizzle_type<0, 0, 1, 2>& xxyz_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 2>*>(addressof(x)); };
swizzle_type<0, 0, 1, 3>& xxyw_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 3>*>(addressof(x)); };
swizzle_type<0, 0, 2, 0>& xxzx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 0>*>(addressof(x)); };
swizzle_type<0, 0, 2, 1>& xxzy_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 1>*>(addressof(x)); };
swizzle_type<0, 0, 2, 2>& xxzz_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 2>*>(addressof(x)); };
swizzle_type<0, 0, 2, 3>& xxzw_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 3>*>(addressof(x)); };
swizzle_type<0, 0, 3, 0>& xxwx_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3, 0>*>(addressof(x)); };
swizzle_type<0, 0, 3, 1>& xxwy_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3, 1>*>(addressof(x)); };
swizzle_type<0, 0, 3, 2>& xxwz_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3, 2>*>(addressof(x)); };
swizzle_type<0, 0, 3, 3>& xxww_() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3, 3>*>(addressof(x)); };
swizzle_type<0, 1, 0, 0>& xyxx_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 0>*>(addressof(x)); };
swizzle_type<0, 1, 0, 1>& xyxy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 1>*>(addressof(x)); };
swizzle_type<0, 1, 0, 2>& xyxz_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 2>*>(addressof(x)); };
swizzle_type<0, 1, 0, 3>& xyxw_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 3>*>(addressof(x)); };
swizzle_type<0, 1, 1, 0>& xyyx_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1, 1>& xyyy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 1>*>(addressof(x)); };
swizzle_type<0, 1, 1, 2>& xyyz_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 2>*>(addressof(x)); };
swizzle_type<0, 1, 1, 3>& xyyw_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 3>*>(addressof(x)); };
swizzle_type<0, 1, 2, 0>& xyzx_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 0>*>(addressof(x)); };
swizzle_type<0, 1, 2, 1>& xyzy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 1>*>(addressof(x)); };
swizzle_type<0, 1, 2, 2>& xyzz_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 2>*>(addressof(x)); };
swizzle_type<0, 1, 2, 3>& xyzw_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 3>*>(addressof(x)); };
swizzle_type<0, 1, 3, 0>& xywx_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3, 0>*>(addressof(x)); };
swizzle_type<0, 1, 3, 1>& xywy_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3, 1>*>(addressof(x)); };
swizzle_type<0, 1, 3, 2>& xywz_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3, 2>*>(addressof(x)); };
swizzle_type<0, 1, 3, 3>& xyww_() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3, 3>*>(addressof(x)); };
swizzle_type<0, 2, 0, 0>& xzxx_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 0>*>(addressof(x)); };
swizzle_type<0, 2, 0, 1>& xzxy_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 1>*>(addressof(x)); };
swizzle_type<0, 2, 0, 2>& xzxz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 2>*>(addressof(x)); };
swizzle_type<0, 2, 0, 3>& xzxw_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 3>*>(addressof(x)); };
swizzle_type<0, 2, 1, 0>& xzyx_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 0>*>(addressof(x)); };
swizzle_type<0, 2, 1, 1>& xzyy_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 1>*>(addressof(x)); };
swizzle_type<0, 2, 1, 2>& xzyz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 2>*>(addressof(x)); };
swizzle_type<0, 2, 1, 3>& xzyw_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 3>*>(addressof(x)); };
swizzle_type<0, 2, 2, 0>& xzzx_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 0>*>(addressof(x)); };
swizzle_type<0, 2, 2, 1>& xzzy_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 1>*>(addressof(x)); };
swizzle_type<0, 2, 2, 2>& xzzz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 2>*>(addressof(x)); };
swizzle_type<0, 2, 2, 3>& xzzw_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 3>*>(addressof(x)); };
swizzle_type<0, 2, 3, 0>& xzwx_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3, 0>*>(addressof(x)); };
swizzle_type<0, 2, 3, 1>& xzwy_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3, 1>*>(addressof(x)); };
swizzle_type<0, 2, 3, 2>& xzwz_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3, 2>*>(addressof(x)); };
swizzle_type<0, 2, 3, 3>& xzww_() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3, 3>*>(addressof(x)); };
swizzle_type<0, 3, 0, 0>& xwxx_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0, 0>*>(addressof(x)); };
swizzle_type<0, 3, 0, 1>& xwxy_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0, 1>*>(addressof(x)); };
swizzle_type<0, 3, 0, 2>& xwxz_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0, 2>*>(addressof(x)); };
swizzle_type<0, 3, 0, 3>& xwxw_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0, 3>*>(addressof(x)); };
swizzle_type<0, 3, 1, 0>& xwyx_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1, 0>*>(addressof(x)); };
swizzle_type<0, 3, 1, 1>& xwyy_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1, 1>*>(addressof(x)); };
swizzle_type<0, 3, 1, 2>& xwyz_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1, 2>*>(addressof(x)); };
swizzle_type<0, 3, 1, 3>& xwyw_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1, 3>*>(addressof(x)); };
swizzle_type<0, 3, 2, 0>& xwzx_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2, 0>*>(addressof(x)); };
swizzle_type<0, 3, 2, 1>& xwzy_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2, 1>*>(addressof(x)); };
swizzle_type<0, 3, 2, 2>& xwzz_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2, 2>*>(addressof(x)); };
swizzle_type<0, 3, 2, 3>& xwzw_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2, 3>*>(addressof(x)); };
swizzle_type<0, 3, 3, 0>& xwwx_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3, 0>*>(addressof(x)); };
swizzle_type<0, 3, 3, 1>& xwwy_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3, 1>*>(addressof(x)); };
swizzle_type<0, 3, 3, 2>& xwwz_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3, 2>*>(addressof(x)); };
swizzle_type<0, 3, 3, 3>& xwww_() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3, 3>*>(addressof(x)); };
swizzle_type<1, 0, 0, 0>& yxxx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 0, 1>& yxxy_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 1>*>(addressof(x)); };
swizzle_type<1, 0, 0, 2>& yxxz_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 2>*>(addressof(x)); };
swizzle_type<1, 0, 0, 3>& yxxw_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 3>*>(addressof(x)); };
swizzle_type<1, 0, 1, 0>& yxyx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1, 1>& yxyy_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 1>*>(addressof(x)); };
swizzle_type<1, 0, 1, 2>& yxyz_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 2>*>(addressof(x)); };
swizzle_type<1, 0, 1, 3>& yxyw_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 3>*>(addressof(x)); };
swizzle_type<1, 0, 2, 0>& yxzx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 0>*>(addressof(x)); };
swizzle_type<1, 0, 2, 1>& yxzy_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 1>*>(addressof(x)); };
swizzle_type<1, 0, 2, 2>& yxzz_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 2>*>(addressof(x)); };
swizzle_type<1, 0, 2, 3>& yxzw_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 3>*>(addressof(x)); };
swizzle_type<1, 0, 3, 0>& yxwx_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3, 0>*>(addressof(x)); };
swizzle_type<1, 0, 3, 1>& yxwy_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3, 1>*>(addressof(x)); };
swizzle_type<1, 0, 3, 2>& yxwz_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3, 2>*>(addressof(x)); };
swizzle_type<1, 0, 3, 3>& yxww_() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3, 3>*>(addressof(x)); };
swizzle_type<1, 1, 0, 0>& yyxx_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 1, 0, 1>& yyxy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 1, 0, 2>& yyxz_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 2>*>(addressof(x)); };
swizzle_type<1, 1, 0, 3>& yyxw_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 3>*>(addressof(x)); };
swizzle_type<1, 1, 1, 0>& yyyx_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1, 1>& yyyy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 1>*>(addressof(x)); };
swizzle_type<1, 1, 1, 2>& yyyz_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 2>*>(addressof(x)); };
swizzle_type<1, 1, 1, 3>& yyyw_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 3>*>(addressof(x)); };
swizzle_type<1, 1, 2, 0>& yyzx_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 0>*>(addressof(x)); };
swizzle_type<1, 1, 2, 1>& yyzy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 1>*>(addressof(x)); };
swizzle_type<1, 1, 2, 2>& yyzz_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 2>*>(addressof(x)); };
swizzle_type<1, 1, 2, 3>& yyzw_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 3>*>(addressof(x)); };
swizzle_type<1, 1, 3, 0>& yywx_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3, 0>*>(addressof(x)); };
swizzle_type<1, 1, 3, 1>& yywy_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3, 1>*>(addressof(x)); };
swizzle_type<1, 1, 3, 2>& yywz_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3, 2>*>(addressof(x)); };
swizzle_type<1, 1, 3, 3>& yyww_() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3, 3>*>(addressof(x)); };
swizzle_type<1, 2, 0, 0>& yzxx_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 0>*>(addressof(x)); };
swizzle_type<1, 2, 0, 1>& yzxy_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 1>*>(addressof(x)); };
swizzle_type<1, 2, 0, 2>& yzxz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 2>*>(addressof(x)); };
swizzle_type<1, 2, 0, 3>& yzxw_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 3>*>(addressof(x)); };
swizzle_type<1, 2, 1, 0>& yzyx_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 0>*>(addressof(x)); };
swizzle_type<1, 2, 1, 1>& yzyy_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 1>*>(addressof(x)); };
swizzle_type<1, 2, 1, 2>& yzyz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 2>*>(addressof(x)); };
swizzle_type<1, 2, 1, 3>& yzyw_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 3>*>(addressof(x)); };
swizzle_type<1, 2, 2, 0>& yzzx_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 0>*>(addressof(x)); };
swizzle_type<1, 2, 2, 1>& yzzy_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 1>*>(addressof(x)); };
swizzle_type<1, 2, 2, 2>& yzzz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 2>*>(addressof(x)); };
swizzle_type<1, 2, 2, 3>& yzzw_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 3>*>(addressof(x)); };
swizzle_type<1, 2, 3, 0>& yzwx_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3, 0>*>(addressof(x)); };
swizzle_type<1, 2, 3, 1>& yzwy_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3, 1>*>(addressof(x)); };
swizzle_type<1, 2, 3, 2>& yzwz_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3, 2>*>(addressof(x)); };
swizzle_type<1, 2, 3, 3>& yzww_() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3, 3>*>(addressof(x)); };
swizzle_type<1, 3, 0, 0>& ywxx_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0, 0>*>(addressof(x)); };
swizzle_type<1, 3, 0, 1>& ywxy_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0, 1>*>(addressof(x)); };
swizzle_type<1, 3, 0, 2>& ywxz_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0, 2>*>(addressof(x)); };
swizzle_type<1, 3, 0, 3>& ywxw_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0, 3>*>(addressof(x)); };
swizzle_type<1, 3, 1, 0>& ywyx_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1, 0>*>(addressof(x)); };
swizzle_type<1, 3, 1, 1>& ywyy_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1, 1>*>(addressof(x)); };
swizzle_type<1, 3, 1, 2>& ywyz_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1, 2>*>(addressof(x)); };
swizzle_type<1, 3, 1, 3>& ywyw_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1, 3>*>(addressof(x)); };
swizzle_type<1, 3, 2, 0>& ywzx_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2, 0>*>(addressof(x)); };
swizzle_type<1, 3, 2, 1>& ywzy_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2, 1>*>(addressof(x)); };
swizzle_type<1, 3, 2, 2>& ywzz_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2, 2>*>(addressof(x)); };
swizzle_type<1, 3, 2, 3>& ywzw_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2, 3>*>(addressof(x)); };
swizzle_type<1, 3, 3, 0>& ywwx_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3, 0>*>(addressof(x)); };
swizzle_type<1, 3, 3, 1>& ywwy_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3, 1>*>(addressof(x)); };
swizzle_type<1, 3, 3, 2>& ywwz_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3, 2>*>(addressof(x)); };
swizzle_type<1, 3, 3, 3>& ywww_() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3, 3>*>(addressof(x)); };
swizzle_type<2, 0, 0, 0>& zxxx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 0>*>(addressof(x)); };
swizzle_type<2, 0, 0, 1>& zxxy_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 1>*>(addressof(x)); };
swizzle_type<2, 0, 0, 2>& zxxz_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 2>*>(addressof(x)); };
swizzle_type<2, 0, 0, 3>& zxxw_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 3>*>(addressof(x)); };
swizzle_type<2, 0, 1, 0>& zxyx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 0>*>(addressof(x)); };
swizzle_type<2, 0, 1, 1>& zxyy_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 1>*>(addressof(x)); };
swizzle_type<2, 0, 1, 2>& zxyz_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 2>*>(addressof(x)); };
swizzle_type<2, 0, 1, 3>& zxyw_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 3>*>(addressof(x)); };
swizzle_type<2, 0, 2, 0>& zxzx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 0>*>(addressof(x)); };
swizzle_type<2, 0, 2, 1>& zxzy_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 1>*>(addressof(x)); };
swizzle_type<2, 0, 2, 2>& zxzz_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 2>*>(addressof(x)); };
swizzle_type<2, 0, 2, 3>& zxzw_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 3>*>(addressof(x)); };
swizzle_type<2, 0, 3, 0>& zxwx_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3, 0>*>(addressof(x)); };
swizzle_type<2, 0, 3, 1>& zxwy_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3, 1>*>(addressof(x)); };
swizzle_type<2, 0, 3, 2>& zxwz_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3, 2>*>(addressof(x)); };
swizzle_type<2, 0, 3, 3>& zxww_() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3, 3>*>(addressof(x)); };
swizzle_type<2, 1, 0, 0>& zyxx_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 0>*>(addressof(x)); };
swizzle_type<2, 1, 0, 1>& zyxy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 1>*>(addressof(x)); };
swizzle_type<2, 1, 0, 2>& zyxz_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 2>*>(addressof(x)); };
swizzle_type<2, 1, 0, 3>& zyxw_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 3>*>(addressof(x)); };
swizzle_type<2, 1, 1, 0>& zyyx_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 0>*>(addressof(x)); };
swizzle_type<2, 1, 1, 1>& zyyy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 1>*>(addressof(x)); };
swizzle_type<2, 1, 1, 2>& zyyz_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 2>*>(addressof(x)); };
swizzle_type<2, 1, 1, 3>& zyyw_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 3>*>(addressof(x)); };
swizzle_type<2, 1, 2, 0>& zyzx_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 0>*>(addressof(x)); };
swizzle_type<2, 1, 2, 1>& zyzy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 1>*>(addressof(x)); };
swizzle_type<2, 1, 2, 2>& zyzz_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 2>*>(addressof(x)); };
swizzle_type<2, 1, 2, 3>& zyzw_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 3>*>(addressof(x)); };
swizzle_type<2, 1, 3, 0>& zywx_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3, 0>*>(addressof(x)); };
swizzle_type<2, 1, 3, 1>& zywy_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3, 1>*>(addressof(x)); };
swizzle_type<2, 1, 3, 2>& zywz_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3, 2>*>(addressof(x)); };
swizzle_type<2, 1, 3, 3>& zyww_() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3, 3>*>(addressof(x)); };
swizzle_type<2, 2, 0, 0>& zzxx_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 0>*>(addressof(x)); };
swizzle_type<2, 2, 0, 1>& zzxy_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 1>*>(addressof(x)); };
swizzle_type<2, 2, 0, 2>& zzxz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 2>*>(addressof(x)); };
swizzle_type<2, 2, 0, 3>& zzxw_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 3>*>(addressof(x)); };
swizzle_type<2, 2, 1, 0>& zzyx_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 0>*>(addressof(x)); };
swizzle_type<2, 2, 1, 1>& zzyy_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 1>*>(addressof(x)); };
swizzle_type<2, 2, 1, 2>& zzyz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 2>*>(addressof(x)); };
swizzle_type<2, 2, 1, 3>& zzyw_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 3>*>(addressof(x)); };
swizzle_type<2, 2, 2, 0>& zzzx_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 0>*>(addressof(x)); };
swizzle_type<2, 2, 2, 1>& zzzy_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 1>*>(addressof(x)); };
swizzle_type<2, 2, 2, 2>& zzzz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 2>*>(addressof(x)); };
swizzle_type<2, 2, 2, 3>& zzzw_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 3>*>(addressof(x)); };
swizzle_type<2, 2, 3, 0>& zzwx_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3, 0>*>(addressof(x)); };
swizzle_type<2, 2, 3, 1>& zzwy_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3, 1>*>(addressof(x)); };
swizzle_type<2, 2, 3, 2>& zzwz_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3, 2>*>(addressof(x)); };
swizzle_type<2, 2, 3, 3>& zzww_() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3, 3>*>(addressof(x)); };
swizzle_type<2, 3, 0, 0>& zwxx_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0, 0>*>(addressof(x)); };
swizzle_type<2, 3, 0, 1>& zwxy_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0, 1>*>(addressof(x)); };
swizzle_type<2, 3, 0, 2>& zwxz_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0, 2>*>(addressof(x)); };
swizzle_type<2, 3, 0, 3>& zwxw_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0, 3>*>(addressof(x)); };
swizzle_type<2, 3, 1, 0>& zwyx_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1, 0>*>(addressof(x)); };
swizzle_type<2, 3, 1, 1>& zwyy_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1, 1>*>(addressof(x)); };
swizzle_type<2, 3, 1, 2>& zwyz_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1, 2>*>(addressof(x)); };
swizzle_type<2, 3, 1, 3>& zwyw_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1, 3>*>(addressof(x)); };
swizzle_type<2, 3, 2, 0>& zwzx_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2, 0>*>(addressof(x)); };
swizzle_type<2, 3, 2, 1>& zwzy_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2, 1>*>(addressof(x)); };
swizzle_type<2, 3, 2, 2>& zwzz_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2, 2>*>(addressof(x)); };
swizzle_type<2, 3, 2, 3>& zwzw_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2, 3>*>(addressof(x)); };
swizzle_type<2, 3, 3, 0>& zwwx_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3, 0>*>(addressof(x)); };
swizzle_type<2, 3, 3, 1>& zwwy_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3, 1>*>(addressof(x)); };
swizzle_type<2, 3, 3, 2>& zwwz_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3, 2>*>(addressof(x)); };
swizzle_type<2, 3, 3, 3>& zwww_() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3, 3>*>(addressof(x)); };
swizzle_type<3, 0, 0, 0>& wxxx_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0, 0>*>(addressof(x)); };
swizzle_type<3, 0, 0, 1>& wxxy_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0, 1>*>(addressof(x)); };
swizzle_type<3, 0, 0, 2>& wxxz_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0, 2>*>(addressof(x)); };
swizzle_type<3, 0, 0, 3>& wxxw_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0, 3>*>(addressof(x)); };
swizzle_type<3, 0, 1, 0>& wxyx_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1, 0>*>(addressof(x)); };
swizzle_type<3, 0, 1, 1>& wxyy_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1, 1>*>(addressof(x)); };
swizzle_type<3, 0, 1, 2>& wxyz_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1, 2>*>(addressof(x)); };
swizzle_type<3, 0, 1, 3>& wxyw_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1, 3>*>(addressof(x)); };
swizzle_type<3, 0, 2, 0>& wxzx_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2, 0>*>(addressof(x)); };
swizzle_type<3, 0, 2, 1>& wxzy_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2, 1>*>(addressof(x)); };
swizzle_type<3, 0, 2, 2>& wxzz_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2, 2>*>(addressof(x)); };
swizzle_type<3, 0, 2, 3>& wxzw_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2, 3>*>(addressof(x)); };
swizzle_type<3, 0, 3, 0>& wxwx_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3, 0>*>(addressof(x)); };
swizzle_type<3, 0, 3, 1>& wxwy_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3, 1>*>(addressof(x)); };
swizzle_type<3, 0, 3, 2>& wxwz_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3, 2>*>(addressof(x)); };
swizzle_type<3, 0, 3, 3>& wxww_() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3, 3>*>(addressof(x)); };
swizzle_type<3, 1, 0, 0>& wyxx_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0, 0>*>(addressof(x)); };
swizzle_type<3, 1, 0, 1>& wyxy_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0, 1>*>(addressof(x)); };
swizzle_type<3, 1, 0, 2>& wyxz_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0, 2>*>(addressof(x)); };
swizzle_type<3, 1, 0, 3>& wyxw_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0, 3>*>(addressof(x)); };
swizzle_type<3, 1, 1, 0>& wyyx_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1, 0>*>(addressof(x)); };
swizzle_type<3, 1, 1, 1>& wyyy_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1, 1>*>(addressof(x)); };
swizzle_type<3, 1, 1, 2>& wyyz_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1, 2>*>(addressof(x)); };
swizzle_type<3, 1, 1, 3>& wyyw_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1, 3>*>(addressof(x)); };
swizzle_type<3, 1, 2, 0>& wyzx_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2, 0>*>(addressof(x)); };
swizzle_type<3, 1, 2, 1>& wyzy_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2, 1>*>(addressof(x)); };
swizzle_type<3, 1, 2, 2>& wyzz_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2, 2>*>(addressof(x)); };
swizzle_type<3, 1, 2, 3>& wyzw_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2, 3>*>(addressof(x)); };
swizzle_type<3, 1, 3, 0>& wywx_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3, 0>*>(addressof(x)); };
swizzle_type<3, 1, 3, 1>& wywy_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3, 1>*>(addressof(x)); };
swizzle_type<3, 1, 3, 2>& wywz_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3, 2>*>(addressof(x)); };
swizzle_type<3, 1, 3, 3>& wyww_() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3, 3>*>(addressof(x)); };
swizzle_type<3, 2, 0, 0>& wzxx_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0, 0>*>(addressof(x)); };
swizzle_type<3, 2, 0, 1>& wzxy_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0, 1>*>(addressof(x)); };
swizzle_type<3, 2, 0, 2>& wzxz_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0, 2>*>(addressof(x)); };
swizzle_type<3, 2, 0, 3>& wzxw_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0, 3>*>(addressof(x)); };
swizzle_type<3, 2, 1, 0>& wzyx_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1, 0>*>(addressof(x)); };
swizzle_type<3, 2, 1, 1>& wzyy_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1, 1>*>(addressof(x)); };
swizzle_type<3, 2, 1, 2>& wzyz_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1, 2>*>(addressof(x)); };
swizzle_type<3, 2, 1, 3>& wzyw_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1, 3>*>(addressof(x)); };
swizzle_type<3, 2, 2, 0>& wzzx_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2, 0>*>(addressof(x)); };
swizzle_type<3, 2, 2, 1>& wzzy_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2, 1>*>(addressof(x)); };
swizzle_type<3, 2, 2, 2>& wzzz_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2, 2>*>(addressof(x)); };
swizzle_type<3, 2, 2, 3>& wzzw_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2, 3>*>(addressof(x)); };
swizzle_type<3, 2, 3, 0>& wzwx_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3, 0>*>(addressof(x)); };
swizzle_type<3, 2, 3, 1>& wzwy_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3, 1>*>(addressof(x)); };
swizzle_type<3, 2, 3, 2>& wzwz_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3, 2>*>(addressof(x)); };
swizzle_type<3, 2, 3, 3>& wzww_() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3, 3>*>(addressof(x)); };
swizzle_type<3, 3, 0, 0>& wwxx_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0, 0>*>(addressof(x)); };
swizzle_type<3, 3, 0, 1>& wwxy_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0, 1>*>(addressof(x)); };
swizzle_type<3, 3, 0, 2>& wwxz_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0, 2>*>(addressof(x)); };
swizzle_type<3, 3, 0, 3>& wwxw_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0, 3>*>(addressof(x)); };
swizzle_type<3, 3, 1, 0>& wwyx_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1, 0>*>(addressof(x)); };
swizzle_type<3, 3, 1, 1>& wwyy_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1, 1>*>(addressof(x)); };
swizzle_type<3, 3, 1, 2>& wwyz_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1, 2>*>(addressof(x)); };
swizzle_type<3, 3, 1, 3>& wwyw_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1, 3>*>(addressof(x)); };
swizzle_type<3, 3, 2, 0>& wwzx_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2, 0>*>(addressof(x)); };
swizzle_type<3, 3, 2, 1>& wwzy_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2, 1>*>(addressof(x)); };
swizzle_type<3, 3, 2, 2>& wwzz_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2, 2>*>(addressof(x)); };
swizzle_type<3, 3, 2, 3>& wwzw_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2, 3>*>(addressof(x)); };
swizzle_type<3, 3, 3, 0>& wwwx_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3, 0>*>(addressof(x)); };
swizzle_type<3, 3, 3, 1>& wwwy_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3, 1>*>(addressof(x)); };
swizzle_type<3, 3, 3, 2>& wwwz_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3, 2>*>(addressof(x)); };
swizzle_type<3, 3, 3, 3>& wwww_() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3, 3>*>(addressof(x)); };
auto xxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 0>*>(addressof(x))).decay(); };
auto xxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 1>*>(addressof(x))).decay(); };
auto xxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 2>*>(addressof(x))).decay(); };
auto xxxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 3>*>(addressof(x))).decay(); };
auto xxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 0>*>(addressof(x))).decay(); };
auto xxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 1>*>(addressof(x))).decay(); };
auto xxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 2>*>(addressof(x))).decay(); };
auto xxyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 3>*>(addressof(x))).decay(); };
auto xxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 0>*>(addressof(x))).decay(); };
auto xxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 1>*>(addressof(x))).decay(); };
auto xxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 2>*>(addressof(x))).decay(); };
auto xxzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 3>*>(addressof(x))).decay(); };
auto xxwx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3, 0>*>(addressof(x))).decay(); };
auto xxwy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3, 1>*>(addressof(x))).decay(); };
auto xxwz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3, 2>*>(addressof(x))).decay(); };
auto xxww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3, 3>*>(addressof(x))).decay(); };
auto xyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 0>*>(addressof(x))).decay(); };
auto xyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 1>*>(addressof(x))).decay(); };
auto xyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 2>*>(addressof(x))).decay(); };
auto xyxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 3>*>(addressof(x))).decay(); };
auto xyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 0>*>(addressof(x))).decay(); };
auto xyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 1>*>(addressof(x))).decay(); };
auto xyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 2>*>(addressof(x))).decay(); };
auto xyyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 3>*>(addressof(x))).decay(); };
auto xyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 0>*>(addressof(x))).decay(); };
auto xyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 1>*>(addressof(x))).decay(); };
auto xyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 2>*>(addressof(x))).decay(); };
auto xyzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 3>*>(addressof(x))).decay(); };
auto xywx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3, 0>*>(addressof(x))).decay(); };
auto xywy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3, 1>*>(addressof(x))).decay(); };
auto xywz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3, 2>*>(addressof(x))).decay(); };
auto xyww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3, 3>*>(addressof(x))).decay(); };
auto xzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 0>*>(addressof(x))).decay(); };
auto xzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 1>*>(addressof(x))).decay(); };
auto xzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 2>*>(addressof(x))).decay(); };
auto xzxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 3>*>(addressof(x))).decay(); };
auto xzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 0>*>(addressof(x))).decay(); };
auto xzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 1>*>(addressof(x))).decay(); };
auto xzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 2>*>(addressof(x))).decay(); };
auto xzyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 3>*>(addressof(x))).decay(); };
auto xzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 0>*>(addressof(x))).decay(); };
auto xzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 1>*>(addressof(x))).decay(); };
auto xzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 2>*>(addressof(x))).decay(); };
auto xzzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 3>*>(addressof(x))).decay(); };
auto xzwx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3, 0>*>(addressof(x))).decay(); };
auto xzwy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3, 1>*>(addressof(x))).decay(); };
auto xzwz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3, 2>*>(addressof(x))).decay(); };
auto xzww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3, 3>*>(addressof(x))).decay(); };
auto xwxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0, 0>*>(addressof(x))).decay(); };
auto xwxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0, 1>*>(addressof(x))).decay(); };
auto xwxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0, 2>*>(addressof(x))).decay(); };
auto xwxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0, 3>*>(addressof(x))).decay(); };
auto xwyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1, 0>*>(addressof(x))).decay(); };
auto xwyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1, 1>*>(addressof(x))).decay(); };
auto xwyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1, 2>*>(addressof(x))).decay(); };
auto xwyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1, 3>*>(addressof(x))).decay(); };
auto xwzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2, 0>*>(addressof(x))).decay(); };
auto xwzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2, 1>*>(addressof(x))).decay(); };
auto xwzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2, 2>*>(addressof(x))).decay(); };
auto xwzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2, 3>*>(addressof(x))).decay(); };
auto xwwx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3, 0>*>(addressof(x))).decay(); };
auto xwwy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3, 1>*>(addressof(x))).decay(); };
auto xwwz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3, 2>*>(addressof(x))).decay(); };
auto xwww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3, 3>*>(addressof(x))).decay(); };
auto yxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 0>*>(addressof(x))).decay(); };
auto yxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 1>*>(addressof(x))).decay(); };
auto yxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 2>*>(addressof(x))).decay(); };
auto yxxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 3>*>(addressof(x))).decay(); };
auto yxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 0>*>(addressof(x))).decay(); };
auto yxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 1>*>(addressof(x))).decay(); };
auto yxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 2>*>(addressof(x))).decay(); };
auto yxyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 3>*>(addressof(x))).decay(); };
auto yxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 0>*>(addressof(x))).decay(); };
auto yxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 1>*>(addressof(x))).decay(); };
auto yxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 2>*>(addressof(x))).decay(); };
auto yxzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 3>*>(addressof(x))).decay(); };
auto yxwx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3, 0>*>(addressof(x))).decay(); };
auto yxwy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3, 1>*>(addressof(x))).decay(); };
auto yxwz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3, 2>*>(addressof(x))).decay(); };
auto yxww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3, 3>*>(addressof(x))).decay(); };
auto yyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 0>*>(addressof(x))).decay(); };
auto yyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 1>*>(addressof(x))).decay(); };
auto yyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 2>*>(addressof(x))).decay(); };
auto yyxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 3>*>(addressof(x))).decay(); };
auto yyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 0>*>(addressof(x))).decay(); };
auto yyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 1>*>(addressof(x))).decay(); };
auto yyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 2>*>(addressof(x))).decay(); };
auto yyyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 3>*>(addressof(x))).decay(); };
auto yyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 0>*>(addressof(x))).decay(); };
auto yyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 1>*>(addressof(x))).decay(); };
auto yyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 2>*>(addressof(x))).decay(); };
auto yyzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 3>*>(addressof(x))).decay(); };
auto yywx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3, 0>*>(addressof(x))).decay(); };
auto yywy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3, 1>*>(addressof(x))).decay(); };
auto yywz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3, 2>*>(addressof(x))).decay(); };
auto yyww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3, 3>*>(addressof(x))).decay(); };
auto yzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 0>*>(addressof(x))).decay(); };
auto yzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 1>*>(addressof(x))).decay(); };
auto yzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 2>*>(addressof(x))).decay(); };
auto yzxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 3>*>(addressof(x))).decay(); };
auto yzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 0>*>(addressof(x))).decay(); };
auto yzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 1>*>(addressof(x))).decay(); };
auto yzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 2>*>(addressof(x))).decay(); };
auto yzyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 3>*>(addressof(x))).decay(); };
auto yzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 0>*>(addressof(x))).decay(); };
auto yzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 1>*>(addressof(x))).decay(); };
auto yzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 2>*>(addressof(x))).decay(); };
auto yzzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 3>*>(addressof(x))).decay(); };
auto yzwx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3, 0>*>(addressof(x))).decay(); };
auto yzwy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3, 1>*>(addressof(x))).decay(); };
auto yzwz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3, 2>*>(addressof(x))).decay(); };
auto yzww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3, 3>*>(addressof(x))).decay(); };
auto ywxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0, 0>*>(addressof(x))).decay(); };
auto ywxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0, 1>*>(addressof(x))).decay(); };
auto ywxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0, 2>*>(addressof(x))).decay(); };
auto ywxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0, 3>*>(addressof(x))).decay(); };
auto ywyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1, 0>*>(addressof(x))).decay(); };
auto ywyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1, 1>*>(addressof(x))).decay(); };
auto ywyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1, 2>*>(addressof(x))).decay(); };
auto ywyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1, 3>*>(addressof(x))).decay(); };
auto ywzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2, 0>*>(addressof(x))).decay(); };
auto ywzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2, 1>*>(addressof(x))).decay(); };
auto ywzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2, 2>*>(addressof(x))).decay(); };
auto ywzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2, 3>*>(addressof(x))).decay(); };
auto ywwx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3, 0>*>(addressof(x))).decay(); };
auto ywwy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3, 1>*>(addressof(x))).decay(); };
auto ywwz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3, 2>*>(addressof(x))).decay(); };
auto ywww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3, 3>*>(addressof(x))).decay(); };
auto zxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 0>*>(addressof(x))).decay(); };
auto zxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 1>*>(addressof(x))).decay(); };
auto zxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 2>*>(addressof(x))).decay(); };
auto zxxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 3>*>(addressof(x))).decay(); };
auto zxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 0>*>(addressof(x))).decay(); };
auto zxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 1>*>(addressof(x))).decay(); };
auto zxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 2>*>(addressof(x))).decay(); };
auto zxyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 3>*>(addressof(x))).decay(); };
auto zxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 0>*>(addressof(x))).decay(); };
auto zxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 1>*>(addressof(x))).decay(); };
auto zxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 2>*>(addressof(x))).decay(); };
auto zxzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 3>*>(addressof(x))).decay(); };
auto zxwx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3, 0>*>(addressof(x))).decay(); };
auto zxwy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3, 1>*>(addressof(x))).decay(); };
auto zxwz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3, 2>*>(addressof(x))).decay(); };
auto zxww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3, 3>*>(addressof(x))).decay(); };
auto zyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 0>*>(addressof(x))).decay(); };
auto zyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 1>*>(addressof(x))).decay(); };
auto zyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 2>*>(addressof(x))).decay(); };
auto zyxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 3>*>(addressof(x))).decay(); };
auto zyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 0>*>(addressof(x))).decay(); };
auto zyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 1>*>(addressof(x))).decay(); };
auto zyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 2>*>(addressof(x))).decay(); };
auto zyyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 3>*>(addressof(x))).decay(); };
auto zyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 0>*>(addressof(x))).decay(); };
auto zyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 1>*>(addressof(x))).decay(); };
auto zyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 2>*>(addressof(x))).decay(); };
auto zyzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 3>*>(addressof(x))).decay(); };
auto zywx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3, 0>*>(addressof(x))).decay(); };
auto zywy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3, 1>*>(addressof(x))).decay(); };
auto zywz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3, 2>*>(addressof(x))).decay(); };
auto zyww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3, 3>*>(addressof(x))).decay(); };
auto zzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 0>*>(addressof(x))).decay(); };
auto zzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 1>*>(addressof(x))).decay(); };
auto zzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 2>*>(addressof(x))).decay(); };
auto zzxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 3>*>(addressof(x))).decay(); };
auto zzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 0>*>(addressof(x))).decay(); };
auto zzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 1>*>(addressof(x))).decay(); };
auto zzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 2>*>(addressof(x))).decay(); };
auto zzyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 3>*>(addressof(x))).decay(); };
auto zzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 0>*>(addressof(x))).decay(); };
auto zzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 1>*>(addressof(x))).decay(); };
auto zzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 2>*>(addressof(x))).decay(); };
auto zzzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 3>*>(addressof(x))).decay(); };
auto zzwx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3, 0>*>(addressof(x))).decay(); };
auto zzwy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3, 1>*>(addressof(x))).decay(); };
auto zzwz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3, 2>*>(addressof(x))).decay(); };
auto zzww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3, 3>*>(addressof(x))).decay(); };
auto zwxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0, 0>*>(addressof(x))).decay(); };
auto zwxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0, 1>*>(addressof(x))).decay(); };
auto zwxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0, 2>*>(addressof(x))).decay(); };
auto zwxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0, 3>*>(addressof(x))).decay(); };
auto zwyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1, 0>*>(addressof(x))).decay(); };
auto zwyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1, 1>*>(addressof(x))).decay(); };
auto zwyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1, 2>*>(addressof(x))).decay(); };
auto zwyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1, 3>*>(addressof(x))).decay(); };
auto zwzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2, 0>*>(addressof(x))).decay(); };
auto zwzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2, 1>*>(addressof(x))).decay(); };
auto zwzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2, 2>*>(addressof(x))).decay(); };
auto zwzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2, 3>*>(addressof(x))).decay(); };
auto zwwx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3, 0>*>(addressof(x))).decay(); };
auto zwwy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3, 1>*>(addressof(x))).decay(); };
auto zwwz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3, 2>*>(addressof(x))).decay(); };
auto zwww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3, 3>*>(addressof(x))).decay(); };
auto wxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0, 0>*>(addressof(x))).decay(); };
auto wxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0, 1>*>(addressof(x))).decay(); };
auto wxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0, 2>*>(addressof(x))).decay(); };
auto wxxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0, 3>*>(addressof(x))).decay(); };
auto wxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1, 0>*>(addressof(x))).decay(); };
auto wxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1, 1>*>(addressof(x))).decay(); };
auto wxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1, 2>*>(addressof(x))).decay(); };
auto wxyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1, 3>*>(addressof(x))).decay(); };
auto wxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2, 0>*>(addressof(x))).decay(); };
auto wxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2, 1>*>(addressof(x))).decay(); };
auto wxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2, 2>*>(addressof(x))).decay(); };
auto wxzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2, 3>*>(addressof(x))).decay(); };
auto wxwx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3, 0>*>(addressof(x))).decay(); };
auto wxwy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3, 1>*>(addressof(x))).decay(); };
auto wxwz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3, 2>*>(addressof(x))).decay(); };
auto wxww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3, 3>*>(addressof(x))).decay(); };
auto wyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0, 0>*>(addressof(x))).decay(); };
auto wyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0, 1>*>(addressof(x))).decay(); };
auto wyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0, 2>*>(addressof(x))).decay(); };
auto wyxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0, 3>*>(addressof(x))).decay(); };
auto wyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1, 0>*>(addressof(x))).decay(); };
auto wyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1, 1>*>(addressof(x))).decay(); };
auto wyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1, 2>*>(addressof(x))).decay(); };
auto wyyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1, 3>*>(addressof(x))).decay(); };
auto wyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2, 0>*>(addressof(x))).decay(); };
auto wyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2, 1>*>(addressof(x))).decay(); };
auto wyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2, 2>*>(addressof(x))).decay(); };
auto wyzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2, 3>*>(addressof(x))).decay(); };
auto wywx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3, 0>*>(addressof(x))).decay(); };
auto wywy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3, 1>*>(addressof(x))).decay(); };
auto wywz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3, 2>*>(addressof(x))).decay(); };
auto wyww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3, 3>*>(addressof(x))).decay(); };
auto wzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0, 0>*>(addressof(x))).decay(); };
auto wzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0, 1>*>(addressof(x))).decay(); };
auto wzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0, 2>*>(addressof(x))).decay(); };
auto wzxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0, 3>*>(addressof(x))).decay(); };
auto wzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1, 0>*>(addressof(x))).decay(); };
auto wzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1, 1>*>(addressof(x))).decay(); };
auto wzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1, 2>*>(addressof(x))).decay(); };
auto wzyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1, 3>*>(addressof(x))).decay(); };
auto wzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2, 0>*>(addressof(x))).decay(); };
auto wzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2, 1>*>(addressof(x))).decay(); };
auto wzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2, 2>*>(addressof(x))).decay(); };
auto wzzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2, 3>*>(addressof(x))).decay(); };
auto wzwx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3, 0>*>(addressof(x))).decay(); };
auto wzwy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3, 1>*>(addressof(x))).decay(); };
auto wzwz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3, 2>*>(addressof(x))).decay(); };
auto wzww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3, 3>*>(addressof(x))).decay(); };
auto wwxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0, 0>*>(addressof(x))).decay(); };
auto wwxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0, 1>*>(addressof(x))).decay(); };
auto wwxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0, 2>*>(addressof(x))).decay(); };
auto wwxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0, 3>*>(addressof(x))).decay(); };
auto wwyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1, 0>*>(addressof(x))).decay(); };
auto wwyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1, 1>*>(addressof(x))).decay(); };
auto wwyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1, 2>*>(addressof(x))).decay(); };
auto wwyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1, 3>*>(addressof(x))).decay(); };
auto wwzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2, 0>*>(addressof(x))).decay(); };
auto wwzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2, 1>*>(addressof(x))).decay(); };
auto wwzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2, 2>*>(addressof(x))).decay(); };
auto wwzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2, 3>*>(addressof(x))).decay(); };
auto wwwx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3, 0>*>(addressof(x))).decay(); };
auto wwwy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3, 1>*>(addressof(x))).decay(); };
auto wwwz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3, 2>*>(addressof(x))).decay(); };
auto wwww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3, 3>*>(addressof(x))).decay(); };
