swizzle_type<0, 0>& xx() noexcept { return *reinterpret_cast<swizzle_type<0, 0>*>(addressof(x)); };
swizzle_type<0, 1>& xy() noexcept { return *reinterpret_cast<swizzle_type<0, 1>*>(addressof(x)); };
swizzle_type<0, 2>& xz() noexcept { return *reinterpret_cast<swizzle_type<0, 2>*>(addressof(x)); };
swizzle_type<0, 3>& xw() noexcept { return *reinterpret_cast<swizzle_type<0, 3>*>(addressof(x)); };
swizzle_type<1, 0>& yx() noexcept { return *reinterpret_cast<swizzle_type<1, 0>*>(addressof(x)); };
swizzle_type<1, 1>& yy() noexcept { return *reinterpret_cast<swizzle_type<1, 1>*>(addressof(x)); };
swizzle_type<1, 2>& yz() noexcept { return *reinterpret_cast<swizzle_type<1, 2>*>(addressof(x)); };
swizzle_type<1, 3>& yw() noexcept { return *reinterpret_cast<swizzle_type<1, 3>*>(addressof(x)); };
swizzle_type<2, 0>& zx() noexcept { return *reinterpret_cast<swizzle_type<2, 0>*>(addressof(x)); };
swizzle_type<2, 1>& zy() noexcept { return *reinterpret_cast<swizzle_type<2, 1>*>(addressof(x)); };
swizzle_type<2, 2>& zz() noexcept { return *reinterpret_cast<swizzle_type<2, 2>*>(addressof(x)); };
swizzle_type<2, 3>& zw() noexcept { return *reinterpret_cast<swizzle_type<2, 3>*>(addressof(x)); };
swizzle_type<3, 0>& wx() noexcept { return *reinterpret_cast<swizzle_type<3, 0>*>(addressof(x)); };
swizzle_type<3, 1>& wy() noexcept { return *reinterpret_cast<swizzle_type<3, 1>*>(addressof(x)); };
swizzle_type<3, 2>& wz() noexcept { return *reinterpret_cast<swizzle_type<3, 2>*>(addressof(x)); };
swizzle_type<3, 3>& ww() noexcept { return *reinterpret_cast<swizzle_type<3, 3>*>(addressof(x)); };
auto xx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0>*>(addressof(x))); };
auto xy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1>*>(addressof(x))); };
auto xz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2>*>(addressof(x))); };
auto xw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3>*>(addressof(x))); };
auto yx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0>*>(addressof(x))); };
auto yy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1>*>(addressof(x))); };
auto yz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2>*>(addressof(x))); };
auto yw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3>*>(addressof(x))); };
auto zx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0>*>(addressof(x))); };
auto zy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1>*>(addressof(x))); };
auto zz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2>*>(addressof(x))); };
auto zw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3>*>(addressof(x))); };
auto wx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0>*>(addressof(x))); };
auto wy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1>*>(addressof(x))); };
auto wz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2>*>(addressof(x))); };
auto ww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3>*>(addressof(x))); };

swizzle_type<0, 0, 0>& xxx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1>& xxy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 0, 2>& xxz() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2>*>(addressof(x)); };
swizzle_type<0, 0, 3>& xxw() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3>*>(addressof(x)); };
swizzle_type<0, 1, 0>& xyx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1>& xyy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1>*>(addressof(x)); };
swizzle_type<0, 1, 2>& xyz() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2>*>(addressof(x)); };
swizzle_type<0, 1, 3>& xyw() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3>*>(addressof(x)); };
swizzle_type<0, 2, 0>& xzx() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0>*>(addressof(x)); };
swizzle_type<0, 2, 1>& xzy() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1>*>(addressof(x)); };
swizzle_type<0, 2, 2>& xzz() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2>*>(addressof(x)); };
swizzle_type<0, 2, 3>& xzw() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3>*>(addressof(x)); };
swizzle_type<0, 3, 0>& xwx() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0>*>(addressof(x)); };
swizzle_type<0, 3, 1>& xwy() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1>*>(addressof(x)); };
swizzle_type<0, 3, 2>& xwz() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2>*>(addressof(x)); };
swizzle_type<0, 3, 3>& xww() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3>*>(addressof(x)); };
swizzle_type<1, 0, 0>& yxx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1>& yxy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 0, 2>& yxz() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2>*>(addressof(x)); };
swizzle_type<1, 0, 3>& yxw() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3>*>(addressof(x)); };
swizzle_type<1, 1, 0>& yyx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1>& yyy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1>*>(addressof(x)); };
swizzle_type<1, 1, 2>& yyz() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2>*>(addressof(x)); };
swizzle_type<1, 1, 3>& yyw() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3>*>(addressof(x)); };
swizzle_type<1, 2, 0>& yzx() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0>*>(addressof(x)); };
swizzle_type<1, 2, 1>& yzy() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1>*>(addressof(x)); };
swizzle_type<1, 2, 2>& yzz() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2>*>(addressof(x)); };
swizzle_type<1, 2, 3>& yzw() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3>*>(addressof(x)); };
swizzle_type<1, 3, 0>& ywx() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0>*>(addressof(x)); };
swizzle_type<1, 3, 1>& ywy() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1>*>(addressof(x)); };
swizzle_type<1, 3, 2>& ywz() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2>*>(addressof(x)); };
swizzle_type<1, 3, 3>& yww() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3>*>(addressof(x)); };
swizzle_type<2, 0, 0>& zxx() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0>*>(addressof(x)); };
swizzle_type<2, 0, 1>& zxy() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1>*>(addressof(x)); };
swizzle_type<2, 0, 2>& zxz() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2>*>(addressof(x)); };
swizzle_type<2, 0, 3>& zxw() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3>*>(addressof(x)); };
swizzle_type<2, 1, 0>& zyx() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0>*>(addressof(x)); };
swizzle_type<2, 1, 1>& zyy() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1>*>(addressof(x)); };
swizzle_type<2, 1, 2>& zyz() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2>*>(addressof(x)); };
swizzle_type<2, 1, 3>& zyw() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3>*>(addressof(x)); };
swizzle_type<2, 2, 0>& zzx() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0>*>(addressof(x)); };
swizzle_type<2, 2, 1>& zzy() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1>*>(addressof(x)); };
swizzle_type<2, 2, 2>& zzz() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2>*>(addressof(x)); };
swizzle_type<2, 2, 3>& zzw() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3>*>(addressof(x)); };
swizzle_type<2, 3, 0>& zwx() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0>*>(addressof(x)); };
swizzle_type<2, 3, 1>& zwy() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1>*>(addressof(x)); };
swizzle_type<2, 3, 2>& zwz() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2>*>(addressof(x)); };
swizzle_type<2, 3, 3>& zww() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3>*>(addressof(x)); };
swizzle_type<3, 0, 0>& wxx() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0>*>(addressof(x)); };
swizzle_type<3, 0, 1>& wxy() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1>*>(addressof(x)); };
swizzle_type<3, 0, 2>& wxz() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2>*>(addressof(x)); };
swizzle_type<3, 0, 3>& wxw() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3>*>(addressof(x)); };
swizzle_type<3, 1, 0>& wyx() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0>*>(addressof(x)); };
swizzle_type<3, 1, 1>& wyy() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1>*>(addressof(x)); };
swizzle_type<3, 1, 2>& wyz() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2>*>(addressof(x)); };
swizzle_type<3, 1, 3>& wyw() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3>*>(addressof(x)); };
swizzle_type<3, 2, 0>& wzx() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0>*>(addressof(x)); };
swizzle_type<3, 2, 1>& wzy() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1>*>(addressof(x)); };
swizzle_type<3, 2, 2>& wzz() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2>*>(addressof(x)); };
swizzle_type<3, 2, 3>& wzw() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3>*>(addressof(x)); };
swizzle_type<3, 3, 0>& wwx() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0>*>(addressof(x)); };
swizzle_type<3, 3, 1>& wwy() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1>*>(addressof(x)); };
swizzle_type<3, 3, 2>& wwz() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2>*>(addressof(x)); };
swizzle_type<3, 3, 3>& www() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3>*>(addressof(x)); };
auto xxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0>*>(addressof(x))); };
auto xxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1>*>(addressof(x))); };
auto xxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2>*>(addressof(x))); };
auto xxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3>*>(addressof(x))); };
auto xyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0>*>(addressof(x))); };
auto xyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1>*>(addressof(x))); };
auto xyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2>*>(addressof(x))); };
auto xyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3>*>(addressof(x))); };
auto xzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0>*>(addressof(x))); };
auto xzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1>*>(addressof(x))); };
auto xzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2>*>(addressof(x))); };
auto xzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3>*>(addressof(x))); };
auto xwx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0>*>(addressof(x))); };
auto xwy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1>*>(addressof(x))); };
auto xwz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2>*>(addressof(x))); };
auto xww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3>*>(addressof(x))); };
auto yxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0>*>(addressof(x))); };
auto yxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1>*>(addressof(x))); };
auto yxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2>*>(addressof(x))); };
auto yxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3>*>(addressof(x))); };
auto yyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0>*>(addressof(x))); };
auto yyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1>*>(addressof(x))); };
auto yyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2>*>(addressof(x))); };
auto yyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3>*>(addressof(x))); };
auto yzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0>*>(addressof(x))); };
auto yzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1>*>(addressof(x))); };
auto yzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2>*>(addressof(x))); };
auto yzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3>*>(addressof(x))); };
auto ywx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0>*>(addressof(x))); };
auto ywy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1>*>(addressof(x))); };
auto ywz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2>*>(addressof(x))); };
auto yww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3>*>(addressof(x))); };
auto zxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0>*>(addressof(x))); };
auto zxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1>*>(addressof(x))); };
auto zxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2>*>(addressof(x))); };
auto zxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3>*>(addressof(x))); };
auto zyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0>*>(addressof(x))); };
auto zyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1>*>(addressof(x))); };
auto zyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2>*>(addressof(x))); };
auto zyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3>*>(addressof(x))); };
auto zzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0>*>(addressof(x))); };
auto zzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1>*>(addressof(x))); };
auto zzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2>*>(addressof(x))); };
auto zzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3>*>(addressof(x))); };
auto zwx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0>*>(addressof(x))); };
auto zwy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1>*>(addressof(x))); };
auto zwz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2>*>(addressof(x))); };
auto zww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3>*>(addressof(x))); };
auto wxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0>*>(addressof(x))); };
auto wxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1>*>(addressof(x))); };
auto wxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2>*>(addressof(x))); };
auto wxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3>*>(addressof(x))); };
auto wyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0>*>(addressof(x))); };
auto wyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1>*>(addressof(x))); };
auto wyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2>*>(addressof(x))); };
auto wyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3>*>(addressof(x))); };
auto wzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0>*>(addressof(x))); };
auto wzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1>*>(addressof(x))); };
auto wzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2>*>(addressof(x))); };
auto wzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3>*>(addressof(x))); };
auto wwx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0>*>(addressof(x))); };
auto wwy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1>*>(addressof(x))); };
auto wwz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2>*>(addressof(x))); };
auto www() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3>*>(addressof(x))); };

swizzle_type<0, 0, 0, 0>& xxxx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 0>*>(addressof(x)); };
swizzle_type<0, 0, 0, 1>& xxxy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 1>*>(addressof(x)); };
swizzle_type<0, 0, 0, 2>& xxxz() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 2>*>(addressof(x)); };
swizzle_type<0, 0, 0, 3>& xxxw() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 0, 3>*>(addressof(x)); };
swizzle_type<0, 0, 1, 0>& xxyx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 0>*>(addressof(x)); };
swizzle_type<0, 0, 1, 1>& xxyy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 1>*>(addressof(x)); };
swizzle_type<0, 0, 1, 2>& xxyz() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 2>*>(addressof(x)); };
swizzle_type<0, 0, 1, 3>& xxyw() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 1, 3>*>(addressof(x)); };
swizzle_type<0, 0, 2, 0>& xxzx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 0>*>(addressof(x)); };
swizzle_type<0, 0, 2, 1>& xxzy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 1>*>(addressof(x)); };
swizzle_type<0, 0, 2, 2>& xxzz() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 2>*>(addressof(x)); };
swizzle_type<0, 0, 2, 3>& xxzw() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 2, 3>*>(addressof(x)); };
swizzle_type<0, 0, 3, 0>& xxwx() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3, 0>*>(addressof(x)); };
swizzle_type<0, 0, 3, 1>& xxwy() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3, 1>*>(addressof(x)); };
swizzle_type<0, 0, 3, 2>& xxwz() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3, 2>*>(addressof(x)); };
swizzle_type<0, 0, 3, 3>& xxww() noexcept { return *reinterpret_cast<swizzle_type<0, 0, 3, 3>*>(addressof(x)); };
swizzle_type<0, 1, 0, 0>& xyxx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 0>*>(addressof(x)); };
swizzle_type<0, 1, 0, 1>& xyxy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 1>*>(addressof(x)); };
swizzle_type<0, 1, 0, 2>& xyxz() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 2>*>(addressof(x)); };
swizzle_type<0, 1, 0, 3>& xyxw() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 0, 3>*>(addressof(x)); };
swizzle_type<0, 1, 1, 0>& xyyx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 0>*>(addressof(x)); };
swizzle_type<0, 1, 1, 1>& xyyy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 1>*>(addressof(x)); };
swizzle_type<0, 1, 1, 2>& xyyz() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 2>*>(addressof(x)); };
swizzle_type<0, 1, 1, 3>& xyyw() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 1, 3>*>(addressof(x)); };
swizzle_type<0, 1, 2, 0>& xyzx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 0>*>(addressof(x)); };
swizzle_type<0, 1, 2, 1>& xyzy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 1>*>(addressof(x)); };
swizzle_type<0, 1, 2, 2>& xyzz() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 2>*>(addressof(x)); };
swizzle_type<0, 1, 2, 3>& xyzw() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 2, 3>*>(addressof(x)); };
swizzle_type<0, 1, 3, 0>& xywx() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3, 0>*>(addressof(x)); };
swizzle_type<0, 1, 3, 1>& xywy() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3, 1>*>(addressof(x)); };
swizzle_type<0, 1, 3, 2>& xywz() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3, 2>*>(addressof(x)); };
swizzle_type<0, 1, 3, 3>& xyww() noexcept { return *reinterpret_cast<swizzle_type<0, 1, 3, 3>*>(addressof(x)); };
swizzle_type<0, 2, 0, 0>& xzxx() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 0>*>(addressof(x)); };
swizzle_type<0, 2, 0, 1>& xzxy() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 1>*>(addressof(x)); };
swizzle_type<0, 2, 0, 2>& xzxz() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 2>*>(addressof(x)); };
swizzle_type<0, 2, 0, 3>& xzxw() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 0, 3>*>(addressof(x)); };
swizzle_type<0, 2, 1, 0>& xzyx() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 0>*>(addressof(x)); };
swizzle_type<0, 2, 1, 1>& xzyy() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 1>*>(addressof(x)); };
swizzle_type<0, 2, 1, 2>& xzyz() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 2>*>(addressof(x)); };
swizzle_type<0, 2, 1, 3>& xzyw() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 1, 3>*>(addressof(x)); };
swizzle_type<0, 2, 2, 0>& xzzx() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 0>*>(addressof(x)); };
swizzle_type<0, 2, 2, 1>& xzzy() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 1>*>(addressof(x)); };
swizzle_type<0, 2, 2, 2>& xzzz() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 2>*>(addressof(x)); };
swizzle_type<0, 2, 2, 3>& xzzw() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 2, 3>*>(addressof(x)); };
swizzle_type<0, 2, 3, 0>& xzwx() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3, 0>*>(addressof(x)); };
swizzle_type<0, 2, 3, 1>& xzwy() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3, 1>*>(addressof(x)); };
swizzle_type<0, 2, 3, 2>& xzwz() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3, 2>*>(addressof(x)); };
swizzle_type<0, 2, 3, 3>& xzww() noexcept { return *reinterpret_cast<swizzle_type<0, 2, 3, 3>*>(addressof(x)); };
swizzle_type<0, 3, 0, 0>& xwxx() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0, 0>*>(addressof(x)); };
swizzle_type<0, 3, 0, 1>& xwxy() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0, 1>*>(addressof(x)); };
swizzle_type<0, 3, 0, 2>& xwxz() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0, 2>*>(addressof(x)); };
swizzle_type<0, 3, 0, 3>& xwxw() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 0, 3>*>(addressof(x)); };
swizzle_type<0, 3, 1, 0>& xwyx() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1, 0>*>(addressof(x)); };
swizzle_type<0, 3, 1, 1>& xwyy() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1, 1>*>(addressof(x)); };
swizzle_type<0, 3, 1, 2>& xwyz() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1, 2>*>(addressof(x)); };
swizzle_type<0, 3, 1, 3>& xwyw() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 1, 3>*>(addressof(x)); };
swizzle_type<0, 3, 2, 0>& xwzx() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2, 0>*>(addressof(x)); };
swizzle_type<0, 3, 2, 1>& xwzy() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2, 1>*>(addressof(x)); };
swizzle_type<0, 3, 2, 2>& xwzz() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2, 2>*>(addressof(x)); };
swizzle_type<0, 3, 2, 3>& xwzw() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 2, 3>*>(addressof(x)); };
swizzle_type<0, 3, 3, 0>& xwwx() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3, 0>*>(addressof(x)); };
swizzle_type<0, 3, 3, 1>& xwwy() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3, 1>*>(addressof(x)); };
swizzle_type<0, 3, 3, 2>& xwwz() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3, 2>*>(addressof(x)); };
swizzle_type<0, 3, 3, 3>& xwww() noexcept { return *reinterpret_cast<swizzle_type<0, 3, 3, 3>*>(addressof(x)); };
swizzle_type<1, 0, 0, 0>& yxxx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 0>*>(addressof(x)); };
swizzle_type<1, 0, 0, 1>& yxxy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 1>*>(addressof(x)); };
swizzle_type<1, 0, 0, 2>& yxxz() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 2>*>(addressof(x)); };
swizzle_type<1, 0, 0, 3>& yxxw() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 0, 3>*>(addressof(x)); };
swizzle_type<1, 0, 1, 0>& yxyx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 0>*>(addressof(x)); };
swizzle_type<1, 0, 1, 1>& yxyy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 1>*>(addressof(x)); };
swizzle_type<1, 0, 1, 2>& yxyz() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 2>*>(addressof(x)); };
swizzle_type<1, 0, 1, 3>& yxyw() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 1, 3>*>(addressof(x)); };
swizzle_type<1, 0, 2, 0>& yxzx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 0>*>(addressof(x)); };
swizzle_type<1, 0, 2, 1>& yxzy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 1>*>(addressof(x)); };
swizzle_type<1, 0, 2, 2>& yxzz() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 2>*>(addressof(x)); };
swizzle_type<1, 0, 2, 3>& yxzw() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 2, 3>*>(addressof(x)); };
swizzle_type<1, 0, 3, 0>& yxwx() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3, 0>*>(addressof(x)); };
swizzle_type<1, 0, 3, 1>& yxwy() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3, 1>*>(addressof(x)); };
swizzle_type<1, 0, 3, 2>& yxwz() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3, 2>*>(addressof(x)); };
swizzle_type<1, 0, 3, 3>& yxww() noexcept { return *reinterpret_cast<swizzle_type<1, 0, 3, 3>*>(addressof(x)); };
swizzle_type<1, 1, 0, 0>& yyxx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 0>*>(addressof(x)); };
swizzle_type<1, 1, 0, 1>& yyxy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 1>*>(addressof(x)); };
swizzle_type<1, 1, 0, 2>& yyxz() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 2>*>(addressof(x)); };
swizzle_type<1, 1, 0, 3>& yyxw() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 0, 3>*>(addressof(x)); };
swizzle_type<1, 1, 1, 0>& yyyx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 0>*>(addressof(x)); };
swizzle_type<1, 1, 1, 1>& yyyy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 1>*>(addressof(x)); };
swizzle_type<1, 1, 1, 2>& yyyz() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 2>*>(addressof(x)); };
swizzle_type<1, 1, 1, 3>& yyyw() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 1, 3>*>(addressof(x)); };
swizzle_type<1, 1, 2, 0>& yyzx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 0>*>(addressof(x)); };
swizzle_type<1, 1, 2, 1>& yyzy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 1>*>(addressof(x)); };
swizzle_type<1, 1, 2, 2>& yyzz() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 2>*>(addressof(x)); };
swizzle_type<1, 1, 2, 3>& yyzw() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 2, 3>*>(addressof(x)); };
swizzle_type<1, 1, 3, 0>& yywx() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3, 0>*>(addressof(x)); };
swizzle_type<1, 1, 3, 1>& yywy() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3, 1>*>(addressof(x)); };
swizzle_type<1, 1, 3, 2>& yywz() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3, 2>*>(addressof(x)); };
swizzle_type<1, 1, 3, 3>& yyww() noexcept { return *reinterpret_cast<swizzle_type<1, 1, 3, 3>*>(addressof(x)); };
swizzle_type<1, 2, 0, 0>& yzxx() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 0>*>(addressof(x)); };
swizzle_type<1, 2, 0, 1>& yzxy() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 1>*>(addressof(x)); };
swizzle_type<1, 2, 0, 2>& yzxz() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 2>*>(addressof(x)); };
swizzle_type<1, 2, 0, 3>& yzxw() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 0, 3>*>(addressof(x)); };
swizzle_type<1, 2, 1, 0>& yzyx() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 0>*>(addressof(x)); };
swizzle_type<1, 2, 1, 1>& yzyy() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 1>*>(addressof(x)); };
swizzle_type<1, 2, 1, 2>& yzyz() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 2>*>(addressof(x)); };
swizzle_type<1, 2, 1, 3>& yzyw() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 1, 3>*>(addressof(x)); };
swizzle_type<1, 2, 2, 0>& yzzx() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 0>*>(addressof(x)); };
swizzle_type<1, 2, 2, 1>& yzzy() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 1>*>(addressof(x)); };
swizzle_type<1, 2, 2, 2>& yzzz() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 2>*>(addressof(x)); };
swizzle_type<1, 2, 2, 3>& yzzw() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 2, 3>*>(addressof(x)); };
swizzle_type<1, 2, 3, 0>& yzwx() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3, 0>*>(addressof(x)); };
swizzle_type<1, 2, 3, 1>& yzwy() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3, 1>*>(addressof(x)); };
swizzle_type<1, 2, 3, 2>& yzwz() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3, 2>*>(addressof(x)); };
swizzle_type<1, 2, 3, 3>& yzww() noexcept { return *reinterpret_cast<swizzle_type<1, 2, 3, 3>*>(addressof(x)); };
swizzle_type<1, 3, 0, 0>& ywxx() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0, 0>*>(addressof(x)); };
swizzle_type<1, 3, 0, 1>& ywxy() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0, 1>*>(addressof(x)); };
swizzle_type<1, 3, 0, 2>& ywxz() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0, 2>*>(addressof(x)); };
swizzle_type<1, 3, 0, 3>& ywxw() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 0, 3>*>(addressof(x)); };
swizzle_type<1, 3, 1, 0>& ywyx() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1, 0>*>(addressof(x)); };
swizzle_type<1, 3, 1, 1>& ywyy() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1, 1>*>(addressof(x)); };
swizzle_type<1, 3, 1, 2>& ywyz() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1, 2>*>(addressof(x)); };
swizzle_type<1, 3, 1, 3>& ywyw() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 1, 3>*>(addressof(x)); };
swizzle_type<1, 3, 2, 0>& ywzx() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2, 0>*>(addressof(x)); };
swizzle_type<1, 3, 2, 1>& ywzy() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2, 1>*>(addressof(x)); };
swizzle_type<1, 3, 2, 2>& ywzz() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2, 2>*>(addressof(x)); };
swizzle_type<1, 3, 2, 3>& ywzw() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 2, 3>*>(addressof(x)); };
swizzle_type<1, 3, 3, 0>& ywwx() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3, 0>*>(addressof(x)); };
swizzle_type<1, 3, 3, 1>& ywwy() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3, 1>*>(addressof(x)); };
swizzle_type<1, 3, 3, 2>& ywwz() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3, 2>*>(addressof(x)); };
swizzle_type<1, 3, 3, 3>& ywww() noexcept { return *reinterpret_cast<swizzle_type<1, 3, 3, 3>*>(addressof(x)); };
swizzle_type<2, 0, 0, 0>& zxxx() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 0>*>(addressof(x)); };
swizzle_type<2, 0, 0, 1>& zxxy() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 1>*>(addressof(x)); };
swizzle_type<2, 0, 0, 2>& zxxz() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 2>*>(addressof(x)); };
swizzle_type<2, 0, 0, 3>& zxxw() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 0, 3>*>(addressof(x)); };
swizzle_type<2, 0, 1, 0>& zxyx() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 0>*>(addressof(x)); };
swizzle_type<2, 0, 1, 1>& zxyy() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 1>*>(addressof(x)); };
swizzle_type<2, 0, 1, 2>& zxyz() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 2>*>(addressof(x)); };
swizzle_type<2, 0, 1, 3>& zxyw() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 1, 3>*>(addressof(x)); };
swizzle_type<2, 0, 2, 0>& zxzx() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 0>*>(addressof(x)); };
swizzle_type<2, 0, 2, 1>& zxzy() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 1>*>(addressof(x)); };
swizzle_type<2, 0, 2, 2>& zxzz() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 2>*>(addressof(x)); };
swizzle_type<2, 0, 2, 3>& zxzw() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 2, 3>*>(addressof(x)); };
swizzle_type<2, 0, 3, 0>& zxwx() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3, 0>*>(addressof(x)); };
swizzle_type<2, 0, 3, 1>& zxwy() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3, 1>*>(addressof(x)); };
swizzle_type<2, 0, 3, 2>& zxwz() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3, 2>*>(addressof(x)); };
swizzle_type<2, 0, 3, 3>& zxww() noexcept { return *reinterpret_cast<swizzle_type<2, 0, 3, 3>*>(addressof(x)); };
swizzle_type<2, 1, 0, 0>& zyxx() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 0>*>(addressof(x)); };
swizzle_type<2, 1, 0, 1>& zyxy() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 1>*>(addressof(x)); };
swizzle_type<2, 1, 0, 2>& zyxz() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 2>*>(addressof(x)); };
swizzle_type<2, 1, 0, 3>& zyxw() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 0, 3>*>(addressof(x)); };
swizzle_type<2, 1, 1, 0>& zyyx() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 0>*>(addressof(x)); };
swizzle_type<2, 1, 1, 1>& zyyy() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 1>*>(addressof(x)); };
swizzle_type<2, 1, 1, 2>& zyyz() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 2>*>(addressof(x)); };
swizzle_type<2, 1, 1, 3>& zyyw() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 1, 3>*>(addressof(x)); };
swizzle_type<2, 1, 2, 0>& zyzx() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 0>*>(addressof(x)); };
swizzle_type<2, 1, 2, 1>& zyzy() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 1>*>(addressof(x)); };
swizzle_type<2, 1, 2, 2>& zyzz() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 2>*>(addressof(x)); };
swizzle_type<2, 1, 2, 3>& zyzw() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 2, 3>*>(addressof(x)); };
swizzle_type<2, 1, 3, 0>& zywx() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3, 0>*>(addressof(x)); };
swizzle_type<2, 1, 3, 1>& zywy() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3, 1>*>(addressof(x)); };
swizzle_type<2, 1, 3, 2>& zywz() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3, 2>*>(addressof(x)); };
swizzle_type<2, 1, 3, 3>& zyww() noexcept { return *reinterpret_cast<swizzle_type<2, 1, 3, 3>*>(addressof(x)); };
swizzle_type<2, 2, 0, 0>& zzxx() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 0>*>(addressof(x)); };
swizzle_type<2, 2, 0, 1>& zzxy() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 1>*>(addressof(x)); };
swizzle_type<2, 2, 0, 2>& zzxz() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 2>*>(addressof(x)); };
swizzle_type<2, 2, 0, 3>& zzxw() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 0, 3>*>(addressof(x)); };
swizzle_type<2, 2, 1, 0>& zzyx() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 0>*>(addressof(x)); };
swizzle_type<2, 2, 1, 1>& zzyy() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 1>*>(addressof(x)); };
swizzle_type<2, 2, 1, 2>& zzyz() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 2>*>(addressof(x)); };
swizzle_type<2, 2, 1, 3>& zzyw() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 1, 3>*>(addressof(x)); };
swizzle_type<2, 2, 2, 0>& zzzx() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 0>*>(addressof(x)); };
swizzle_type<2, 2, 2, 1>& zzzy() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 1>*>(addressof(x)); };
swizzle_type<2, 2, 2, 2>& zzzz() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 2>*>(addressof(x)); };
swizzle_type<2, 2, 2, 3>& zzzw() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 2, 3>*>(addressof(x)); };
swizzle_type<2, 2, 3, 0>& zzwx() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3, 0>*>(addressof(x)); };
swizzle_type<2, 2, 3, 1>& zzwy() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3, 1>*>(addressof(x)); };
swizzle_type<2, 2, 3, 2>& zzwz() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3, 2>*>(addressof(x)); };
swizzle_type<2, 2, 3, 3>& zzww() noexcept { return *reinterpret_cast<swizzle_type<2, 2, 3, 3>*>(addressof(x)); };
swizzle_type<2, 3, 0, 0>& zwxx() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0, 0>*>(addressof(x)); };
swizzle_type<2, 3, 0, 1>& zwxy() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0, 1>*>(addressof(x)); };
swizzle_type<2, 3, 0, 2>& zwxz() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0, 2>*>(addressof(x)); };
swizzle_type<2, 3, 0, 3>& zwxw() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 0, 3>*>(addressof(x)); };
swizzle_type<2, 3, 1, 0>& zwyx() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1, 0>*>(addressof(x)); };
swizzle_type<2, 3, 1, 1>& zwyy() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1, 1>*>(addressof(x)); };
swizzle_type<2, 3, 1, 2>& zwyz() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1, 2>*>(addressof(x)); };
swizzle_type<2, 3, 1, 3>& zwyw() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 1, 3>*>(addressof(x)); };
swizzle_type<2, 3, 2, 0>& zwzx() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2, 0>*>(addressof(x)); };
swizzle_type<2, 3, 2, 1>& zwzy() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2, 1>*>(addressof(x)); };
swizzle_type<2, 3, 2, 2>& zwzz() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2, 2>*>(addressof(x)); };
swizzle_type<2, 3, 2, 3>& zwzw() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 2, 3>*>(addressof(x)); };
swizzle_type<2, 3, 3, 0>& zwwx() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3, 0>*>(addressof(x)); };
swizzle_type<2, 3, 3, 1>& zwwy() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3, 1>*>(addressof(x)); };
swizzle_type<2, 3, 3, 2>& zwwz() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3, 2>*>(addressof(x)); };
swizzle_type<2, 3, 3, 3>& zwww() noexcept { return *reinterpret_cast<swizzle_type<2, 3, 3, 3>*>(addressof(x)); };
swizzle_type<3, 0, 0, 0>& wxxx() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0, 0>*>(addressof(x)); };
swizzle_type<3, 0, 0, 1>& wxxy() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0, 1>*>(addressof(x)); };
swizzle_type<3, 0, 0, 2>& wxxz() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0, 2>*>(addressof(x)); };
swizzle_type<3, 0, 0, 3>& wxxw() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 0, 3>*>(addressof(x)); };
swizzle_type<3, 0, 1, 0>& wxyx() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1, 0>*>(addressof(x)); };
swizzle_type<3, 0, 1, 1>& wxyy() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1, 1>*>(addressof(x)); };
swizzle_type<3, 0, 1, 2>& wxyz() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1, 2>*>(addressof(x)); };
swizzle_type<3, 0, 1, 3>& wxyw() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 1, 3>*>(addressof(x)); };
swizzle_type<3, 0, 2, 0>& wxzx() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2, 0>*>(addressof(x)); };
swizzle_type<3, 0, 2, 1>& wxzy() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2, 1>*>(addressof(x)); };
swizzle_type<3, 0, 2, 2>& wxzz() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2, 2>*>(addressof(x)); };
swizzle_type<3, 0, 2, 3>& wxzw() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 2, 3>*>(addressof(x)); };
swizzle_type<3, 0, 3, 0>& wxwx() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3, 0>*>(addressof(x)); };
swizzle_type<3, 0, 3, 1>& wxwy() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3, 1>*>(addressof(x)); };
swizzle_type<3, 0, 3, 2>& wxwz() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3, 2>*>(addressof(x)); };
swizzle_type<3, 0, 3, 3>& wxww() noexcept { return *reinterpret_cast<swizzle_type<3, 0, 3, 3>*>(addressof(x)); };
swizzle_type<3, 1, 0, 0>& wyxx() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0, 0>*>(addressof(x)); };
swizzle_type<3, 1, 0, 1>& wyxy() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0, 1>*>(addressof(x)); };
swizzle_type<3, 1, 0, 2>& wyxz() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0, 2>*>(addressof(x)); };
swizzle_type<3, 1, 0, 3>& wyxw() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 0, 3>*>(addressof(x)); };
swizzle_type<3, 1, 1, 0>& wyyx() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1, 0>*>(addressof(x)); };
swizzle_type<3, 1, 1, 1>& wyyy() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1, 1>*>(addressof(x)); };
swizzle_type<3, 1, 1, 2>& wyyz() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1, 2>*>(addressof(x)); };
swizzle_type<3, 1, 1, 3>& wyyw() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 1, 3>*>(addressof(x)); };
swizzle_type<3, 1, 2, 0>& wyzx() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2, 0>*>(addressof(x)); };
swizzle_type<3, 1, 2, 1>& wyzy() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2, 1>*>(addressof(x)); };
swizzle_type<3, 1, 2, 2>& wyzz() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2, 2>*>(addressof(x)); };
swizzle_type<3, 1, 2, 3>& wyzw() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 2, 3>*>(addressof(x)); };
swizzle_type<3, 1, 3, 0>& wywx() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3, 0>*>(addressof(x)); };
swizzle_type<3, 1, 3, 1>& wywy() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3, 1>*>(addressof(x)); };
swizzle_type<3, 1, 3, 2>& wywz() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3, 2>*>(addressof(x)); };
swizzle_type<3, 1, 3, 3>& wyww() noexcept { return *reinterpret_cast<swizzle_type<3, 1, 3, 3>*>(addressof(x)); };
swizzle_type<3, 2, 0, 0>& wzxx() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0, 0>*>(addressof(x)); };
swizzle_type<3, 2, 0, 1>& wzxy() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0, 1>*>(addressof(x)); };
swizzle_type<3, 2, 0, 2>& wzxz() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0, 2>*>(addressof(x)); };
swizzle_type<3, 2, 0, 3>& wzxw() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 0, 3>*>(addressof(x)); };
swizzle_type<3, 2, 1, 0>& wzyx() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1, 0>*>(addressof(x)); };
swizzle_type<3, 2, 1, 1>& wzyy() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1, 1>*>(addressof(x)); };
swizzle_type<3, 2, 1, 2>& wzyz() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1, 2>*>(addressof(x)); };
swizzle_type<3, 2, 1, 3>& wzyw() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 1, 3>*>(addressof(x)); };
swizzle_type<3, 2, 2, 0>& wzzx() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2, 0>*>(addressof(x)); };
swizzle_type<3, 2, 2, 1>& wzzy() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2, 1>*>(addressof(x)); };
swizzle_type<3, 2, 2, 2>& wzzz() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2, 2>*>(addressof(x)); };
swizzle_type<3, 2, 2, 3>& wzzw() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 2, 3>*>(addressof(x)); };
swizzle_type<3, 2, 3, 0>& wzwx() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3, 0>*>(addressof(x)); };
swizzle_type<3, 2, 3, 1>& wzwy() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3, 1>*>(addressof(x)); };
swizzle_type<3, 2, 3, 2>& wzwz() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3, 2>*>(addressof(x)); };
swizzle_type<3, 2, 3, 3>& wzww() noexcept { return *reinterpret_cast<swizzle_type<3, 2, 3, 3>*>(addressof(x)); };
swizzle_type<3, 3, 0, 0>& wwxx() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0, 0>*>(addressof(x)); };
swizzle_type<3, 3, 0, 1>& wwxy() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0, 1>*>(addressof(x)); };
swizzle_type<3, 3, 0, 2>& wwxz() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0, 2>*>(addressof(x)); };
swizzle_type<3, 3, 0, 3>& wwxw() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 0, 3>*>(addressof(x)); };
swizzle_type<3, 3, 1, 0>& wwyx() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1, 0>*>(addressof(x)); };
swizzle_type<3, 3, 1, 1>& wwyy() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1, 1>*>(addressof(x)); };
swizzle_type<3, 3, 1, 2>& wwyz() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1, 2>*>(addressof(x)); };
swizzle_type<3, 3, 1, 3>& wwyw() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 1, 3>*>(addressof(x)); };
swizzle_type<3, 3, 2, 0>& wwzx() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2, 0>*>(addressof(x)); };
swizzle_type<3, 3, 2, 1>& wwzy() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2, 1>*>(addressof(x)); };
swizzle_type<3, 3, 2, 2>& wwzz() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2, 2>*>(addressof(x)); };
swizzle_type<3, 3, 2, 3>& wwzw() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 2, 3>*>(addressof(x)); };
swizzle_type<3, 3, 3, 0>& wwwx() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3, 0>*>(addressof(x)); };
swizzle_type<3, 3, 3, 1>& wwwy() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3, 1>*>(addressof(x)); };
swizzle_type<3, 3, 3, 2>& wwwz() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3, 2>*>(addressof(x)); };
swizzle_type<3, 3, 3, 3>& wwww() noexcept { return *reinterpret_cast<swizzle_type<3, 3, 3, 3>*>(addressof(x)); };
auto xxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 0>*>(addressof(x))); };
auto xxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 1>*>(addressof(x))); };
auto xxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 2>*>(addressof(x))); };
auto xxxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 0, 3>*>(addressof(x))); };
auto xxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 0>*>(addressof(x))); };
auto xxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 1>*>(addressof(x))); };
auto xxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 2>*>(addressof(x))); };
auto xxyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 1, 3>*>(addressof(x))); };
auto xxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 0>*>(addressof(x))); };
auto xxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 1>*>(addressof(x))); };
auto xxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 2>*>(addressof(x))); };
auto xxzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 2, 3>*>(addressof(x))); };
auto xxwx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3, 0>*>(addressof(x))); };
auto xxwy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3, 1>*>(addressof(x))); };
auto xxwz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3, 2>*>(addressof(x))); };
auto xxww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 0, 3, 3>*>(addressof(x))); };
auto xyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 0>*>(addressof(x))); };
auto xyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 1>*>(addressof(x))); };
auto xyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 2>*>(addressof(x))); };
auto xyxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 0, 3>*>(addressof(x))); };
auto xyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 0>*>(addressof(x))); };
auto xyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 1>*>(addressof(x))); };
auto xyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 2>*>(addressof(x))); };
auto xyyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 1, 3>*>(addressof(x))); };
auto xyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 0>*>(addressof(x))); };
auto xyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 1>*>(addressof(x))); };
auto xyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 2>*>(addressof(x))); };
auto xyzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 2, 3>*>(addressof(x))); };
auto xywx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3, 0>*>(addressof(x))); };
auto xywy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3, 1>*>(addressof(x))); };
auto xywz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3, 2>*>(addressof(x))); };
auto xyww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 1, 3, 3>*>(addressof(x))); };
auto xzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 0>*>(addressof(x))); };
auto xzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 1>*>(addressof(x))); };
auto xzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 2>*>(addressof(x))); };
auto xzxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 0, 3>*>(addressof(x))); };
auto xzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 0>*>(addressof(x))); };
auto xzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 1>*>(addressof(x))); };
auto xzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 2>*>(addressof(x))); };
auto xzyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 1, 3>*>(addressof(x))); };
auto xzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 0>*>(addressof(x))); };
auto xzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 1>*>(addressof(x))); };
auto xzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 2>*>(addressof(x))); };
auto xzzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 2, 3>*>(addressof(x))); };
auto xzwx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3, 0>*>(addressof(x))); };
auto xzwy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3, 1>*>(addressof(x))); };
auto xzwz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3, 2>*>(addressof(x))); };
auto xzww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 2, 3, 3>*>(addressof(x))); };
auto xwxx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0, 0>*>(addressof(x))); };
auto xwxy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0, 1>*>(addressof(x))); };
auto xwxz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0, 2>*>(addressof(x))); };
auto xwxw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 0, 3>*>(addressof(x))); };
auto xwyx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1, 0>*>(addressof(x))); };
auto xwyy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1, 1>*>(addressof(x))); };
auto xwyz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1, 2>*>(addressof(x))); };
auto xwyw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 1, 3>*>(addressof(x))); };
auto xwzx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2, 0>*>(addressof(x))); };
auto xwzy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2, 1>*>(addressof(x))); };
auto xwzz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2, 2>*>(addressof(x))); };
auto xwzw() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 2, 3>*>(addressof(x))); };
auto xwwx() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3, 0>*>(addressof(x))); };
auto xwwy() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3, 1>*>(addressof(x))); };
auto xwwz() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3, 2>*>(addressof(x))); };
auto xwww() const noexcept { return (*reinterpret_cast<const swizzle_type<0, 3, 3, 3>*>(addressof(x))); };
auto yxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 0>*>(addressof(x))); };
auto yxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 1>*>(addressof(x))); };
auto yxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 2>*>(addressof(x))); };
auto yxxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 0, 3>*>(addressof(x))); };
auto yxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 0>*>(addressof(x))); };
auto yxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 1>*>(addressof(x))); };
auto yxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 2>*>(addressof(x))); };
auto yxyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 1, 3>*>(addressof(x))); };
auto yxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 0>*>(addressof(x))); };
auto yxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 1>*>(addressof(x))); };
auto yxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 2>*>(addressof(x))); };
auto yxzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 2, 3>*>(addressof(x))); };
auto yxwx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3, 0>*>(addressof(x))); };
auto yxwy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3, 1>*>(addressof(x))); };
auto yxwz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3, 2>*>(addressof(x))); };
auto yxww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 0, 3, 3>*>(addressof(x))); };
auto yyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 0>*>(addressof(x))); };
auto yyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 1>*>(addressof(x))); };
auto yyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 2>*>(addressof(x))); };
auto yyxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 0, 3>*>(addressof(x))); };
auto yyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 0>*>(addressof(x))); };
auto yyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 1>*>(addressof(x))); };
auto yyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 2>*>(addressof(x))); };
auto yyyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 1, 3>*>(addressof(x))); };
auto yyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 0>*>(addressof(x))); };
auto yyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 1>*>(addressof(x))); };
auto yyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 2>*>(addressof(x))); };
auto yyzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 2, 3>*>(addressof(x))); };
auto yywx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3, 0>*>(addressof(x))); };
auto yywy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3, 1>*>(addressof(x))); };
auto yywz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3, 2>*>(addressof(x))); };
auto yyww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 1, 3, 3>*>(addressof(x))); };
auto yzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 0>*>(addressof(x))); };
auto yzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 1>*>(addressof(x))); };
auto yzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 2>*>(addressof(x))); };
auto yzxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 0, 3>*>(addressof(x))); };
auto yzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 0>*>(addressof(x))); };
auto yzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 1>*>(addressof(x))); };
auto yzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 2>*>(addressof(x))); };
auto yzyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 1, 3>*>(addressof(x))); };
auto yzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 0>*>(addressof(x))); };
auto yzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 1>*>(addressof(x))); };
auto yzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 2>*>(addressof(x))); };
auto yzzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 2, 3>*>(addressof(x))); };
auto yzwx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3, 0>*>(addressof(x))); };
auto yzwy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3, 1>*>(addressof(x))); };
auto yzwz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3, 2>*>(addressof(x))); };
auto yzww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 2, 3, 3>*>(addressof(x))); };
auto ywxx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0, 0>*>(addressof(x))); };
auto ywxy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0, 1>*>(addressof(x))); };
auto ywxz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0, 2>*>(addressof(x))); };
auto ywxw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 0, 3>*>(addressof(x))); };
auto ywyx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1, 0>*>(addressof(x))); };
auto ywyy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1, 1>*>(addressof(x))); };
auto ywyz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1, 2>*>(addressof(x))); };
auto ywyw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 1, 3>*>(addressof(x))); };
auto ywzx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2, 0>*>(addressof(x))); };
auto ywzy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2, 1>*>(addressof(x))); };
auto ywzz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2, 2>*>(addressof(x))); };
auto ywzw() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 2, 3>*>(addressof(x))); };
auto ywwx() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3, 0>*>(addressof(x))); };
auto ywwy() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3, 1>*>(addressof(x))); };
auto ywwz() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3, 2>*>(addressof(x))); };
auto ywww() const noexcept { return (*reinterpret_cast<const swizzle_type<1, 3, 3, 3>*>(addressof(x))); };
auto zxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 0>*>(addressof(x))); };
auto zxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 1>*>(addressof(x))); };
auto zxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 2>*>(addressof(x))); };
auto zxxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 0, 3>*>(addressof(x))); };
auto zxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 0>*>(addressof(x))); };
auto zxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 1>*>(addressof(x))); };
auto zxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 2>*>(addressof(x))); };
auto zxyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 1, 3>*>(addressof(x))); };
auto zxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 0>*>(addressof(x))); };
auto zxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 1>*>(addressof(x))); };
auto zxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 2>*>(addressof(x))); };
auto zxzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 2, 3>*>(addressof(x))); };
auto zxwx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3, 0>*>(addressof(x))); };
auto zxwy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3, 1>*>(addressof(x))); };
auto zxwz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3, 2>*>(addressof(x))); };
auto zxww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 0, 3, 3>*>(addressof(x))); };
auto zyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 0>*>(addressof(x))); };
auto zyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 1>*>(addressof(x))); };
auto zyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 2>*>(addressof(x))); };
auto zyxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 0, 3>*>(addressof(x))); };
auto zyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 0>*>(addressof(x))); };
auto zyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 1>*>(addressof(x))); };
auto zyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 2>*>(addressof(x))); };
auto zyyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 1, 3>*>(addressof(x))); };
auto zyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 0>*>(addressof(x))); };
auto zyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 1>*>(addressof(x))); };
auto zyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 2>*>(addressof(x))); };
auto zyzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 2, 3>*>(addressof(x))); };
auto zywx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3, 0>*>(addressof(x))); };
auto zywy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3, 1>*>(addressof(x))); };
auto zywz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3, 2>*>(addressof(x))); };
auto zyww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 1, 3, 3>*>(addressof(x))); };
auto zzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 0>*>(addressof(x))); };
auto zzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 1>*>(addressof(x))); };
auto zzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 2>*>(addressof(x))); };
auto zzxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 0, 3>*>(addressof(x))); };
auto zzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 0>*>(addressof(x))); };
auto zzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 1>*>(addressof(x))); };
auto zzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 2>*>(addressof(x))); };
auto zzyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 1, 3>*>(addressof(x))); };
auto zzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 0>*>(addressof(x))); };
auto zzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 1>*>(addressof(x))); };
auto zzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 2>*>(addressof(x))); };
auto zzzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 2, 3>*>(addressof(x))); };
auto zzwx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3, 0>*>(addressof(x))); };
auto zzwy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3, 1>*>(addressof(x))); };
auto zzwz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3, 2>*>(addressof(x))); };
auto zzww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 2, 3, 3>*>(addressof(x))); };
auto zwxx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0, 0>*>(addressof(x))); };
auto zwxy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0, 1>*>(addressof(x))); };
auto zwxz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0, 2>*>(addressof(x))); };
auto zwxw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 0, 3>*>(addressof(x))); };
auto zwyx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1, 0>*>(addressof(x))); };
auto zwyy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1, 1>*>(addressof(x))); };
auto zwyz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1, 2>*>(addressof(x))); };
auto zwyw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 1, 3>*>(addressof(x))); };
auto zwzx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2, 0>*>(addressof(x))); };
auto zwzy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2, 1>*>(addressof(x))); };
auto zwzz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2, 2>*>(addressof(x))); };
auto zwzw() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 2, 3>*>(addressof(x))); };
auto zwwx() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3, 0>*>(addressof(x))); };
auto zwwy() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3, 1>*>(addressof(x))); };
auto zwwz() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3, 2>*>(addressof(x))); };
auto zwww() const noexcept { return (*reinterpret_cast<const swizzle_type<2, 3, 3, 3>*>(addressof(x))); };
auto wxxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0, 0>*>(addressof(x))); };
auto wxxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0, 1>*>(addressof(x))); };
auto wxxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0, 2>*>(addressof(x))); };
auto wxxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 0, 3>*>(addressof(x))); };
auto wxyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1, 0>*>(addressof(x))); };
auto wxyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1, 1>*>(addressof(x))); };
auto wxyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1, 2>*>(addressof(x))); };
auto wxyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 1, 3>*>(addressof(x))); };
auto wxzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2, 0>*>(addressof(x))); };
auto wxzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2, 1>*>(addressof(x))); };
auto wxzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2, 2>*>(addressof(x))); };
auto wxzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 2, 3>*>(addressof(x))); };
auto wxwx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3, 0>*>(addressof(x))); };
auto wxwy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3, 1>*>(addressof(x))); };
auto wxwz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3, 2>*>(addressof(x))); };
auto wxww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 0, 3, 3>*>(addressof(x))); };
auto wyxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0, 0>*>(addressof(x))); };
auto wyxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0, 1>*>(addressof(x))); };
auto wyxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0, 2>*>(addressof(x))); };
auto wyxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 0, 3>*>(addressof(x))); };
auto wyyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1, 0>*>(addressof(x))); };
auto wyyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1, 1>*>(addressof(x))); };
auto wyyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1, 2>*>(addressof(x))); };
auto wyyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 1, 3>*>(addressof(x))); };
auto wyzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2, 0>*>(addressof(x))); };
auto wyzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2, 1>*>(addressof(x))); };
auto wyzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2, 2>*>(addressof(x))); };
auto wyzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 2, 3>*>(addressof(x))); };
auto wywx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3, 0>*>(addressof(x))); };
auto wywy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3, 1>*>(addressof(x))); };
auto wywz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3, 2>*>(addressof(x))); };
auto wyww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 1, 3, 3>*>(addressof(x))); };
auto wzxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0, 0>*>(addressof(x))); };
auto wzxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0, 1>*>(addressof(x))); };
auto wzxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0, 2>*>(addressof(x))); };
auto wzxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 0, 3>*>(addressof(x))); };
auto wzyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1, 0>*>(addressof(x))); };
auto wzyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1, 1>*>(addressof(x))); };
auto wzyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1, 2>*>(addressof(x))); };
auto wzyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 1, 3>*>(addressof(x))); };
auto wzzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2, 0>*>(addressof(x))); };
auto wzzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2, 1>*>(addressof(x))); };
auto wzzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2, 2>*>(addressof(x))); };
auto wzzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 2, 3>*>(addressof(x))); };
auto wzwx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3, 0>*>(addressof(x))); };
auto wzwy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3, 1>*>(addressof(x))); };
auto wzwz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3, 2>*>(addressof(x))); };
auto wzww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 2, 3, 3>*>(addressof(x))); };
auto wwxx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0, 0>*>(addressof(x))); };
auto wwxy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0, 1>*>(addressof(x))); };
auto wwxz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0, 2>*>(addressof(x))); };
auto wwxw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 0, 3>*>(addressof(x))); };
auto wwyx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1, 0>*>(addressof(x))); };
auto wwyy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1, 1>*>(addressof(x))); };
auto wwyz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1, 2>*>(addressof(x))); };
auto wwyw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 1, 3>*>(addressof(x))); };
auto wwzx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2, 0>*>(addressof(x))); };
auto wwzy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2, 1>*>(addressof(x))); };
auto wwzz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2, 2>*>(addressof(x))); };
auto wwzw() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 2, 3>*>(addressof(x))); };
auto wwwx() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3, 0>*>(addressof(x))); };
auto wwwy() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3, 1>*>(addressof(x))); };
auto wwwz() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3, 2>*>(addressof(x))); };
auto wwww() const noexcept { return (*reinterpret_cast<const swizzle_type<3, 3, 3, 3>*>(addressof(x))); };
