[[nodiscard]] auto xx() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x00, 2)); }
[[nodiscard]] auto xy() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x01, 2)); }
[[nodiscard]] auto xz() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x02, 2)); }
[[nodiscard]] auto xw() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x03, 2)); }
[[nodiscard]] auto yx() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x10, 2)); }
[[nodiscard]] auto yy() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x11, 2)); }
[[nodiscard]] auto yz() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x12, 2)); }
[[nodiscard]] auto yw() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x13, 2)); }
[[nodiscard]] auto zx() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x20, 2)); }
[[nodiscard]] auto zy() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x21, 2)); }
[[nodiscard]] auto zz() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x22, 2)); }
[[nodiscard]] auto zw() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x23, 2)); }
[[nodiscard]] auto wx() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x30, 2)); }
[[nodiscard]] auto wy() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x31, 2)); }
[[nodiscard]] auto wz() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x32, 2)); }
[[nodiscard]] auto ww() { return def<Vector<T, 2>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x33, 2)); }

[[nodiscard]] auto xxx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x000, 3)); }
[[nodiscard]] auto xxy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x001, 3)); }
[[nodiscard]] auto xxz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x002, 3)); }
[[nodiscard]] auto xxw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x003, 3)); }
[[nodiscard]] auto xyx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x010, 3)); }
[[nodiscard]] auto xyy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x011, 3)); }
[[nodiscard]] auto xyz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x012, 3)); }
[[nodiscard]] auto xyw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x013, 3)); }
[[nodiscard]] auto xzx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x020, 3)); }
[[nodiscard]] auto xzy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x021, 3)); }
[[nodiscard]] auto xzz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x022, 3)); }
[[nodiscard]] auto xzw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x023, 3)); }
[[nodiscard]] auto xwx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x030, 3)); }
[[nodiscard]] auto xwy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x031, 3)); }
[[nodiscard]] auto xwz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x032, 3)); }
[[nodiscard]] auto xww() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x033, 3)); }
[[nodiscard]] auto yxx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x100, 3)); }
[[nodiscard]] auto yxy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x101, 3)); }
[[nodiscard]] auto yxz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x102, 3)); }
[[nodiscard]] auto yxw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x103, 3)); }
[[nodiscard]] auto yyx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x110, 3)); }
[[nodiscard]] auto yyy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x111, 3)); }
[[nodiscard]] auto yyz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x112, 3)); }
[[nodiscard]] auto yyw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x113, 3)); }
[[nodiscard]] auto yzx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x120, 3)); }
[[nodiscard]] auto yzy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x121, 3)); }
[[nodiscard]] auto yzz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x122, 3)); }
[[nodiscard]] auto yzw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x123, 3)); }
[[nodiscard]] auto ywx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x130, 3)); }
[[nodiscard]] auto ywy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x131, 3)); }
[[nodiscard]] auto ywz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x132, 3)); }
[[nodiscard]] auto yww() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x133, 3)); }
[[nodiscard]] auto zxx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x200, 3)); }
[[nodiscard]] auto zxy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x201, 3)); }
[[nodiscard]] auto zxz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x202, 3)); }
[[nodiscard]] auto zxw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x203, 3)); }
[[nodiscard]] auto zyx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x210, 3)); }
[[nodiscard]] auto zyy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x211, 3)); }
[[nodiscard]] auto zyz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x212, 3)); }
[[nodiscard]] auto zyw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x213, 3)); }
[[nodiscard]] auto zzx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x220, 3)); }
[[nodiscard]] auto zzy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x221, 3)); }
[[nodiscard]] auto zzz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x222, 3)); }
[[nodiscard]] auto zzw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x223, 3)); }
[[nodiscard]] auto zwx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x230, 3)); }
[[nodiscard]] auto zwy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x231, 3)); }
[[nodiscard]] auto zwz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x232, 3)); }
[[nodiscard]] auto zww() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x233, 3)); }
[[nodiscard]] auto wxx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x300, 3)); }
[[nodiscard]] auto wxy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x301, 3)); }
[[nodiscard]] auto wxz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x302, 3)); }
[[nodiscard]] auto wxw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x303, 3)); }
[[nodiscard]] auto wyx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x310, 3)); }
[[nodiscard]] auto wyy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x311, 3)); }
[[nodiscard]] auto wyz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x312, 3)); }
[[nodiscard]] auto wyw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x313, 3)); }
[[nodiscard]] auto wzx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x320, 3)); }
[[nodiscard]] auto wzy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x321, 3)); }
[[nodiscard]] auto wzz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x322, 3)); }
[[nodiscard]] auto wzw() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x323, 3)); }
[[nodiscard]] auto wwx() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x330, 3)); }
[[nodiscard]] auto wwy() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x331, 3)); }
[[nodiscard]] auto wwz() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x332, 3)); }
[[nodiscard]] auto www() { return def<Vector<T, 3>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x333, 3)); }

[[nodiscard]] auto xxxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0000, 4)); }
[[nodiscard]] auto xxxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0001, 4)); }
[[nodiscard]] auto xxxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0002, 4)); }
[[nodiscard]] auto xxxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0003, 4)); }
[[nodiscard]] auto xxyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0010, 4)); }
[[nodiscard]] auto xxyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0011, 4)); }
[[nodiscard]] auto xxyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0012, 4)); }
[[nodiscard]] auto xxyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0013, 4)); }
[[nodiscard]] auto xxzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0020, 4)); }
[[nodiscard]] auto xxzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0021, 4)); }
[[nodiscard]] auto xxzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0022, 4)); }
[[nodiscard]] auto xxzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0023, 4)); }
[[nodiscard]] auto xxwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0030, 4)); }
[[nodiscard]] auto xxwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0031, 4)); }
[[nodiscard]] auto xxwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0032, 4)); }
[[nodiscard]] auto xxww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0033, 4)); }
[[nodiscard]] auto xyxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0100, 4)); }
[[nodiscard]] auto xyxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0101, 4)); }
[[nodiscard]] auto xyxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0102, 4)); }
[[nodiscard]] auto xyxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0103, 4)); }
[[nodiscard]] auto xyyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0110, 4)); }
[[nodiscard]] auto xyyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0111, 4)); }
[[nodiscard]] auto xyyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0112, 4)); }
[[nodiscard]] auto xyyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0113, 4)); }
[[nodiscard]] auto xyzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0120, 4)); }
[[nodiscard]] auto xyzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0121, 4)); }
[[nodiscard]] auto xyzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0122, 4)); }
[[nodiscard]] auto xyzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0123, 4)); }
[[nodiscard]] auto xywx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0130, 4)); }
[[nodiscard]] auto xywy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0131, 4)); }
[[nodiscard]] auto xywz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0132, 4)); }
[[nodiscard]] auto xyww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0133, 4)); }
[[nodiscard]] auto xzxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0200, 4)); }
[[nodiscard]] auto xzxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0201, 4)); }
[[nodiscard]] auto xzxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0202, 4)); }
[[nodiscard]] auto xzxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0203, 4)); }
[[nodiscard]] auto xzyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0210, 4)); }
[[nodiscard]] auto xzyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0211, 4)); }
[[nodiscard]] auto xzyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0212, 4)); }
[[nodiscard]] auto xzyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0213, 4)); }
[[nodiscard]] auto xzzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0220, 4)); }
[[nodiscard]] auto xzzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0221, 4)); }
[[nodiscard]] auto xzzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0222, 4)); }
[[nodiscard]] auto xzzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0223, 4)); }
[[nodiscard]] auto xzwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0230, 4)); }
[[nodiscard]] auto xzwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0231, 4)); }
[[nodiscard]] auto xzwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0232, 4)); }
[[nodiscard]] auto xzww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0233, 4)); }
[[nodiscard]] auto xwxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0300, 4)); }
[[nodiscard]] auto xwxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0301, 4)); }
[[nodiscard]] auto xwxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0302, 4)); }
[[nodiscard]] auto xwxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0303, 4)); }
[[nodiscard]] auto xwyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0310, 4)); }
[[nodiscard]] auto xwyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0311, 4)); }
[[nodiscard]] auto xwyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0312, 4)); }
[[nodiscard]] auto xwyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0313, 4)); }
[[nodiscard]] auto xwzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0320, 4)); }
[[nodiscard]] auto xwzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0321, 4)); }
[[nodiscard]] auto xwzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0322, 4)); }
[[nodiscard]] auto xwzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0323, 4)); }
[[nodiscard]] auto xwwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0330, 4)); }
[[nodiscard]] auto xwwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0331, 4)); }
[[nodiscard]] auto xwwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0332, 4)); }
[[nodiscard]] auto xwww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x0333, 4)); }
[[nodiscard]] auto yxxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1000, 4)); }
[[nodiscard]] auto yxxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1001, 4)); }
[[nodiscard]] auto yxxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1002, 4)); }
[[nodiscard]] auto yxxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1003, 4)); }
[[nodiscard]] auto yxyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1010, 4)); }
[[nodiscard]] auto yxyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1011, 4)); }
[[nodiscard]] auto yxyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1012, 4)); }
[[nodiscard]] auto yxyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1013, 4)); }
[[nodiscard]] auto yxzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1020, 4)); }
[[nodiscard]] auto yxzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1021, 4)); }
[[nodiscard]] auto yxzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1022, 4)); }
[[nodiscard]] auto yxzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1023, 4)); }
[[nodiscard]] auto yxwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1030, 4)); }
[[nodiscard]] auto yxwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1031, 4)); }
[[nodiscard]] auto yxwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1032, 4)); }
[[nodiscard]] auto yxww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1033, 4)); }
[[nodiscard]] auto yyxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1100, 4)); }
[[nodiscard]] auto yyxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1101, 4)); }
[[nodiscard]] auto yyxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1102, 4)); }
[[nodiscard]] auto yyxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1103, 4)); }
[[nodiscard]] auto yyyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1110, 4)); }
[[nodiscard]] auto yyyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1111, 4)); }
[[nodiscard]] auto yyyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1112, 4)); }
[[nodiscard]] auto yyyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1113, 4)); }
[[nodiscard]] auto yyzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1120, 4)); }
[[nodiscard]] auto yyzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1121, 4)); }
[[nodiscard]] auto yyzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1122, 4)); }
[[nodiscard]] auto yyzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1123, 4)); }
[[nodiscard]] auto yywx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1130, 4)); }
[[nodiscard]] auto yywy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1131, 4)); }
[[nodiscard]] auto yywz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1132, 4)); }
[[nodiscard]] auto yyww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1133, 4)); }
[[nodiscard]] auto yzxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1200, 4)); }
[[nodiscard]] auto yzxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1201, 4)); }
[[nodiscard]] auto yzxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1202, 4)); }
[[nodiscard]] auto yzxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1203, 4)); }
[[nodiscard]] auto yzyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1210, 4)); }
[[nodiscard]] auto yzyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1211, 4)); }
[[nodiscard]] auto yzyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1212, 4)); }
[[nodiscard]] auto yzyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1213, 4)); }
[[nodiscard]] auto yzzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1220, 4)); }
[[nodiscard]] auto yzzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1221, 4)); }
[[nodiscard]] auto yzzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1222, 4)); }
[[nodiscard]] auto yzzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1223, 4)); }
[[nodiscard]] auto yzwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1230, 4)); }
[[nodiscard]] auto yzwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1231, 4)); }
[[nodiscard]] auto yzwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1232, 4)); }
[[nodiscard]] auto yzww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1233, 4)); }
[[nodiscard]] auto ywxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1300, 4)); }
[[nodiscard]] auto ywxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1301, 4)); }
[[nodiscard]] auto ywxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1302, 4)); }
[[nodiscard]] auto ywxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1303, 4)); }
[[nodiscard]] auto ywyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1310, 4)); }
[[nodiscard]] auto ywyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1311, 4)); }
[[nodiscard]] auto ywyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1312, 4)); }
[[nodiscard]] auto ywyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1313, 4)); }
[[nodiscard]] auto ywzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1320, 4)); }
[[nodiscard]] auto ywzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1321, 4)); }
[[nodiscard]] auto ywzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1322, 4)); }
[[nodiscard]] auto ywzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1323, 4)); }
[[nodiscard]] auto ywwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1330, 4)); }
[[nodiscard]] auto ywwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1331, 4)); }
[[nodiscard]] auto ywwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1332, 4)); }
[[nodiscard]] auto ywww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x1333, 4)); }
[[nodiscard]] auto zxxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2000, 4)); }
[[nodiscard]] auto zxxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2001, 4)); }
[[nodiscard]] auto zxxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2002, 4)); }
[[nodiscard]] auto zxxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2003, 4)); }
[[nodiscard]] auto zxyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2010, 4)); }
[[nodiscard]] auto zxyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2011, 4)); }
[[nodiscard]] auto zxyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2012, 4)); }
[[nodiscard]] auto zxyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2013, 4)); }
[[nodiscard]] auto zxzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2020, 4)); }
[[nodiscard]] auto zxzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2021, 4)); }
[[nodiscard]] auto zxzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2022, 4)); }
[[nodiscard]] auto zxzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2023, 4)); }
[[nodiscard]] auto zxwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2030, 4)); }
[[nodiscard]] auto zxwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2031, 4)); }
[[nodiscard]] auto zxwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2032, 4)); }
[[nodiscard]] auto zxww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2033, 4)); }
[[nodiscard]] auto zyxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2100, 4)); }
[[nodiscard]] auto zyxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2101, 4)); }
[[nodiscard]] auto zyxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2102, 4)); }
[[nodiscard]] auto zyxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2103, 4)); }
[[nodiscard]] auto zyyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2110, 4)); }
[[nodiscard]] auto zyyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2111, 4)); }
[[nodiscard]] auto zyyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2112, 4)); }
[[nodiscard]] auto zyyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2113, 4)); }
[[nodiscard]] auto zyzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2120, 4)); }
[[nodiscard]] auto zyzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2121, 4)); }
[[nodiscard]] auto zyzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2122, 4)); }
[[nodiscard]] auto zyzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2123, 4)); }
[[nodiscard]] auto zywx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2130, 4)); }
[[nodiscard]] auto zywy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2131, 4)); }
[[nodiscard]] auto zywz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2132, 4)); }
[[nodiscard]] auto zyww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2133, 4)); }
[[nodiscard]] auto zzxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2200, 4)); }
[[nodiscard]] auto zzxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2201, 4)); }
[[nodiscard]] auto zzxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2202, 4)); }
[[nodiscard]] auto zzxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2203, 4)); }
[[nodiscard]] auto zzyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2210, 4)); }
[[nodiscard]] auto zzyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2211, 4)); }
[[nodiscard]] auto zzyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2212, 4)); }
[[nodiscard]] auto zzyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2213, 4)); }
[[nodiscard]] auto zzzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2220, 4)); }
[[nodiscard]] auto zzzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2221, 4)); }
[[nodiscard]] auto zzzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2222, 4)); }
[[nodiscard]] auto zzzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2223, 4)); }
[[nodiscard]] auto zzwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2230, 4)); }
[[nodiscard]] auto zzwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2231, 4)); }
[[nodiscard]] auto zzwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2232, 4)); }
[[nodiscard]] auto zzww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2233, 4)); }
[[nodiscard]] auto zwxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2300, 4)); }
[[nodiscard]] auto zwxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2301, 4)); }
[[nodiscard]] auto zwxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2302, 4)); }
[[nodiscard]] auto zwxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2303, 4)); }
[[nodiscard]] auto zwyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2310, 4)); }
[[nodiscard]] auto zwyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2311, 4)); }
[[nodiscard]] auto zwyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2312, 4)); }
[[nodiscard]] auto zwyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2313, 4)); }
[[nodiscard]] auto zwzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2320, 4)); }
[[nodiscard]] auto zwzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2321, 4)); }
[[nodiscard]] auto zwzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2322, 4)); }
[[nodiscard]] auto zwzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2323, 4)); }
[[nodiscard]] auto zwwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2330, 4)); }
[[nodiscard]] auto zwwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2331, 4)); }
[[nodiscard]] auto zwwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2332, 4)); }
[[nodiscard]] auto zwww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x2333, 4)); }
[[nodiscard]] auto wxxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3000, 4)); }
[[nodiscard]] auto wxxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3001, 4)); }
[[nodiscard]] auto wxxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3002, 4)); }
[[nodiscard]] auto wxxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3003, 4)); }
[[nodiscard]] auto wxyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3010, 4)); }
[[nodiscard]] auto wxyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3011, 4)); }
[[nodiscard]] auto wxyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3012, 4)); }
[[nodiscard]] auto wxyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3013, 4)); }
[[nodiscard]] auto wxzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3020, 4)); }
[[nodiscard]] auto wxzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3021, 4)); }
[[nodiscard]] auto wxzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3022, 4)); }
[[nodiscard]] auto wxzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3023, 4)); }
[[nodiscard]] auto wxwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3030, 4)); }
[[nodiscard]] auto wxwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3031, 4)); }
[[nodiscard]] auto wxwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3032, 4)); }
[[nodiscard]] auto wxww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3033, 4)); }
[[nodiscard]] auto wyxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3100, 4)); }
[[nodiscard]] auto wyxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3101, 4)); }
[[nodiscard]] auto wyxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3102, 4)); }
[[nodiscard]] auto wyxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3103, 4)); }
[[nodiscard]] auto wyyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3110, 4)); }
[[nodiscard]] auto wyyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3111, 4)); }
[[nodiscard]] auto wyyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3112, 4)); }
[[nodiscard]] auto wyyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3113, 4)); }
[[nodiscard]] auto wyzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3120, 4)); }
[[nodiscard]] auto wyzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3121, 4)); }
[[nodiscard]] auto wyzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3122, 4)); }
[[nodiscard]] auto wyzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3123, 4)); }
[[nodiscard]] auto wywx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3130, 4)); }
[[nodiscard]] auto wywy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3131, 4)); }
[[nodiscard]] auto wywz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3132, 4)); }
[[nodiscard]] auto wyww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3133, 4)); }
[[nodiscard]] auto wzxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3200, 4)); }
[[nodiscard]] auto wzxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3201, 4)); }
[[nodiscard]] auto wzxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3202, 4)); }
[[nodiscard]] auto wzxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3203, 4)); }
[[nodiscard]] auto wzyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3210, 4)); }
[[nodiscard]] auto wzyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3211, 4)); }
[[nodiscard]] auto wzyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3212, 4)); }
[[nodiscard]] auto wzyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3213, 4)); }
[[nodiscard]] auto wzzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3220, 4)); }
[[nodiscard]] auto wzzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3221, 4)); }
[[nodiscard]] auto wzzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3222, 4)); }
[[nodiscard]] auto wzzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3223, 4)); }
[[nodiscard]] auto wzwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3230, 4)); }
[[nodiscard]] auto wzwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3231, 4)); }
[[nodiscard]] auto wzwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3232, 4)); }
[[nodiscard]] auto wzww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3233, 4)); }
[[nodiscard]] auto wwxx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3300, 4)); }
[[nodiscard]] auto wwxy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3301, 4)); }
[[nodiscard]] auto wwxz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3302, 4)); }
[[nodiscard]] auto wwxw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3303, 4)); }
[[nodiscard]] auto wwyx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3310, 4)); }
[[nodiscard]] auto wwyy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3311, 4)); }
[[nodiscard]] auto wwyz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3312, 4)); }
[[nodiscard]] auto wwyw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3313, 4)); }
[[nodiscard]] auto wwzx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3320, 4)); }
[[nodiscard]] auto wwzy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3321, 4)); }
[[nodiscard]] auto wwzz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3322, 4)); }
[[nodiscard]] auto wwzw() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3323, 4)); }
[[nodiscard]] auto wwwx() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3330, 4)); }
[[nodiscard]] auto wwwy() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3331, 4)); }
[[nodiscard]] auto wwwz() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3332, 4)); }
[[nodiscard]] auto wwww() { return def<Vector<T, 4>>(Function::current()->swizzle(Type::of<T>(), expression(), 0x3333, 4)); }
