// this file was generated by generate_cuda_math_lib.py, please do not manually modify 
 
#pragma once

using oc_int = int;
using oc_uint = unsigned int;
using oc_float = float;
using oc_bool = bool;

struct alignas(8) oc_int2{
	oc_int x;
	oc_int y;

	__device__ oc_int2() noexcept 
		:x{}, y{} {}
	__device__ oc_int2(oc_int s) noexcept 
		:x(s), y(s) {}
	__device__ oc_int2(oc_int x, oc_int y) noexcept 
		:x(x), y(y) {}
	__device__ constexpr oc_int operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_int &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(16) oc_int3{
	oc_int x;
	oc_int y;
	oc_int z;

	__device__ oc_int3() noexcept 
		:x{}, y{}, z{} {}
	__device__ oc_int3(oc_int s) noexcept 
		:x(s), y(s), z(s) {}
	__device__ oc_int3(oc_int x, oc_int y, oc_int z) noexcept 
		:x(x), y(y), z(z) {}
	__device__ constexpr oc_int operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_int &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(16) oc_int4{
	oc_int x;
	oc_int y;
	oc_int z;
	oc_int w;

	__device__ oc_int4() noexcept 
		:x{}, y{}, z{}, w{} {}
	__device__ oc_int4(oc_int s) noexcept 
		:x(s), y(s), z(s), w(s) {}
	__device__ oc_int4(oc_int x, oc_int y, oc_int z, oc_int w) noexcept 
		:x(x), y(y), z(z), w(w) {}
	__device__ constexpr oc_int operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_int &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(8) oc_uint2{
	oc_uint x;
	oc_uint y;

	__device__ oc_uint2() noexcept 
		:x{}, y{} {}
	__device__ oc_uint2(oc_uint s) noexcept 
		:x(s), y(s) {}
	__device__ oc_uint2(oc_uint x, oc_uint y) noexcept 
		:x(x), y(y) {}
	__device__ constexpr oc_uint operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_uint &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(16) oc_uint3{
	oc_uint x;
	oc_uint y;
	oc_uint z;

	__device__ oc_uint3() noexcept 
		:x{}, y{}, z{} {}
	__device__ oc_uint3(oc_uint s) noexcept 
		:x(s), y(s), z(s) {}
	__device__ oc_uint3(oc_uint x, oc_uint y, oc_uint z) noexcept 
		:x(x), y(y), z(z) {}
	__device__ constexpr oc_uint operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_uint &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(16) oc_uint4{
	oc_uint x;
	oc_uint y;
	oc_uint z;
	oc_uint w;

	__device__ oc_uint4() noexcept 
		:x{}, y{}, z{}, w{} {}
	__device__ oc_uint4(oc_uint s) noexcept 
		:x(s), y(s), z(s), w(s) {}
	__device__ oc_uint4(oc_uint x, oc_uint y, oc_uint z, oc_uint w) noexcept 
		:x(x), y(y), z(z), w(w) {}
	__device__ constexpr oc_uint operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_uint &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(8) oc_float2{
	oc_float x;
	oc_float y;

	__device__ oc_float2() noexcept 
		:x{}, y{} {}
	__device__ oc_float2(oc_float s) noexcept 
		:x(s), y(s) {}
	__device__ oc_float2(oc_float x, oc_float y) noexcept 
		:x(x), y(y) {}
	__device__ constexpr oc_float operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_float &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(16) oc_float3{
	oc_float x;
	oc_float y;
	oc_float z;

	__device__ oc_float3() noexcept 
		:x{}, y{}, z{} {}
	__device__ oc_float3(oc_float s) noexcept 
		:x(s), y(s), z(s) {}
	__device__ oc_float3(oc_float x, oc_float y, oc_float z) noexcept 
		:x(x), y(y), z(z) {}
	__device__ constexpr oc_float operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_float &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(16) oc_float4{
	oc_float x;
	oc_float y;
	oc_float z;
	oc_float w;

	__device__ oc_float4() noexcept 
		:x{}, y{}, z{}, w{} {}
	__device__ oc_float4(oc_float s) noexcept 
		:x(s), y(s), z(s), w(s) {}
	__device__ oc_float4(oc_float x, oc_float y, oc_float z, oc_float w) noexcept 
		:x(x), y(y), z(z), w(w) {}
	__device__ constexpr oc_float operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_float &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(8) oc_bool2{
	oc_bool x;
	oc_bool y;

	__device__ oc_bool2() noexcept 
		:x{}, y{} {}
	__device__ oc_bool2(oc_bool s) noexcept 
		:x(s), y(s) {}
	__device__ oc_bool2(oc_bool x, oc_bool y) noexcept 
		:x(x), y(y) {}
	__device__ constexpr oc_bool operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_bool &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(16) oc_bool3{
	oc_bool x;
	oc_bool y;
	oc_bool z;

	__device__ oc_bool3() noexcept 
		:x{}, y{}, z{} {}
	__device__ oc_bool3(oc_bool s) noexcept 
		:x(s), y(s), z(s) {}
	__device__ oc_bool3(oc_bool x, oc_bool y, oc_bool z) noexcept 
		:x(x), y(y), z(z) {}
	__device__ constexpr oc_bool operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_bool &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

struct alignas(16) oc_bool4{
	oc_bool x;
	oc_bool y;
	oc_bool z;
	oc_bool w;

	__device__ oc_bool4() noexcept 
		:x{}, y{}, z{}, w{} {}
	__device__ oc_bool4(oc_bool s) noexcept 
		:x(s), y(s), z(s), w(s) {}
	__device__ oc_bool4(oc_bool x, oc_bool y, oc_bool z, oc_bool w) noexcept 
		:x(x), y(y), z(z), w(w) {}
	__device__ constexpr oc_bool operator[](oc_uint i) const noexcept { return (&x)[i]; }
	__device__ constexpr oc_bool &operator[](oc_uint i) noexcept { return (&x)[i]; }
};

__device__ oc_int2 operator+(oc_int2 vec) { return oc_int2(+vec.x, +vec.y); }
__device__ oc_int2 operator-(oc_int2 vec) { return oc_int2(-vec.x, -vec.y); }
__device__ oc_int2 operator!(oc_int2 vec) { return oc_int2(!vec.x, !vec.y); }
__device__ oc_int2 operator~(oc_int2 vec) { return oc_int2(~vec.x, ~vec.y); }

__device__ oc_int3 operator+(oc_int3 vec) { return oc_int3(+vec.x, +vec.y, +vec.z); }
__device__ oc_int3 operator-(oc_int3 vec) { return oc_int3(-vec.x, -vec.y, -vec.z); }
__device__ oc_int3 operator!(oc_int3 vec) { return oc_int3(!vec.x, !vec.y, !vec.z); }
__device__ oc_int3 operator~(oc_int3 vec) { return oc_int3(~vec.x, ~vec.y, ~vec.z); }

__device__ oc_int4 operator+(oc_int4 vec) { return oc_int4(+vec.x, +vec.y, +vec.z, +vec.w); }
__device__ oc_int4 operator-(oc_int4 vec) { return oc_int4(-vec.x, -vec.y, -vec.z, -vec.w); }
__device__ oc_int4 operator!(oc_int4 vec) { return oc_int4(!vec.x, !vec.y, !vec.z, !vec.w); }
__device__ oc_int4 operator~(oc_int4 vec) { return oc_int4(~vec.x, ~vec.y, ~vec.z, ~vec.w); }

__device__ oc_uint2 operator+(oc_uint2 vec) { return oc_uint2(+vec.x, +vec.y); }
__device__ oc_uint2 operator-(oc_uint2 vec) { return oc_uint2(-vec.x, -vec.y); }
__device__ oc_uint2 operator!(oc_uint2 vec) { return oc_uint2(!vec.x, !vec.y); }
__device__ oc_uint2 operator~(oc_uint2 vec) { return oc_uint2(~vec.x, ~vec.y); }

__device__ oc_uint3 operator+(oc_uint3 vec) { return oc_uint3(+vec.x, +vec.y, +vec.z); }
__device__ oc_uint3 operator-(oc_uint3 vec) { return oc_uint3(-vec.x, -vec.y, -vec.z); }
__device__ oc_uint3 operator!(oc_uint3 vec) { return oc_uint3(!vec.x, !vec.y, !vec.z); }
__device__ oc_uint3 operator~(oc_uint3 vec) { return oc_uint3(~vec.x, ~vec.y, ~vec.z); }

__device__ oc_uint4 operator+(oc_uint4 vec) { return oc_uint4(+vec.x, +vec.y, +vec.z, +vec.w); }
__device__ oc_uint4 operator-(oc_uint4 vec) { return oc_uint4(-vec.x, -vec.y, -vec.z, -vec.w); }
__device__ oc_uint4 operator!(oc_uint4 vec) { return oc_uint4(!vec.x, !vec.y, !vec.z, !vec.w); }
__device__ oc_uint4 operator~(oc_uint4 vec) { return oc_uint4(~vec.x, ~vec.y, ~vec.z, ~vec.w); }

__device__ oc_float2 operator+(oc_float2 vec) { return oc_float2(+vec.x, +vec.y); }
__device__ oc_float2 operator-(oc_float2 vec) { return oc_float2(-vec.x, -vec.y); }
__device__ oc_float2 operator!(oc_float2 vec) { return oc_float2(!vec.x, !vec.y); }

__device__ oc_float3 operator+(oc_float3 vec) { return oc_float3(+vec.x, +vec.y, +vec.z); }
__device__ oc_float3 operator-(oc_float3 vec) { return oc_float3(-vec.x, -vec.y, -vec.z); }
__device__ oc_float3 operator!(oc_float3 vec) { return oc_float3(!vec.x, !vec.y, !vec.z); }

__device__ oc_float4 operator+(oc_float4 vec) { return oc_float4(+vec.x, +vec.y, +vec.z, +vec.w); }
__device__ oc_float4 operator-(oc_float4 vec) { return oc_float4(-vec.x, -vec.y, -vec.z, -vec.w); }
__device__ oc_float4 operator!(oc_float4 vec) { return oc_float4(!vec.x, !vec.y, !vec.z, !vec.w); }

__device__ oc_bool2 operator+(oc_bool2 vec) { return oc_bool2(+vec.x, +vec.y); }
__device__ oc_bool2 operator-(oc_bool2 vec) { return oc_bool2(-vec.x, -vec.y); }
__device__ oc_bool2 operator!(oc_bool2 vec) { return oc_bool2(!vec.x, !vec.y); }
__device__ oc_bool2 operator~(oc_bool2 vec) { return oc_bool2(~vec.x, ~vec.y); }

__device__ oc_bool3 operator+(oc_bool3 vec) { return oc_bool3(+vec.x, +vec.y, +vec.z); }
__device__ oc_bool3 operator-(oc_bool3 vec) { return oc_bool3(-vec.x, -vec.y, -vec.z); }
__device__ oc_bool3 operator!(oc_bool3 vec) { return oc_bool3(!vec.x, !vec.y, !vec.z); }
__device__ oc_bool3 operator~(oc_bool3 vec) { return oc_bool3(~vec.x, ~vec.y, ~vec.z); }

__device__ oc_bool4 operator+(oc_bool4 vec) { return oc_bool4(+vec.x, +vec.y, +vec.z, +vec.w); }
__device__ oc_bool4 operator-(oc_bool4 vec) { return oc_bool4(-vec.x, -vec.y, -vec.z, -vec.w); }
__device__ oc_bool4 operator!(oc_bool4 vec) { return oc_bool4(!vec.x, !vec.y, !vec.z, !vec.w); }
__device__ oc_bool4 operator~(oc_bool4 vec) { return oc_bool4(~vec.x, ~vec.y, ~vec.z, ~vec.w); }


__device__ oc_int2 operator+(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x + rhs.x, lhs.y + rhs.y); }
__device__ oc_int2 operator+(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x + rhs, lhs.y + rhs); }
__device__ oc_int2 operator+(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs + rhs.x, lhs + rhs.y); }
__device__ oc_int2 operator-(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x - rhs.x, lhs.y - rhs.y); }
__device__ oc_int2 operator-(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x - rhs, lhs.y - rhs); }
__device__ oc_int2 operator-(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs - rhs.x, lhs - rhs.y); }
__device__ oc_int2 operator*(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x * rhs.x, lhs.y * rhs.y); }
__device__ oc_int2 operator*(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x * rhs, lhs.y * rhs); }
__device__ oc_int2 operator*(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs * rhs.x, lhs * rhs.y); }
__device__ oc_int2 operator/(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x / rhs.x, lhs.y / rhs.y); }
__device__ oc_int2 operator/(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x / rhs, lhs.y / rhs); }
__device__ oc_int2 operator/(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs / rhs.x, lhs / rhs.y); }
__device__ oc_int2 operator%(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x % rhs.x, lhs.y % rhs.y); }
__device__ oc_int2 operator%(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x % rhs, lhs.y % rhs); }
__device__ oc_int2 operator%(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs % rhs.x, lhs % rhs.y); }
__device__ oc_bool2 operator==(oc_int2 lhs, oc_int2 rhs) { return oc_bool2(lhs.x == rhs.x, lhs.y == rhs.y); }
__device__ oc_bool2 operator==(oc_int2 lhs, oc_int rhs) { return oc_bool2(lhs.x == rhs, lhs.y == rhs); }
__device__ oc_bool2 operator==(oc_int lhs, oc_int2 rhs) { return oc_bool2(lhs == rhs.x, lhs == rhs.y); }
__device__ oc_bool2 operator!=(oc_int2 lhs, oc_int2 rhs) { return oc_bool2(lhs.x != rhs.x, lhs.y != rhs.y); }
__device__ oc_bool2 operator!=(oc_int2 lhs, oc_int rhs) { return oc_bool2(lhs.x != rhs, lhs.y != rhs); }
__device__ oc_bool2 operator!=(oc_int lhs, oc_int2 rhs) { return oc_bool2(lhs != rhs.x, lhs != rhs.y); }
__device__ oc_bool2 operator>(oc_int2 lhs, oc_int2 rhs) { return oc_bool2(lhs.x > rhs.x, lhs.y > rhs.y); }
__device__ oc_bool2 operator>(oc_int2 lhs, oc_int rhs) { return oc_bool2(lhs.x > rhs, lhs.y > rhs); }
__device__ oc_bool2 operator>(oc_int lhs, oc_int2 rhs) { return oc_bool2(lhs > rhs.x, lhs > rhs.y); }
__device__ oc_bool2 operator<(oc_int2 lhs, oc_int2 rhs) { return oc_bool2(lhs.x < rhs.x, lhs.y < rhs.y); }
__device__ oc_bool2 operator<(oc_int2 lhs, oc_int rhs) { return oc_bool2(lhs.x < rhs, lhs.y < rhs); }
__device__ oc_bool2 operator<(oc_int lhs, oc_int2 rhs) { return oc_bool2(lhs < rhs.x, lhs < rhs.y); }
__device__ oc_bool2 operator>=(oc_int2 lhs, oc_int2 rhs) { return oc_bool2(lhs.x >= rhs.x, lhs.y >= rhs.y); }
__device__ oc_bool2 operator>=(oc_int2 lhs, oc_int rhs) { return oc_bool2(lhs.x >= rhs, lhs.y >= rhs); }
__device__ oc_bool2 operator>=(oc_int lhs, oc_int2 rhs) { return oc_bool2(lhs >= rhs.x, lhs >= rhs.y); }
__device__ oc_bool2 operator<=(oc_int2 lhs, oc_int2 rhs) { return oc_bool2(lhs.x <= rhs.x, lhs.y <= rhs.y); }
__device__ oc_bool2 operator<=(oc_int2 lhs, oc_int rhs) { return oc_bool2(lhs.x <= rhs, lhs.y <= rhs); }
__device__ oc_bool2 operator<=(oc_int lhs, oc_int2 rhs) { return oc_bool2(lhs <= rhs.x, lhs <= rhs.y); }
__device__ oc_bool2 operator&&(oc_int2 lhs, oc_int2 rhs) { return oc_bool2(lhs.x && rhs.x, lhs.y && rhs.y); }
__device__ oc_bool2 operator&&(oc_int2 lhs, oc_int rhs) { return oc_bool2(lhs.x && rhs, lhs.y && rhs); }
__device__ oc_bool2 operator&&(oc_int lhs, oc_int2 rhs) { return oc_bool2(lhs && rhs.x, lhs && rhs.y); }
__device__ oc_bool2 operator||(oc_int2 lhs, oc_int2 rhs) { return oc_bool2(lhs.x || rhs.x, lhs.y || rhs.y); }
__device__ oc_bool2 operator||(oc_int2 lhs, oc_int rhs) { return oc_bool2(lhs.x || rhs, lhs.y || rhs); }
__device__ oc_bool2 operator||(oc_int lhs, oc_int2 rhs) { return oc_bool2(lhs || rhs.x, lhs || rhs.y); }
__device__ oc_int2 operator&(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x & rhs.x, lhs.y & rhs.y); }
__device__ oc_int2 operator&(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x & rhs, lhs.y & rhs); }
__device__ oc_int2 operator&(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs & rhs.x, lhs & rhs.y); }
__device__ oc_int2 operator|(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x | rhs.x, lhs.y | rhs.y); }
__device__ oc_int2 operator|(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x | rhs, lhs.y | rhs); }
__device__ oc_int2 operator|(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs | rhs.x, lhs | rhs.y); }
__device__ oc_int2 operator^(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x ^ rhs.x, lhs.y ^ rhs.y); }
__device__ oc_int2 operator^(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x ^ rhs, lhs.y ^ rhs); }
__device__ oc_int2 operator^(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs ^ rhs.x, lhs ^ rhs.y); }
__device__ oc_int2 operator<<(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x << rhs.x, lhs.y << rhs.y); }
__device__ oc_int2 operator<<(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x << rhs, lhs.y << rhs); }
__device__ oc_int2 operator<<(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs << rhs.x, lhs << rhs.y); }
__device__ oc_int2 operator>>(oc_int2 lhs, oc_int2 rhs) { return oc_int2(lhs.x >> rhs.x, lhs.y >> rhs.y); }
__device__ oc_int2 operator>>(oc_int2 lhs, oc_int rhs) { return oc_int2(lhs.x >> rhs, lhs.y >> rhs); }
__device__ oc_int2 operator>>(oc_int lhs, oc_int2 rhs) { return oc_int2(lhs >> rhs.x, lhs >> rhs.y); }
__device__ oc_int3 operator+(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x + rhs.x, lhs.y + rhs.y, lhs.z + rhs.z); }
__device__ oc_int3 operator+(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x + rhs, lhs.y + rhs, lhs.z + rhs); }
__device__ oc_int3 operator+(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs + rhs.x, lhs + rhs.y, lhs + rhs.z); }
__device__ oc_int3 operator-(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x - rhs.x, lhs.y - rhs.y, lhs.z - rhs.z); }
__device__ oc_int3 operator-(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x - rhs, lhs.y - rhs, lhs.z - rhs); }
__device__ oc_int3 operator-(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs - rhs.x, lhs - rhs.y, lhs - rhs.z); }
__device__ oc_int3 operator*(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x * rhs.x, lhs.y * rhs.y, lhs.z * rhs.z); }
__device__ oc_int3 operator*(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x * rhs, lhs.y * rhs, lhs.z * rhs); }
__device__ oc_int3 operator*(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs * rhs.x, lhs * rhs.y, lhs * rhs.z); }
__device__ oc_int3 operator/(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x / rhs.x, lhs.y / rhs.y, lhs.z / rhs.z); }
__device__ oc_int3 operator/(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x / rhs, lhs.y / rhs, lhs.z / rhs); }
__device__ oc_int3 operator/(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs / rhs.x, lhs / rhs.y, lhs / rhs.z); }
__device__ oc_int3 operator%(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x % rhs.x, lhs.y % rhs.y, lhs.z % rhs.z); }
__device__ oc_int3 operator%(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x % rhs, lhs.y % rhs, lhs.z % rhs); }
__device__ oc_int3 operator%(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs % rhs.x, lhs % rhs.y, lhs % rhs.z); }
__device__ oc_bool3 operator==(oc_int3 lhs, oc_int3 rhs) { return oc_bool3(lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z); }
__device__ oc_bool3 operator==(oc_int3 lhs, oc_int rhs) { return oc_bool3(lhs.x == rhs, lhs.y == rhs, lhs.z == rhs); }
__device__ oc_bool3 operator==(oc_int lhs, oc_int3 rhs) { return oc_bool3(lhs == rhs.x, lhs == rhs.y, lhs == rhs.z); }
__device__ oc_bool3 operator!=(oc_int3 lhs, oc_int3 rhs) { return oc_bool3(lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z); }
__device__ oc_bool3 operator!=(oc_int3 lhs, oc_int rhs) { return oc_bool3(lhs.x != rhs, lhs.y != rhs, lhs.z != rhs); }
__device__ oc_bool3 operator!=(oc_int lhs, oc_int3 rhs) { return oc_bool3(lhs != rhs.x, lhs != rhs.y, lhs != rhs.z); }
__device__ oc_bool3 operator>(oc_int3 lhs, oc_int3 rhs) { return oc_bool3(lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z); }
__device__ oc_bool3 operator>(oc_int3 lhs, oc_int rhs) { return oc_bool3(lhs.x > rhs, lhs.y > rhs, lhs.z > rhs); }
__device__ oc_bool3 operator>(oc_int lhs, oc_int3 rhs) { return oc_bool3(lhs > rhs.x, lhs > rhs.y, lhs > rhs.z); }
__device__ oc_bool3 operator<(oc_int3 lhs, oc_int3 rhs) { return oc_bool3(lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z); }
__device__ oc_bool3 operator<(oc_int3 lhs, oc_int rhs) { return oc_bool3(lhs.x < rhs, lhs.y < rhs, lhs.z < rhs); }
__device__ oc_bool3 operator<(oc_int lhs, oc_int3 rhs) { return oc_bool3(lhs < rhs.x, lhs < rhs.y, lhs < rhs.z); }
__device__ oc_bool3 operator>=(oc_int3 lhs, oc_int3 rhs) { return oc_bool3(lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z); }
__device__ oc_bool3 operator>=(oc_int3 lhs, oc_int rhs) { return oc_bool3(lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs); }
__device__ oc_bool3 operator>=(oc_int lhs, oc_int3 rhs) { return oc_bool3(lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z); }
__device__ oc_bool3 operator<=(oc_int3 lhs, oc_int3 rhs) { return oc_bool3(lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z); }
__device__ oc_bool3 operator<=(oc_int3 lhs, oc_int rhs) { return oc_bool3(lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs); }
__device__ oc_bool3 operator<=(oc_int lhs, oc_int3 rhs) { return oc_bool3(lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z); }
__device__ oc_bool3 operator&&(oc_int3 lhs, oc_int3 rhs) { return oc_bool3(lhs.x && rhs.x, lhs.y && rhs.y, lhs.z && rhs.z); }
__device__ oc_bool3 operator&&(oc_int3 lhs, oc_int rhs) { return oc_bool3(lhs.x && rhs, lhs.y && rhs, lhs.z && rhs); }
__device__ oc_bool3 operator&&(oc_int lhs, oc_int3 rhs) { return oc_bool3(lhs && rhs.x, lhs && rhs.y, lhs && rhs.z); }
__device__ oc_bool3 operator||(oc_int3 lhs, oc_int3 rhs) { return oc_bool3(lhs.x || rhs.x, lhs.y || rhs.y, lhs.z || rhs.z); }
__device__ oc_bool3 operator||(oc_int3 lhs, oc_int rhs) { return oc_bool3(lhs.x || rhs, lhs.y || rhs, lhs.z || rhs); }
__device__ oc_bool3 operator||(oc_int lhs, oc_int3 rhs) { return oc_bool3(lhs || rhs.x, lhs || rhs.y, lhs || rhs.z); }
__device__ oc_int3 operator&(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x & rhs.x, lhs.y & rhs.y, lhs.z & rhs.z); }
__device__ oc_int3 operator&(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x & rhs, lhs.y & rhs, lhs.z & rhs); }
__device__ oc_int3 operator&(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs & rhs.x, lhs & rhs.y, lhs & rhs.z); }
__device__ oc_int3 operator|(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x | rhs.x, lhs.y | rhs.y, lhs.z | rhs.z); }
__device__ oc_int3 operator|(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x | rhs, lhs.y | rhs, lhs.z | rhs); }
__device__ oc_int3 operator|(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs | rhs.x, lhs | rhs.y, lhs | rhs.z); }
__device__ oc_int3 operator^(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x ^ rhs.x, lhs.y ^ rhs.y, lhs.z ^ rhs.z); }
__device__ oc_int3 operator^(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x ^ rhs, lhs.y ^ rhs, lhs.z ^ rhs); }
__device__ oc_int3 operator^(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs ^ rhs.x, lhs ^ rhs.y, lhs ^ rhs.z); }
__device__ oc_int3 operator<<(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x << rhs.x, lhs.y << rhs.y, lhs.z << rhs.z); }
__device__ oc_int3 operator<<(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x << rhs, lhs.y << rhs, lhs.z << rhs); }
__device__ oc_int3 operator<<(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs << rhs.x, lhs << rhs.y, lhs << rhs.z); }
__device__ oc_int3 operator>>(oc_int3 lhs, oc_int3 rhs) { return oc_int3(lhs.x >> rhs.x, lhs.y >> rhs.y, lhs.z >> rhs.z); }
__device__ oc_int3 operator>>(oc_int3 lhs, oc_int rhs) { return oc_int3(lhs.x >> rhs, lhs.y >> rhs, lhs.z >> rhs); }
__device__ oc_int3 operator>>(oc_int lhs, oc_int3 rhs) { return oc_int3(lhs >> rhs.x, lhs >> rhs.y, lhs >> rhs.z); }
__device__ oc_int4 operator+(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x + rhs.x, lhs.y + rhs.y, lhs.z + rhs.z, lhs.w + rhs.w); }
__device__ oc_int4 operator+(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x + rhs, lhs.y + rhs, lhs.z + rhs, lhs.w + rhs); }
__device__ oc_int4 operator+(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs + rhs.x, lhs + rhs.y, lhs + rhs.z, lhs + rhs.w); }
__device__ oc_int4 operator-(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x - rhs.x, lhs.y - rhs.y, lhs.z - rhs.z, lhs.w - rhs.w); }
__device__ oc_int4 operator-(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x - rhs, lhs.y - rhs, lhs.z - rhs, lhs.w - rhs); }
__device__ oc_int4 operator-(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs - rhs.x, lhs - rhs.y, lhs - rhs.z, lhs - rhs.w); }
__device__ oc_int4 operator*(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x * rhs.x, lhs.y * rhs.y, lhs.z * rhs.z, lhs.w * rhs.w); }
__device__ oc_int4 operator*(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x * rhs, lhs.y * rhs, lhs.z * rhs, lhs.w * rhs); }
__device__ oc_int4 operator*(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs * rhs.x, lhs * rhs.y, lhs * rhs.z, lhs * rhs.w); }
__device__ oc_int4 operator/(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x / rhs.x, lhs.y / rhs.y, lhs.z / rhs.z, lhs.w / rhs.w); }
__device__ oc_int4 operator/(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x / rhs, lhs.y / rhs, lhs.z / rhs, lhs.w / rhs); }
__device__ oc_int4 operator/(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs / rhs.x, lhs / rhs.y, lhs / rhs.z, lhs / rhs.w); }
__device__ oc_int4 operator%(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x % rhs.x, lhs.y % rhs.y, lhs.z % rhs.z, lhs.w % rhs.w); }
__device__ oc_int4 operator%(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x % rhs, lhs.y % rhs, lhs.z % rhs, lhs.w % rhs); }
__device__ oc_int4 operator%(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs % rhs.x, lhs % rhs.y, lhs % rhs.z, lhs % rhs.w); }
__device__ oc_bool4 operator==(oc_int4 lhs, oc_int4 rhs) { return oc_bool4(lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z, lhs.w == rhs.w); }
__device__ oc_bool4 operator==(oc_int4 lhs, oc_int rhs) { return oc_bool4(lhs.x == rhs, lhs.y == rhs, lhs.z == rhs, lhs.w == rhs); }
__device__ oc_bool4 operator==(oc_int lhs, oc_int4 rhs) { return oc_bool4(lhs == rhs.x, lhs == rhs.y, lhs == rhs.z, lhs == rhs.w); }
__device__ oc_bool4 operator!=(oc_int4 lhs, oc_int4 rhs) { return oc_bool4(lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z, lhs.w != rhs.w); }
__device__ oc_bool4 operator!=(oc_int4 lhs, oc_int rhs) { return oc_bool4(lhs.x != rhs, lhs.y != rhs, lhs.z != rhs, lhs.w != rhs); }
__device__ oc_bool4 operator!=(oc_int lhs, oc_int4 rhs) { return oc_bool4(lhs != rhs.x, lhs != rhs.y, lhs != rhs.z, lhs != rhs.w); }
__device__ oc_bool4 operator>(oc_int4 lhs, oc_int4 rhs) { return oc_bool4(lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z, lhs.w > rhs.w); }
__device__ oc_bool4 operator>(oc_int4 lhs, oc_int rhs) { return oc_bool4(lhs.x > rhs, lhs.y > rhs, lhs.z > rhs, lhs.w > rhs); }
__device__ oc_bool4 operator>(oc_int lhs, oc_int4 rhs) { return oc_bool4(lhs > rhs.x, lhs > rhs.y, lhs > rhs.z, lhs > rhs.w); }
__device__ oc_bool4 operator<(oc_int4 lhs, oc_int4 rhs) { return oc_bool4(lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z, lhs.w < rhs.w); }
__device__ oc_bool4 operator<(oc_int4 lhs, oc_int rhs) { return oc_bool4(lhs.x < rhs, lhs.y < rhs, lhs.z < rhs, lhs.w < rhs); }
__device__ oc_bool4 operator<(oc_int lhs, oc_int4 rhs) { return oc_bool4(lhs < rhs.x, lhs < rhs.y, lhs < rhs.z, lhs < rhs.w); }
__device__ oc_bool4 operator>=(oc_int4 lhs, oc_int4 rhs) { return oc_bool4(lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z, lhs.w >= rhs.w); }
__device__ oc_bool4 operator>=(oc_int4 lhs, oc_int rhs) { return oc_bool4(lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs, lhs.w >= rhs); }
__device__ oc_bool4 operator>=(oc_int lhs, oc_int4 rhs) { return oc_bool4(lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z, lhs >= rhs.w); }
__device__ oc_bool4 operator<=(oc_int4 lhs, oc_int4 rhs) { return oc_bool4(lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z, lhs.w <= rhs.w); }
__device__ oc_bool4 operator<=(oc_int4 lhs, oc_int rhs) { return oc_bool4(lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs, lhs.w <= rhs); }
__device__ oc_bool4 operator<=(oc_int lhs, oc_int4 rhs) { return oc_bool4(lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z, lhs <= rhs.w); }
__device__ oc_bool4 operator&&(oc_int4 lhs, oc_int4 rhs) { return oc_bool4(lhs.x && rhs.x, lhs.y && rhs.y, lhs.z && rhs.z, lhs.w && rhs.w); }
__device__ oc_bool4 operator&&(oc_int4 lhs, oc_int rhs) { return oc_bool4(lhs.x && rhs, lhs.y && rhs, lhs.z && rhs, lhs.w && rhs); }
__device__ oc_bool4 operator&&(oc_int lhs, oc_int4 rhs) { return oc_bool4(lhs && rhs.x, lhs && rhs.y, lhs && rhs.z, lhs && rhs.w); }
__device__ oc_bool4 operator||(oc_int4 lhs, oc_int4 rhs) { return oc_bool4(lhs.x || rhs.x, lhs.y || rhs.y, lhs.z || rhs.z, lhs.w || rhs.w); }
__device__ oc_bool4 operator||(oc_int4 lhs, oc_int rhs) { return oc_bool4(lhs.x || rhs, lhs.y || rhs, lhs.z || rhs, lhs.w || rhs); }
__device__ oc_bool4 operator||(oc_int lhs, oc_int4 rhs) { return oc_bool4(lhs || rhs.x, lhs || rhs.y, lhs || rhs.z, lhs || rhs.w); }
__device__ oc_int4 operator&(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x & rhs.x, lhs.y & rhs.y, lhs.z & rhs.z, lhs.w & rhs.w); }
__device__ oc_int4 operator&(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x & rhs, lhs.y & rhs, lhs.z & rhs, lhs.w & rhs); }
__device__ oc_int4 operator&(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs & rhs.x, lhs & rhs.y, lhs & rhs.z, lhs & rhs.w); }
__device__ oc_int4 operator|(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x | rhs.x, lhs.y | rhs.y, lhs.z | rhs.z, lhs.w | rhs.w); }
__device__ oc_int4 operator|(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x | rhs, lhs.y | rhs, lhs.z | rhs, lhs.w | rhs); }
__device__ oc_int4 operator|(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs | rhs.x, lhs | rhs.y, lhs | rhs.z, lhs | rhs.w); }
__device__ oc_int4 operator^(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x ^ rhs.x, lhs.y ^ rhs.y, lhs.z ^ rhs.z, lhs.w ^ rhs.w); }
__device__ oc_int4 operator^(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x ^ rhs, lhs.y ^ rhs, lhs.z ^ rhs, lhs.w ^ rhs); }
__device__ oc_int4 operator^(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs ^ rhs.x, lhs ^ rhs.y, lhs ^ rhs.z, lhs ^ rhs.w); }
__device__ oc_int4 operator<<(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x << rhs.x, lhs.y << rhs.y, lhs.z << rhs.z, lhs.w << rhs.w); }
__device__ oc_int4 operator<<(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x << rhs, lhs.y << rhs, lhs.z << rhs, lhs.w << rhs); }
__device__ oc_int4 operator<<(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs << rhs.x, lhs << rhs.y, lhs << rhs.z, lhs << rhs.w); }
__device__ oc_int4 operator>>(oc_int4 lhs, oc_int4 rhs) { return oc_int4(lhs.x >> rhs.x, lhs.y >> rhs.y, lhs.z >> rhs.z, lhs.w >> rhs.w); }
__device__ oc_int4 operator>>(oc_int4 lhs, oc_int rhs) { return oc_int4(lhs.x >> rhs, lhs.y >> rhs, lhs.z >> rhs, lhs.w >> rhs); }
__device__ oc_int4 operator>>(oc_int lhs, oc_int4 rhs) { return oc_int4(lhs >> rhs.x, lhs >> rhs.y, lhs >> rhs.z, lhs >> rhs.w); }

__device__ oc_uint2 operator+(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x + rhs.x, lhs.y + rhs.y); }
__device__ oc_uint2 operator+(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x + rhs, lhs.y + rhs); }
__device__ oc_uint2 operator+(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs + rhs.x, lhs + rhs.y); }
__device__ oc_uint2 operator-(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x - rhs.x, lhs.y - rhs.y); }
__device__ oc_uint2 operator-(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x - rhs, lhs.y - rhs); }
__device__ oc_uint2 operator-(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs - rhs.x, lhs - rhs.y); }
__device__ oc_uint2 operator*(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x * rhs.x, lhs.y * rhs.y); }
__device__ oc_uint2 operator*(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x * rhs, lhs.y * rhs); }
__device__ oc_uint2 operator*(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs * rhs.x, lhs * rhs.y); }
__device__ oc_uint2 operator/(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x / rhs.x, lhs.y / rhs.y); }
__device__ oc_uint2 operator/(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x / rhs, lhs.y / rhs); }
__device__ oc_uint2 operator/(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs / rhs.x, lhs / rhs.y); }
__device__ oc_uint2 operator%(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x % rhs.x, lhs.y % rhs.y); }
__device__ oc_uint2 operator%(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x % rhs, lhs.y % rhs); }
__device__ oc_uint2 operator%(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs % rhs.x, lhs % rhs.y); }
__device__ oc_bool2 operator==(oc_uint2 lhs, oc_uint2 rhs) { return oc_bool2(lhs.x == rhs.x, lhs.y == rhs.y); }
__device__ oc_bool2 operator==(oc_uint2 lhs, oc_uint rhs) { return oc_bool2(lhs.x == rhs, lhs.y == rhs); }
__device__ oc_bool2 operator==(oc_uint lhs, oc_uint2 rhs) { return oc_bool2(lhs == rhs.x, lhs == rhs.y); }
__device__ oc_bool2 operator!=(oc_uint2 lhs, oc_uint2 rhs) { return oc_bool2(lhs.x != rhs.x, lhs.y != rhs.y); }
__device__ oc_bool2 operator!=(oc_uint2 lhs, oc_uint rhs) { return oc_bool2(lhs.x != rhs, lhs.y != rhs); }
__device__ oc_bool2 operator!=(oc_uint lhs, oc_uint2 rhs) { return oc_bool2(lhs != rhs.x, lhs != rhs.y); }
__device__ oc_bool2 operator>(oc_uint2 lhs, oc_uint2 rhs) { return oc_bool2(lhs.x > rhs.x, lhs.y > rhs.y); }
__device__ oc_bool2 operator>(oc_uint2 lhs, oc_uint rhs) { return oc_bool2(lhs.x > rhs, lhs.y > rhs); }
__device__ oc_bool2 operator>(oc_uint lhs, oc_uint2 rhs) { return oc_bool2(lhs > rhs.x, lhs > rhs.y); }
__device__ oc_bool2 operator<(oc_uint2 lhs, oc_uint2 rhs) { return oc_bool2(lhs.x < rhs.x, lhs.y < rhs.y); }
__device__ oc_bool2 operator<(oc_uint2 lhs, oc_uint rhs) { return oc_bool2(lhs.x < rhs, lhs.y < rhs); }
__device__ oc_bool2 operator<(oc_uint lhs, oc_uint2 rhs) { return oc_bool2(lhs < rhs.x, lhs < rhs.y); }
__device__ oc_bool2 operator>=(oc_uint2 lhs, oc_uint2 rhs) { return oc_bool2(lhs.x >= rhs.x, lhs.y >= rhs.y); }
__device__ oc_bool2 operator>=(oc_uint2 lhs, oc_uint rhs) { return oc_bool2(lhs.x >= rhs, lhs.y >= rhs); }
__device__ oc_bool2 operator>=(oc_uint lhs, oc_uint2 rhs) { return oc_bool2(lhs >= rhs.x, lhs >= rhs.y); }
__device__ oc_bool2 operator<=(oc_uint2 lhs, oc_uint2 rhs) { return oc_bool2(lhs.x <= rhs.x, lhs.y <= rhs.y); }
__device__ oc_bool2 operator<=(oc_uint2 lhs, oc_uint rhs) { return oc_bool2(lhs.x <= rhs, lhs.y <= rhs); }
__device__ oc_bool2 operator<=(oc_uint lhs, oc_uint2 rhs) { return oc_bool2(lhs <= rhs.x, lhs <= rhs.y); }
__device__ oc_bool2 operator&&(oc_uint2 lhs, oc_uint2 rhs) { return oc_bool2(lhs.x && rhs.x, lhs.y && rhs.y); }
__device__ oc_bool2 operator&&(oc_uint2 lhs, oc_uint rhs) { return oc_bool2(lhs.x && rhs, lhs.y && rhs); }
__device__ oc_bool2 operator&&(oc_uint lhs, oc_uint2 rhs) { return oc_bool2(lhs && rhs.x, lhs && rhs.y); }
__device__ oc_bool2 operator||(oc_uint2 lhs, oc_uint2 rhs) { return oc_bool2(lhs.x || rhs.x, lhs.y || rhs.y); }
__device__ oc_bool2 operator||(oc_uint2 lhs, oc_uint rhs) { return oc_bool2(lhs.x || rhs, lhs.y || rhs); }
__device__ oc_bool2 operator||(oc_uint lhs, oc_uint2 rhs) { return oc_bool2(lhs || rhs.x, lhs || rhs.y); }
__device__ oc_uint2 operator&(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x & rhs.x, lhs.y & rhs.y); }
__device__ oc_uint2 operator&(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x & rhs, lhs.y & rhs); }
__device__ oc_uint2 operator&(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs & rhs.x, lhs & rhs.y); }
__device__ oc_uint2 operator|(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x | rhs.x, lhs.y | rhs.y); }
__device__ oc_uint2 operator|(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x | rhs, lhs.y | rhs); }
__device__ oc_uint2 operator|(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs | rhs.x, lhs | rhs.y); }
__device__ oc_uint2 operator^(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x ^ rhs.x, lhs.y ^ rhs.y); }
__device__ oc_uint2 operator^(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x ^ rhs, lhs.y ^ rhs); }
__device__ oc_uint2 operator^(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs ^ rhs.x, lhs ^ rhs.y); }
__device__ oc_uint2 operator<<(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x << rhs.x, lhs.y << rhs.y); }
__device__ oc_uint2 operator<<(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x << rhs, lhs.y << rhs); }
__device__ oc_uint2 operator<<(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs << rhs.x, lhs << rhs.y); }
__device__ oc_uint2 operator>>(oc_uint2 lhs, oc_uint2 rhs) { return oc_uint2(lhs.x >> rhs.x, lhs.y >> rhs.y); }
__device__ oc_uint2 operator>>(oc_uint2 lhs, oc_uint rhs) { return oc_uint2(lhs.x >> rhs, lhs.y >> rhs); }
__device__ oc_uint2 operator>>(oc_uint lhs, oc_uint2 rhs) { return oc_uint2(lhs >> rhs.x, lhs >> rhs.y); }
__device__ oc_uint3 operator+(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x + rhs.x, lhs.y + rhs.y, lhs.z + rhs.z); }
__device__ oc_uint3 operator+(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x + rhs, lhs.y + rhs, lhs.z + rhs); }
__device__ oc_uint3 operator+(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs + rhs.x, lhs + rhs.y, lhs + rhs.z); }
__device__ oc_uint3 operator-(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x - rhs.x, lhs.y - rhs.y, lhs.z - rhs.z); }
__device__ oc_uint3 operator-(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x - rhs, lhs.y - rhs, lhs.z - rhs); }
__device__ oc_uint3 operator-(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs - rhs.x, lhs - rhs.y, lhs - rhs.z); }
__device__ oc_uint3 operator*(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x * rhs.x, lhs.y * rhs.y, lhs.z * rhs.z); }
__device__ oc_uint3 operator*(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x * rhs, lhs.y * rhs, lhs.z * rhs); }
__device__ oc_uint3 operator*(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs * rhs.x, lhs * rhs.y, lhs * rhs.z); }
__device__ oc_uint3 operator/(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x / rhs.x, lhs.y / rhs.y, lhs.z / rhs.z); }
__device__ oc_uint3 operator/(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x / rhs, lhs.y / rhs, lhs.z / rhs); }
__device__ oc_uint3 operator/(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs / rhs.x, lhs / rhs.y, lhs / rhs.z); }
__device__ oc_uint3 operator%(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x % rhs.x, lhs.y % rhs.y, lhs.z % rhs.z); }
__device__ oc_uint3 operator%(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x % rhs, lhs.y % rhs, lhs.z % rhs); }
__device__ oc_uint3 operator%(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs % rhs.x, lhs % rhs.y, lhs % rhs.z); }
__device__ oc_bool3 operator==(oc_uint3 lhs, oc_uint3 rhs) { return oc_bool3(lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z); }
__device__ oc_bool3 operator==(oc_uint3 lhs, oc_uint rhs) { return oc_bool3(lhs.x == rhs, lhs.y == rhs, lhs.z == rhs); }
__device__ oc_bool3 operator==(oc_uint lhs, oc_uint3 rhs) { return oc_bool3(lhs == rhs.x, lhs == rhs.y, lhs == rhs.z); }
__device__ oc_bool3 operator!=(oc_uint3 lhs, oc_uint3 rhs) { return oc_bool3(lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z); }
__device__ oc_bool3 operator!=(oc_uint3 lhs, oc_uint rhs) { return oc_bool3(lhs.x != rhs, lhs.y != rhs, lhs.z != rhs); }
__device__ oc_bool3 operator!=(oc_uint lhs, oc_uint3 rhs) { return oc_bool3(lhs != rhs.x, lhs != rhs.y, lhs != rhs.z); }
__device__ oc_bool3 operator>(oc_uint3 lhs, oc_uint3 rhs) { return oc_bool3(lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z); }
__device__ oc_bool3 operator>(oc_uint3 lhs, oc_uint rhs) { return oc_bool3(lhs.x > rhs, lhs.y > rhs, lhs.z > rhs); }
__device__ oc_bool3 operator>(oc_uint lhs, oc_uint3 rhs) { return oc_bool3(lhs > rhs.x, lhs > rhs.y, lhs > rhs.z); }
__device__ oc_bool3 operator<(oc_uint3 lhs, oc_uint3 rhs) { return oc_bool3(lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z); }
__device__ oc_bool3 operator<(oc_uint3 lhs, oc_uint rhs) { return oc_bool3(lhs.x < rhs, lhs.y < rhs, lhs.z < rhs); }
__device__ oc_bool3 operator<(oc_uint lhs, oc_uint3 rhs) { return oc_bool3(lhs < rhs.x, lhs < rhs.y, lhs < rhs.z); }
__device__ oc_bool3 operator>=(oc_uint3 lhs, oc_uint3 rhs) { return oc_bool3(lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z); }
__device__ oc_bool3 operator>=(oc_uint3 lhs, oc_uint rhs) { return oc_bool3(lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs); }
__device__ oc_bool3 operator>=(oc_uint lhs, oc_uint3 rhs) { return oc_bool3(lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z); }
__device__ oc_bool3 operator<=(oc_uint3 lhs, oc_uint3 rhs) { return oc_bool3(lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z); }
__device__ oc_bool3 operator<=(oc_uint3 lhs, oc_uint rhs) { return oc_bool3(lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs); }
__device__ oc_bool3 operator<=(oc_uint lhs, oc_uint3 rhs) { return oc_bool3(lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z); }
__device__ oc_bool3 operator&&(oc_uint3 lhs, oc_uint3 rhs) { return oc_bool3(lhs.x && rhs.x, lhs.y && rhs.y, lhs.z && rhs.z); }
__device__ oc_bool3 operator&&(oc_uint3 lhs, oc_uint rhs) { return oc_bool3(lhs.x && rhs, lhs.y && rhs, lhs.z && rhs); }
__device__ oc_bool3 operator&&(oc_uint lhs, oc_uint3 rhs) { return oc_bool3(lhs && rhs.x, lhs && rhs.y, lhs && rhs.z); }
__device__ oc_bool3 operator||(oc_uint3 lhs, oc_uint3 rhs) { return oc_bool3(lhs.x || rhs.x, lhs.y || rhs.y, lhs.z || rhs.z); }
__device__ oc_bool3 operator||(oc_uint3 lhs, oc_uint rhs) { return oc_bool3(lhs.x || rhs, lhs.y || rhs, lhs.z || rhs); }
__device__ oc_bool3 operator||(oc_uint lhs, oc_uint3 rhs) { return oc_bool3(lhs || rhs.x, lhs || rhs.y, lhs || rhs.z); }
__device__ oc_uint3 operator&(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x & rhs.x, lhs.y & rhs.y, lhs.z & rhs.z); }
__device__ oc_uint3 operator&(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x & rhs, lhs.y & rhs, lhs.z & rhs); }
__device__ oc_uint3 operator&(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs & rhs.x, lhs & rhs.y, lhs & rhs.z); }
__device__ oc_uint3 operator|(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x | rhs.x, lhs.y | rhs.y, lhs.z | rhs.z); }
__device__ oc_uint3 operator|(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x | rhs, lhs.y | rhs, lhs.z | rhs); }
__device__ oc_uint3 operator|(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs | rhs.x, lhs | rhs.y, lhs | rhs.z); }
__device__ oc_uint3 operator^(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x ^ rhs.x, lhs.y ^ rhs.y, lhs.z ^ rhs.z); }
__device__ oc_uint3 operator^(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x ^ rhs, lhs.y ^ rhs, lhs.z ^ rhs); }
__device__ oc_uint3 operator^(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs ^ rhs.x, lhs ^ rhs.y, lhs ^ rhs.z); }
__device__ oc_uint3 operator<<(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x << rhs.x, lhs.y << rhs.y, lhs.z << rhs.z); }
__device__ oc_uint3 operator<<(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x << rhs, lhs.y << rhs, lhs.z << rhs); }
__device__ oc_uint3 operator<<(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs << rhs.x, lhs << rhs.y, lhs << rhs.z); }
__device__ oc_uint3 operator>>(oc_uint3 lhs, oc_uint3 rhs) { return oc_uint3(lhs.x >> rhs.x, lhs.y >> rhs.y, lhs.z >> rhs.z); }
__device__ oc_uint3 operator>>(oc_uint3 lhs, oc_uint rhs) { return oc_uint3(lhs.x >> rhs, lhs.y >> rhs, lhs.z >> rhs); }
__device__ oc_uint3 operator>>(oc_uint lhs, oc_uint3 rhs) { return oc_uint3(lhs >> rhs.x, lhs >> rhs.y, lhs >> rhs.z); }
__device__ oc_uint4 operator+(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x + rhs.x, lhs.y + rhs.y, lhs.z + rhs.z, lhs.w + rhs.w); }
__device__ oc_uint4 operator+(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x + rhs, lhs.y + rhs, lhs.z + rhs, lhs.w + rhs); }
__device__ oc_uint4 operator+(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs + rhs.x, lhs + rhs.y, lhs + rhs.z, lhs + rhs.w); }
__device__ oc_uint4 operator-(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x - rhs.x, lhs.y - rhs.y, lhs.z - rhs.z, lhs.w - rhs.w); }
__device__ oc_uint4 operator-(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x - rhs, lhs.y - rhs, lhs.z - rhs, lhs.w - rhs); }
__device__ oc_uint4 operator-(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs - rhs.x, lhs - rhs.y, lhs - rhs.z, lhs - rhs.w); }
__device__ oc_uint4 operator*(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x * rhs.x, lhs.y * rhs.y, lhs.z * rhs.z, lhs.w * rhs.w); }
__device__ oc_uint4 operator*(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x * rhs, lhs.y * rhs, lhs.z * rhs, lhs.w * rhs); }
__device__ oc_uint4 operator*(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs * rhs.x, lhs * rhs.y, lhs * rhs.z, lhs * rhs.w); }
__device__ oc_uint4 operator/(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x / rhs.x, lhs.y / rhs.y, lhs.z / rhs.z, lhs.w / rhs.w); }
__device__ oc_uint4 operator/(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x / rhs, lhs.y / rhs, lhs.z / rhs, lhs.w / rhs); }
__device__ oc_uint4 operator/(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs / rhs.x, lhs / rhs.y, lhs / rhs.z, lhs / rhs.w); }
__device__ oc_uint4 operator%(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x % rhs.x, lhs.y % rhs.y, lhs.z % rhs.z, lhs.w % rhs.w); }
__device__ oc_uint4 operator%(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x % rhs, lhs.y % rhs, lhs.z % rhs, lhs.w % rhs); }
__device__ oc_uint4 operator%(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs % rhs.x, lhs % rhs.y, lhs % rhs.z, lhs % rhs.w); }
__device__ oc_bool4 operator==(oc_uint4 lhs, oc_uint4 rhs) { return oc_bool4(lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z, lhs.w == rhs.w); }
__device__ oc_bool4 operator==(oc_uint4 lhs, oc_uint rhs) { return oc_bool4(lhs.x == rhs, lhs.y == rhs, lhs.z == rhs, lhs.w == rhs); }
__device__ oc_bool4 operator==(oc_uint lhs, oc_uint4 rhs) { return oc_bool4(lhs == rhs.x, lhs == rhs.y, lhs == rhs.z, lhs == rhs.w); }
__device__ oc_bool4 operator!=(oc_uint4 lhs, oc_uint4 rhs) { return oc_bool4(lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z, lhs.w != rhs.w); }
__device__ oc_bool4 operator!=(oc_uint4 lhs, oc_uint rhs) { return oc_bool4(lhs.x != rhs, lhs.y != rhs, lhs.z != rhs, lhs.w != rhs); }
__device__ oc_bool4 operator!=(oc_uint lhs, oc_uint4 rhs) { return oc_bool4(lhs != rhs.x, lhs != rhs.y, lhs != rhs.z, lhs != rhs.w); }
__device__ oc_bool4 operator>(oc_uint4 lhs, oc_uint4 rhs) { return oc_bool4(lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z, lhs.w > rhs.w); }
__device__ oc_bool4 operator>(oc_uint4 lhs, oc_uint rhs) { return oc_bool4(lhs.x > rhs, lhs.y > rhs, lhs.z > rhs, lhs.w > rhs); }
__device__ oc_bool4 operator>(oc_uint lhs, oc_uint4 rhs) { return oc_bool4(lhs > rhs.x, lhs > rhs.y, lhs > rhs.z, lhs > rhs.w); }
__device__ oc_bool4 operator<(oc_uint4 lhs, oc_uint4 rhs) { return oc_bool4(lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z, lhs.w < rhs.w); }
__device__ oc_bool4 operator<(oc_uint4 lhs, oc_uint rhs) { return oc_bool4(lhs.x < rhs, lhs.y < rhs, lhs.z < rhs, lhs.w < rhs); }
__device__ oc_bool4 operator<(oc_uint lhs, oc_uint4 rhs) { return oc_bool4(lhs < rhs.x, lhs < rhs.y, lhs < rhs.z, lhs < rhs.w); }
__device__ oc_bool4 operator>=(oc_uint4 lhs, oc_uint4 rhs) { return oc_bool4(lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z, lhs.w >= rhs.w); }
__device__ oc_bool4 operator>=(oc_uint4 lhs, oc_uint rhs) { return oc_bool4(lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs, lhs.w >= rhs); }
__device__ oc_bool4 operator>=(oc_uint lhs, oc_uint4 rhs) { return oc_bool4(lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z, lhs >= rhs.w); }
__device__ oc_bool4 operator<=(oc_uint4 lhs, oc_uint4 rhs) { return oc_bool4(lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z, lhs.w <= rhs.w); }
__device__ oc_bool4 operator<=(oc_uint4 lhs, oc_uint rhs) { return oc_bool4(lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs, lhs.w <= rhs); }
__device__ oc_bool4 operator<=(oc_uint lhs, oc_uint4 rhs) { return oc_bool4(lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z, lhs <= rhs.w); }
__device__ oc_bool4 operator&&(oc_uint4 lhs, oc_uint4 rhs) { return oc_bool4(lhs.x && rhs.x, lhs.y && rhs.y, lhs.z && rhs.z, lhs.w && rhs.w); }
__device__ oc_bool4 operator&&(oc_uint4 lhs, oc_uint rhs) { return oc_bool4(lhs.x && rhs, lhs.y && rhs, lhs.z && rhs, lhs.w && rhs); }
__device__ oc_bool4 operator&&(oc_uint lhs, oc_uint4 rhs) { return oc_bool4(lhs && rhs.x, lhs && rhs.y, lhs && rhs.z, lhs && rhs.w); }
__device__ oc_bool4 operator||(oc_uint4 lhs, oc_uint4 rhs) { return oc_bool4(lhs.x || rhs.x, lhs.y || rhs.y, lhs.z || rhs.z, lhs.w || rhs.w); }
__device__ oc_bool4 operator||(oc_uint4 lhs, oc_uint rhs) { return oc_bool4(lhs.x || rhs, lhs.y || rhs, lhs.z || rhs, lhs.w || rhs); }
__device__ oc_bool4 operator||(oc_uint lhs, oc_uint4 rhs) { return oc_bool4(lhs || rhs.x, lhs || rhs.y, lhs || rhs.z, lhs || rhs.w); }
__device__ oc_uint4 operator&(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x & rhs.x, lhs.y & rhs.y, lhs.z & rhs.z, lhs.w & rhs.w); }
__device__ oc_uint4 operator&(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x & rhs, lhs.y & rhs, lhs.z & rhs, lhs.w & rhs); }
__device__ oc_uint4 operator&(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs & rhs.x, lhs & rhs.y, lhs & rhs.z, lhs & rhs.w); }
__device__ oc_uint4 operator|(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x | rhs.x, lhs.y | rhs.y, lhs.z | rhs.z, lhs.w | rhs.w); }
__device__ oc_uint4 operator|(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x | rhs, lhs.y | rhs, lhs.z | rhs, lhs.w | rhs); }
__device__ oc_uint4 operator|(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs | rhs.x, lhs | rhs.y, lhs | rhs.z, lhs | rhs.w); }
__device__ oc_uint4 operator^(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x ^ rhs.x, lhs.y ^ rhs.y, lhs.z ^ rhs.z, lhs.w ^ rhs.w); }
__device__ oc_uint4 operator^(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x ^ rhs, lhs.y ^ rhs, lhs.z ^ rhs, lhs.w ^ rhs); }
__device__ oc_uint4 operator^(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs ^ rhs.x, lhs ^ rhs.y, lhs ^ rhs.z, lhs ^ rhs.w); }
__device__ oc_uint4 operator<<(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x << rhs.x, lhs.y << rhs.y, lhs.z << rhs.z, lhs.w << rhs.w); }
__device__ oc_uint4 operator<<(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x << rhs, lhs.y << rhs, lhs.z << rhs, lhs.w << rhs); }
__device__ oc_uint4 operator<<(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs << rhs.x, lhs << rhs.y, lhs << rhs.z, lhs << rhs.w); }
__device__ oc_uint4 operator>>(oc_uint4 lhs, oc_uint4 rhs) { return oc_uint4(lhs.x >> rhs.x, lhs.y >> rhs.y, lhs.z >> rhs.z, lhs.w >> rhs.w); }
__device__ oc_uint4 operator>>(oc_uint4 lhs, oc_uint rhs) { return oc_uint4(lhs.x >> rhs, lhs.y >> rhs, lhs.z >> rhs, lhs.w >> rhs); }
__device__ oc_uint4 operator>>(oc_uint lhs, oc_uint4 rhs) { return oc_uint4(lhs >> rhs.x, lhs >> rhs.y, lhs >> rhs.z, lhs >> rhs.w); }

__device__ oc_float2 operator+(oc_float2 lhs, oc_float2 rhs) { return oc_float2(lhs.x + rhs.x, lhs.y + rhs.y); }
__device__ oc_float2 operator+(oc_float2 lhs, oc_float rhs) { return oc_float2(lhs.x + rhs, lhs.y + rhs); }
__device__ oc_float2 operator+(oc_float lhs, oc_float2 rhs) { return oc_float2(lhs + rhs.x, lhs + rhs.y); }
__device__ oc_float2 operator-(oc_float2 lhs, oc_float2 rhs) { return oc_float2(lhs.x - rhs.x, lhs.y - rhs.y); }
__device__ oc_float2 operator-(oc_float2 lhs, oc_float rhs) { return oc_float2(lhs.x - rhs, lhs.y - rhs); }
__device__ oc_float2 operator-(oc_float lhs, oc_float2 rhs) { return oc_float2(lhs - rhs.x, lhs - rhs.y); }
__device__ oc_float2 operator*(oc_float2 lhs, oc_float2 rhs) { return oc_float2(lhs.x * rhs.x, lhs.y * rhs.y); }
__device__ oc_float2 operator*(oc_float2 lhs, oc_float rhs) { return oc_float2(lhs.x * rhs, lhs.y * rhs); }
__device__ oc_float2 operator*(oc_float lhs, oc_float2 rhs) { return oc_float2(lhs * rhs.x, lhs * rhs.y); }
__device__ oc_float2 operator/(oc_float2 lhs, oc_float2 rhs) { return oc_float2(lhs.x / rhs.x, lhs.y / rhs.y); }
__device__ oc_float2 operator/(oc_float2 lhs, oc_float rhs) { return oc_float2(lhs.x / rhs, lhs.y / rhs); }
__device__ oc_float2 operator/(oc_float lhs, oc_float2 rhs) { return oc_float2(lhs / rhs.x, lhs / rhs.y); }
__device__ oc_bool2 operator==(oc_float2 lhs, oc_float2 rhs) { return oc_bool2(lhs.x == rhs.x, lhs.y == rhs.y); }
__device__ oc_bool2 operator==(oc_float2 lhs, oc_float rhs) { return oc_bool2(lhs.x == rhs, lhs.y == rhs); }
__device__ oc_bool2 operator==(oc_float lhs, oc_float2 rhs) { return oc_bool2(lhs == rhs.x, lhs == rhs.y); }
__device__ oc_bool2 operator!=(oc_float2 lhs, oc_float2 rhs) { return oc_bool2(lhs.x != rhs.x, lhs.y != rhs.y); }
__device__ oc_bool2 operator!=(oc_float2 lhs, oc_float rhs) { return oc_bool2(lhs.x != rhs, lhs.y != rhs); }
__device__ oc_bool2 operator!=(oc_float lhs, oc_float2 rhs) { return oc_bool2(lhs != rhs.x, lhs != rhs.y); }
__device__ oc_bool2 operator>(oc_float2 lhs, oc_float2 rhs) { return oc_bool2(lhs.x > rhs.x, lhs.y > rhs.y); }
__device__ oc_bool2 operator>(oc_float2 lhs, oc_float rhs) { return oc_bool2(lhs.x > rhs, lhs.y > rhs); }
__device__ oc_bool2 operator>(oc_float lhs, oc_float2 rhs) { return oc_bool2(lhs > rhs.x, lhs > rhs.y); }
__device__ oc_bool2 operator<(oc_float2 lhs, oc_float2 rhs) { return oc_bool2(lhs.x < rhs.x, lhs.y < rhs.y); }
__device__ oc_bool2 operator<(oc_float2 lhs, oc_float rhs) { return oc_bool2(lhs.x < rhs, lhs.y < rhs); }
__device__ oc_bool2 operator<(oc_float lhs, oc_float2 rhs) { return oc_bool2(lhs < rhs.x, lhs < rhs.y); }
__device__ oc_bool2 operator>=(oc_float2 lhs, oc_float2 rhs) { return oc_bool2(lhs.x >= rhs.x, lhs.y >= rhs.y); }
__device__ oc_bool2 operator>=(oc_float2 lhs, oc_float rhs) { return oc_bool2(lhs.x >= rhs, lhs.y >= rhs); }
__device__ oc_bool2 operator>=(oc_float lhs, oc_float2 rhs) { return oc_bool2(lhs >= rhs.x, lhs >= rhs.y); }
__device__ oc_bool2 operator<=(oc_float2 lhs, oc_float2 rhs) { return oc_bool2(lhs.x <= rhs.x, lhs.y <= rhs.y); }
__device__ oc_bool2 operator<=(oc_float2 lhs, oc_float rhs) { return oc_bool2(lhs.x <= rhs, lhs.y <= rhs); }
__device__ oc_bool2 operator<=(oc_float lhs, oc_float2 rhs) { return oc_bool2(lhs <= rhs.x, lhs <= rhs.y); }
__device__ oc_bool2 operator&&(oc_float2 lhs, oc_float2 rhs) { return oc_bool2(lhs.x && rhs.x, lhs.y && rhs.y); }
__device__ oc_bool2 operator&&(oc_float2 lhs, oc_float rhs) { return oc_bool2(lhs.x && rhs, lhs.y && rhs); }
__device__ oc_bool2 operator&&(oc_float lhs, oc_float2 rhs) { return oc_bool2(lhs && rhs.x, lhs && rhs.y); }
__device__ oc_bool2 operator||(oc_float2 lhs, oc_float2 rhs) { return oc_bool2(lhs.x || rhs.x, lhs.y || rhs.y); }
__device__ oc_bool2 operator||(oc_float2 lhs, oc_float rhs) { return oc_bool2(lhs.x || rhs, lhs.y || rhs); }
__device__ oc_bool2 operator||(oc_float lhs, oc_float2 rhs) { return oc_bool2(lhs || rhs.x, lhs || rhs.y); }
__device__ oc_float3 operator+(oc_float3 lhs, oc_float3 rhs) { return oc_float3(lhs.x + rhs.x, lhs.y + rhs.y, lhs.z + rhs.z); }
__device__ oc_float3 operator+(oc_float3 lhs, oc_float rhs) { return oc_float3(lhs.x + rhs, lhs.y + rhs, lhs.z + rhs); }
__device__ oc_float3 operator+(oc_float lhs, oc_float3 rhs) { return oc_float3(lhs + rhs.x, lhs + rhs.y, lhs + rhs.z); }
__device__ oc_float3 operator-(oc_float3 lhs, oc_float3 rhs) { return oc_float3(lhs.x - rhs.x, lhs.y - rhs.y, lhs.z - rhs.z); }
__device__ oc_float3 operator-(oc_float3 lhs, oc_float rhs) { return oc_float3(lhs.x - rhs, lhs.y - rhs, lhs.z - rhs); }
__device__ oc_float3 operator-(oc_float lhs, oc_float3 rhs) { return oc_float3(lhs - rhs.x, lhs - rhs.y, lhs - rhs.z); }
__device__ oc_float3 operator*(oc_float3 lhs, oc_float3 rhs) { return oc_float3(lhs.x * rhs.x, lhs.y * rhs.y, lhs.z * rhs.z); }
__device__ oc_float3 operator*(oc_float3 lhs, oc_float rhs) { return oc_float3(lhs.x * rhs, lhs.y * rhs, lhs.z * rhs); }
__device__ oc_float3 operator*(oc_float lhs, oc_float3 rhs) { return oc_float3(lhs * rhs.x, lhs * rhs.y, lhs * rhs.z); }
__device__ oc_float3 operator/(oc_float3 lhs, oc_float3 rhs) { return oc_float3(lhs.x / rhs.x, lhs.y / rhs.y, lhs.z / rhs.z); }
__device__ oc_float3 operator/(oc_float3 lhs, oc_float rhs) { return oc_float3(lhs.x / rhs, lhs.y / rhs, lhs.z / rhs); }
__device__ oc_float3 operator/(oc_float lhs, oc_float3 rhs) { return oc_float3(lhs / rhs.x, lhs / rhs.y, lhs / rhs.z); }
__device__ oc_bool3 operator==(oc_float3 lhs, oc_float3 rhs) { return oc_bool3(lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z); }
__device__ oc_bool3 operator==(oc_float3 lhs, oc_float rhs) { return oc_bool3(lhs.x == rhs, lhs.y == rhs, lhs.z == rhs); }
__device__ oc_bool3 operator==(oc_float lhs, oc_float3 rhs) { return oc_bool3(lhs == rhs.x, lhs == rhs.y, lhs == rhs.z); }
__device__ oc_bool3 operator!=(oc_float3 lhs, oc_float3 rhs) { return oc_bool3(lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z); }
__device__ oc_bool3 operator!=(oc_float3 lhs, oc_float rhs) { return oc_bool3(lhs.x != rhs, lhs.y != rhs, lhs.z != rhs); }
__device__ oc_bool3 operator!=(oc_float lhs, oc_float3 rhs) { return oc_bool3(lhs != rhs.x, lhs != rhs.y, lhs != rhs.z); }
__device__ oc_bool3 operator>(oc_float3 lhs, oc_float3 rhs) { return oc_bool3(lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z); }
__device__ oc_bool3 operator>(oc_float3 lhs, oc_float rhs) { return oc_bool3(lhs.x > rhs, lhs.y > rhs, lhs.z > rhs); }
__device__ oc_bool3 operator>(oc_float lhs, oc_float3 rhs) { return oc_bool3(lhs > rhs.x, lhs > rhs.y, lhs > rhs.z); }
__device__ oc_bool3 operator<(oc_float3 lhs, oc_float3 rhs) { return oc_bool3(lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z); }
__device__ oc_bool3 operator<(oc_float3 lhs, oc_float rhs) { return oc_bool3(lhs.x < rhs, lhs.y < rhs, lhs.z < rhs); }
__device__ oc_bool3 operator<(oc_float lhs, oc_float3 rhs) { return oc_bool3(lhs < rhs.x, lhs < rhs.y, lhs < rhs.z); }
__device__ oc_bool3 operator>=(oc_float3 lhs, oc_float3 rhs) { return oc_bool3(lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z); }
__device__ oc_bool3 operator>=(oc_float3 lhs, oc_float rhs) { return oc_bool3(lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs); }
__device__ oc_bool3 operator>=(oc_float lhs, oc_float3 rhs) { return oc_bool3(lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z); }
__device__ oc_bool3 operator<=(oc_float3 lhs, oc_float3 rhs) { return oc_bool3(lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z); }
__device__ oc_bool3 operator<=(oc_float3 lhs, oc_float rhs) { return oc_bool3(lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs); }
__device__ oc_bool3 operator<=(oc_float lhs, oc_float3 rhs) { return oc_bool3(lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z); }
__device__ oc_bool3 operator&&(oc_float3 lhs, oc_float3 rhs) { return oc_bool3(lhs.x && rhs.x, lhs.y && rhs.y, lhs.z && rhs.z); }
__device__ oc_bool3 operator&&(oc_float3 lhs, oc_float rhs) { return oc_bool3(lhs.x && rhs, lhs.y && rhs, lhs.z && rhs); }
__device__ oc_bool3 operator&&(oc_float lhs, oc_float3 rhs) { return oc_bool3(lhs && rhs.x, lhs && rhs.y, lhs && rhs.z); }
__device__ oc_bool3 operator||(oc_float3 lhs, oc_float3 rhs) { return oc_bool3(lhs.x || rhs.x, lhs.y || rhs.y, lhs.z || rhs.z); }
__device__ oc_bool3 operator||(oc_float3 lhs, oc_float rhs) { return oc_bool3(lhs.x || rhs, lhs.y || rhs, lhs.z || rhs); }
__device__ oc_bool3 operator||(oc_float lhs, oc_float3 rhs) { return oc_bool3(lhs || rhs.x, lhs || rhs.y, lhs || rhs.z); }
__device__ oc_float4 operator+(oc_float4 lhs, oc_float4 rhs) { return oc_float4(lhs.x + rhs.x, lhs.y + rhs.y, lhs.z + rhs.z, lhs.w + rhs.w); }
__device__ oc_float4 operator+(oc_float4 lhs, oc_float rhs) { return oc_float4(lhs.x + rhs, lhs.y + rhs, lhs.z + rhs, lhs.w + rhs); }
__device__ oc_float4 operator+(oc_float lhs, oc_float4 rhs) { return oc_float4(lhs + rhs.x, lhs + rhs.y, lhs + rhs.z, lhs + rhs.w); }
__device__ oc_float4 operator-(oc_float4 lhs, oc_float4 rhs) { return oc_float4(lhs.x - rhs.x, lhs.y - rhs.y, lhs.z - rhs.z, lhs.w - rhs.w); }
__device__ oc_float4 operator-(oc_float4 lhs, oc_float rhs) { return oc_float4(lhs.x - rhs, lhs.y - rhs, lhs.z - rhs, lhs.w - rhs); }
__device__ oc_float4 operator-(oc_float lhs, oc_float4 rhs) { return oc_float4(lhs - rhs.x, lhs - rhs.y, lhs - rhs.z, lhs - rhs.w); }
__device__ oc_float4 operator*(oc_float4 lhs, oc_float4 rhs) { return oc_float4(lhs.x * rhs.x, lhs.y * rhs.y, lhs.z * rhs.z, lhs.w * rhs.w); }
__device__ oc_float4 operator*(oc_float4 lhs, oc_float rhs) { return oc_float4(lhs.x * rhs, lhs.y * rhs, lhs.z * rhs, lhs.w * rhs); }
__device__ oc_float4 operator*(oc_float lhs, oc_float4 rhs) { return oc_float4(lhs * rhs.x, lhs * rhs.y, lhs * rhs.z, lhs * rhs.w); }
__device__ oc_float4 operator/(oc_float4 lhs, oc_float4 rhs) { return oc_float4(lhs.x / rhs.x, lhs.y / rhs.y, lhs.z / rhs.z, lhs.w / rhs.w); }
__device__ oc_float4 operator/(oc_float4 lhs, oc_float rhs) { return oc_float4(lhs.x / rhs, lhs.y / rhs, lhs.z / rhs, lhs.w / rhs); }
__device__ oc_float4 operator/(oc_float lhs, oc_float4 rhs) { return oc_float4(lhs / rhs.x, lhs / rhs.y, lhs / rhs.z, lhs / rhs.w); }
__device__ oc_bool4 operator==(oc_float4 lhs, oc_float4 rhs) { return oc_bool4(lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z, lhs.w == rhs.w); }
__device__ oc_bool4 operator==(oc_float4 lhs, oc_float rhs) { return oc_bool4(lhs.x == rhs, lhs.y == rhs, lhs.z == rhs, lhs.w == rhs); }
__device__ oc_bool4 operator==(oc_float lhs, oc_float4 rhs) { return oc_bool4(lhs == rhs.x, lhs == rhs.y, lhs == rhs.z, lhs == rhs.w); }
__device__ oc_bool4 operator!=(oc_float4 lhs, oc_float4 rhs) { return oc_bool4(lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z, lhs.w != rhs.w); }
__device__ oc_bool4 operator!=(oc_float4 lhs, oc_float rhs) { return oc_bool4(lhs.x != rhs, lhs.y != rhs, lhs.z != rhs, lhs.w != rhs); }
__device__ oc_bool4 operator!=(oc_float lhs, oc_float4 rhs) { return oc_bool4(lhs != rhs.x, lhs != rhs.y, lhs != rhs.z, lhs != rhs.w); }
__device__ oc_bool4 operator>(oc_float4 lhs, oc_float4 rhs) { return oc_bool4(lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z, lhs.w > rhs.w); }
__device__ oc_bool4 operator>(oc_float4 lhs, oc_float rhs) { return oc_bool4(lhs.x > rhs, lhs.y > rhs, lhs.z > rhs, lhs.w > rhs); }
__device__ oc_bool4 operator>(oc_float lhs, oc_float4 rhs) { return oc_bool4(lhs > rhs.x, lhs > rhs.y, lhs > rhs.z, lhs > rhs.w); }
__device__ oc_bool4 operator<(oc_float4 lhs, oc_float4 rhs) { return oc_bool4(lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z, lhs.w < rhs.w); }
__device__ oc_bool4 operator<(oc_float4 lhs, oc_float rhs) { return oc_bool4(lhs.x < rhs, lhs.y < rhs, lhs.z < rhs, lhs.w < rhs); }
__device__ oc_bool4 operator<(oc_float lhs, oc_float4 rhs) { return oc_bool4(lhs < rhs.x, lhs < rhs.y, lhs < rhs.z, lhs < rhs.w); }
__device__ oc_bool4 operator>=(oc_float4 lhs, oc_float4 rhs) { return oc_bool4(lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z, lhs.w >= rhs.w); }
__device__ oc_bool4 operator>=(oc_float4 lhs, oc_float rhs) { return oc_bool4(lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs, lhs.w >= rhs); }
__device__ oc_bool4 operator>=(oc_float lhs, oc_float4 rhs) { return oc_bool4(lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z, lhs >= rhs.w); }
__device__ oc_bool4 operator<=(oc_float4 lhs, oc_float4 rhs) { return oc_bool4(lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z, lhs.w <= rhs.w); }
__device__ oc_bool4 operator<=(oc_float4 lhs, oc_float rhs) { return oc_bool4(lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs, lhs.w <= rhs); }
__device__ oc_bool4 operator<=(oc_float lhs, oc_float4 rhs) { return oc_bool4(lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z, lhs <= rhs.w); }
__device__ oc_bool4 operator&&(oc_float4 lhs, oc_float4 rhs) { return oc_bool4(lhs.x && rhs.x, lhs.y && rhs.y, lhs.z && rhs.z, lhs.w && rhs.w); }
__device__ oc_bool4 operator&&(oc_float4 lhs, oc_float rhs) { return oc_bool4(lhs.x && rhs, lhs.y && rhs, lhs.z && rhs, lhs.w && rhs); }
__device__ oc_bool4 operator&&(oc_float lhs, oc_float4 rhs) { return oc_bool4(lhs && rhs.x, lhs && rhs.y, lhs && rhs.z, lhs && rhs.w); }
__device__ oc_bool4 operator||(oc_float4 lhs, oc_float4 rhs) { return oc_bool4(lhs.x || rhs.x, lhs.y || rhs.y, lhs.z || rhs.z, lhs.w || rhs.w); }
__device__ oc_bool4 operator||(oc_float4 lhs, oc_float rhs) { return oc_bool4(lhs.x || rhs, lhs.y || rhs, lhs.z || rhs, lhs.w || rhs); }
__device__ oc_bool4 operator||(oc_float lhs, oc_float4 rhs) { return oc_bool4(lhs || rhs.x, lhs || rhs.y, lhs || rhs.z, lhs || rhs.w); }

__device__ oc_bool2 operator==(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x == rhs.x, lhs.y == rhs.y); }
__device__ oc_bool2 operator==(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x == rhs, lhs.y == rhs); }
__device__ oc_bool2 operator==(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs == rhs.x, lhs == rhs.y); }
__device__ oc_bool2 operator!=(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x != rhs.x, lhs.y != rhs.y); }
__device__ oc_bool2 operator!=(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x != rhs, lhs.y != rhs); }
__device__ oc_bool2 operator!=(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs != rhs.x, lhs != rhs.y); }
__device__ oc_bool2 operator>(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x > rhs.x, lhs.y > rhs.y); }
__device__ oc_bool2 operator>(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x > rhs, lhs.y > rhs); }
__device__ oc_bool2 operator>(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs > rhs.x, lhs > rhs.y); }
__device__ oc_bool2 operator<(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x < rhs.x, lhs.y < rhs.y); }
__device__ oc_bool2 operator<(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x < rhs, lhs.y < rhs); }
__device__ oc_bool2 operator<(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs < rhs.x, lhs < rhs.y); }
__device__ oc_bool2 operator>=(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x >= rhs.x, lhs.y >= rhs.y); }
__device__ oc_bool2 operator>=(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x >= rhs, lhs.y >= rhs); }
__device__ oc_bool2 operator>=(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs >= rhs.x, lhs >= rhs.y); }
__device__ oc_bool2 operator<=(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x <= rhs.x, lhs.y <= rhs.y); }
__device__ oc_bool2 operator<=(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x <= rhs, lhs.y <= rhs); }
__device__ oc_bool2 operator<=(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs <= rhs.x, lhs <= rhs.y); }
__device__ oc_bool2 operator&&(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x && rhs.x, lhs.y && rhs.y); }
__device__ oc_bool2 operator&&(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x && rhs, lhs.y && rhs); }
__device__ oc_bool2 operator&&(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs && rhs.x, lhs && rhs.y); }
__device__ oc_bool2 operator||(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x || rhs.x, lhs.y || rhs.y); }
__device__ oc_bool2 operator||(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x || rhs, lhs.y || rhs); }
__device__ oc_bool2 operator||(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs || rhs.x, lhs || rhs.y); }
__device__ oc_bool2 operator&(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x & rhs.x, lhs.y & rhs.y); }
__device__ oc_bool2 operator&(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x & rhs, lhs.y & rhs); }
__device__ oc_bool2 operator&(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs & rhs.x, lhs & rhs.y); }
__device__ oc_bool2 operator|(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x | rhs.x, lhs.y | rhs.y); }
__device__ oc_bool2 operator|(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x | rhs, lhs.y | rhs); }
__device__ oc_bool2 operator|(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs | rhs.x, lhs | rhs.y); }
__device__ oc_bool2 operator^(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x ^ rhs.x, lhs.y ^ rhs.y); }
__device__ oc_bool2 operator^(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x ^ rhs, lhs.y ^ rhs); }
__device__ oc_bool2 operator^(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs ^ rhs.x, lhs ^ rhs.y); }
__device__ oc_bool2 operator<<(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x << rhs.x, lhs.y << rhs.y); }
__device__ oc_bool2 operator<<(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x << rhs, lhs.y << rhs); }
__device__ oc_bool2 operator<<(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs << rhs.x, lhs << rhs.y); }
__device__ oc_bool2 operator>>(oc_bool2 lhs, oc_bool2 rhs) { return oc_bool2(lhs.x >> rhs.x, lhs.y >> rhs.y); }
__device__ oc_bool2 operator>>(oc_bool2 lhs, oc_bool rhs) { return oc_bool2(lhs.x >> rhs, lhs.y >> rhs); }
__device__ oc_bool2 operator>>(oc_bool lhs, oc_bool2 rhs) { return oc_bool2(lhs >> rhs.x, lhs >> rhs.y); }
__device__ oc_bool3 operator==(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z); }
__device__ oc_bool3 operator==(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x == rhs, lhs.y == rhs, lhs.z == rhs); }
__device__ oc_bool3 operator==(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs == rhs.x, lhs == rhs.y, lhs == rhs.z); }
__device__ oc_bool3 operator!=(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z); }
__device__ oc_bool3 operator!=(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x != rhs, lhs.y != rhs, lhs.z != rhs); }
__device__ oc_bool3 operator!=(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs != rhs.x, lhs != rhs.y, lhs != rhs.z); }
__device__ oc_bool3 operator>(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z); }
__device__ oc_bool3 operator>(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x > rhs, lhs.y > rhs, lhs.z > rhs); }
__device__ oc_bool3 operator>(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs > rhs.x, lhs > rhs.y, lhs > rhs.z); }
__device__ oc_bool3 operator<(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z); }
__device__ oc_bool3 operator<(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x < rhs, lhs.y < rhs, lhs.z < rhs); }
__device__ oc_bool3 operator<(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs < rhs.x, lhs < rhs.y, lhs < rhs.z); }
__device__ oc_bool3 operator>=(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z); }
__device__ oc_bool3 operator>=(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs); }
__device__ oc_bool3 operator>=(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z); }
__device__ oc_bool3 operator<=(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z); }
__device__ oc_bool3 operator<=(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs); }
__device__ oc_bool3 operator<=(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z); }
__device__ oc_bool3 operator&&(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x && rhs.x, lhs.y && rhs.y, lhs.z && rhs.z); }
__device__ oc_bool3 operator&&(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x && rhs, lhs.y && rhs, lhs.z && rhs); }
__device__ oc_bool3 operator&&(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs && rhs.x, lhs && rhs.y, lhs && rhs.z); }
__device__ oc_bool3 operator||(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x || rhs.x, lhs.y || rhs.y, lhs.z || rhs.z); }
__device__ oc_bool3 operator||(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x || rhs, lhs.y || rhs, lhs.z || rhs); }
__device__ oc_bool3 operator||(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs || rhs.x, lhs || rhs.y, lhs || rhs.z); }
__device__ oc_bool3 operator&(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x & rhs.x, lhs.y & rhs.y, lhs.z & rhs.z); }
__device__ oc_bool3 operator&(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x & rhs, lhs.y & rhs, lhs.z & rhs); }
__device__ oc_bool3 operator&(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs & rhs.x, lhs & rhs.y, lhs & rhs.z); }
__device__ oc_bool3 operator|(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x | rhs.x, lhs.y | rhs.y, lhs.z | rhs.z); }
__device__ oc_bool3 operator|(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x | rhs, lhs.y | rhs, lhs.z | rhs); }
__device__ oc_bool3 operator|(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs | rhs.x, lhs | rhs.y, lhs | rhs.z); }
__device__ oc_bool3 operator^(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x ^ rhs.x, lhs.y ^ rhs.y, lhs.z ^ rhs.z); }
__device__ oc_bool3 operator^(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x ^ rhs, lhs.y ^ rhs, lhs.z ^ rhs); }
__device__ oc_bool3 operator^(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs ^ rhs.x, lhs ^ rhs.y, lhs ^ rhs.z); }
__device__ oc_bool3 operator<<(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x << rhs.x, lhs.y << rhs.y, lhs.z << rhs.z); }
__device__ oc_bool3 operator<<(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x << rhs, lhs.y << rhs, lhs.z << rhs); }
__device__ oc_bool3 operator<<(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs << rhs.x, lhs << rhs.y, lhs << rhs.z); }
__device__ oc_bool3 operator>>(oc_bool3 lhs, oc_bool3 rhs) { return oc_bool3(lhs.x >> rhs.x, lhs.y >> rhs.y, lhs.z >> rhs.z); }
__device__ oc_bool3 operator>>(oc_bool3 lhs, oc_bool rhs) { return oc_bool3(lhs.x >> rhs, lhs.y >> rhs, lhs.z >> rhs); }
__device__ oc_bool3 operator>>(oc_bool lhs, oc_bool3 rhs) { return oc_bool3(lhs >> rhs.x, lhs >> rhs.y, lhs >> rhs.z); }
__device__ oc_bool4 operator==(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z, lhs.w == rhs.w); }
__device__ oc_bool4 operator==(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x == rhs, lhs.y == rhs, lhs.z == rhs, lhs.w == rhs); }
__device__ oc_bool4 operator==(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs == rhs.x, lhs == rhs.y, lhs == rhs.z, lhs == rhs.w); }
__device__ oc_bool4 operator!=(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z, lhs.w != rhs.w); }
__device__ oc_bool4 operator!=(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x != rhs, lhs.y != rhs, lhs.z != rhs, lhs.w != rhs); }
__device__ oc_bool4 operator!=(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs != rhs.x, lhs != rhs.y, lhs != rhs.z, lhs != rhs.w); }
__device__ oc_bool4 operator>(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z, lhs.w > rhs.w); }
__device__ oc_bool4 operator>(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x > rhs, lhs.y > rhs, lhs.z > rhs, lhs.w > rhs); }
__device__ oc_bool4 operator>(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs > rhs.x, lhs > rhs.y, lhs > rhs.z, lhs > rhs.w); }
__device__ oc_bool4 operator<(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z, lhs.w < rhs.w); }
__device__ oc_bool4 operator<(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x < rhs, lhs.y < rhs, lhs.z < rhs, lhs.w < rhs); }
__device__ oc_bool4 operator<(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs < rhs.x, lhs < rhs.y, lhs < rhs.z, lhs < rhs.w); }
__device__ oc_bool4 operator>=(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z, lhs.w >= rhs.w); }
__device__ oc_bool4 operator>=(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs, lhs.w >= rhs); }
__device__ oc_bool4 operator>=(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z, lhs >= rhs.w); }
__device__ oc_bool4 operator<=(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z, lhs.w <= rhs.w); }
__device__ oc_bool4 operator<=(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs, lhs.w <= rhs); }
__device__ oc_bool4 operator<=(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z, lhs <= rhs.w); }
__device__ oc_bool4 operator&&(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x && rhs.x, lhs.y && rhs.y, lhs.z && rhs.z, lhs.w && rhs.w); }
__device__ oc_bool4 operator&&(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x && rhs, lhs.y && rhs, lhs.z && rhs, lhs.w && rhs); }
__device__ oc_bool4 operator&&(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs && rhs.x, lhs && rhs.y, lhs && rhs.z, lhs && rhs.w); }
__device__ oc_bool4 operator||(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x || rhs.x, lhs.y || rhs.y, lhs.z || rhs.z, lhs.w || rhs.w); }
__device__ oc_bool4 operator||(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x || rhs, lhs.y || rhs, lhs.z || rhs, lhs.w || rhs); }
__device__ oc_bool4 operator||(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs || rhs.x, lhs || rhs.y, lhs || rhs.z, lhs || rhs.w); }
__device__ oc_bool4 operator&(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x & rhs.x, lhs.y & rhs.y, lhs.z & rhs.z, lhs.w & rhs.w); }
__device__ oc_bool4 operator&(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x & rhs, lhs.y & rhs, lhs.z & rhs, lhs.w & rhs); }
__device__ oc_bool4 operator&(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs & rhs.x, lhs & rhs.y, lhs & rhs.z, lhs & rhs.w); }
__device__ oc_bool4 operator|(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x | rhs.x, lhs.y | rhs.y, lhs.z | rhs.z, lhs.w | rhs.w); }
__device__ oc_bool4 operator|(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x | rhs, lhs.y | rhs, lhs.z | rhs, lhs.w | rhs); }
__device__ oc_bool4 operator|(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs | rhs.x, lhs | rhs.y, lhs | rhs.z, lhs | rhs.w); }
__device__ oc_bool4 operator^(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x ^ rhs.x, lhs.y ^ rhs.y, lhs.z ^ rhs.z, lhs.w ^ rhs.w); }
__device__ oc_bool4 operator^(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x ^ rhs, lhs.y ^ rhs, lhs.z ^ rhs, lhs.w ^ rhs); }
__device__ oc_bool4 operator^(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs ^ rhs.x, lhs ^ rhs.y, lhs ^ rhs.z, lhs ^ rhs.w); }
__device__ oc_bool4 operator<<(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x << rhs.x, lhs.y << rhs.y, lhs.z << rhs.z, lhs.w << rhs.w); }
__device__ oc_bool4 operator<<(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x << rhs, lhs.y << rhs, lhs.z << rhs, lhs.w << rhs); }
__device__ oc_bool4 operator<<(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs << rhs.x, lhs << rhs.y, lhs << rhs.z, lhs << rhs.w); }
__device__ oc_bool4 operator>>(oc_bool4 lhs, oc_bool4 rhs) { return oc_bool4(lhs.x >> rhs.x, lhs.y >> rhs.y, lhs.z >> rhs.z, lhs.w >> rhs.w); }
__device__ oc_bool4 operator>>(oc_bool4 lhs, oc_bool rhs) { return oc_bool4(lhs.x >> rhs, lhs.y >> rhs, lhs.z >> rhs, lhs.w >> rhs); }
__device__ oc_bool4 operator>>(oc_bool lhs, oc_bool4 rhs) { return oc_bool4(lhs >> rhs.x, lhs >> rhs.y, lhs >> rhs.z, lhs >> rhs.w); }

__device__ oc_bool oc_any(oc_bool2 vec) { return vec.x || vec.y; }
__device__ oc_bool oc_any(oc_bool3 vec) { return vec.x || vec.y || vec.z; }
__device__ oc_bool oc_any(oc_bool4 vec) { return vec.x || vec.y || vec.z || vec.w; }
__device__ oc_bool oc_all(oc_bool2 vec) { return vec.x && vec.y; }
__device__ oc_bool oc_all(oc_bool3 vec) { return vec.x && vec.y && vec.z; }
__device__ oc_bool oc_all(oc_bool4 vec) { return vec.x && vec.y && vec.z && vec.w; }
__device__ oc_bool oc_none(oc_bool2 vec) { return !oc_any(vec); }
__device__ oc_bool oc_none(oc_bool3 vec) { return !oc_any(vec); }
__device__ oc_bool oc_none(oc_bool4 vec) { return !oc_any(vec); }

struct oc_float2x2 {
	oc_float2 cols[2];
	__device__ explicit constexpr oc_float2x2(oc_float s = 1.f)
		:cols{oc_float2(s, 0.f), oc_float2(0.f, s)} {}
	__device__ oc_float2x2(oc_float2 c0, oc_float2 c1)
		:cols{c0, c1} {}
	__device__ auto &operator[](oc_uint i) noexcept { return cols[i]; }
	__device__ auto operator[](oc_uint i) const noexcept { return cols[i]; }
};
 
struct oc_float3x3 {
	oc_float3 cols[3];
	__device__ explicit constexpr oc_float3x3(oc_float s = 1.f)
		:cols{oc_float3(s, 0.f, 0.f), oc_float3(0.f, s, 0.f), oc_float3(0.f, 0.f, s)} {}
	__device__ oc_float3x3(oc_float3 c0, oc_float3 c1, oc_float3 c2)
		:cols{c0, c1, c2} {}
	__device__ auto &operator[](oc_uint i) noexcept { return cols[i]; }
	__device__ auto operator[](oc_uint i) const noexcept { return cols[i]; }
};
 
struct oc_float4x4 {
	oc_float4 cols[4];
	__device__ explicit constexpr oc_float4x4(oc_float s = 1.f)
		:cols{oc_float4(s, 0.f, 0.f, 0.f), oc_float4(0.f, s, 0.f, 0.f), oc_float4(0.f, 0.f, s, 0.f), oc_float4(0.f, 0.f, 0.f, s)} {}
	__device__ oc_float4x4(oc_float4 c0, oc_float4 c1, oc_float4 c2, oc_float4 c3)
		:cols{c0, c1, c2, c3} {}
	__device__ auto &operator[](oc_uint i) noexcept { return cols[i]; }
	__device__ auto operator[](oc_uint i) const noexcept { return cols[i]; }
};
 
__device__ auto operator+(oc_float2x2 m, oc_int s) {
	return oc_float2x2(m[0] + s, m[1] + s);
}
__device__ auto operator+(oc_int s, oc_float2x2 m) {
	return oc_float2x2(s + m[0], s + m[1]);
}
__device__ auto operator-(oc_float2x2 m, oc_int s) {
	return oc_float2x2(m[0] - s, m[1] - s);
}
__device__ auto operator-(oc_int s, oc_float2x2 m) {
	return oc_float2x2(s - m[0], s - m[1]);
}
__device__ auto operator*(oc_float2x2 m, oc_int s) {
	return oc_float2x2(m[0] * s, m[1] * s);
}
__device__ auto operator*(oc_int s, oc_float2x2 m) {
	return oc_float2x2(s * m[0], s * m[1]);
}
__device__ auto operator/(oc_float2x2 m, oc_int s) {
	return oc_float2x2(m[0] / s, m[1] / s);
}
__device__ auto operator/(oc_int s, oc_float2x2 m) {
	return oc_float2x2(s / m[0], s / m[1]);
}
__device__ auto operator+(oc_float2x2 m, oc_uint s) {
	return oc_float2x2(m[0] + s, m[1] + s);
}
__device__ auto operator+(oc_uint s, oc_float2x2 m) {
	return oc_float2x2(s + m[0], s + m[1]);
}
__device__ auto operator-(oc_float2x2 m, oc_uint s) {
	return oc_float2x2(m[0] - s, m[1] - s);
}
__device__ auto operator-(oc_uint s, oc_float2x2 m) {
	return oc_float2x2(s - m[0], s - m[1]);
}
__device__ auto operator*(oc_float2x2 m, oc_uint s) {
	return oc_float2x2(m[0] * s, m[1] * s);
}
__device__ auto operator*(oc_uint s, oc_float2x2 m) {
	return oc_float2x2(s * m[0], s * m[1]);
}
__device__ auto operator/(oc_float2x2 m, oc_uint s) {
	return oc_float2x2(m[0] / s, m[1] / s);
}
__device__ auto operator/(oc_uint s, oc_float2x2 m) {
	return oc_float2x2(s / m[0], s / m[1]);
}
__device__ auto operator+(oc_float2x2 m, oc_float s) {
	return oc_float2x2(m[0] + s, m[1] + s);
}
__device__ auto operator+(oc_float s, oc_float2x2 m) {
	return oc_float2x2(s + m[0], s + m[1]);
}
__device__ auto operator-(oc_float2x2 m, oc_float s) {
	return oc_float2x2(m[0] - s, m[1] - s);
}
__device__ auto operator-(oc_float s, oc_float2x2 m) {
	return oc_float2x2(s - m[0], s - m[1]);
}
__device__ auto operator*(oc_float2x2 m, oc_float s) {
	return oc_float2x2(m[0] * s, m[1] * s);
}
__device__ auto operator*(oc_float s, oc_float2x2 m) {
	return oc_float2x2(s * m[0], s * m[1]);
}
__device__ auto operator/(oc_float2x2 m, oc_float s) {
	return oc_float2x2(m[0] / s, m[1] / s);
}
__device__ auto operator/(oc_float s, oc_float2x2 m) {
	return oc_float2x2(s / m[0], s / m[1]);
}
__device__ auto operator*(oc_float2x2 m, oc_float2 v) {
	return v[0] * m[0] + v[1] * m[1];
}
__device__ auto operator+(oc_float2x2 lhs, oc_float2x2 rhs) {
	return oc_float2x2(lhs[0] + rhs[0], lhs[1] + rhs[1]);
}
__device__ auto operator-(oc_float2x2 lhs, oc_float2x2 rhs) {
	return oc_float2x2(lhs[0] - rhs[0], lhs[1] - rhs[1]);
}
__device__ auto operator*(oc_float2x2 lhs, oc_float2x2 rhs) {
	return oc_float2x2(lhs * rhs[0], lhs * rhs[1]);
}
__device__ auto operator+(oc_float3x3 m, oc_int s) {
	return oc_float3x3(m[0] + s, m[1] + s, m[2] + s);
}
__device__ auto operator+(oc_int s, oc_float3x3 m) {
	return oc_float3x3(s + m[0], s + m[1], s + m[2]);
}
__device__ auto operator-(oc_float3x3 m, oc_int s) {
	return oc_float3x3(m[0] - s, m[1] - s, m[2] - s);
}
__device__ auto operator-(oc_int s, oc_float3x3 m) {
	return oc_float3x3(s - m[0], s - m[1], s - m[2]);
}
__device__ auto operator*(oc_float3x3 m, oc_int s) {
	return oc_float3x3(m[0] * s, m[1] * s, m[2] * s);
}
__device__ auto operator*(oc_int s, oc_float3x3 m) {
	return oc_float3x3(s * m[0], s * m[1], s * m[2]);
}
__device__ auto operator/(oc_float3x3 m, oc_int s) {
	return oc_float3x3(m[0] / s, m[1] / s, m[2] / s);
}
__device__ auto operator/(oc_int s, oc_float3x3 m) {
	return oc_float3x3(s / m[0], s / m[1], s / m[2]);
}
__device__ auto operator+(oc_float3x3 m, oc_uint s) {
	return oc_float3x3(m[0] + s, m[1] + s, m[2] + s);
}
__device__ auto operator+(oc_uint s, oc_float3x3 m) {
	return oc_float3x3(s + m[0], s + m[1], s + m[2]);
}
__device__ auto operator-(oc_float3x3 m, oc_uint s) {
	return oc_float3x3(m[0] - s, m[1] - s, m[2] - s);
}
__device__ auto operator-(oc_uint s, oc_float3x3 m) {
	return oc_float3x3(s - m[0], s - m[1], s - m[2]);
}
__device__ auto operator*(oc_float3x3 m, oc_uint s) {
	return oc_float3x3(m[0] * s, m[1] * s, m[2] * s);
}
__device__ auto operator*(oc_uint s, oc_float3x3 m) {
	return oc_float3x3(s * m[0], s * m[1], s * m[2]);
}
__device__ auto operator/(oc_float3x3 m, oc_uint s) {
	return oc_float3x3(m[0] / s, m[1] / s, m[2] / s);
}
__device__ auto operator/(oc_uint s, oc_float3x3 m) {
	return oc_float3x3(s / m[0], s / m[1], s / m[2]);
}
__device__ auto operator+(oc_float3x3 m, oc_float s) {
	return oc_float3x3(m[0] + s, m[1] + s, m[2] + s);
}
__device__ auto operator+(oc_float s, oc_float3x3 m) {
	return oc_float3x3(s + m[0], s + m[1], s + m[2]);
}
__device__ auto operator-(oc_float3x3 m, oc_float s) {
	return oc_float3x3(m[0] - s, m[1] - s, m[2] - s);
}
__device__ auto operator-(oc_float s, oc_float3x3 m) {
	return oc_float3x3(s - m[0], s - m[1], s - m[2]);
}
__device__ auto operator*(oc_float3x3 m, oc_float s) {
	return oc_float3x3(m[0] * s, m[1] * s, m[2] * s);
}
__device__ auto operator*(oc_float s, oc_float3x3 m) {
	return oc_float3x3(s * m[0], s * m[1], s * m[2]);
}
__device__ auto operator/(oc_float3x3 m, oc_float s) {
	return oc_float3x3(m[0] / s, m[1] / s, m[2] / s);
}
__device__ auto operator/(oc_float s, oc_float3x3 m) {
	return oc_float3x3(s / m[0], s / m[1], s / m[2]);
}
__device__ auto operator*(oc_float3x3 m, oc_float3 v) {
	return v[0] * m[0] + v[1] * m[1] + v[2] * m[2];
}
__device__ auto operator+(oc_float3x3 lhs, oc_float3x3 rhs) {
	return oc_float3x3(lhs[0] + rhs[0], lhs[1] + rhs[1], lhs[2] + rhs[2]);
}
__device__ auto operator-(oc_float3x3 lhs, oc_float3x3 rhs) {
	return oc_float3x3(lhs[0] - rhs[0], lhs[1] - rhs[1], lhs[2] - rhs[2]);
}
__device__ auto operator*(oc_float3x3 lhs, oc_float3x3 rhs) {
	return oc_float3x3(lhs * rhs[0], lhs * rhs[1], lhs * rhs[2]);
}
__device__ auto operator+(oc_float4x4 m, oc_int s) {
	return oc_float4x4(m[0] + s, m[1] + s, m[2] + s, m[3] + s);
}
__device__ auto operator+(oc_int s, oc_float4x4 m) {
	return oc_float4x4(s + m[0], s + m[1], s + m[2], s + m[3]);
}
__device__ auto operator-(oc_float4x4 m, oc_int s) {
	return oc_float4x4(m[0] - s, m[1] - s, m[2] - s, m[3] - s);
}
__device__ auto operator-(oc_int s, oc_float4x4 m) {
	return oc_float4x4(s - m[0], s - m[1], s - m[2], s - m[3]);
}
__device__ auto operator*(oc_float4x4 m, oc_int s) {
	return oc_float4x4(m[0] * s, m[1] * s, m[2] * s, m[3] * s);
}
__device__ auto operator*(oc_int s, oc_float4x4 m) {
	return oc_float4x4(s * m[0], s * m[1], s * m[2], s * m[3]);
}
__device__ auto operator/(oc_float4x4 m, oc_int s) {
	return oc_float4x4(m[0] / s, m[1] / s, m[2] / s, m[3] / s);
}
__device__ auto operator/(oc_int s, oc_float4x4 m) {
	return oc_float4x4(s / m[0], s / m[1], s / m[2], s / m[3]);
}
__device__ auto operator+(oc_float4x4 m, oc_uint s) {
	return oc_float4x4(m[0] + s, m[1] + s, m[2] + s, m[3] + s);
}
__device__ auto operator+(oc_uint s, oc_float4x4 m) {
	return oc_float4x4(s + m[0], s + m[1], s + m[2], s + m[3]);
}
__device__ auto operator-(oc_float4x4 m, oc_uint s) {
	return oc_float4x4(m[0] - s, m[1] - s, m[2] - s, m[3] - s);
}
__device__ auto operator-(oc_uint s, oc_float4x4 m) {
	return oc_float4x4(s - m[0], s - m[1], s - m[2], s - m[3]);
}
__device__ auto operator*(oc_float4x4 m, oc_uint s) {
	return oc_float4x4(m[0] * s, m[1] * s, m[2] * s, m[3] * s);
}
__device__ auto operator*(oc_uint s, oc_float4x4 m) {
	return oc_float4x4(s * m[0], s * m[1], s * m[2], s * m[3]);
}
__device__ auto operator/(oc_float4x4 m, oc_uint s) {
	return oc_float4x4(m[0] / s, m[1] / s, m[2] / s, m[3] / s);
}
__device__ auto operator/(oc_uint s, oc_float4x4 m) {
	return oc_float4x4(s / m[0], s / m[1], s / m[2], s / m[3]);
}
__device__ auto operator+(oc_float4x4 m, oc_float s) {
	return oc_float4x4(m[0] + s, m[1] + s, m[2] + s, m[3] + s);
}
__device__ auto operator+(oc_float s, oc_float4x4 m) {
	return oc_float4x4(s + m[0], s + m[1], s + m[2], s + m[3]);
}
__device__ auto operator-(oc_float4x4 m, oc_float s) {
	return oc_float4x4(m[0] - s, m[1] - s, m[2] - s, m[3] - s);
}
__device__ auto operator-(oc_float s, oc_float4x4 m) {
	return oc_float4x4(s - m[0], s - m[1], s - m[2], s - m[3]);
}
__device__ auto operator*(oc_float4x4 m, oc_float s) {
	return oc_float4x4(m[0] * s, m[1] * s, m[2] * s, m[3] * s);
}
__device__ auto operator*(oc_float s, oc_float4x4 m) {
	return oc_float4x4(s * m[0], s * m[1], s * m[2], s * m[3]);
}
__device__ auto operator/(oc_float4x4 m, oc_float s) {
	return oc_float4x4(m[0] / s, m[1] / s, m[2] / s, m[3] / s);
}
__device__ auto operator/(oc_float s, oc_float4x4 m) {
	return oc_float4x4(s / m[0], s / m[1], s / m[2], s / m[3]);
}
__device__ auto operator*(oc_float4x4 m, oc_float4 v) {
	return v[0] * m[0] + v[1] * m[1] + v[2] * m[2] + v[3] * m[3];
}
__device__ auto operator+(oc_float4x4 lhs, oc_float4x4 rhs) {
	return oc_float4x4(lhs[0] + rhs[0], lhs[1] + rhs[1], lhs[2] + rhs[2], lhs[3] + rhs[3]);
}
__device__ auto operator-(oc_float4x4 lhs, oc_float4x4 rhs) {
	return oc_float4x4(lhs[0] - rhs[0], lhs[1] - rhs[1], lhs[2] - rhs[2], lhs[3] - rhs[3]);
}
__device__ auto operator*(oc_float4x4 lhs, oc_float4x4 rhs) {
	return oc_float4x4(lhs * rhs[0], lhs * rhs[1], lhs * rhs[2], lhs * rhs[3]);
}

__device__ oc_int oc_select(oc_bool pred, oc_int t, oc_int f) { return pred ? t : f; }
__device__ oc_int2 oc_select(oc_bool2 pred, oc_int2 t, oc_int2 f) {
	return oc_int2(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y));
}
__device__ oc_int3 oc_select(oc_bool3 pred, oc_int3 t, oc_int3 f) {
	return oc_int3(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y), oc_select(pred.z, t.z, f.z));
}
__device__ oc_int4 oc_select(oc_bool4 pred, oc_int4 t, oc_int4 f) {
	return oc_int4(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y), oc_select(pred.z, t.z, f.z), oc_select(pred.w, t.w, f.w));
}

__device__ oc_uint oc_select(oc_bool pred, oc_uint t, oc_uint f) { return pred ? t : f; }
__device__ oc_uint2 oc_select(oc_bool2 pred, oc_uint2 t, oc_uint2 f) {
	return oc_uint2(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y));
}
__device__ oc_uint3 oc_select(oc_bool3 pred, oc_uint3 t, oc_uint3 f) {
	return oc_uint3(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y), oc_select(pred.z, t.z, f.z));
}
__device__ oc_uint4 oc_select(oc_bool4 pred, oc_uint4 t, oc_uint4 f) {
	return oc_uint4(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y), oc_select(pred.z, t.z, f.z), oc_select(pred.w, t.w, f.w));
}

__device__ oc_float oc_select(oc_bool pred, oc_float t, oc_float f) { return pred ? t : f; }
__device__ oc_float2 oc_select(oc_bool2 pred, oc_float2 t, oc_float2 f) {
	return oc_float2(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y));
}
__device__ oc_float3 oc_select(oc_bool3 pred, oc_float3 t, oc_float3 f) {
	return oc_float3(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y), oc_select(pred.z, t.z, f.z));
}
__device__ oc_float4 oc_select(oc_bool4 pred, oc_float4 t, oc_float4 f) {
	return oc_float4(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y), oc_select(pred.z, t.z, f.z), oc_select(pred.w, t.w, f.w));
}

__device__ oc_bool oc_select(oc_bool pred, oc_bool t, oc_bool f) { return pred ? t : f; }
__device__ oc_bool2 oc_select(oc_bool2 pred, oc_bool2 t, oc_bool2 f) {
	return oc_bool2(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y));
}
__device__ oc_bool3 oc_select(oc_bool3 pred, oc_bool3 t, oc_bool3 f) {
	return oc_bool3(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y), oc_select(pred.z, t.z, f.z));
}
__device__ oc_bool4 oc_select(oc_bool4 pred, oc_bool4 t, oc_bool4 f) {
	return oc_bool4(oc_select(pred.x, t.x, f.x), oc_select(pred.y, t.y, f.y), oc_select(pred.z, t.z, f.z), oc_select(pred.w, t.w, f.w));
}

__device__ oc_int oc_rcp(oc_int v) { return 1.f / v; }
__device__ oc_int2 oc_rcp(oc_int2 v) { return oc_int2(oc_rcp(v.x), oc_rcp(v.y)); }
__device__ oc_int3 oc_rcp(oc_int3 v) { return oc_int3(oc_rcp(v.x), oc_rcp(v.y), oc_rcp(v.z)); }
__device__ oc_int4 oc_rcp(oc_int4 v) { return oc_int4(oc_rcp(v.x), oc_rcp(v.y), oc_rcp(v.z), oc_rcp(v.w)); }
__device__ oc_uint oc_rcp(oc_uint v) { return 1.f / v; }
__device__ oc_uint2 oc_rcp(oc_uint2 v) { return oc_uint2(oc_rcp(v.x), oc_rcp(v.y)); }
__device__ oc_uint3 oc_rcp(oc_uint3 v) { return oc_uint3(oc_rcp(v.x), oc_rcp(v.y), oc_rcp(v.z)); }
__device__ oc_uint4 oc_rcp(oc_uint4 v) { return oc_uint4(oc_rcp(v.x), oc_rcp(v.y), oc_rcp(v.z), oc_rcp(v.w)); }
__device__ oc_float oc_rcp(oc_float v) { return 1.f / v; }
__device__ oc_float2 oc_rcp(oc_float2 v) { return oc_float2(oc_rcp(v.x), oc_rcp(v.y)); }
__device__ oc_float3 oc_rcp(oc_float3 v) { return oc_float3(oc_rcp(v.x), oc_rcp(v.y), oc_rcp(v.z)); }
__device__ oc_float4 oc_rcp(oc_float4 v) { return oc_float4(oc_rcp(v.x), oc_rcp(v.y), oc_rcp(v.z), oc_rcp(v.w)); }
__device__ oc_bool oc_rcp(oc_bool v) { return 1.f / v; }
__device__ oc_bool2 oc_rcp(oc_bool2 v) { return oc_bool2(oc_rcp(v.x), oc_rcp(v.y)); }
__device__ oc_bool3 oc_rcp(oc_bool3 v) { return oc_bool3(oc_rcp(v.x), oc_rcp(v.y), oc_rcp(v.z)); }
__device__ oc_bool4 oc_rcp(oc_bool4 v) { return oc_bool4(oc_rcp(v.x), oc_rcp(v.y), oc_rcp(v.z), oc_rcp(v.w)); }

__device__ oc_int oc_abs(oc_int v) { return abs(v); }
__device__ oc_int2 oc_abs(oc_int2 v) { return oc_int2(oc_abs(v.x), oc_abs(v.y)); }
__device__ oc_int3 oc_abs(oc_int3 v) { return oc_int3(oc_abs(v.x), oc_abs(v.y), oc_abs(v.z)); }
__device__ oc_int4 oc_abs(oc_int4 v) { return oc_int4(oc_abs(v.x), oc_abs(v.y), oc_abs(v.z), oc_abs(v.w)); }
__device__ oc_float oc_abs(oc_float v) { return abs(v); }
__device__ oc_float2 oc_abs(oc_float2 v) { return oc_float2(oc_abs(v.x), oc_abs(v.y)); }
__device__ oc_float3 oc_abs(oc_float3 v) { return oc_float3(oc_abs(v.x), oc_abs(v.y), oc_abs(v.z)); }
__device__ oc_float4 oc_abs(oc_float4 v) { return oc_float4(oc_abs(v.x), oc_abs(v.y), oc_abs(v.z), oc_abs(v.w)); }

__device__ oc_float oc_cos(oc_float v) { return cos(v); }
__device__ oc_float2 oc_cos(oc_float2 v) { return oc_float2(oc_cos(v.x), oc_cos(v.y)); }
__device__ oc_float3 oc_cos(oc_float3 v) { return oc_float3(oc_cos(v.x), oc_cos(v.y), oc_cos(v.z)); }
__device__ oc_float4 oc_cos(oc_float4 v) { return oc_float4(oc_cos(v.x), oc_cos(v.y), oc_cos(v.z), oc_cos(v.w)); }

__device__ oc_float oc_sin(oc_float v) { return sin(v); }
__device__ oc_float2 oc_sin(oc_float2 v) { return oc_float2(oc_sin(v.x), oc_sin(v.y)); }
__device__ oc_float3 oc_sin(oc_float3 v) { return oc_float3(oc_sin(v.x), oc_sin(v.y), oc_sin(v.z)); }
__device__ oc_float4 oc_sin(oc_float4 v) { return oc_float4(oc_sin(v.x), oc_sin(v.y), oc_sin(v.z), oc_sin(v.w)); }

__device__ oc_int oc_sqr(oc_int v) { return v * v; }
__device__ oc_int2 oc_sqr(oc_int2 v) { return oc_int2(oc_sqr(v.x), oc_sqr(v.y)); }
__device__ oc_int3 oc_sqr(oc_int3 v) { return oc_int3(oc_sqr(v.x), oc_sqr(v.y), oc_sqr(v.z)); }
__device__ oc_int4 oc_sqr(oc_int4 v) { return oc_int4(oc_sqr(v.x), oc_sqr(v.y), oc_sqr(v.z), oc_sqr(v.w)); }
__device__ oc_uint oc_sqr(oc_uint v) { return v * v; }
__device__ oc_uint2 oc_sqr(oc_uint2 v) { return oc_uint2(oc_sqr(v.x), oc_sqr(v.y)); }
__device__ oc_uint3 oc_sqr(oc_uint3 v) { return oc_uint3(oc_sqr(v.x), oc_sqr(v.y), oc_sqr(v.z)); }
__device__ oc_uint4 oc_sqr(oc_uint4 v) { return oc_uint4(oc_sqr(v.x), oc_sqr(v.y), oc_sqr(v.z), oc_sqr(v.w)); }
__device__ oc_float oc_sqr(oc_float v) { return v * v; }
__device__ oc_float2 oc_sqr(oc_float2 v) { return oc_float2(oc_sqr(v.x), oc_sqr(v.y)); }
__device__ oc_float3 oc_sqr(oc_float3 v) { return oc_float3(oc_sqr(v.x), oc_sqr(v.y), oc_sqr(v.z)); }
__device__ oc_float4 oc_sqr(oc_float4 v) { return oc_float4(oc_sqr(v.x), oc_sqr(v.y), oc_sqr(v.z), oc_sqr(v.w)); }

__device__ oc_float oc_sqrt(oc_float v) { return sqrt(v); }
__device__ oc_float2 oc_sqrt(oc_float2 v) { return oc_float2(oc_sqrt(v.x), oc_sqrt(v.y)); }
__device__ oc_float3 oc_sqrt(oc_float3 v) { return oc_float3(oc_sqrt(v.x), oc_sqrt(v.y), oc_sqrt(v.z)); }
__device__ oc_float4 oc_sqrt(oc_float4 v) { return oc_float4(oc_sqrt(v.x), oc_sqrt(v.y), oc_sqrt(v.z), oc_sqrt(v.w)); }

__device__ oc_float oc_degrees(oc_float v) { return v * (180.f / 3.1415926535f); }
__device__ oc_float2 oc_degrees(oc_float2 v) { return oc_float2(oc_degrees(v.x), oc_degrees(v.y)); }
__device__ oc_float3 oc_degrees(oc_float3 v) { return oc_float3(oc_degrees(v.x), oc_degrees(v.y), oc_degrees(v.z)); }
__device__ oc_float4 oc_degrees(oc_float4 v) { return oc_float4(oc_degrees(v.x), oc_degrees(v.y), oc_degrees(v.z), oc_degrees(v.w)); }

__device__ oc_float oc_radians(oc_float v) { return v * (3.1415926535f / 180.f); }
__device__ oc_float2 oc_radians(oc_float2 v) { return oc_float2(oc_radians(v.x), oc_radians(v.y)); }
__device__ oc_float3 oc_radians(oc_float3 v) { return oc_float3(oc_radians(v.x), oc_radians(v.y), oc_radians(v.z)); }
__device__ oc_float4 oc_radians(oc_float4 v) { return oc_float4(oc_radians(v.x), oc_radians(v.y), oc_radians(v.z), oc_radians(v.w)); }

__device__ oc_float oc_saturate(oc_float v) { return min(1.f, max(0.f, v)); }
__device__ oc_float2 oc_saturate(oc_float2 v) { return oc_float2(oc_saturate(v.x), oc_saturate(v.y)); }
__device__ oc_float3 oc_saturate(oc_float3 v) { return oc_float3(oc_saturate(v.x), oc_saturate(v.y), oc_saturate(v.z)); }
__device__ oc_float4 oc_saturate(oc_float4 v) { return oc_float4(oc_saturate(v.x), oc_saturate(v.y), oc_saturate(v.z), oc_saturate(v.w)); }

 