swizzle_type<0, 0>& xx() { return reinterpret_cast<swizzle_type<0, 0>&>(arr); };
swizzle_type<0, 1>& xy() { return reinterpret_cast<swizzle_type<0, 1>&>(arr); };
swizzle_type<1, 0>& yx() { return reinterpret_cast<swizzle_type<1, 0>&>(arr); };
swizzle_type<1, 1>& yy() { return reinterpret_cast<swizzle_type<1, 1>&>(arr); };

swizzle_type<0, 0, 0>& xxx() { return reinterpret_cast<swizzle_type<0, 0, 0>&>(arr); };
swizzle_type<0, 0, 1>& xxy() { return reinterpret_cast<swizzle_type<0, 0, 1>&>(arr); };
swizzle_type<0, 1, 0>& xyx() { return reinterpret_cast<swizzle_type<0, 1, 0>&>(arr); };
swizzle_type<0, 1, 1>& xyy() { return reinterpret_cast<swizzle_type<0, 1, 1>&>(arr); };
swizzle_type<1, 0, 0>& yxx() { return reinterpret_cast<swizzle_type<1, 0, 0>&>(arr); };
swizzle_type<1, 0, 1>& yxy() { return reinterpret_cast<swizzle_type<1, 0, 1>&>(arr); };
swizzle_type<1, 1, 0>& yyx() { return reinterpret_cast<swizzle_type<1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1>& yyy() { return reinterpret_cast<swizzle_type<1, 1, 1>&>(arr); };

swizzle_type<0, 0, 0, 0>& xxxx() { return reinterpret_cast<swizzle_type<0, 0, 0, 0>&>(arr); };
swizzle_type<0, 0, 0, 1>& xxxy() { return reinterpret_cast<swizzle_type<0, 0, 0, 1>&>(arr); };
swizzle_type<0, 0, 1, 0>& xxyx() { return reinterpret_cast<swizzle_type<0, 0, 1, 0>&>(arr); };
swizzle_type<0, 0, 1, 1>& xxyy() { return reinterpret_cast<swizzle_type<0, 0, 1, 1>&>(arr); };
swizzle_type<0, 1, 0, 0>& xyxx() { return reinterpret_cast<swizzle_type<0, 1, 0, 0>&>(arr); };
swizzle_type<0, 1, 0, 1>& xyxy() { return reinterpret_cast<swizzle_type<0, 1, 0, 1>&>(arr); };
swizzle_type<0, 1, 1, 0>& xyyx() { return reinterpret_cast<swizzle_type<0, 1, 1, 0>&>(arr); };
swizzle_type<0, 1, 1, 1>& xyyy() { return reinterpret_cast<swizzle_type<0, 1, 1, 1>&>(arr); };
swizzle_type<1, 0, 0, 0>& yxxx() { return reinterpret_cast<swizzle_type<1, 0, 0, 0>&>(arr); };
swizzle_type<1, 0, 0, 1>& yxxy() { return reinterpret_cast<swizzle_type<1, 0, 0, 1>&>(arr); };
swizzle_type<1, 0, 1, 0>& yxyx() { return reinterpret_cast<swizzle_type<1, 0, 1, 0>&>(arr); };
swizzle_type<1, 0, 1, 1>& yxyy() { return reinterpret_cast<swizzle_type<1, 0, 1, 1>&>(arr); };
swizzle_type<1, 1, 0, 0>& yyxx() { return reinterpret_cast<swizzle_type<1, 1, 0, 0>&>(arr); };
swizzle_type<1, 1, 0, 1>& yyxy() { return reinterpret_cast<swizzle_type<1, 1, 0, 1>&>(arr); };
swizzle_type<1, 1, 1, 0>& yyyx() { return reinterpret_cast<swizzle_type<1, 1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1, 1>& yyyy() { return reinterpret_cast<swizzle_type<1, 1, 1, 1>&>(arr); };
