swizzle_type<0, 0>& xx() noexcept { return reinterpret_cast<swizzle_type<0, 0>&>(arr); };
swizzle_type<0, 1>& xy() noexcept { return reinterpret_cast<swizzle_type<0, 1>&>(arr); };
swizzle_type<1, 0>& yx() noexcept { return reinterpret_cast<swizzle_type<1, 0>&>(arr); };
swizzle_type<1, 1>& yy() noexcept { return reinterpret_cast<swizzle_type<1, 1>&>(arr); };
auto xx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0>&>(arr).to_vec(); };
auto xy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1>&>(arr).to_vec(); };
auto yx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0>&>(arr).to_vec(); };
auto yy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1>&>(arr).to_vec(); };

swizzle_type<0, 0, 0>& xxx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0>&>(arr); };
swizzle_type<0, 0, 1>& xxy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1>&>(arr); };
swizzle_type<0, 1, 0>& xyx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0>&>(arr); };
swizzle_type<0, 1, 1>& xyy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1>&>(arr); };
swizzle_type<1, 0, 0>& yxx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0>&>(arr); };
swizzle_type<1, 0, 1>& yxy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1>&>(arr); };
swizzle_type<1, 1, 0>& yyx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1>& yyy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1>&>(arr); };
auto xxx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 0>&>(arr).to_vec(); };
auto xxy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 1>&>(arr).to_vec(); };
auto xyx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 0>&>(arr).to_vec(); };
auto xyy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 1>&>(arr).to_vec(); };
auto yxx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 0>&>(arr).to_vec(); };
auto yxy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 1>&>(arr).to_vec(); };
auto yyx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 0>&>(arr).to_vec(); };
auto yyy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 1>&>(arr).to_vec(); };

swizzle_type<0, 0, 0, 0>& xxxx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 0>&>(arr); };
swizzle_type<0, 0, 0, 1>& xxxy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 1>&>(arr); };
swizzle_type<0, 0, 1, 0>& xxyx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 0>&>(arr); };
swizzle_type<0, 0, 1, 1>& xxyy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 1>&>(arr); };
swizzle_type<0, 1, 0, 0>& xyxx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 0>&>(arr); };
swizzle_type<0, 1, 0, 1>& xyxy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 1>&>(arr); };
swizzle_type<0, 1, 1, 0>& xyyx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 0>&>(arr); };
swizzle_type<0, 1, 1, 1>& xyyy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 1>&>(arr); };
swizzle_type<1, 0, 0, 0>& yxxx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 0>&>(arr); };
swizzle_type<1, 0, 0, 1>& yxxy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 1>&>(arr); };
swizzle_type<1, 0, 1, 0>& yxyx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 0>&>(arr); };
swizzle_type<1, 0, 1, 1>& yxyy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 1>&>(arr); };
swizzle_type<1, 1, 0, 0>& yyxx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 0>&>(arr); };
swizzle_type<1, 1, 0, 1>& yyxy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 1>&>(arr); };
swizzle_type<1, 1, 1, 0>& yyyx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1, 1>& yyyy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 1>&>(arr); };
auto xxxx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 0, 0>&>(arr).to_vec(); };
auto xxxy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 0, 1>&>(arr).to_vec(); };
auto xxyx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 1, 0>&>(arr).to_vec(); };
auto xxyy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 1, 1>&>(arr).to_vec(); };
auto xyxx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 0, 0>&>(arr).to_vec(); };
auto xyxy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 0, 1>&>(arr).to_vec(); };
auto xyyx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 1, 0>&>(arr).to_vec(); };
auto xyyy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 1, 1>&>(arr).to_vec(); };
auto yxxx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 0, 0>&>(arr).to_vec(); };
auto yxxy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 0, 1>&>(arr).to_vec(); };
auto yxyx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 1, 0>&>(arr).to_vec(); };
auto yxyy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 1, 1>&>(arr).to_vec(); };
auto yyxx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 0, 0>&>(arr).to_vec(); };
auto yyxy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 0, 1>&>(arr).to_vec(); };
auto yyyx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 1, 0>&>(arr).to_vec(); };
auto yyyy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 1, 1>&>(arr).to_vec(); };
