swizzle_type<0, 0>& xx() noexcept { return reinterpret_cast<swizzle_type<0, 0>&>(arr); };
swizzle_type<0, 1>& xy() noexcept { return reinterpret_cast<swizzle_type<0, 1>&>(arr); };
swizzle_type<0, 2>& xz() noexcept { return reinterpret_cast<swizzle_type<0, 2>&>(arr); };
swizzle_type<1, 0>& yx() noexcept { return reinterpret_cast<swizzle_type<1, 0>&>(arr); };
swizzle_type<1, 1>& yy() noexcept { return reinterpret_cast<swizzle_type<1, 1>&>(arr); };
swizzle_type<1, 2>& yz() noexcept { return reinterpret_cast<swizzle_type<1, 2>&>(arr); };
swizzle_type<2, 0>& zx() noexcept { return reinterpret_cast<swizzle_type<2, 0>&>(arr); };
swizzle_type<2, 1>& zy() noexcept { return reinterpret_cast<swizzle_type<2, 1>&>(arr); };
swizzle_type<2, 2>& zz() noexcept { return reinterpret_cast<swizzle_type<2, 2>&>(arr); };
const swizzle_type<0, 0>& xx() const noexcept { return reinterpret_cast<swizzle_type<0, 0>&>(arr); };
const swizzle_type<0, 1>& xy() const noexcept { return reinterpret_cast<swizzle_type<0, 1>&>(arr); };
const swizzle_type<0, 2>& xz() const noexcept { return reinterpret_cast<swizzle_type<0, 2>&>(arr); };
const swizzle_type<1, 0>& yx() const noexcept { return reinterpret_cast<swizzle_type<1, 0>&>(arr); };
const swizzle_type<1, 1>& yy() const noexcept { return reinterpret_cast<swizzle_type<1, 1>&>(arr); };
const swizzle_type<1, 2>& yz() const noexcept { return reinterpret_cast<swizzle_type<1, 2>&>(arr); };
const swizzle_type<2, 0>& zx() const noexcept { return reinterpret_cast<swizzle_type<2, 0>&>(arr); };
const swizzle_type<2, 1>& zy() const noexcept { return reinterpret_cast<swizzle_type<2, 1>&>(arr); };
const swizzle_type<2, 2>& zz() const noexcept { return reinterpret_cast<swizzle_type<2, 2>&>(arr); };

swizzle_type<0, 0, 0>& xxx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0>&>(arr); };
swizzle_type<0, 0, 1>& xxy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1>&>(arr); };
swizzle_type<0, 0, 2>& xxz() noexcept { return reinterpret_cast<swizzle_type<0, 0, 2>&>(arr); };
swizzle_type<0, 1, 0>& xyx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0>&>(arr); };
swizzle_type<0, 1, 1>& xyy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1>&>(arr); };
swizzle_type<0, 1, 2>& xyz() noexcept { return reinterpret_cast<swizzle_type<0, 1, 2>&>(arr); };
swizzle_type<0, 2, 0>& xzx() noexcept { return reinterpret_cast<swizzle_type<0, 2, 0>&>(arr); };
swizzle_type<0, 2, 1>& xzy() noexcept { return reinterpret_cast<swizzle_type<0, 2, 1>&>(arr); };
swizzle_type<0, 2, 2>& xzz() noexcept { return reinterpret_cast<swizzle_type<0, 2, 2>&>(arr); };
swizzle_type<1, 0, 0>& yxx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0>&>(arr); };
swizzle_type<1, 0, 1>& yxy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1>&>(arr); };
swizzle_type<1, 0, 2>& yxz() noexcept { return reinterpret_cast<swizzle_type<1, 0, 2>&>(arr); };
swizzle_type<1, 1, 0>& yyx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1>& yyy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1>&>(arr); };
swizzle_type<1, 1, 2>& yyz() noexcept { return reinterpret_cast<swizzle_type<1, 1, 2>&>(arr); };
swizzle_type<1, 2, 0>& yzx() noexcept { return reinterpret_cast<swizzle_type<1, 2, 0>&>(arr); };
swizzle_type<1, 2, 1>& yzy() noexcept { return reinterpret_cast<swizzle_type<1, 2, 1>&>(arr); };
swizzle_type<1, 2, 2>& yzz() noexcept { return reinterpret_cast<swizzle_type<1, 2, 2>&>(arr); };
swizzle_type<2, 0, 0>& zxx() noexcept { return reinterpret_cast<swizzle_type<2, 0, 0>&>(arr); };
swizzle_type<2, 0, 1>& zxy() noexcept { return reinterpret_cast<swizzle_type<2, 0, 1>&>(arr); };
swizzle_type<2, 0, 2>& zxz() noexcept { return reinterpret_cast<swizzle_type<2, 0, 2>&>(arr); };
swizzle_type<2, 1, 0>& zyx() noexcept { return reinterpret_cast<swizzle_type<2, 1, 0>&>(arr); };
swizzle_type<2, 1, 1>& zyy() noexcept { return reinterpret_cast<swizzle_type<2, 1, 1>&>(arr); };
swizzle_type<2, 1, 2>& zyz() noexcept { return reinterpret_cast<swizzle_type<2, 1, 2>&>(arr); };
swizzle_type<2, 2, 0>& zzx() noexcept { return reinterpret_cast<swizzle_type<2, 2, 0>&>(arr); };
swizzle_type<2, 2, 1>& zzy() noexcept { return reinterpret_cast<swizzle_type<2, 2, 1>&>(arr); };
swizzle_type<2, 2, 2>& zzz() noexcept { return reinterpret_cast<swizzle_type<2, 2, 2>&>(arr); };
const swizzle_type<0, 0, 0>& xxx() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 0>&>(arr); };
const swizzle_type<0, 0, 1>& xxy() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 1>&>(arr); };
const swizzle_type<0, 0, 2>& xxz() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 2>&>(arr); };
const swizzle_type<0, 1, 0>& xyx() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 0>&>(arr); };
const swizzle_type<0, 1, 1>& xyy() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 1>&>(arr); };
const swizzle_type<0, 1, 2>& xyz() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 2>&>(arr); };
const swizzle_type<0, 2, 0>& xzx() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 0>&>(arr); };
const swizzle_type<0, 2, 1>& xzy() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 1>&>(arr); };
const swizzle_type<0, 2, 2>& xzz() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 2>&>(arr); };
const swizzle_type<1, 0, 0>& yxx() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 0>&>(arr); };
const swizzle_type<1, 0, 1>& yxy() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 1>&>(arr); };
const swizzle_type<1, 0, 2>& yxz() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 2>&>(arr); };
const swizzle_type<1, 1, 0>& yyx() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 0>&>(arr); };
const swizzle_type<1, 1, 1>& yyy() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 1>&>(arr); };
const swizzle_type<1, 1, 2>& yyz() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 2>&>(arr); };
const swizzle_type<1, 2, 0>& yzx() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 0>&>(arr); };
const swizzle_type<1, 2, 1>& yzy() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 1>&>(arr); };
const swizzle_type<1, 2, 2>& yzz() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 2>&>(arr); };
const swizzle_type<2, 0, 0>& zxx() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 0>&>(arr); };
const swizzle_type<2, 0, 1>& zxy() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 1>&>(arr); };
const swizzle_type<2, 0, 2>& zxz() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 2>&>(arr); };
const swizzle_type<2, 1, 0>& zyx() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 0>&>(arr); };
const swizzle_type<2, 1, 1>& zyy() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 1>&>(arr); };
const swizzle_type<2, 1, 2>& zyz() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 2>&>(arr); };
const swizzle_type<2, 2, 0>& zzx() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 0>&>(arr); };
const swizzle_type<2, 2, 1>& zzy() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 1>&>(arr); };
const swizzle_type<2, 2, 2>& zzz() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 2>&>(arr); };

swizzle_type<0, 0, 0, 0>& xxxx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 0>&>(arr); };
swizzle_type<0, 0, 0, 1>& xxxy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 1>&>(arr); };
swizzle_type<0, 0, 0, 2>& xxxz() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 2>&>(arr); };
swizzle_type<0, 0, 1, 0>& xxyx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 0>&>(arr); };
swizzle_type<0, 0, 1, 1>& xxyy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 1>&>(arr); };
swizzle_type<0, 0, 1, 2>& xxyz() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 2>&>(arr); };
swizzle_type<0, 0, 2, 0>& xxzx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 0>&>(arr); };
swizzle_type<0, 0, 2, 1>& xxzy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 1>&>(arr); };
swizzle_type<0, 0, 2, 2>& xxzz() noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 2>&>(arr); };
swizzle_type<0, 1, 0, 0>& xyxx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 0>&>(arr); };
swizzle_type<0, 1, 0, 1>& xyxy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 1>&>(arr); };
swizzle_type<0, 1, 0, 2>& xyxz() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 2>&>(arr); };
swizzle_type<0, 1, 1, 0>& xyyx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 0>&>(arr); };
swizzle_type<0, 1, 1, 1>& xyyy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 1>&>(arr); };
swizzle_type<0, 1, 1, 2>& xyyz() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 2>&>(arr); };
swizzle_type<0, 1, 2, 0>& xyzx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 0>&>(arr); };
swizzle_type<0, 1, 2, 1>& xyzy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 1>&>(arr); };
swizzle_type<0, 1, 2, 2>& xyzz() noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 2>&>(arr); };
swizzle_type<0, 2, 0, 0>& xzxx() noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 0>&>(arr); };
swizzle_type<0, 2, 0, 1>& xzxy() noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 1>&>(arr); };
swizzle_type<0, 2, 0, 2>& xzxz() noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 2>&>(arr); };
swizzle_type<0, 2, 1, 0>& xzyx() noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 0>&>(arr); };
swizzle_type<0, 2, 1, 1>& xzyy() noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 1>&>(arr); };
swizzle_type<0, 2, 1, 2>& xzyz() noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 2>&>(arr); };
swizzle_type<0, 2, 2, 0>& xzzx() noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 0>&>(arr); };
swizzle_type<0, 2, 2, 1>& xzzy() noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 1>&>(arr); };
swizzle_type<0, 2, 2, 2>& xzzz() noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 2>&>(arr); };
swizzle_type<1, 0, 0, 0>& yxxx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 0>&>(arr); };
swizzle_type<1, 0, 0, 1>& yxxy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 1>&>(arr); };
swizzle_type<1, 0, 0, 2>& yxxz() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 2>&>(arr); };
swizzle_type<1, 0, 1, 0>& yxyx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 0>&>(arr); };
swizzle_type<1, 0, 1, 1>& yxyy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 1>&>(arr); };
swizzle_type<1, 0, 1, 2>& yxyz() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 2>&>(arr); };
swizzle_type<1, 0, 2, 0>& yxzx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 0>&>(arr); };
swizzle_type<1, 0, 2, 1>& yxzy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 1>&>(arr); };
swizzle_type<1, 0, 2, 2>& yxzz() noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 2>&>(arr); };
swizzle_type<1, 1, 0, 0>& yyxx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 0>&>(arr); };
swizzle_type<1, 1, 0, 1>& yyxy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 1>&>(arr); };
swizzle_type<1, 1, 0, 2>& yyxz() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 2>&>(arr); };
swizzle_type<1, 1, 1, 0>& yyyx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1, 1>& yyyy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 1>&>(arr); };
swizzle_type<1, 1, 1, 2>& yyyz() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 2>&>(arr); };
swizzle_type<1, 1, 2, 0>& yyzx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 0>&>(arr); };
swizzle_type<1, 1, 2, 1>& yyzy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 1>&>(arr); };
swizzle_type<1, 1, 2, 2>& yyzz() noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 2>&>(arr); };
swizzle_type<1, 2, 0, 0>& yzxx() noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 0>&>(arr); };
swizzle_type<1, 2, 0, 1>& yzxy() noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 1>&>(arr); };
swizzle_type<1, 2, 0, 2>& yzxz() noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 2>&>(arr); };
swizzle_type<1, 2, 1, 0>& yzyx() noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 0>&>(arr); };
swizzle_type<1, 2, 1, 1>& yzyy() noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 1>&>(arr); };
swizzle_type<1, 2, 1, 2>& yzyz() noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 2>&>(arr); };
swizzle_type<1, 2, 2, 0>& yzzx() noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 0>&>(arr); };
swizzle_type<1, 2, 2, 1>& yzzy() noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 1>&>(arr); };
swizzle_type<1, 2, 2, 2>& yzzz() noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 2>&>(arr); };
swizzle_type<2, 0, 0, 0>& zxxx() noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 0>&>(arr); };
swizzle_type<2, 0, 0, 1>& zxxy() noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 1>&>(arr); };
swizzle_type<2, 0, 0, 2>& zxxz() noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 2>&>(arr); };
swizzle_type<2, 0, 1, 0>& zxyx() noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 0>&>(arr); };
swizzle_type<2, 0, 1, 1>& zxyy() noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 1>&>(arr); };
swizzle_type<2, 0, 1, 2>& zxyz() noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 2>&>(arr); };
swizzle_type<2, 0, 2, 0>& zxzx() noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 0>&>(arr); };
swizzle_type<2, 0, 2, 1>& zxzy() noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 1>&>(arr); };
swizzle_type<2, 0, 2, 2>& zxzz() noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 2>&>(arr); };
swizzle_type<2, 1, 0, 0>& zyxx() noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 0>&>(arr); };
swizzle_type<2, 1, 0, 1>& zyxy() noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 1>&>(arr); };
swizzle_type<2, 1, 0, 2>& zyxz() noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 2>&>(arr); };
swizzle_type<2, 1, 1, 0>& zyyx() noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 0>&>(arr); };
swizzle_type<2, 1, 1, 1>& zyyy() noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 1>&>(arr); };
swizzle_type<2, 1, 1, 2>& zyyz() noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 2>&>(arr); };
swizzle_type<2, 1, 2, 0>& zyzx() noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 0>&>(arr); };
swizzle_type<2, 1, 2, 1>& zyzy() noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 1>&>(arr); };
swizzle_type<2, 1, 2, 2>& zyzz() noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 2>&>(arr); };
swizzle_type<2, 2, 0, 0>& zzxx() noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 0>&>(arr); };
swizzle_type<2, 2, 0, 1>& zzxy() noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 1>&>(arr); };
swizzle_type<2, 2, 0, 2>& zzxz() noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 2>&>(arr); };
swizzle_type<2, 2, 1, 0>& zzyx() noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 0>&>(arr); };
swizzle_type<2, 2, 1, 1>& zzyy() noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 1>&>(arr); };
swizzle_type<2, 2, 1, 2>& zzyz() noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 2>&>(arr); };
swizzle_type<2, 2, 2, 0>& zzzx() noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 0>&>(arr); };
swizzle_type<2, 2, 2, 1>& zzzy() noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 1>&>(arr); };
swizzle_type<2, 2, 2, 2>& zzzz() noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 2>&>(arr); };
const swizzle_type<0, 0, 0, 0>& xxxx() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 0>&>(arr); };
const swizzle_type<0, 0, 0, 1>& xxxy() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 1>&>(arr); };
const swizzle_type<0, 0, 0, 2>& xxxz() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 2>&>(arr); };
const swizzle_type<0, 0, 1, 0>& xxyx() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 0>&>(arr); };
const swizzle_type<0, 0, 1, 1>& xxyy() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 1>&>(arr); };
const swizzle_type<0, 0, 1, 2>& xxyz() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 2>&>(arr); };
const swizzle_type<0, 0, 2, 0>& xxzx() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 0>&>(arr); };
const swizzle_type<0, 0, 2, 1>& xxzy() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 1>&>(arr); };
const swizzle_type<0, 0, 2, 2>& xxzz() const noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 2>&>(arr); };
const swizzle_type<0, 1, 0, 0>& xyxx() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 0>&>(arr); };
const swizzle_type<0, 1, 0, 1>& xyxy() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 1>&>(arr); };
const swizzle_type<0, 1, 0, 2>& xyxz() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 2>&>(arr); };
const swizzle_type<0, 1, 1, 0>& xyyx() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 0>&>(arr); };
const swizzle_type<0, 1, 1, 1>& xyyy() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 1>&>(arr); };
const swizzle_type<0, 1, 1, 2>& xyyz() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 2>&>(arr); };
const swizzle_type<0, 1, 2, 0>& xyzx() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 0>&>(arr); };
const swizzle_type<0, 1, 2, 1>& xyzy() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 1>&>(arr); };
const swizzle_type<0, 1, 2, 2>& xyzz() const noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 2>&>(arr); };
const swizzle_type<0, 2, 0, 0>& xzxx() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 0>&>(arr); };
const swizzle_type<0, 2, 0, 1>& xzxy() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 1>&>(arr); };
const swizzle_type<0, 2, 0, 2>& xzxz() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 2>&>(arr); };
const swizzle_type<0, 2, 1, 0>& xzyx() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 0>&>(arr); };
const swizzle_type<0, 2, 1, 1>& xzyy() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 1>&>(arr); };
const swizzle_type<0, 2, 1, 2>& xzyz() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 2>&>(arr); };
const swizzle_type<0, 2, 2, 0>& xzzx() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 0>&>(arr); };
const swizzle_type<0, 2, 2, 1>& xzzy() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 1>&>(arr); };
const swizzle_type<0, 2, 2, 2>& xzzz() const noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 2>&>(arr); };
const swizzle_type<1, 0, 0, 0>& yxxx() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 0>&>(arr); };
const swizzle_type<1, 0, 0, 1>& yxxy() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 1>&>(arr); };
const swizzle_type<1, 0, 0, 2>& yxxz() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 2>&>(arr); };
const swizzle_type<1, 0, 1, 0>& yxyx() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 0>&>(arr); };
const swizzle_type<1, 0, 1, 1>& yxyy() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 1>&>(arr); };
const swizzle_type<1, 0, 1, 2>& yxyz() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 2>&>(arr); };
const swizzle_type<1, 0, 2, 0>& yxzx() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 0>&>(arr); };
const swizzle_type<1, 0, 2, 1>& yxzy() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 1>&>(arr); };
const swizzle_type<1, 0, 2, 2>& yxzz() const noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 2>&>(arr); };
const swizzle_type<1, 1, 0, 0>& yyxx() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 0>&>(arr); };
const swizzle_type<1, 1, 0, 1>& yyxy() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 1>&>(arr); };
const swizzle_type<1, 1, 0, 2>& yyxz() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 2>&>(arr); };
const swizzle_type<1, 1, 1, 0>& yyyx() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 0>&>(arr); };
const swizzle_type<1, 1, 1, 1>& yyyy() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 1>&>(arr); };
const swizzle_type<1, 1, 1, 2>& yyyz() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 2>&>(arr); };
const swizzle_type<1, 1, 2, 0>& yyzx() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 0>&>(arr); };
const swizzle_type<1, 1, 2, 1>& yyzy() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 1>&>(arr); };
const swizzle_type<1, 1, 2, 2>& yyzz() const noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 2>&>(arr); };
const swizzle_type<1, 2, 0, 0>& yzxx() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 0>&>(arr); };
const swizzle_type<1, 2, 0, 1>& yzxy() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 1>&>(arr); };
const swizzle_type<1, 2, 0, 2>& yzxz() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 2>&>(arr); };
const swizzle_type<1, 2, 1, 0>& yzyx() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 0>&>(arr); };
const swizzle_type<1, 2, 1, 1>& yzyy() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 1>&>(arr); };
const swizzle_type<1, 2, 1, 2>& yzyz() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 2>&>(arr); };
const swizzle_type<1, 2, 2, 0>& yzzx() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 0>&>(arr); };
const swizzle_type<1, 2, 2, 1>& yzzy() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 1>&>(arr); };
const swizzle_type<1, 2, 2, 2>& yzzz() const noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 2>&>(arr); };
const swizzle_type<2, 0, 0, 0>& zxxx() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 0>&>(arr); };
const swizzle_type<2, 0, 0, 1>& zxxy() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 1>&>(arr); };
const swizzle_type<2, 0, 0, 2>& zxxz() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 2>&>(arr); };
const swizzle_type<2, 0, 1, 0>& zxyx() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 0>&>(arr); };
const swizzle_type<2, 0, 1, 1>& zxyy() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 1>&>(arr); };
const swizzle_type<2, 0, 1, 2>& zxyz() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 2>&>(arr); };
const swizzle_type<2, 0, 2, 0>& zxzx() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 0>&>(arr); };
const swizzle_type<2, 0, 2, 1>& zxzy() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 1>&>(arr); };
const swizzle_type<2, 0, 2, 2>& zxzz() const noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 2>&>(arr); };
const swizzle_type<2, 1, 0, 0>& zyxx() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 0>&>(arr); };
const swizzle_type<2, 1, 0, 1>& zyxy() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 1>&>(arr); };
const swizzle_type<2, 1, 0, 2>& zyxz() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 2>&>(arr); };
const swizzle_type<2, 1, 1, 0>& zyyx() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 0>&>(arr); };
const swizzle_type<2, 1, 1, 1>& zyyy() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 1>&>(arr); };
const swizzle_type<2, 1, 1, 2>& zyyz() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 2>&>(arr); };
const swizzle_type<2, 1, 2, 0>& zyzx() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 0>&>(arr); };
const swizzle_type<2, 1, 2, 1>& zyzy() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 1>&>(arr); };
const swizzle_type<2, 1, 2, 2>& zyzz() const noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 2>&>(arr); };
const swizzle_type<2, 2, 0, 0>& zzxx() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 0>&>(arr); };
const swizzle_type<2, 2, 0, 1>& zzxy() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 1>&>(arr); };
const swizzle_type<2, 2, 0, 2>& zzxz() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 2>&>(arr); };
const swizzle_type<2, 2, 1, 0>& zzyx() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 0>&>(arr); };
const swizzle_type<2, 2, 1, 1>& zzyy() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 1>&>(arr); };
const swizzle_type<2, 2, 1, 2>& zzyz() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 2>&>(arr); };
const swizzle_type<2, 2, 2, 0>& zzzx() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 0>&>(arr); };
const swizzle_type<2, 2, 2, 1>& zzzy() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 1>&>(arr); };
const swizzle_type<2, 2, 2, 2>& zzzz() const noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 2>&>(arr); };
