swizzle_type<0, 0>& xx() noexcept { return reinterpret_cast<swizzle_type<0, 0>&>(arr); };
swizzle_type<0, 1>& xy() noexcept { return reinterpret_cast<swizzle_type<0, 1>&>(arr); };
swizzle_type<0, 2>& xz() noexcept { return reinterpret_cast<swizzle_type<0, 2>&>(arr); };
swizzle_type<0, 3>& xw() noexcept { return reinterpret_cast<swizzle_type<0, 3>&>(arr); };
swizzle_type<1, 0>& yx() noexcept { return reinterpret_cast<swizzle_type<1, 0>&>(arr); };
swizzle_type<1, 1>& yy() noexcept { return reinterpret_cast<swizzle_type<1, 1>&>(arr); };
swizzle_type<1, 2>& yz() noexcept { return reinterpret_cast<swizzle_type<1, 2>&>(arr); };
swizzle_type<1, 3>& yw() noexcept { return reinterpret_cast<swizzle_type<1, 3>&>(arr); };
swizzle_type<2, 0>& zx() noexcept { return reinterpret_cast<swizzle_type<2, 0>&>(arr); };
swizzle_type<2, 1>& zy() noexcept { return reinterpret_cast<swizzle_type<2, 1>&>(arr); };
swizzle_type<2, 2>& zz() noexcept { return reinterpret_cast<swizzle_type<2, 2>&>(arr); };
swizzle_type<2, 3>& zw() noexcept { return reinterpret_cast<swizzle_type<2, 3>&>(arr); };
swizzle_type<3, 0>& wx() noexcept { return reinterpret_cast<swizzle_type<3, 0>&>(arr); };
swizzle_type<3, 1>& wy() noexcept { return reinterpret_cast<swizzle_type<3, 1>&>(arr); };
swizzle_type<3, 2>& wz() noexcept { return reinterpret_cast<swizzle_type<3, 2>&>(arr); };
swizzle_type<3, 3>& ww() noexcept { return reinterpret_cast<swizzle_type<3, 3>&>(arr); };
auto xx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0>&>(arr).to_vec(); };
auto xy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1>&>(arr).to_vec(); };
auto xz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2>&>(arr).to_vec(); };
auto xw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3>&>(arr).to_vec(); };
auto yx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0>&>(arr).to_vec(); };
auto yy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1>&>(arr).to_vec(); };
auto yz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2>&>(arr).to_vec(); };
auto yw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3>&>(arr).to_vec(); };
auto zx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0>&>(arr).to_vec(); };
auto zy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1>&>(arr).to_vec(); };
auto zz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2>&>(arr).to_vec(); };
auto zw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3>&>(arr).to_vec(); };
auto wx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0>&>(arr).to_vec(); };
auto wy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1>&>(arr).to_vec(); };
auto wz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2>&>(arr).to_vec(); };
auto ww_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3>&>(arr).to_vec(); };

swizzle_type<0, 0, 0>& xxx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0>&>(arr); };
swizzle_type<0, 0, 1>& xxy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1>&>(arr); };
swizzle_type<0, 0, 2>& xxz() noexcept { return reinterpret_cast<swizzle_type<0, 0, 2>&>(arr); };
swizzle_type<0, 0, 3>& xxw() noexcept { return reinterpret_cast<swizzle_type<0, 0, 3>&>(arr); };
swizzle_type<0, 1, 0>& xyx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0>&>(arr); };
swizzle_type<0, 1, 1>& xyy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1>&>(arr); };
swizzle_type<0, 1, 2>& xyz() noexcept { return reinterpret_cast<swizzle_type<0, 1, 2>&>(arr); };
swizzle_type<0, 1, 3>& xyw() noexcept { return reinterpret_cast<swizzle_type<0, 1, 3>&>(arr); };
swizzle_type<0, 2, 0>& xzx() noexcept { return reinterpret_cast<swizzle_type<0, 2, 0>&>(arr); };
swizzle_type<0, 2, 1>& xzy() noexcept { return reinterpret_cast<swizzle_type<0, 2, 1>&>(arr); };
swizzle_type<0, 2, 2>& xzz() noexcept { return reinterpret_cast<swizzle_type<0, 2, 2>&>(arr); };
swizzle_type<0, 2, 3>& xzw() noexcept { return reinterpret_cast<swizzle_type<0, 2, 3>&>(arr); };
swizzle_type<0, 3, 0>& xwx() noexcept { return reinterpret_cast<swizzle_type<0, 3, 0>&>(arr); };
swizzle_type<0, 3, 1>& xwy() noexcept { return reinterpret_cast<swizzle_type<0, 3, 1>&>(arr); };
swizzle_type<0, 3, 2>& xwz() noexcept { return reinterpret_cast<swizzle_type<0, 3, 2>&>(arr); };
swizzle_type<0, 3, 3>& xww() noexcept { return reinterpret_cast<swizzle_type<0, 3, 3>&>(arr); };
swizzle_type<1, 0, 0>& yxx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0>&>(arr); };
swizzle_type<1, 0, 1>& yxy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1>&>(arr); };
swizzle_type<1, 0, 2>& yxz() noexcept { return reinterpret_cast<swizzle_type<1, 0, 2>&>(arr); };
swizzle_type<1, 0, 3>& yxw() noexcept { return reinterpret_cast<swizzle_type<1, 0, 3>&>(arr); };
swizzle_type<1, 1, 0>& yyx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1>& yyy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1>&>(arr); };
swizzle_type<1, 1, 2>& yyz() noexcept { return reinterpret_cast<swizzle_type<1, 1, 2>&>(arr); };
swizzle_type<1, 1, 3>& yyw() noexcept { return reinterpret_cast<swizzle_type<1, 1, 3>&>(arr); };
swizzle_type<1, 2, 0>& yzx() noexcept { return reinterpret_cast<swizzle_type<1, 2, 0>&>(arr); };
swizzle_type<1, 2, 1>& yzy() noexcept { return reinterpret_cast<swizzle_type<1, 2, 1>&>(arr); };
swizzle_type<1, 2, 2>& yzz() noexcept { return reinterpret_cast<swizzle_type<1, 2, 2>&>(arr); };
swizzle_type<1, 2, 3>& yzw() noexcept { return reinterpret_cast<swizzle_type<1, 2, 3>&>(arr); };
swizzle_type<1, 3, 0>& ywx() noexcept { return reinterpret_cast<swizzle_type<1, 3, 0>&>(arr); };
swizzle_type<1, 3, 1>& ywy() noexcept { return reinterpret_cast<swizzle_type<1, 3, 1>&>(arr); };
swizzle_type<1, 3, 2>& ywz() noexcept { return reinterpret_cast<swizzle_type<1, 3, 2>&>(arr); };
swizzle_type<1, 3, 3>& yww() noexcept { return reinterpret_cast<swizzle_type<1, 3, 3>&>(arr); };
swizzle_type<2, 0, 0>& zxx() noexcept { return reinterpret_cast<swizzle_type<2, 0, 0>&>(arr); };
swizzle_type<2, 0, 1>& zxy() noexcept { return reinterpret_cast<swizzle_type<2, 0, 1>&>(arr); };
swizzle_type<2, 0, 2>& zxz() noexcept { return reinterpret_cast<swizzle_type<2, 0, 2>&>(arr); };
swizzle_type<2, 0, 3>& zxw() noexcept { return reinterpret_cast<swizzle_type<2, 0, 3>&>(arr); };
swizzle_type<2, 1, 0>& zyx() noexcept { return reinterpret_cast<swizzle_type<2, 1, 0>&>(arr); };
swizzle_type<2, 1, 1>& zyy() noexcept { return reinterpret_cast<swizzle_type<2, 1, 1>&>(arr); };
swizzle_type<2, 1, 2>& zyz() noexcept { return reinterpret_cast<swizzle_type<2, 1, 2>&>(arr); };
swizzle_type<2, 1, 3>& zyw() noexcept { return reinterpret_cast<swizzle_type<2, 1, 3>&>(arr); };
swizzle_type<2, 2, 0>& zzx() noexcept { return reinterpret_cast<swizzle_type<2, 2, 0>&>(arr); };
swizzle_type<2, 2, 1>& zzy() noexcept { return reinterpret_cast<swizzle_type<2, 2, 1>&>(arr); };
swizzle_type<2, 2, 2>& zzz() noexcept { return reinterpret_cast<swizzle_type<2, 2, 2>&>(arr); };
swizzle_type<2, 2, 3>& zzw() noexcept { return reinterpret_cast<swizzle_type<2, 2, 3>&>(arr); };
swizzle_type<2, 3, 0>& zwx() noexcept { return reinterpret_cast<swizzle_type<2, 3, 0>&>(arr); };
swizzle_type<2, 3, 1>& zwy() noexcept { return reinterpret_cast<swizzle_type<2, 3, 1>&>(arr); };
swizzle_type<2, 3, 2>& zwz() noexcept { return reinterpret_cast<swizzle_type<2, 3, 2>&>(arr); };
swizzle_type<2, 3, 3>& zww() noexcept { return reinterpret_cast<swizzle_type<2, 3, 3>&>(arr); };
swizzle_type<3, 0, 0>& wxx() noexcept { return reinterpret_cast<swizzle_type<3, 0, 0>&>(arr); };
swizzle_type<3, 0, 1>& wxy() noexcept { return reinterpret_cast<swizzle_type<3, 0, 1>&>(arr); };
swizzle_type<3, 0, 2>& wxz() noexcept { return reinterpret_cast<swizzle_type<3, 0, 2>&>(arr); };
swizzle_type<3, 0, 3>& wxw() noexcept { return reinterpret_cast<swizzle_type<3, 0, 3>&>(arr); };
swizzle_type<3, 1, 0>& wyx() noexcept { return reinterpret_cast<swizzle_type<3, 1, 0>&>(arr); };
swizzle_type<3, 1, 1>& wyy() noexcept { return reinterpret_cast<swizzle_type<3, 1, 1>&>(arr); };
swizzle_type<3, 1, 2>& wyz() noexcept { return reinterpret_cast<swizzle_type<3, 1, 2>&>(arr); };
swizzle_type<3, 1, 3>& wyw() noexcept { return reinterpret_cast<swizzle_type<3, 1, 3>&>(arr); };
swizzle_type<3, 2, 0>& wzx() noexcept { return reinterpret_cast<swizzle_type<3, 2, 0>&>(arr); };
swizzle_type<3, 2, 1>& wzy() noexcept { return reinterpret_cast<swizzle_type<3, 2, 1>&>(arr); };
swizzle_type<3, 2, 2>& wzz() noexcept { return reinterpret_cast<swizzle_type<3, 2, 2>&>(arr); };
swizzle_type<3, 2, 3>& wzw() noexcept { return reinterpret_cast<swizzle_type<3, 2, 3>&>(arr); };
swizzle_type<3, 3, 0>& wwx() noexcept { return reinterpret_cast<swizzle_type<3, 3, 0>&>(arr); };
swizzle_type<3, 3, 1>& wwy() noexcept { return reinterpret_cast<swizzle_type<3, 3, 1>&>(arr); };
swizzle_type<3, 3, 2>& wwz() noexcept { return reinterpret_cast<swizzle_type<3, 3, 2>&>(arr); };
swizzle_type<3, 3, 3>& www() noexcept { return reinterpret_cast<swizzle_type<3, 3, 3>&>(arr); };
auto xxx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 0>&>(arr).to_vec(); };
auto xxy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 1>&>(arr).to_vec(); };
auto xxz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 2>&>(arr).to_vec(); };
auto xxw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 3>&>(arr).to_vec(); };
auto xyx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 0>&>(arr).to_vec(); };
auto xyy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 1>&>(arr).to_vec(); };
auto xyz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 2>&>(arr).to_vec(); };
auto xyw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 3>&>(arr).to_vec(); };
auto xzx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 0>&>(arr).to_vec(); };
auto xzy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 1>&>(arr).to_vec(); };
auto xzz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 2>&>(arr).to_vec(); };
auto xzw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 3>&>(arr).to_vec(); };
auto xwx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 0>&>(arr).to_vec(); };
auto xwy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 1>&>(arr).to_vec(); };
auto xwz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 2>&>(arr).to_vec(); };
auto xww_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 3>&>(arr).to_vec(); };
auto yxx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 0>&>(arr).to_vec(); };
auto yxy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 1>&>(arr).to_vec(); };
auto yxz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 2>&>(arr).to_vec(); };
auto yxw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 3>&>(arr).to_vec(); };
auto yyx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 0>&>(arr).to_vec(); };
auto yyy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 1>&>(arr).to_vec(); };
auto yyz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 2>&>(arr).to_vec(); };
auto yyw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 3>&>(arr).to_vec(); };
auto yzx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 0>&>(arr).to_vec(); };
auto yzy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 1>&>(arr).to_vec(); };
auto yzz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 2>&>(arr).to_vec(); };
auto yzw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 3>&>(arr).to_vec(); };
auto ywx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 0>&>(arr).to_vec(); };
auto ywy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 1>&>(arr).to_vec(); };
auto ywz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 2>&>(arr).to_vec(); };
auto yww_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 3>&>(arr).to_vec(); };
auto zxx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 0>&>(arr).to_vec(); };
auto zxy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 1>&>(arr).to_vec(); };
auto zxz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 2>&>(arr).to_vec(); };
auto zxw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 3>&>(arr).to_vec(); };
auto zyx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 0>&>(arr).to_vec(); };
auto zyy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 1>&>(arr).to_vec(); };
auto zyz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 2>&>(arr).to_vec(); };
auto zyw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 3>&>(arr).to_vec(); };
auto zzx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 0>&>(arr).to_vec(); };
auto zzy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 1>&>(arr).to_vec(); };
auto zzz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 2>&>(arr).to_vec(); };
auto zzw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 3>&>(arr).to_vec(); };
auto zwx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 0>&>(arr).to_vec(); };
auto zwy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 1>&>(arr).to_vec(); };
auto zwz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 2>&>(arr).to_vec(); };
auto zww_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 3>&>(arr).to_vec(); };
auto wxx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 0>&>(arr).to_vec(); };
auto wxy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 1>&>(arr).to_vec(); };
auto wxz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 2>&>(arr).to_vec(); };
auto wxw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 3>&>(arr).to_vec(); };
auto wyx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 0>&>(arr).to_vec(); };
auto wyy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 1>&>(arr).to_vec(); };
auto wyz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 2>&>(arr).to_vec(); };
auto wyw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 3>&>(arr).to_vec(); };
auto wzx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 0>&>(arr).to_vec(); };
auto wzy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 1>&>(arr).to_vec(); };
auto wzz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 2>&>(arr).to_vec(); };
auto wzw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 3>&>(arr).to_vec(); };
auto wwx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 0>&>(arr).to_vec(); };
auto wwy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 1>&>(arr).to_vec(); };
auto wwz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 2>&>(arr).to_vec(); };
auto www_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 3>&>(arr).to_vec(); };

swizzle_type<0, 0, 0, 0>& xxxx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 0>&>(arr); };
swizzle_type<0, 0, 0, 1>& xxxy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 1>&>(arr); };
swizzle_type<0, 0, 0, 2>& xxxz() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 2>&>(arr); };
swizzle_type<0, 0, 0, 3>& xxxw() noexcept { return reinterpret_cast<swizzle_type<0, 0, 0, 3>&>(arr); };
swizzle_type<0, 0, 1, 0>& xxyx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 0>&>(arr); };
swizzle_type<0, 0, 1, 1>& xxyy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 1>&>(arr); };
swizzle_type<0, 0, 1, 2>& xxyz() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 2>&>(arr); };
swizzle_type<0, 0, 1, 3>& xxyw() noexcept { return reinterpret_cast<swizzle_type<0, 0, 1, 3>&>(arr); };
swizzle_type<0, 0, 2, 0>& xxzx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 0>&>(arr); };
swizzle_type<0, 0, 2, 1>& xxzy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 1>&>(arr); };
swizzle_type<0, 0, 2, 2>& xxzz() noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 2>&>(arr); };
swizzle_type<0, 0, 2, 3>& xxzw() noexcept { return reinterpret_cast<swizzle_type<0, 0, 2, 3>&>(arr); };
swizzle_type<0, 0, 3, 0>& xxwx() noexcept { return reinterpret_cast<swizzle_type<0, 0, 3, 0>&>(arr); };
swizzle_type<0, 0, 3, 1>& xxwy() noexcept { return reinterpret_cast<swizzle_type<0, 0, 3, 1>&>(arr); };
swizzle_type<0, 0, 3, 2>& xxwz() noexcept { return reinterpret_cast<swizzle_type<0, 0, 3, 2>&>(arr); };
swizzle_type<0, 0, 3, 3>& xxww() noexcept { return reinterpret_cast<swizzle_type<0, 0, 3, 3>&>(arr); };
swizzle_type<0, 1, 0, 0>& xyxx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 0>&>(arr); };
swizzle_type<0, 1, 0, 1>& xyxy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 1>&>(arr); };
swizzle_type<0, 1, 0, 2>& xyxz() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 2>&>(arr); };
swizzle_type<0, 1, 0, 3>& xyxw() noexcept { return reinterpret_cast<swizzle_type<0, 1, 0, 3>&>(arr); };
swizzle_type<0, 1, 1, 0>& xyyx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 0>&>(arr); };
swizzle_type<0, 1, 1, 1>& xyyy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 1>&>(arr); };
swizzle_type<0, 1, 1, 2>& xyyz() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 2>&>(arr); };
swizzle_type<0, 1, 1, 3>& xyyw() noexcept { return reinterpret_cast<swizzle_type<0, 1, 1, 3>&>(arr); };
swizzle_type<0, 1, 2, 0>& xyzx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 0>&>(arr); };
swizzle_type<0, 1, 2, 1>& xyzy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 1>&>(arr); };
swizzle_type<0, 1, 2, 2>& xyzz() noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 2>&>(arr); };
swizzle_type<0, 1, 2, 3>& xyzw() noexcept { return reinterpret_cast<swizzle_type<0, 1, 2, 3>&>(arr); };
swizzle_type<0, 1, 3, 0>& xywx() noexcept { return reinterpret_cast<swizzle_type<0, 1, 3, 0>&>(arr); };
swizzle_type<0, 1, 3, 1>& xywy() noexcept { return reinterpret_cast<swizzle_type<0, 1, 3, 1>&>(arr); };
swizzle_type<0, 1, 3, 2>& xywz() noexcept { return reinterpret_cast<swizzle_type<0, 1, 3, 2>&>(arr); };
swizzle_type<0, 1, 3, 3>& xyww() noexcept { return reinterpret_cast<swizzle_type<0, 1, 3, 3>&>(arr); };
swizzle_type<0, 2, 0, 0>& xzxx() noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 0>&>(arr); };
swizzle_type<0, 2, 0, 1>& xzxy() noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 1>&>(arr); };
swizzle_type<0, 2, 0, 2>& xzxz() noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 2>&>(arr); };
swizzle_type<0, 2, 0, 3>& xzxw() noexcept { return reinterpret_cast<swizzle_type<0, 2, 0, 3>&>(arr); };
swizzle_type<0, 2, 1, 0>& xzyx() noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 0>&>(arr); };
swizzle_type<0, 2, 1, 1>& xzyy() noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 1>&>(arr); };
swizzle_type<0, 2, 1, 2>& xzyz() noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 2>&>(arr); };
swizzle_type<0, 2, 1, 3>& xzyw() noexcept { return reinterpret_cast<swizzle_type<0, 2, 1, 3>&>(arr); };
swizzle_type<0, 2, 2, 0>& xzzx() noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 0>&>(arr); };
swizzle_type<0, 2, 2, 1>& xzzy() noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 1>&>(arr); };
swizzle_type<0, 2, 2, 2>& xzzz() noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 2>&>(arr); };
swizzle_type<0, 2, 2, 3>& xzzw() noexcept { return reinterpret_cast<swizzle_type<0, 2, 2, 3>&>(arr); };
swizzle_type<0, 2, 3, 0>& xzwx() noexcept { return reinterpret_cast<swizzle_type<0, 2, 3, 0>&>(arr); };
swizzle_type<0, 2, 3, 1>& xzwy() noexcept { return reinterpret_cast<swizzle_type<0, 2, 3, 1>&>(arr); };
swizzle_type<0, 2, 3, 2>& xzwz() noexcept { return reinterpret_cast<swizzle_type<0, 2, 3, 2>&>(arr); };
swizzle_type<0, 2, 3, 3>& xzww() noexcept { return reinterpret_cast<swizzle_type<0, 2, 3, 3>&>(arr); };
swizzle_type<0, 3, 0, 0>& xwxx() noexcept { return reinterpret_cast<swizzle_type<0, 3, 0, 0>&>(arr); };
swizzle_type<0, 3, 0, 1>& xwxy() noexcept { return reinterpret_cast<swizzle_type<0, 3, 0, 1>&>(arr); };
swizzle_type<0, 3, 0, 2>& xwxz() noexcept { return reinterpret_cast<swizzle_type<0, 3, 0, 2>&>(arr); };
swizzle_type<0, 3, 0, 3>& xwxw() noexcept { return reinterpret_cast<swizzle_type<0, 3, 0, 3>&>(arr); };
swizzle_type<0, 3, 1, 0>& xwyx() noexcept { return reinterpret_cast<swizzle_type<0, 3, 1, 0>&>(arr); };
swizzle_type<0, 3, 1, 1>& xwyy() noexcept { return reinterpret_cast<swizzle_type<0, 3, 1, 1>&>(arr); };
swizzle_type<0, 3, 1, 2>& xwyz() noexcept { return reinterpret_cast<swizzle_type<0, 3, 1, 2>&>(arr); };
swizzle_type<0, 3, 1, 3>& xwyw() noexcept { return reinterpret_cast<swizzle_type<0, 3, 1, 3>&>(arr); };
swizzle_type<0, 3, 2, 0>& xwzx() noexcept { return reinterpret_cast<swizzle_type<0, 3, 2, 0>&>(arr); };
swizzle_type<0, 3, 2, 1>& xwzy() noexcept { return reinterpret_cast<swizzle_type<0, 3, 2, 1>&>(arr); };
swizzle_type<0, 3, 2, 2>& xwzz() noexcept { return reinterpret_cast<swizzle_type<0, 3, 2, 2>&>(arr); };
swizzle_type<0, 3, 2, 3>& xwzw() noexcept { return reinterpret_cast<swizzle_type<0, 3, 2, 3>&>(arr); };
swizzle_type<0, 3, 3, 0>& xwwx() noexcept { return reinterpret_cast<swizzle_type<0, 3, 3, 0>&>(arr); };
swizzle_type<0, 3, 3, 1>& xwwy() noexcept { return reinterpret_cast<swizzle_type<0, 3, 3, 1>&>(arr); };
swizzle_type<0, 3, 3, 2>& xwwz() noexcept { return reinterpret_cast<swizzle_type<0, 3, 3, 2>&>(arr); };
swizzle_type<0, 3, 3, 3>& xwww() noexcept { return reinterpret_cast<swizzle_type<0, 3, 3, 3>&>(arr); };
swizzle_type<1, 0, 0, 0>& yxxx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 0>&>(arr); };
swizzle_type<1, 0, 0, 1>& yxxy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 1>&>(arr); };
swizzle_type<1, 0, 0, 2>& yxxz() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 2>&>(arr); };
swizzle_type<1, 0, 0, 3>& yxxw() noexcept { return reinterpret_cast<swizzle_type<1, 0, 0, 3>&>(arr); };
swizzle_type<1, 0, 1, 0>& yxyx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 0>&>(arr); };
swizzle_type<1, 0, 1, 1>& yxyy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 1>&>(arr); };
swizzle_type<1, 0, 1, 2>& yxyz() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 2>&>(arr); };
swizzle_type<1, 0, 1, 3>& yxyw() noexcept { return reinterpret_cast<swizzle_type<1, 0, 1, 3>&>(arr); };
swizzle_type<1, 0, 2, 0>& yxzx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 0>&>(arr); };
swizzle_type<1, 0, 2, 1>& yxzy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 1>&>(arr); };
swizzle_type<1, 0, 2, 2>& yxzz() noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 2>&>(arr); };
swizzle_type<1, 0, 2, 3>& yxzw() noexcept { return reinterpret_cast<swizzle_type<1, 0, 2, 3>&>(arr); };
swizzle_type<1, 0, 3, 0>& yxwx() noexcept { return reinterpret_cast<swizzle_type<1, 0, 3, 0>&>(arr); };
swizzle_type<1, 0, 3, 1>& yxwy() noexcept { return reinterpret_cast<swizzle_type<1, 0, 3, 1>&>(arr); };
swizzle_type<1, 0, 3, 2>& yxwz() noexcept { return reinterpret_cast<swizzle_type<1, 0, 3, 2>&>(arr); };
swizzle_type<1, 0, 3, 3>& yxww() noexcept { return reinterpret_cast<swizzle_type<1, 0, 3, 3>&>(arr); };
swizzle_type<1, 1, 0, 0>& yyxx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 0>&>(arr); };
swizzle_type<1, 1, 0, 1>& yyxy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 1>&>(arr); };
swizzle_type<1, 1, 0, 2>& yyxz() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 2>&>(arr); };
swizzle_type<1, 1, 0, 3>& yyxw() noexcept { return reinterpret_cast<swizzle_type<1, 1, 0, 3>&>(arr); };
swizzle_type<1, 1, 1, 0>& yyyx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1, 1>& yyyy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 1>&>(arr); };
swizzle_type<1, 1, 1, 2>& yyyz() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 2>&>(arr); };
swizzle_type<1, 1, 1, 3>& yyyw() noexcept { return reinterpret_cast<swizzle_type<1, 1, 1, 3>&>(arr); };
swizzle_type<1, 1, 2, 0>& yyzx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 0>&>(arr); };
swizzle_type<1, 1, 2, 1>& yyzy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 1>&>(arr); };
swizzle_type<1, 1, 2, 2>& yyzz() noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 2>&>(arr); };
swizzle_type<1, 1, 2, 3>& yyzw() noexcept { return reinterpret_cast<swizzle_type<1, 1, 2, 3>&>(arr); };
swizzle_type<1, 1, 3, 0>& yywx() noexcept { return reinterpret_cast<swizzle_type<1, 1, 3, 0>&>(arr); };
swizzle_type<1, 1, 3, 1>& yywy() noexcept { return reinterpret_cast<swizzle_type<1, 1, 3, 1>&>(arr); };
swizzle_type<1, 1, 3, 2>& yywz() noexcept { return reinterpret_cast<swizzle_type<1, 1, 3, 2>&>(arr); };
swizzle_type<1, 1, 3, 3>& yyww() noexcept { return reinterpret_cast<swizzle_type<1, 1, 3, 3>&>(arr); };
swizzle_type<1, 2, 0, 0>& yzxx() noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 0>&>(arr); };
swizzle_type<1, 2, 0, 1>& yzxy() noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 1>&>(arr); };
swizzle_type<1, 2, 0, 2>& yzxz() noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 2>&>(arr); };
swizzle_type<1, 2, 0, 3>& yzxw() noexcept { return reinterpret_cast<swizzle_type<1, 2, 0, 3>&>(arr); };
swizzle_type<1, 2, 1, 0>& yzyx() noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 0>&>(arr); };
swizzle_type<1, 2, 1, 1>& yzyy() noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 1>&>(arr); };
swizzle_type<1, 2, 1, 2>& yzyz() noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 2>&>(arr); };
swizzle_type<1, 2, 1, 3>& yzyw() noexcept { return reinterpret_cast<swizzle_type<1, 2, 1, 3>&>(arr); };
swizzle_type<1, 2, 2, 0>& yzzx() noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 0>&>(arr); };
swizzle_type<1, 2, 2, 1>& yzzy() noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 1>&>(arr); };
swizzle_type<1, 2, 2, 2>& yzzz() noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 2>&>(arr); };
swizzle_type<1, 2, 2, 3>& yzzw() noexcept { return reinterpret_cast<swizzle_type<1, 2, 2, 3>&>(arr); };
swizzle_type<1, 2, 3, 0>& yzwx() noexcept { return reinterpret_cast<swizzle_type<1, 2, 3, 0>&>(arr); };
swizzle_type<1, 2, 3, 1>& yzwy() noexcept { return reinterpret_cast<swizzle_type<1, 2, 3, 1>&>(arr); };
swizzle_type<1, 2, 3, 2>& yzwz() noexcept { return reinterpret_cast<swizzle_type<1, 2, 3, 2>&>(arr); };
swizzle_type<1, 2, 3, 3>& yzww() noexcept { return reinterpret_cast<swizzle_type<1, 2, 3, 3>&>(arr); };
swizzle_type<1, 3, 0, 0>& ywxx() noexcept { return reinterpret_cast<swizzle_type<1, 3, 0, 0>&>(arr); };
swizzle_type<1, 3, 0, 1>& ywxy() noexcept { return reinterpret_cast<swizzle_type<1, 3, 0, 1>&>(arr); };
swizzle_type<1, 3, 0, 2>& ywxz() noexcept { return reinterpret_cast<swizzle_type<1, 3, 0, 2>&>(arr); };
swizzle_type<1, 3, 0, 3>& ywxw() noexcept { return reinterpret_cast<swizzle_type<1, 3, 0, 3>&>(arr); };
swizzle_type<1, 3, 1, 0>& ywyx() noexcept { return reinterpret_cast<swizzle_type<1, 3, 1, 0>&>(arr); };
swizzle_type<1, 3, 1, 1>& ywyy() noexcept { return reinterpret_cast<swizzle_type<1, 3, 1, 1>&>(arr); };
swizzle_type<1, 3, 1, 2>& ywyz() noexcept { return reinterpret_cast<swizzle_type<1, 3, 1, 2>&>(arr); };
swizzle_type<1, 3, 1, 3>& ywyw() noexcept { return reinterpret_cast<swizzle_type<1, 3, 1, 3>&>(arr); };
swizzle_type<1, 3, 2, 0>& ywzx() noexcept { return reinterpret_cast<swizzle_type<1, 3, 2, 0>&>(arr); };
swizzle_type<1, 3, 2, 1>& ywzy() noexcept { return reinterpret_cast<swizzle_type<1, 3, 2, 1>&>(arr); };
swizzle_type<1, 3, 2, 2>& ywzz() noexcept { return reinterpret_cast<swizzle_type<1, 3, 2, 2>&>(arr); };
swizzle_type<1, 3, 2, 3>& ywzw() noexcept { return reinterpret_cast<swizzle_type<1, 3, 2, 3>&>(arr); };
swizzle_type<1, 3, 3, 0>& ywwx() noexcept { return reinterpret_cast<swizzle_type<1, 3, 3, 0>&>(arr); };
swizzle_type<1, 3, 3, 1>& ywwy() noexcept { return reinterpret_cast<swizzle_type<1, 3, 3, 1>&>(arr); };
swizzle_type<1, 3, 3, 2>& ywwz() noexcept { return reinterpret_cast<swizzle_type<1, 3, 3, 2>&>(arr); };
swizzle_type<1, 3, 3, 3>& ywww() noexcept { return reinterpret_cast<swizzle_type<1, 3, 3, 3>&>(arr); };
swizzle_type<2, 0, 0, 0>& zxxx() noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 0>&>(arr); };
swizzle_type<2, 0, 0, 1>& zxxy() noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 1>&>(arr); };
swizzle_type<2, 0, 0, 2>& zxxz() noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 2>&>(arr); };
swizzle_type<2, 0, 0, 3>& zxxw() noexcept { return reinterpret_cast<swizzle_type<2, 0, 0, 3>&>(arr); };
swizzle_type<2, 0, 1, 0>& zxyx() noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 0>&>(arr); };
swizzle_type<2, 0, 1, 1>& zxyy() noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 1>&>(arr); };
swizzle_type<2, 0, 1, 2>& zxyz() noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 2>&>(arr); };
swizzle_type<2, 0, 1, 3>& zxyw() noexcept { return reinterpret_cast<swizzle_type<2, 0, 1, 3>&>(arr); };
swizzle_type<2, 0, 2, 0>& zxzx() noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 0>&>(arr); };
swizzle_type<2, 0, 2, 1>& zxzy() noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 1>&>(arr); };
swizzle_type<2, 0, 2, 2>& zxzz() noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 2>&>(arr); };
swizzle_type<2, 0, 2, 3>& zxzw() noexcept { return reinterpret_cast<swizzle_type<2, 0, 2, 3>&>(arr); };
swizzle_type<2, 0, 3, 0>& zxwx() noexcept { return reinterpret_cast<swizzle_type<2, 0, 3, 0>&>(arr); };
swizzle_type<2, 0, 3, 1>& zxwy() noexcept { return reinterpret_cast<swizzle_type<2, 0, 3, 1>&>(arr); };
swizzle_type<2, 0, 3, 2>& zxwz() noexcept { return reinterpret_cast<swizzle_type<2, 0, 3, 2>&>(arr); };
swizzle_type<2, 0, 3, 3>& zxww() noexcept { return reinterpret_cast<swizzle_type<2, 0, 3, 3>&>(arr); };
swizzle_type<2, 1, 0, 0>& zyxx() noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 0>&>(arr); };
swizzle_type<2, 1, 0, 1>& zyxy() noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 1>&>(arr); };
swizzle_type<2, 1, 0, 2>& zyxz() noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 2>&>(arr); };
swizzle_type<2, 1, 0, 3>& zyxw() noexcept { return reinterpret_cast<swizzle_type<2, 1, 0, 3>&>(arr); };
swizzle_type<2, 1, 1, 0>& zyyx() noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 0>&>(arr); };
swizzle_type<2, 1, 1, 1>& zyyy() noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 1>&>(arr); };
swizzle_type<2, 1, 1, 2>& zyyz() noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 2>&>(arr); };
swizzle_type<2, 1, 1, 3>& zyyw() noexcept { return reinterpret_cast<swizzle_type<2, 1, 1, 3>&>(arr); };
swizzle_type<2, 1, 2, 0>& zyzx() noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 0>&>(arr); };
swizzle_type<2, 1, 2, 1>& zyzy() noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 1>&>(arr); };
swizzle_type<2, 1, 2, 2>& zyzz() noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 2>&>(arr); };
swizzle_type<2, 1, 2, 3>& zyzw() noexcept { return reinterpret_cast<swizzle_type<2, 1, 2, 3>&>(arr); };
swizzle_type<2, 1, 3, 0>& zywx() noexcept { return reinterpret_cast<swizzle_type<2, 1, 3, 0>&>(arr); };
swizzle_type<2, 1, 3, 1>& zywy() noexcept { return reinterpret_cast<swizzle_type<2, 1, 3, 1>&>(arr); };
swizzle_type<2, 1, 3, 2>& zywz() noexcept { return reinterpret_cast<swizzle_type<2, 1, 3, 2>&>(arr); };
swizzle_type<2, 1, 3, 3>& zyww() noexcept { return reinterpret_cast<swizzle_type<2, 1, 3, 3>&>(arr); };
swizzle_type<2, 2, 0, 0>& zzxx() noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 0>&>(arr); };
swizzle_type<2, 2, 0, 1>& zzxy() noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 1>&>(arr); };
swizzle_type<2, 2, 0, 2>& zzxz() noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 2>&>(arr); };
swizzle_type<2, 2, 0, 3>& zzxw() noexcept { return reinterpret_cast<swizzle_type<2, 2, 0, 3>&>(arr); };
swizzle_type<2, 2, 1, 0>& zzyx() noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 0>&>(arr); };
swizzle_type<2, 2, 1, 1>& zzyy() noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 1>&>(arr); };
swizzle_type<2, 2, 1, 2>& zzyz() noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 2>&>(arr); };
swizzle_type<2, 2, 1, 3>& zzyw() noexcept { return reinterpret_cast<swizzle_type<2, 2, 1, 3>&>(arr); };
swizzle_type<2, 2, 2, 0>& zzzx() noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 0>&>(arr); };
swizzle_type<2, 2, 2, 1>& zzzy() noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 1>&>(arr); };
swizzle_type<2, 2, 2, 2>& zzzz() noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 2>&>(arr); };
swizzle_type<2, 2, 2, 3>& zzzw() noexcept { return reinterpret_cast<swizzle_type<2, 2, 2, 3>&>(arr); };
swizzle_type<2, 2, 3, 0>& zzwx() noexcept { return reinterpret_cast<swizzle_type<2, 2, 3, 0>&>(arr); };
swizzle_type<2, 2, 3, 1>& zzwy() noexcept { return reinterpret_cast<swizzle_type<2, 2, 3, 1>&>(arr); };
swizzle_type<2, 2, 3, 2>& zzwz() noexcept { return reinterpret_cast<swizzle_type<2, 2, 3, 2>&>(arr); };
swizzle_type<2, 2, 3, 3>& zzww() noexcept { return reinterpret_cast<swizzle_type<2, 2, 3, 3>&>(arr); };
swizzle_type<2, 3, 0, 0>& zwxx() noexcept { return reinterpret_cast<swizzle_type<2, 3, 0, 0>&>(arr); };
swizzle_type<2, 3, 0, 1>& zwxy() noexcept { return reinterpret_cast<swizzle_type<2, 3, 0, 1>&>(arr); };
swizzle_type<2, 3, 0, 2>& zwxz() noexcept { return reinterpret_cast<swizzle_type<2, 3, 0, 2>&>(arr); };
swizzle_type<2, 3, 0, 3>& zwxw() noexcept { return reinterpret_cast<swizzle_type<2, 3, 0, 3>&>(arr); };
swizzle_type<2, 3, 1, 0>& zwyx() noexcept { return reinterpret_cast<swizzle_type<2, 3, 1, 0>&>(arr); };
swizzle_type<2, 3, 1, 1>& zwyy() noexcept { return reinterpret_cast<swizzle_type<2, 3, 1, 1>&>(arr); };
swizzle_type<2, 3, 1, 2>& zwyz() noexcept { return reinterpret_cast<swizzle_type<2, 3, 1, 2>&>(arr); };
swizzle_type<2, 3, 1, 3>& zwyw() noexcept { return reinterpret_cast<swizzle_type<2, 3, 1, 3>&>(arr); };
swizzle_type<2, 3, 2, 0>& zwzx() noexcept { return reinterpret_cast<swizzle_type<2, 3, 2, 0>&>(arr); };
swizzle_type<2, 3, 2, 1>& zwzy() noexcept { return reinterpret_cast<swizzle_type<2, 3, 2, 1>&>(arr); };
swizzle_type<2, 3, 2, 2>& zwzz() noexcept { return reinterpret_cast<swizzle_type<2, 3, 2, 2>&>(arr); };
swizzle_type<2, 3, 2, 3>& zwzw() noexcept { return reinterpret_cast<swizzle_type<2, 3, 2, 3>&>(arr); };
swizzle_type<2, 3, 3, 0>& zwwx() noexcept { return reinterpret_cast<swizzle_type<2, 3, 3, 0>&>(arr); };
swizzle_type<2, 3, 3, 1>& zwwy() noexcept { return reinterpret_cast<swizzle_type<2, 3, 3, 1>&>(arr); };
swizzle_type<2, 3, 3, 2>& zwwz() noexcept { return reinterpret_cast<swizzle_type<2, 3, 3, 2>&>(arr); };
swizzle_type<2, 3, 3, 3>& zwww() noexcept { return reinterpret_cast<swizzle_type<2, 3, 3, 3>&>(arr); };
swizzle_type<3, 0, 0, 0>& wxxx() noexcept { return reinterpret_cast<swizzle_type<3, 0, 0, 0>&>(arr); };
swizzle_type<3, 0, 0, 1>& wxxy() noexcept { return reinterpret_cast<swizzle_type<3, 0, 0, 1>&>(arr); };
swizzle_type<3, 0, 0, 2>& wxxz() noexcept { return reinterpret_cast<swizzle_type<3, 0, 0, 2>&>(arr); };
swizzle_type<3, 0, 0, 3>& wxxw() noexcept { return reinterpret_cast<swizzle_type<3, 0, 0, 3>&>(arr); };
swizzle_type<3, 0, 1, 0>& wxyx() noexcept { return reinterpret_cast<swizzle_type<3, 0, 1, 0>&>(arr); };
swizzle_type<3, 0, 1, 1>& wxyy() noexcept { return reinterpret_cast<swizzle_type<3, 0, 1, 1>&>(arr); };
swizzle_type<3, 0, 1, 2>& wxyz() noexcept { return reinterpret_cast<swizzle_type<3, 0, 1, 2>&>(arr); };
swizzle_type<3, 0, 1, 3>& wxyw() noexcept { return reinterpret_cast<swizzle_type<3, 0, 1, 3>&>(arr); };
swizzle_type<3, 0, 2, 0>& wxzx() noexcept { return reinterpret_cast<swizzle_type<3, 0, 2, 0>&>(arr); };
swizzle_type<3, 0, 2, 1>& wxzy() noexcept { return reinterpret_cast<swizzle_type<3, 0, 2, 1>&>(arr); };
swizzle_type<3, 0, 2, 2>& wxzz() noexcept { return reinterpret_cast<swizzle_type<3, 0, 2, 2>&>(arr); };
swizzle_type<3, 0, 2, 3>& wxzw() noexcept { return reinterpret_cast<swizzle_type<3, 0, 2, 3>&>(arr); };
swizzle_type<3, 0, 3, 0>& wxwx() noexcept { return reinterpret_cast<swizzle_type<3, 0, 3, 0>&>(arr); };
swizzle_type<3, 0, 3, 1>& wxwy() noexcept { return reinterpret_cast<swizzle_type<3, 0, 3, 1>&>(arr); };
swizzle_type<3, 0, 3, 2>& wxwz() noexcept { return reinterpret_cast<swizzle_type<3, 0, 3, 2>&>(arr); };
swizzle_type<3, 0, 3, 3>& wxww() noexcept { return reinterpret_cast<swizzle_type<3, 0, 3, 3>&>(arr); };
swizzle_type<3, 1, 0, 0>& wyxx() noexcept { return reinterpret_cast<swizzle_type<3, 1, 0, 0>&>(arr); };
swizzle_type<3, 1, 0, 1>& wyxy() noexcept { return reinterpret_cast<swizzle_type<3, 1, 0, 1>&>(arr); };
swizzle_type<3, 1, 0, 2>& wyxz() noexcept { return reinterpret_cast<swizzle_type<3, 1, 0, 2>&>(arr); };
swizzle_type<3, 1, 0, 3>& wyxw() noexcept { return reinterpret_cast<swizzle_type<3, 1, 0, 3>&>(arr); };
swizzle_type<3, 1, 1, 0>& wyyx() noexcept { return reinterpret_cast<swizzle_type<3, 1, 1, 0>&>(arr); };
swizzle_type<3, 1, 1, 1>& wyyy() noexcept { return reinterpret_cast<swizzle_type<3, 1, 1, 1>&>(arr); };
swizzle_type<3, 1, 1, 2>& wyyz() noexcept { return reinterpret_cast<swizzle_type<3, 1, 1, 2>&>(arr); };
swizzle_type<3, 1, 1, 3>& wyyw() noexcept { return reinterpret_cast<swizzle_type<3, 1, 1, 3>&>(arr); };
swizzle_type<3, 1, 2, 0>& wyzx() noexcept { return reinterpret_cast<swizzle_type<3, 1, 2, 0>&>(arr); };
swizzle_type<3, 1, 2, 1>& wyzy() noexcept { return reinterpret_cast<swizzle_type<3, 1, 2, 1>&>(arr); };
swizzle_type<3, 1, 2, 2>& wyzz() noexcept { return reinterpret_cast<swizzle_type<3, 1, 2, 2>&>(arr); };
swizzle_type<3, 1, 2, 3>& wyzw() noexcept { return reinterpret_cast<swizzle_type<3, 1, 2, 3>&>(arr); };
swizzle_type<3, 1, 3, 0>& wywx() noexcept { return reinterpret_cast<swizzle_type<3, 1, 3, 0>&>(arr); };
swizzle_type<3, 1, 3, 1>& wywy() noexcept { return reinterpret_cast<swizzle_type<3, 1, 3, 1>&>(arr); };
swizzle_type<3, 1, 3, 2>& wywz() noexcept { return reinterpret_cast<swizzle_type<3, 1, 3, 2>&>(arr); };
swizzle_type<3, 1, 3, 3>& wyww() noexcept { return reinterpret_cast<swizzle_type<3, 1, 3, 3>&>(arr); };
swizzle_type<3, 2, 0, 0>& wzxx() noexcept { return reinterpret_cast<swizzle_type<3, 2, 0, 0>&>(arr); };
swizzle_type<3, 2, 0, 1>& wzxy() noexcept { return reinterpret_cast<swizzle_type<3, 2, 0, 1>&>(arr); };
swizzle_type<3, 2, 0, 2>& wzxz() noexcept { return reinterpret_cast<swizzle_type<3, 2, 0, 2>&>(arr); };
swizzle_type<3, 2, 0, 3>& wzxw() noexcept { return reinterpret_cast<swizzle_type<3, 2, 0, 3>&>(arr); };
swizzle_type<3, 2, 1, 0>& wzyx() noexcept { return reinterpret_cast<swizzle_type<3, 2, 1, 0>&>(arr); };
swizzle_type<3, 2, 1, 1>& wzyy() noexcept { return reinterpret_cast<swizzle_type<3, 2, 1, 1>&>(arr); };
swizzle_type<3, 2, 1, 2>& wzyz() noexcept { return reinterpret_cast<swizzle_type<3, 2, 1, 2>&>(arr); };
swizzle_type<3, 2, 1, 3>& wzyw() noexcept { return reinterpret_cast<swizzle_type<3, 2, 1, 3>&>(arr); };
swizzle_type<3, 2, 2, 0>& wzzx() noexcept { return reinterpret_cast<swizzle_type<3, 2, 2, 0>&>(arr); };
swizzle_type<3, 2, 2, 1>& wzzy() noexcept { return reinterpret_cast<swizzle_type<3, 2, 2, 1>&>(arr); };
swizzle_type<3, 2, 2, 2>& wzzz() noexcept { return reinterpret_cast<swizzle_type<3, 2, 2, 2>&>(arr); };
swizzle_type<3, 2, 2, 3>& wzzw() noexcept { return reinterpret_cast<swizzle_type<3, 2, 2, 3>&>(arr); };
swizzle_type<3, 2, 3, 0>& wzwx() noexcept { return reinterpret_cast<swizzle_type<3, 2, 3, 0>&>(arr); };
swizzle_type<3, 2, 3, 1>& wzwy() noexcept { return reinterpret_cast<swizzle_type<3, 2, 3, 1>&>(arr); };
swizzle_type<3, 2, 3, 2>& wzwz() noexcept { return reinterpret_cast<swizzle_type<3, 2, 3, 2>&>(arr); };
swizzle_type<3, 2, 3, 3>& wzww() noexcept { return reinterpret_cast<swizzle_type<3, 2, 3, 3>&>(arr); };
swizzle_type<3, 3, 0, 0>& wwxx() noexcept { return reinterpret_cast<swizzle_type<3, 3, 0, 0>&>(arr); };
swizzle_type<3, 3, 0, 1>& wwxy() noexcept { return reinterpret_cast<swizzle_type<3, 3, 0, 1>&>(arr); };
swizzle_type<3, 3, 0, 2>& wwxz() noexcept { return reinterpret_cast<swizzle_type<3, 3, 0, 2>&>(arr); };
swizzle_type<3, 3, 0, 3>& wwxw() noexcept { return reinterpret_cast<swizzle_type<3, 3, 0, 3>&>(arr); };
swizzle_type<3, 3, 1, 0>& wwyx() noexcept { return reinterpret_cast<swizzle_type<3, 3, 1, 0>&>(arr); };
swizzle_type<3, 3, 1, 1>& wwyy() noexcept { return reinterpret_cast<swizzle_type<3, 3, 1, 1>&>(arr); };
swizzle_type<3, 3, 1, 2>& wwyz() noexcept { return reinterpret_cast<swizzle_type<3, 3, 1, 2>&>(arr); };
swizzle_type<3, 3, 1, 3>& wwyw() noexcept { return reinterpret_cast<swizzle_type<3, 3, 1, 3>&>(arr); };
swizzle_type<3, 3, 2, 0>& wwzx() noexcept { return reinterpret_cast<swizzle_type<3, 3, 2, 0>&>(arr); };
swizzle_type<3, 3, 2, 1>& wwzy() noexcept { return reinterpret_cast<swizzle_type<3, 3, 2, 1>&>(arr); };
swizzle_type<3, 3, 2, 2>& wwzz() noexcept { return reinterpret_cast<swizzle_type<3, 3, 2, 2>&>(arr); };
swizzle_type<3, 3, 2, 3>& wwzw() noexcept { return reinterpret_cast<swizzle_type<3, 3, 2, 3>&>(arr); };
swizzle_type<3, 3, 3, 0>& wwwx() noexcept { return reinterpret_cast<swizzle_type<3, 3, 3, 0>&>(arr); };
swizzle_type<3, 3, 3, 1>& wwwy() noexcept { return reinterpret_cast<swizzle_type<3, 3, 3, 1>&>(arr); };
swizzle_type<3, 3, 3, 2>& wwwz() noexcept { return reinterpret_cast<swizzle_type<3, 3, 3, 2>&>(arr); };
swizzle_type<3, 3, 3, 3>& wwww() noexcept { return reinterpret_cast<swizzle_type<3, 3, 3, 3>&>(arr); };
auto xxxx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 0, 0>&>(arr).to_vec(); };
auto xxxy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 0, 1>&>(arr).to_vec(); };
auto xxxz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 0, 2>&>(arr).to_vec(); };
auto xxxw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 0, 3>&>(arr).to_vec(); };
auto xxyx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 1, 0>&>(arr).to_vec(); };
auto xxyy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 1, 1>&>(arr).to_vec(); };
auto xxyz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 1, 2>&>(arr).to_vec(); };
auto xxyw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 1, 3>&>(arr).to_vec(); };
auto xxzx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 2, 0>&>(arr).to_vec(); };
auto xxzy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 2, 1>&>(arr).to_vec(); };
auto xxzz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 2, 2>&>(arr).to_vec(); };
auto xxzw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 2, 3>&>(arr).to_vec(); };
auto xxwx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 3, 0>&>(arr).to_vec(); };
auto xxwy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 3, 1>&>(arr).to_vec(); };
auto xxwz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 3, 2>&>(arr).to_vec(); };
auto xxww_() const noexcept { return reinterpret_cast<const swizzle_type<0, 0, 3, 3>&>(arr).to_vec(); };
auto xyxx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 0, 0>&>(arr).to_vec(); };
auto xyxy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 0, 1>&>(arr).to_vec(); };
auto xyxz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 0, 2>&>(arr).to_vec(); };
auto xyxw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 0, 3>&>(arr).to_vec(); };
auto xyyx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 1, 0>&>(arr).to_vec(); };
auto xyyy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 1, 1>&>(arr).to_vec(); };
auto xyyz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 1, 2>&>(arr).to_vec(); };
auto xyyw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 1, 3>&>(arr).to_vec(); };
auto xyzx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 2, 0>&>(arr).to_vec(); };
auto xyzy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 2, 1>&>(arr).to_vec(); };
auto xyzz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 2, 2>&>(arr).to_vec(); };
auto xyzw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 2, 3>&>(arr).to_vec(); };
auto xywx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 3, 0>&>(arr).to_vec(); };
auto xywy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 3, 1>&>(arr).to_vec(); };
auto xywz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 3, 2>&>(arr).to_vec(); };
auto xyww_() const noexcept { return reinterpret_cast<const swizzle_type<0, 1, 3, 3>&>(arr).to_vec(); };
auto xzxx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 0, 0>&>(arr).to_vec(); };
auto xzxy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 0, 1>&>(arr).to_vec(); };
auto xzxz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 0, 2>&>(arr).to_vec(); };
auto xzxw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 0, 3>&>(arr).to_vec(); };
auto xzyx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 1, 0>&>(arr).to_vec(); };
auto xzyy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 1, 1>&>(arr).to_vec(); };
auto xzyz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 1, 2>&>(arr).to_vec(); };
auto xzyw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 1, 3>&>(arr).to_vec(); };
auto xzzx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 2, 0>&>(arr).to_vec(); };
auto xzzy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 2, 1>&>(arr).to_vec(); };
auto xzzz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 2, 2>&>(arr).to_vec(); };
auto xzzw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 2, 3>&>(arr).to_vec(); };
auto xzwx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 3, 0>&>(arr).to_vec(); };
auto xzwy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 3, 1>&>(arr).to_vec(); };
auto xzwz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 3, 2>&>(arr).to_vec(); };
auto xzww_() const noexcept { return reinterpret_cast<const swizzle_type<0, 2, 3, 3>&>(arr).to_vec(); };
auto xwxx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 0, 0>&>(arr).to_vec(); };
auto xwxy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 0, 1>&>(arr).to_vec(); };
auto xwxz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 0, 2>&>(arr).to_vec(); };
auto xwxw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 0, 3>&>(arr).to_vec(); };
auto xwyx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 1, 0>&>(arr).to_vec(); };
auto xwyy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 1, 1>&>(arr).to_vec(); };
auto xwyz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 1, 2>&>(arr).to_vec(); };
auto xwyw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 1, 3>&>(arr).to_vec(); };
auto xwzx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 2, 0>&>(arr).to_vec(); };
auto xwzy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 2, 1>&>(arr).to_vec(); };
auto xwzz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 2, 2>&>(arr).to_vec(); };
auto xwzw_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 2, 3>&>(arr).to_vec(); };
auto xwwx_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 3, 0>&>(arr).to_vec(); };
auto xwwy_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 3, 1>&>(arr).to_vec(); };
auto xwwz_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 3, 2>&>(arr).to_vec(); };
auto xwww_() const noexcept { return reinterpret_cast<const swizzle_type<0, 3, 3, 3>&>(arr).to_vec(); };
auto yxxx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 0, 0>&>(arr).to_vec(); };
auto yxxy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 0, 1>&>(arr).to_vec(); };
auto yxxz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 0, 2>&>(arr).to_vec(); };
auto yxxw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 0, 3>&>(arr).to_vec(); };
auto yxyx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 1, 0>&>(arr).to_vec(); };
auto yxyy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 1, 1>&>(arr).to_vec(); };
auto yxyz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 1, 2>&>(arr).to_vec(); };
auto yxyw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 1, 3>&>(arr).to_vec(); };
auto yxzx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 2, 0>&>(arr).to_vec(); };
auto yxzy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 2, 1>&>(arr).to_vec(); };
auto yxzz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 2, 2>&>(arr).to_vec(); };
auto yxzw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 2, 3>&>(arr).to_vec(); };
auto yxwx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 3, 0>&>(arr).to_vec(); };
auto yxwy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 3, 1>&>(arr).to_vec(); };
auto yxwz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 3, 2>&>(arr).to_vec(); };
auto yxww_() const noexcept { return reinterpret_cast<const swizzle_type<1, 0, 3, 3>&>(arr).to_vec(); };
auto yyxx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 0, 0>&>(arr).to_vec(); };
auto yyxy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 0, 1>&>(arr).to_vec(); };
auto yyxz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 0, 2>&>(arr).to_vec(); };
auto yyxw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 0, 3>&>(arr).to_vec(); };
auto yyyx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 1, 0>&>(arr).to_vec(); };
auto yyyy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 1, 1>&>(arr).to_vec(); };
auto yyyz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 1, 2>&>(arr).to_vec(); };
auto yyyw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 1, 3>&>(arr).to_vec(); };
auto yyzx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 2, 0>&>(arr).to_vec(); };
auto yyzy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 2, 1>&>(arr).to_vec(); };
auto yyzz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 2, 2>&>(arr).to_vec(); };
auto yyzw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 2, 3>&>(arr).to_vec(); };
auto yywx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 3, 0>&>(arr).to_vec(); };
auto yywy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 3, 1>&>(arr).to_vec(); };
auto yywz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 3, 2>&>(arr).to_vec(); };
auto yyww_() const noexcept { return reinterpret_cast<const swizzle_type<1, 1, 3, 3>&>(arr).to_vec(); };
auto yzxx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 0, 0>&>(arr).to_vec(); };
auto yzxy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 0, 1>&>(arr).to_vec(); };
auto yzxz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 0, 2>&>(arr).to_vec(); };
auto yzxw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 0, 3>&>(arr).to_vec(); };
auto yzyx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 1, 0>&>(arr).to_vec(); };
auto yzyy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 1, 1>&>(arr).to_vec(); };
auto yzyz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 1, 2>&>(arr).to_vec(); };
auto yzyw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 1, 3>&>(arr).to_vec(); };
auto yzzx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 2, 0>&>(arr).to_vec(); };
auto yzzy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 2, 1>&>(arr).to_vec(); };
auto yzzz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 2, 2>&>(arr).to_vec(); };
auto yzzw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 2, 3>&>(arr).to_vec(); };
auto yzwx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 3, 0>&>(arr).to_vec(); };
auto yzwy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 3, 1>&>(arr).to_vec(); };
auto yzwz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 3, 2>&>(arr).to_vec(); };
auto yzww_() const noexcept { return reinterpret_cast<const swizzle_type<1, 2, 3, 3>&>(arr).to_vec(); };
auto ywxx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 0, 0>&>(arr).to_vec(); };
auto ywxy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 0, 1>&>(arr).to_vec(); };
auto ywxz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 0, 2>&>(arr).to_vec(); };
auto ywxw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 0, 3>&>(arr).to_vec(); };
auto ywyx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 1, 0>&>(arr).to_vec(); };
auto ywyy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 1, 1>&>(arr).to_vec(); };
auto ywyz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 1, 2>&>(arr).to_vec(); };
auto ywyw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 1, 3>&>(arr).to_vec(); };
auto ywzx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 2, 0>&>(arr).to_vec(); };
auto ywzy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 2, 1>&>(arr).to_vec(); };
auto ywzz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 2, 2>&>(arr).to_vec(); };
auto ywzw_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 2, 3>&>(arr).to_vec(); };
auto ywwx_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 3, 0>&>(arr).to_vec(); };
auto ywwy_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 3, 1>&>(arr).to_vec(); };
auto ywwz_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 3, 2>&>(arr).to_vec(); };
auto ywww_() const noexcept { return reinterpret_cast<const swizzle_type<1, 3, 3, 3>&>(arr).to_vec(); };
auto zxxx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 0, 0>&>(arr).to_vec(); };
auto zxxy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 0, 1>&>(arr).to_vec(); };
auto zxxz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 0, 2>&>(arr).to_vec(); };
auto zxxw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 0, 3>&>(arr).to_vec(); };
auto zxyx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 1, 0>&>(arr).to_vec(); };
auto zxyy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 1, 1>&>(arr).to_vec(); };
auto zxyz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 1, 2>&>(arr).to_vec(); };
auto zxyw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 1, 3>&>(arr).to_vec(); };
auto zxzx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 2, 0>&>(arr).to_vec(); };
auto zxzy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 2, 1>&>(arr).to_vec(); };
auto zxzz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 2, 2>&>(arr).to_vec(); };
auto zxzw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 2, 3>&>(arr).to_vec(); };
auto zxwx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 3, 0>&>(arr).to_vec(); };
auto zxwy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 3, 1>&>(arr).to_vec(); };
auto zxwz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 3, 2>&>(arr).to_vec(); };
auto zxww_() const noexcept { return reinterpret_cast<const swizzle_type<2, 0, 3, 3>&>(arr).to_vec(); };
auto zyxx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 0, 0>&>(arr).to_vec(); };
auto zyxy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 0, 1>&>(arr).to_vec(); };
auto zyxz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 0, 2>&>(arr).to_vec(); };
auto zyxw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 0, 3>&>(arr).to_vec(); };
auto zyyx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 1, 0>&>(arr).to_vec(); };
auto zyyy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 1, 1>&>(arr).to_vec(); };
auto zyyz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 1, 2>&>(arr).to_vec(); };
auto zyyw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 1, 3>&>(arr).to_vec(); };
auto zyzx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 2, 0>&>(arr).to_vec(); };
auto zyzy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 2, 1>&>(arr).to_vec(); };
auto zyzz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 2, 2>&>(arr).to_vec(); };
auto zyzw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 2, 3>&>(arr).to_vec(); };
auto zywx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 3, 0>&>(arr).to_vec(); };
auto zywy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 3, 1>&>(arr).to_vec(); };
auto zywz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 3, 2>&>(arr).to_vec(); };
auto zyww_() const noexcept { return reinterpret_cast<const swizzle_type<2, 1, 3, 3>&>(arr).to_vec(); };
auto zzxx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 0, 0>&>(arr).to_vec(); };
auto zzxy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 0, 1>&>(arr).to_vec(); };
auto zzxz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 0, 2>&>(arr).to_vec(); };
auto zzxw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 0, 3>&>(arr).to_vec(); };
auto zzyx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 1, 0>&>(arr).to_vec(); };
auto zzyy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 1, 1>&>(arr).to_vec(); };
auto zzyz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 1, 2>&>(arr).to_vec(); };
auto zzyw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 1, 3>&>(arr).to_vec(); };
auto zzzx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 2, 0>&>(arr).to_vec(); };
auto zzzy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 2, 1>&>(arr).to_vec(); };
auto zzzz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 2, 2>&>(arr).to_vec(); };
auto zzzw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 2, 3>&>(arr).to_vec(); };
auto zzwx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 3, 0>&>(arr).to_vec(); };
auto zzwy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 3, 1>&>(arr).to_vec(); };
auto zzwz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 3, 2>&>(arr).to_vec(); };
auto zzww_() const noexcept { return reinterpret_cast<const swizzle_type<2, 2, 3, 3>&>(arr).to_vec(); };
auto zwxx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 0, 0>&>(arr).to_vec(); };
auto zwxy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 0, 1>&>(arr).to_vec(); };
auto zwxz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 0, 2>&>(arr).to_vec(); };
auto zwxw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 0, 3>&>(arr).to_vec(); };
auto zwyx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 1, 0>&>(arr).to_vec(); };
auto zwyy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 1, 1>&>(arr).to_vec(); };
auto zwyz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 1, 2>&>(arr).to_vec(); };
auto zwyw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 1, 3>&>(arr).to_vec(); };
auto zwzx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 2, 0>&>(arr).to_vec(); };
auto zwzy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 2, 1>&>(arr).to_vec(); };
auto zwzz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 2, 2>&>(arr).to_vec(); };
auto zwzw_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 2, 3>&>(arr).to_vec(); };
auto zwwx_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 3, 0>&>(arr).to_vec(); };
auto zwwy_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 3, 1>&>(arr).to_vec(); };
auto zwwz_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 3, 2>&>(arr).to_vec(); };
auto zwww_() const noexcept { return reinterpret_cast<const swizzle_type<2, 3, 3, 3>&>(arr).to_vec(); };
auto wxxx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 0, 0>&>(arr).to_vec(); };
auto wxxy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 0, 1>&>(arr).to_vec(); };
auto wxxz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 0, 2>&>(arr).to_vec(); };
auto wxxw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 0, 3>&>(arr).to_vec(); };
auto wxyx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 1, 0>&>(arr).to_vec(); };
auto wxyy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 1, 1>&>(arr).to_vec(); };
auto wxyz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 1, 2>&>(arr).to_vec(); };
auto wxyw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 1, 3>&>(arr).to_vec(); };
auto wxzx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 2, 0>&>(arr).to_vec(); };
auto wxzy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 2, 1>&>(arr).to_vec(); };
auto wxzz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 2, 2>&>(arr).to_vec(); };
auto wxzw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 2, 3>&>(arr).to_vec(); };
auto wxwx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 3, 0>&>(arr).to_vec(); };
auto wxwy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 3, 1>&>(arr).to_vec(); };
auto wxwz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 3, 2>&>(arr).to_vec(); };
auto wxww_() const noexcept { return reinterpret_cast<const swizzle_type<3, 0, 3, 3>&>(arr).to_vec(); };
auto wyxx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 0, 0>&>(arr).to_vec(); };
auto wyxy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 0, 1>&>(arr).to_vec(); };
auto wyxz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 0, 2>&>(arr).to_vec(); };
auto wyxw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 0, 3>&>(arr).to_vec(); };
auto wyyx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 1, 0>&>(arr).to_vec(); };
auto wyyy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 1, 1>&>(arr).to_vec(); };
auto wyyz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 1, 2>&>(arr).to_vec(); };
auto wyyw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 1, 3>&>(arr).to_vec(); };
auto wyzx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 2, 0>&>(arr).to_vec(); };
auto wyzy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 2, 1>&>(arr).to_vec(); };
auto wyzz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 2, 2>&>(arr).to_vec(); };
auto wyzw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 2, 3>&>(arr).to_vec(); };
auto wywx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 3, 0>&>(arr).to_vec(); };
auto wywy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 3, 1>&>(arr).to_vec(); };
auto wywz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 3, 2>&>(arr).to_vec(); };
auto wyww_() const noexcept { return reinterpret_cast<const swizzle_type<3, 1, 3, 3>&>(arr).to_vec(); };
auto wzxx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 0, 0>&>(arr).to_vec(); };
auto wzxy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 0, 1>&>(arr).to_vec(); };
auto wzxz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 0, 2>&>(arr).to_vec(); };
auto wzxw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 0, 3>&>(arr).to_vec(); };
auto wzyx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 1, 0>&>(arr).to_vec(); };
auto wzyy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 1, 1>&>(arr).to_vec(); };
auto wzyz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 1, 2>&>(arr).to_vec(); };
auto wzyw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 1, 3>&>(arr).to_vec(); };
auto wzzx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 2, 0>&>(arr).to_vec(); };
auto wzzy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 2, 1>&>(arr).to_vec(); };
auto wzzz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 2, 2>&>(arr).to_vec(); };
auto wzzw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 2, 3>&>(arr).to_vec(); };
auto wzwx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 3, 0>&>(arr).to_vec(); };
auto wzwy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 3, 1>&>(arr).to_vec(); };
auto wzwz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 3, 2>&>(arr).to_vec(); };
auto wzww_() const noexcept { return reinterpret_cast<const swizzle_type<3, 2, 3, 3>&>(arr).to_vec(); };
auto wwxx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 0, 0>&>(arr).to_vec(); };
auto wwxy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 0, 1>&>(arr).to_vec(); };
auto wwxz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 0, 2>&>(arr).to_vec(); };
auto wwxw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 0, 3>&>(arr).to_vec(); };
auto wwyx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 1, 0>&>(arr).to_vec(); };
auto wwyy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 1, 1>&>(arr).to_vec(); };
auto wwyz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 1, 2>&>(arr).to_vec(); };
auto wwyw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 1, 3>&>(arr).to_vec(); };
auto wwzx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 2, 0>&>(arr).to_vec(); };
auto wwzy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 2, 1>&>(arr).to_vec(); };
auto wwzz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 2, 2>&>(arr).to_vec(); };
auto wwzw_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 2, 3>&>(arr).to_vec(); };
auto wwwx_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 3, 0>&>(arr).to_vec(); };
auto wwwy_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 3, 1>&>(arr).to_vec(); };
auto wwwz_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 3, 2>&>(arr).to_vec(); };
auto wwww_() const noexcept { return reinterpret_cast<const swizzle_type<3, 3, 3, 3>&>(arr).to_vec(); };
