swizzle_type<0, 0>& xx() { return reinterpret_cast<swizzle_type<0, 0>&>(arr); };
swizzle_type<0, 1>& xy() { return reinterpret_cast<swizzle_type<0, 1>&>(arr); };
swizzle_type<0, 2>& xz() { return reinterpret_cast<swizzle_type<0, 2>&>(arr); };
swizzle_type<0, 3>& xw() { return reinterpret_cast<swizzle_type<0, 3>&>(arr); };
swizzle_type<1, 0>& yx() { return reinterpret_cast<swizzle_type<1, 0>&>(arr); };
swizzle_type<1, 1>& yy() { return reinterpret_cast<swizzle_type<1, 1>&>(arr); };
swizzle_type<1, 2>& yz() { return reinterpret_cast<swizzle_type<1, 2>&>(arr); };
swizzle_type<1, 3>& yw() { return reinterpret_cast<swizzle_type<1, 3>&>(arr); };
swizzle_type<2, 0>& zx() { return reinterpret_cast<swizzle_type<2, 0>&>(arr); };
swizzle_type<2, 1>& zy() { return reinterpret_cast<swizzle_type<2, 1>&>(arr); };
swizzle_type<2, 2>& zz() { return reinterpret_cast<swizzle_type<2, 2>&>(arr); };
swizzle_type<2, 3>& zw() { return reinterpret_cast<swizzle_type<2, 3>&>(arr); };
swizzle_type<3, 0>& wx() { return reinterpret_cast<swizzle_type<3, 0>&>(arr); };
swizzle_type<3, 1>& wy() { return reinterpret_cast<swizzle_type<3, 1>&>(arr); };
swizzle_type<3, 2>& wz() { return reinterpret_cast<swizzle_type<3, 2>&>(arr); };
swizzle_type<3, 3>& ww() { return reinterpret_cast<swizzle_type<3, 3>&>(arr); };

swizzle_type<0, 0, 0>& xxx() { return reinterpret_cast<swizzle_type<0, 0, 0>&>(arr); };
swizzle_type<0, 0, 1>& xxy() { return reinterpret_cast<swizzle_type<0, 0, 1>&>(arr); };
swizzle_type<0, 0, 2>& xxz() { return reinterpret_cast<swizzle_type<0, 0, 2>&>(arr); };
swizzle_type<0, 0, 3>& xxw() { return reinterpret_cast<swizzle_type<0, 0, 3>&>(arr); };
swizzle_type<0, 1, 0>& xyx() { return reinterpret_cast<swizzle_type<0, 1, 0>&>(arr); };
swizzle_type<0, 1, 1>& xyy() { return reinterpret_cast<swizzle_type<0, 1, 1>&>(arr); };
swizzle_type<0, 1, 2>& xyz() { return reinterpret_cast<swizzle_type<0, 1, 2>&>(arr); };
swizzle_type<0, 1, 3>& xyw() { return reinterpret_cast<swizzle_type<0, 1, 3>&>(arr); };
swizzle_type<0, 2, 0>& xzx() { return reinterpret_cast<swizzle_type<0, 2, 0>&>(arr); };
swizzle_type<0, 2, 1>& xzy() { return reinterpret_cast<swizzle_type<0, 2, 1>&>(arr); };
swizzle_type<0, 2, 2>& xzz() { return reinterpret_cast<swizzle_type<0, 2, 2>&>(arr); };
swizzle_type<0, 2, 3>& xzw() { return reinterpret_cast<swizzle_type<0, 2, 3>&>(arr); };
swizzle_type<0, 3, 0>& xwx() { return reinterpret_cast<swizzle_type<0, 3, 0>&>(arr); };
swizzle_type<0, 3, 1>& xwy() { return reinterpret_cast<swizzle_type<0, 3, 1>&>(arr); };
swizzle_type<0, 3, 2>& xwz() { return reinterpret_cast<swizzle_type<0, 3, 2>&>(arr); };
swizzle_type<0, 3, 3>& xww() { return reinterpret_cast<swizzle_type<0, 3, 3>&>(arr); };
swizzle_type<1, 0, 0>& yxx() { return reinterpret_cast<swizzle_type<1, 0, 0>&>(arr); };
swizzle_type<1, 0, 1>& yxy() { return reinterpret_cast<swizzle_type<1, 0, 1>&>(arr); };
swizzle_type<1, 0, 2>& yxz() { return reinterpret_cast<swizzle_type<1, 0, 2>&>(arr); };
swizzle_type<1, 0, 3>& yxw() { return reinterpret_cast<swizzle_type<1, 0, 3>&>(arr); };
swizzle_type<1, 1, 0>& yyx() { return reinterpret_cast<swizzle_type<1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1>& yyy() { return reinterpret_cast<swizzle_type<1, 1, 1>&>(arr); };
swizzle_type<1, 1, 2>& yyz() { return reinterpret_cast<swizzle_type<1, 1, 2>&>(arr); };
swizzle_type<1, 1, 3>& yyw() { return reinterpret_cast<swizzle_type<1, 1, 3>&>(arr); };
swizzle_type<1, 2, 0>& yzx() { return reinterpret_cast<swizzle_type<1, 2, 0>&>(arr); };
swizzle_type<1, 2, 1>& yzy() { return reinterpret_cast<swizzle_type<1, 2, 1>&>(arr); };
swizzle_type<1, 2, 2>& yzz() { return reinterpret_cast<swizzle_type<1, 2, 2>&>(arr); };
swizzle_type<1, 2, 3>& yzw() { return reinterpret_cast<swizzle_type<1, 2, 3>&>(arr); };
swizzle_type<1, 3, 0>& ywx() { return reinterpret_cast<swizzle_type<1, 3, 0>&>(arr); };
swizzle_type<1, 3, 1>& ywy() { return reinterpret_cast<swizzle_type<1, 3, 1>&>(arr); };
swizzle_type<1, 3, 2>& ywz() { return reinterpret_cast<swizzle_type<1, 3, 2>&>(arr); };
swizzle_type<1, 3, 3>& yww() { return reinterpret_cast<swizzle_type<1, 3, 3>&>(arr); };
swizzle_type<2, 0, 0>& zxx() { return reinterpret_cast<swizzle_type<2, 0, 0>&>(arr); };
swizzle_type<2, 0, 1>& zxy() { return reinterpret_cast<swizzle_type<2, 0, 1>&>(arr); };
swizzle_type<2, 0, 2>& zxz() { return reinterpret_cast<swizzle_type<2, 0, 2>&>(arr); };
swizzle_type<2, 0, 3>& zxw() { return reinterpret_cast<swizzle_type<2, 0, 3>&>(arr); };
swizzle_type<2, 1, 0>& zyx() { return reinterpret_cast<swizzle_type<2, 1, 0>&>(arr); };
swizzle_type<2, 1, 1>& zyy() { return reinterpret_cast<swizzle_type<2, 1, 1>&>(arr); };
swizzle_type<2, 1, 2>& zyz() { return reinterpret_cast<swizzle_type<2, 1, 2>&>(arr); };
swizzle_type<2, 1, 3>& zyw() { return reinterpret_cast<swizzle_type<2, 1, 3>&>(arr); };
swizzle_type<2, 2, 0>& zzx() { return reinterpret_cast<swizzle_type<2, 2, 0>&>(arr); };
swizzle_type<2, 2, 1>& zzy() { return reinterpret_cast<swizzle_type<2, 2, 1>&>(arr); };
swizzle_type<2, 2, 2>& zzz() { return reinterpret_cast<swizzle_type<2, 2, 2>&>(arr); };
swizzle_type<2, 2, 3>& zzw() { return reinterpret_cast<swizzle_type<2, 2, 3>&>(arr); };
swizzle_type<2, 3, 0>& zwx() { return reinterpret_cast<swizzle_type<2, 3, 0>&>(arr); };
swizzle_type<2, 3, 1>& zwy() { return reinterpret_cast<swizzle_type<2, 3, 1>&>(arr); };
swizzle_type<2, 3, 2>& zwz() { return reinterpret_cast<swizzle_type<2, 3, 2>&>(arr); };
swizzle_type<2, 3, 3>& zww() { return reinterpret_cast<swizzle_type<2, 3, 3>&>(arr); };
swizzle_type<3, 0, 0>& wxx() { return reinterpret_cast<swizzle_type<3, 0, 0>&>(arr); };
swizzle_type<3, 0, 1>& wxy() { return reinterpret_cast<swizzle_type<3, 0, 1>&>(arr); };
swizzle_type<3, 0, 2>& wxz() { return reinterpret_cast<swizzle_type<3, 0, 2>&>(arr); };
swizzle_type<3, 0, 3>& wxw() { return reinterpret_cast<swizzle_type<3, 0, 3>&>(arr); };
swizzle_type<3, 1, 0>& wyx() { return reinterpret_cast<swizzle_type<3, 1, 0>&>(arr); };
swizzle_type<3, 1, 1>& wyy() { return reinterpret_cast<swizzle_type<3, 1, 1>&>(arr); };
swizzle_type<3, 1, 2>& wyz() { return reinterpret_cast<swizzle_type<3, 1, 2>&>(arr); };
swizzle_type<3, 1, 3>& wyw() { return reinterpret_cast<swizzle_type<3, 1, 3>&>(arr); };
swizzle_type<3, 2, 0>& wzx() { return reinterpret_cast<swizzle_type<3, 2, 0>&>(arr); };
swizzle_type<3, 2, 1>& wzy() { return reinterpret_cast<swizzle_type<3, 2, 1>&>(arr); };
swizzle_type<3, 2, 2>& wzz() { return reinterpret_cast<swizzle_type<3, 2, 2>&>(arr); };
swizzle_type<3, 2, 3>& wzw() { return reinterpret_cast<swizzle_type<3, 2, 3>&>(arr); };
swizzle_type<3, 3, 0>& wwx() { return reinterpret_cast<swizzle_type<3, 3, 0>&>(arr); };
swizzle_type<3, 3, 1>& wwy() { return reinterpret_cast<swizzle_type<3, 3, 1>&>(arr); };
swizzle_type<3, 3, 2>& wwz() { return reinterpret_cast<swizzle_type<3, 3, 2>&>(arr); };
swizzle_type<3, 3, 3>& www() { return reinterpret_cast<swizzle_type<3, 3, 3>&>(arr); };

swizzle_type<0, 0, 0, 0>& xxxx() { return reinterpret_cast<swizzle_type<0, 0, 0, 0>&>(arr); };
swizzle_type<0, 0, 0, 1>& xxxy() { return reinterpret_cast<swizzle_type<0, 0, 0, 1>&>(arr); };
swizzle_type<0, 0, 0, 2>& xxxz() { return reinterpret_cast<swizzle_type<0, 0, 0, 2>&>(arr); };
swizzle_type<0, 0, 0, 3>& xxxw() { return reinterpret_cast<swizzle_type<0, 0, 0, 3>&>(arr); };
swizzle_type<0, 0, 1, 0>& xxyx() { return reinterpret_cast<swizzle_type<0, 0, 1, 0>&>(arr); };
swizzle_type<0, 0, 1, 1>& xxyy() { return reinterpret_cast<swizzle_type<0, 0, 1, 1>&>(arr); };
swizzle_type<0, 0, 1, 2>& xxyz() { return reinterpret_cast<swizzle_type<0, 0, 1, 2>&>(arr); };
swizzle_type<0, 0, 1, 3>& xxyw() { return reinterpret_cast<swizzle_type<0, 0, 1, 3>&>(arr); };
swizzle_type<0, 0, 2, 0>& xxzx() { return reinterpret_cast<swizzle_type<0, 0, 2, 0>&>(arr); };
swizzle_type<0, 0, 2, 1>& xxzy() { return reinterpret_cast<swizzle_type<0, 0, 2, 1>&>(arr); };
swizzle_type<0, 0, 2, 2>& xxzz() { return reinterpret_cast<swizzle_type<0, 0, 2, 2>&>(arr); };
swizzle_type<0, 0, 2, 3>& xxzw() { return reinterpret_cast<swizzle_type<0, 0, 2, 3>&>(arr); };
swizzle_type<0, 0, 3, 0>& xxwx() { return reinterpret_cast<swizzle_type<0, 0, 3, 0>&>(arr); };
swizzle_type<0, 0, 3, 1>& xxwy() { return reinterpret_cast<swizzle_type<0, 0, 3, 1>&>(arr); };
swizzle_type<0, 0, 3, 2>& xxwz() { return reinterpret_cast<swizzle_type<0, 0, 3, 2>&>(arr); };
swizzle_type<0, 0, 3, 3>& xxww() { return reinterpret_cast<swizzle_type<0, 0, 3, 3>&>(arr); };
swizzle_type<0, 1, 0, 0>& xyxx() { return reinterpret_cast<swizzle_type<0, 1, 0, 0>&>(arr); };
swizzle_type<0, 1, 0, 1>& xyxy() { return reinterpret_cast<swizzle_type<0, 1, 0, 1>&>(arr); };
swizzle_type<0, 1, 0, 2>& xyxz() { return reinterpret_cast<swizzle_type<0, 1, 0, 2>&>(arr); };
swizzle_type<0, 1, 0, 3>& xyxw() { return reinterpret_cast<swizzle_type<0, 1, 0, 3>&>(arr); };
swizzle_type<0, 1, 1, 0>& xyyx() { return reinterpret_cast<swizzle_type<0, 1, 1, 0>&>(arr); };
swizzle_type<0, 1, 1, 1>& xyyy() { return reinterpret_cast<swizzle_type<0, 1, 1, 1>&>(arr); };
swizzle_type<0, 1, 1, 2>& xyyz() { return reinterpret_cast<swizzle_type<0, 1, 1, 2>&>(arr); };
swizzle_type<0, 1, 1, 3>& xyyw() { return reinterpret_cast<swizzle_type<0, 1, 1, 3>&>(arr); };
swizzle_type<0, 1, 2, 0>& xyzx() { return reinterpret_cast<swizzle_type<0, 1, 2, 0>&>(arr); };
swizzle_type<0, 1, 2, 1>& xyzy() { return reinterpret_cast<swizzle_type<0, 1, 2, 1>&>(arr); };
swizzle_type<0, 1, 2, 2>& xyzz() { return reinterpret_cast<swizzle_type<0, 1, 2, 2>&>(arr); };
swizzle_type<0, 1, 2, 3>& xyzw() { return reinterpret_cast<swizzle_type<0, 1, 2, 3>&>(arr); };
swizzle_type<0, 1, 3, 0>& xywx() { return reinterpret_cast<swizzle_type<0, 1, 3, 0>&>(arr); };
swizzle_type<0, 1, 3, 1>& xywy() { return reinterpret_cast<swizzle_type<0, 1, 3, 1>&>(arr); };
swizzle_type<0, 1, 3, 2>& xywz() { return reinterpret_cast<swizzle_type<0, 1, 3, 2>&>(arr); };
swizzle_type<0, 1, 3, 3>& xyww() { return reinterpret_cast<swizzle_type<0, 1, 3, 3>&>(arr); };
swizzle_type<0, 2, 0, 0>& xzxx() { return reinterpret_cast<swizzle_type<0, 2, 0, 0>&>(arr); };
swizzle_type<0, 2, 0, 1>& xzxy() { return reinterpret_cast<swizzle_type<0, 2, 0, 1>&>(arr); };
swizzle_type<0, 2, 0, 2>& xzxz() { return reinterpret_cast<swizzle_type<0, 2, 0, 2>&>(arr); };
swizzle_type<0, 2, 0, 3>& xzxw() { return reinterpret_cast<swizzle_type<0, 2, 0, 3>&>(arr); };
swizzle_type<0, 2, 1, 0>& xzyx() { return reinterpret_cast<swizzle_type<0, 2, 1, 0>&>(arr); };
swizzle_type<0, 2, 1, 1>& xzyy() { return reinterpret_cast<swizzle_type<0, 2, 1, 1>&>(arr); };
swizzle_type<0, 2, 1, 2>& xzyz() { return reinterpret_cast<swizzle_type<0, 2, 1, 2>&>(arr); };
swizzle_type<0, 2, 1, 3>& xzyw() { return reinterpret_cast<swizzle_type<0, 2, 1, 3>&>(arr); };
swizzle_type<0, 2, 2, 0>& xzzx() { return reinterpret_cast<swizzle_type<0, 2, 2, 0>&>(arr); };
swizzle_type<0, 2, 2, 1>& xzzy() { return reinterpret_cast<swizzle_type<0, 2, 2, 1>&>(arr); };
swizzle_type<0, 2, 2, 2>& xzzz() { return reinterpret_cast<swizzle_type<0, 2, 2, 2>&>(arr); };
swizzle_type<0, 2, 2, 3>& xzzw() { return reinterpret_cast<swizzle_type<0, 2, 2, 3>&>(arr); };
swizzle_type<0, 2, 3, 0>& xzwx() { return reinterpret_cast<swizzle_type<0, 2, 3, 0>&>(arr); };
swizzle_type<0, 2, 3, 1>& xzwy() { return reinterpret_cast<swizzle_type<0, 2, 3, 1>&>(arr); };
swizzle_type<0, 2, 3, 2>& xzwz() { return reinterpret_cast<swizzle_type<0, 2, 3, 2>&>(arr); };
swizzle_type<0, 2, 3, 3>& xzww() { return reinterpret_cast<swizzle_type<0, 2, 3, 3>&>(arr); };
swizzle_type<0, 3, 0, 0>& xwxx() { return reinterpret_cast<swizzle_type<0, 3, 0, 0>&>(arr); };
swizzle_type<0, 3, 0, 1>& xwxy() { return reinterpret_cast<swizzle_type<0, 3, 0, 1>&>(arr); };
swizzle_type<0, 3, 0, 2>& xwxz() { return reinterpret_cast<swizzle_type<0, 3, 0, 2>&>(arr); };
swizzle_type<0, 3, 0, 3>& xwxw() { return reinterpret_cast<swizzle_type<0, 3, 0, 3>&>(arr); };
swizzle_type<0, 3, 1, 0>& xwyx() { return reinterpret_cast<swizzle_type<0, 3, 1, 0>&>(arr); };
swizzle_type<0, 3, 1, 1>& xwyy() { return reinterpret_cast<swizzle_type<0, 3, 1, 1>&>(arr); };
swizzle_type<0, 3, 1, 2>& xwyz() { return reinterpret_cast<swizzle_type<0, 3, 1, 2>&>(arr); };
swizzle_type<0, 3, 1, 3>& xwyw() { return reinterpret_cast<swizzle_type<0, 3, 1, 3>&>(arr); };
swizzle_type<0, 3, 2, 0>& xwzx() { return reinterpret_cast<swizzle_type<0, 3, 2, 0>&>(arr); };
swizzle_type<0, 3, 2, 1>& xwzy() { return reinterpret_cast<swizzle_type<0, 3, 2, 1>&>(arr); };
swizzle_type<0, 3, 2, 2>& xwzz() { return reinterpret_cast<swizzle_type<0, 3, 2, 2>&>(arr); };
swizzle_type<0, 3, 2, 3>& xwzw() { return reinterpret_cast<swizzle_type<0, 3, 2, 3>&>(arr); };
swizzle_type<0, 3, 3, 0>& xwwx() { return reinterpret_cast<swizzle_type<0, 3, 3, 0>&>(arr); };
swizzle_type<0, 3, 3, 1>& xwwy() { return reinterpret_cast<swizzle_type<0, 3, 3, 1>&>(arr); };
swizzle_type<0, 3, 3, 2>& xwwz() { return reinterpret_cast<swizzle_type<0, 3, 3, 2>&>(arr); };
swizzle_type<0, 3, 3, 3>& xwww() { return reinterpret_cast<swizzle_type<0, 3, 3, 3>&>(arr); };
swizzle_type<1, 0, 0, 0>& yxxx() { return reinterpret_cast<swizzle_type<1, 0, 0, 0>&>(arr); };
swizzle_type<1, 0, 0, 1>& yxxy() { return reinterpret_cast<swizzle_type<1, 0, 0, 1>&>(arr); };
swizzle_type<1, 0, 0, 2>& yxxz() { return reinterpret_cast<swizzle_type<1, 0, 0, 2>&>(arr); };
swizzle_type<1, 0, 0, 3>& yxxw() { return reinterpret_cast<swizzle_type<1, 0, 0, 3>&>(arr); };
swizzle_type<1, 0, 1, 0>& yxyx() { return reinterpret_cast<swizzle_type<1, 0, 1, 0>&>(arr); };
swizzle_type<1, 0, 1, 1>& yxyy() { return reinterpret_cast<swizzle_type<1, 0, 1, 1>&>(arr); };
swizzle_type<1, 0, 1, 2>& yxyz() { return reinterpret_cast<swizzle_type<1, 0, 1, 2>&>(arr); };
swizzle_type<1, 0, 1, 3>& yxyw() { return reinterpret_cast<swizzle_type<1, 0, 1, 3>&>(arr); };
swizzle_type<1, 0, 2, 0>& yxzx() { return reinterpret_cast<swizzle_type<1, 0, 2, 0>&>(arr); };
swizzle_type<1, 0, 2, 1>& yxzy() { return reinterpret_cast<swizzle_type<1, 0, 2, 1>&>(arr); };
swizzle_type<1, 0, 2, 2>& yxzz() { return reinterpret_cast<swizzle_type<1, 0, 2, 2>&>(arr); };
swizzle_type<1, 0, 2, 3>& yxzw() { return reinterpret_cast<swizzle_type<1, 0, 2, 3>&>(arr); };
swizzle_type<1, 0, 3, 0>& yxwx() { return reinterpret_cast<swizzle_type<1, 0, 3, 0>&>(arr); };
swizzle_type<1, 0, 3, 1>& yxwy() { return reinterpret_cast<swizzle_type<1, 0, 3, 1>&>(arr); };
swizzle_type<1, 0, 3, 2>& yxwz() { return reinterpret_cast<swizzle_type<1, 0, 3, 2>&>(arr); };
swizzle_type<1, 0, 3, 3>& yxww() { return reinterpret_cast<swizzle_type<1, 0, 3, 3>&>(arr); };
swizzle_type<1, 1, 0, 0>& yyxx() { return reinterpret_cast<swizzle_type<1, 1, 0, 0>&>(arr); };
swizzle_type<1, 1, 0, 1>& yyxy() { return reinterpret_cast<swizzle_type<1, 1, 0, 1>&>(arr); };
swizzle_type<1, 1, 0, 2>& yyxz() { return reinterpret_cast<swizzle_type<1, 1, 0, 2>&>(arr); };
swizzle_type<1, 1, 0, 3>& yyxw() { return reinterpret_cast<swizzle_type<1, 1, 0, 3>&>(arr); };
swizzle_type<1, 1, 1, 0>& yyyx() { return reinterpret_cast<swizzle_type<1, 1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1, 1>& yyyy() { return reinterpret_cast<swizzle_type<1, 1, 1, 1>&>(arr); };
swizzle_type<1, 1, 1, 2>& yyyz() { return reinterpret_cast<swizzle_type<1, 1, 1, 2>&>(arr); };
swizzle_type<1, 1, 1, 3>& yyyw() { return reinterpret_cast<swizzle_type<1, 1, 1, 3>&>(arr); };
swizzle_type<1, 1, 2, 0>& yyzx() { return reinterpret_cast<swizzle_type<1, 1, 2, 0>&>(arr); };
swizzle_type<1, 1, 2, 1>& yyzy() { return reinterpret_cast<swizzle_type<1, 1, 2, 1>&>(arr); };
swizzle_type<1, 1, 2, 2>& yyzz() { return reinterpret_cast<swizzle_type<1, 1, 2, 2>&>(arr); };
swizzle_type<1, 1, 2, 3>& yyzw() { return reinterpret_cast<swizzle_type<1, 1, 2, 3>&>(arr); };
swizzle_type<1, 1, 3, 0>& yywx() { return reinterpret_cast<swizzle_type<1, 1, 3, 0>&>(arr); };
swizzle_type<1, 1, 3, 1>& yywy() { return reinterpret_cast<swizzle_type<1, 1, 3, 1>&>(arr); };
swizzle_type<1, 1, 3, 2>& yywz() { return reinterpret_cast<swizzle_type<1, 1, 3, 2>&>(arr); };
swizzle_type<1, 1, 3, 3>& yyww() { return reinterpret_cast<swizzle_type<1, 1, 3, 3>&>(arr); };
swizzle_type<1, 2, 0, 0>& yzxx() { return reinterpret_cast<swizzle_type<1, 2, 0, 0>&>(arr); };
swizzle_type<1, 2, 0, 1>& yzxy() { return reinterpret_cast<swizzle_type<1, 2, 0, 1>&>(arr); };
swizzle_type<1, 2, 0, 2>& yzxz() { return reinterpret_cast<swizzle_type<1, 2, 0, 2>&>(arr); };
swizzle_type<1, 2, 0, 3>& yzxw() { return reinterpret_cast<swizzle_type<1, 2, 0, 3>&>(arr); };
swizzle_type<1, 2, 1, 0>& yzyx() { return reinterpret_cast<swizzle_type<1, 2, 1, 0>&>(arr); };
swizzle_type<1, 2, 1, 1>& yzyy() { return reinterpret_cast<swizzle_type<1, 2, 1, 1>&>(arr); };
swizzle_type<1, 2, 1, 2>& yzyz() { return reinterpret_cast<swizzle_type<1, 2, 1, 2>&>(arr); };
swizzle_type<1, 2, 1, 3>& yzyw() { return reinterpret_cast<swizzle_type<1, 2, 1, 3>&>(arr); };
swizzle_type<1, 2, 2, 0>& yzzx() { return reinterpret_cast<swizzle_type<1, 2, 2, 0>&>(arr); };
swizzle_type<1, 2, 2, 1>& yzzy() { return reinterpret_cast<swizzle_type<1, 2, 2, 1>&>(arr); };
swizzle_type<1, 2, 2, 2>& yzzz() { return reinterpret_cast<swizzle_type<1, 2, 2, 2>&>(arr); };
swizzle_type<1, 2, 2, 3>& yzzw() { return reinterpret_cast<swizzle_type<1, 2, 2, 3>&>(arr); };
swizzle_type<1, 2, 3, 0>& yzwx() { return reinterpret_cast<swizzle_type<1, 2, 3, 0>&>(arr); };
swizzle_type<1, 2, 3, 1>& yzwy() { return reinterpret_cast<swizzle_type<1, 2, 3, 1>&>(arr); };
swizzle_type<1, 2, 3, 2>& yzwz() { return reinterpret_cast<swizzle_type<1, 2, 3, 2>&>(arr); };
swizzle_type<1, 2, 3, 3>& yzww() { return reinterpret_cast<swizzle_type<1, 2, 3, 3>&>(arr); };
swizzle_type<1, 3, 0, 0>& ywxx() { return reinterpret_cast<swizzle_type<1, 3, 0, 0>&>(arr); };
swizzle_type<1, 3, 0, 1>& ywxy() { return reinterpret_cast<swizzle_type<1, 3, 0, 1>&>(arr); };
swizzle_type<1, 3, 0, 2>& ywxz() { return reinterpret_cast<swizzle_type<1, 3, 0, 2>&>(arr); };
swizzle_type<1, 3, 0, 3>& ywxw() { return reinterpret_cast<swizzle_type<1, 3, 0, 3>&>(arr); };
swizzle_type<1, 3, 1, 0>& ywyx() { return reinterpret_cast<swizzle_type<1, 3, 1, 0>&>(arr); };
swizzle_type<1, 3, 1, 1>& ywyy() { return reinterpret_cast<swizzle_type<1, 3, 1, 1>&>(arr); };
swizzle_type<1, 3, 1, 2>& ywyz() { return reinterpret_cast<swizzle_type<1, 3, 1, 2>&>(arr); };
swizzle_type<1, 3, 1, 3>& ywyw() { return reinterpret_cast<swizzle_type<1, 3, 1, 3>&>(arr); };
swizzle_type<1, 3, 2, 0>& ywzx() { return reinterpret_cast<swizzle_type<1, 3, 2, 0>&>(arr); };
swizzle_type<1, 3, 2, 1>& ywzy() { return reinterpret_cast<swizzle_type<1, 3, 2, 1>&>(arr); };
swizzle_type<1, 3, 2, 2>& ywzz() { return reinterpret_cast<swizzle_type<1, 3, 2, 2>&>(arr); };
swizzle_type<1, 3, 2, 3>& ywzw() { return reinterpret_cast<swizzle_type<1, 3, 2, 3>&>(arr); };
swizzle_type<1, 3, 3, 0>& ywwx() { return reinterpret_cast<swizzle_type<1, 3, 3, 0>&>(arr); };
swizzle_type<1, 3, 3, 1>& ywwy() { return reinterpret_cast<swizzle_type<1, 3, 3, 1>&>(arr); };
swizzle_type<1, 3, 3, 2>& ywwz() { return reinterpret_cast<swizzle_type<1, 3, 3, 2>&>(arr); };
swizzle_type<1, 3, 3, 3>& ywww() { return reinterpret_cast<swizzle_type<1, 3, 3, 3>&>(arr); };
swizzle_type<2, 0, 0, 0>& zxxx() { return reinterpret_cast<swizzle_type<2, 0, 0, 0>&>(arr); };
swizzle_type<2, 0, 0, 1>& zxxy() { return reinterpret_cast<swizzle_type<2, 0, 0, 1>&>(arr); };
swizzle_type<2, 0, 0, 2>& zxxz() { return reinterpret_cast<swizzle_type<2, 0, 0, 2>&>(arr); };
swizzle_type<2, 0, 0, 3>& zxxw() { return reinterpret_cast<swizzle_type<2, 0, 0, 3>&>(arr); };
swizzle_type<2, 0, 1, 0>& zxyx() { return reinterpret_cast<swizzle_type<2, 0, 1, 0>&>(arr); };
swizzle_type<2, 0, 1, 1>& zxyy() { return reinterpret_cast<swizzle_type<2, 0, 1, 1>&>(arr); };
swizzle_type<2, 0, 1, 2>& zxyz() { return reinterpret_cast<swizzle_type<2, 0, 1, 2>&>(arr); };
swizzle_type<2, 0, 1, 3>& zxyw() { return reinterpret_cast<swizzle_type<2, 0, 1, 3>&>(arr); };
swizzle_type<2, 0, 2, 0>& zxzx() { return reinterpret_cast<swizzle_type<2, 0, 2, 0>&>(arr); };
swizzle_type<2, 0, 2, 1>& zxzy() { return reinterpret_cast<swizzle_type<2, 0, 2, 1>&>(arr); };
swizzle_type<2, 0, 2, 2>& zxzz() { return reinterpret_cast<swizzle_type<2, 0, 2, 2>&>(arr); };
swizzle_type<2, 0, 2, 3>& zxzw() { return reinterpret_cast<swizzle_type<2, 0, 2, 3>&>(arr); };
swizzle_type<2, 0, 3, 0>& zxwx() { return reinterpret_cast<swizzle_type<2, 0, 3, 0>&>(arr); };
swizzle_type<2, 0, 3, 1>& zxwy() { return reinterpret_cast<swizzle_type<2, 0, 3, 1>&>(arr); };
swizzle_type<2, 0, 3, 2>& zxwz() { return reinterpret_cast<swizzle_type<2, 0, 3, 2>&>(arr); };
swizzle_type<2, 0, 3, 3>& zxww() { return reinterpret_cast<swizzle_type<2, 0, 3, 3>&>(arr); };
swizzle_type<2, 1, 0, 0>& zyxx() { return reinterpret_cast<swizzle_type<2, 1, 0, 0>&>(arr); };
swizzle_type<2, 1, 0, 1>& zyxy() { return reinterpret_cast<swizzle_type<2, 1, 0, 1>&>(arr); };
swizzle_type<2, 1, 0, 2>& zyxz() { return reinterpret_cast<swizzle_type<2, 1, 0, 2>&>(arr); };
swizzle_type<2, 1, 0, 3>& zyxw() { return reinterpret_cast<swizzle_type<2, 1, 0, 3>&>(arr); };
swizzle_type<2, 1, 1, 0>& zyyx() { return reinterpret_cast<swizzle_type<2, 1, 1, 0>&>(arr); };
swizzle_type<2, 1, 1, 1>& zyyy() { return reinterpret_cast<swizzle_type<2, 1, 1, 1>&>(arr); };
swizzle_type<2, 1, 1, 2>& zyyz() { return reinterpret_cast<swizzle_type<2, 1, 1, 2>&>(arr); };
swizzle_type<2, 1, 1, 3>& zyyw() { return reinterpret_cast<swizzle_type<2, 1, 1, 3>&>(arr); };
swizzle_type<2, 1, 2, 0>& zyzx() { return reinterpret_cast<swizzle_type<2, 1, 2, 0>&>(arr); };
swizzle_type<2, 1, 2, 1>& zyzy() { return reinterpret_cast<swizzle_type<2, 1, 2, 1>&>(arr); };
swizzle_type<2, 1, 2, 2>& zyzz() { return reinterpret_cast<swizzle_type<2, 1, 2, 2>&>(arr); };
swizzle_type<2, 1, 2, 3>& zyzw() { return reinterpret_cast<swizzle_type<2, 1, 2, 3>&>(arr); };
swizzle_type<2, 1, 3, 0>& zywx() { return reinterpret_cast<swizzle_type<2, 1, 3, 0>&>(arr); };
swizzle_type<2, 1, 3, 1>& zywy() { return reinterpret_cast<swizzle_type<2, 1, 3, 1>&>(arr); };
swizzle_type<2, 1, 3, 2>& zywz() { return reinterpret_cast<swizzle_type<2, 1, 3, 2>&>(arr); };
swizzle_type<2, 1, 3, 3>& zyww() { return reinterpret_cast<swizzle_type<2, 1, 3, 3>&>(arr); };
swizzle_type<2, 2, 0, 0>& zzxx() { return reinterpret_cast<swizzle_type<2, 2, 0, 0>&>(arr); };
swizzle_type<2, 2, 0, 1>& zzxy() { return reinterpret_cast<swizzle_type<2, 2, 0, 1>&>(arr); };
swizzle_type<2, 2, 0, 2>& zzxz() { return reinterpret_cast<swizzle_type<2, 2, 0, 2>&>(arr); };
swizzle_type<2, 2, 0, 3>& zzxw() { return reinterpret_cast<swizzle_type<2, 2, 0, 3>&>(arr); };
swizzle_type<2, 2, 1, 0>& zzyx() { return reinterpret_cast<swizzle_type<2, 2, 1, 0>&>(arr); };
swizzle_type<2, 2, 1, 1>& zzyy() { return reinterpret_cast<swizzle_type<2, 2, 1, 1>&>(arr); };
swizzle_type<2, 2, 1, 2>& zzyz() { return reinterpret_cast<swizzle_type<2, 2, 1, 2>&>(arr); };
swizzle_type<2, 2, 1, 3>& zzyw() { return reinterpret_cast<swizzle_type<2, 2, 1, 3>&>(arr); };
swizzle_type<2, 2, 2, 0>& zzzx() { return reinterpret_cast<swizzle_type<2, 2, 2, 0>&>(arr); };
swizzle_type<2, 2, 2, 1>& zzzy() { return reinterpret_cast<swizzle_type<2, 2, 2, 1>&>(arr); };
swizzle_type<2, 2, 2, 2>& zzzz() { return reinterpret_cast<swizzle_type<2, 2, 2, 2>&>(arr); };
swizzle_type<2, 2, 2, 3>& zzzw() { return reinterpret_cast<swizzle_type<2, 2, 2, 3>&>(arr); };
swizzle_type<2, 2, 3, 0>& zzwx() { return reinterpret_cast<swizzle_type<2, 2, 3, 0>&>(arr); };
swizzle_type<2, 2, 3, 1>& zzwy() { return reinterpret_cast<swizzle_type<2, 2, 3, 1>&>(arr); };
swizzle_type<2, 2, 3, 2>& zzwz() { return reinterpret_cast<swizzle_type<2, 2, 3, 2>&>(arr); };
swizzle_type<2, 2, 3, 3>& zzww() { return reinterpret_cast<swizzle_type<2, 2, 3, 3>&>(arr); };
swizzle_type<2, 3, 0, 0>& zwxx() { return reinterpret_cast<swizzle_type<2, 3, 0, 0>&>(arr); };
swizzle_type<2, 3, 0, 1>& zwxy() { return reinterpret_cast<swizzle_type<2, 3, 0, 1>&>(arr); };
swizzle_type<2, 3, 0, 2>& zwxz() { return reinterpret_cast<swizzle_type<2, 3, 0, 2>&>(arr); };
swizzle_type<2, 3, 0, 3>& zwxw() { return reinterpret_cast<swizzle_type<2, 3, 0, 3>&>(arr); };
swizzle_type<2, 3, 1, 0>& zwyx() { return reinterpret_cast<swizzle_type<2, 3, 1, 0>&>(arr); };
swizzle_type<2, 3, 1, 1>& zwyy() { return reinterpret_cast<swizzle_type<2, 3, 1, 1>&>(arr); };
swizzle_type<2, 3, 1, 2>& zwyz() { return reinterpret_cast<swizzle_type<2, 3, 1, 2>&>(arr); };
swizzle_type<2, 3, 1, 3>& zwyw() { return reinterpret_cast<swizzle_type<2, 3, 1, 3>&>(arr); };
swizzle_type<2, 3, 2, 0>& zwzx() { return reinterpret_cast<swizzle_type<2, 3, 2, 0>&>(arr); };
swizzle_type<2, 3, 2, 1>& zwzy() { return reinterpret_cast<swizzle_type<2, 3, 2, 1>&>(arr); };
swizzle_type<2, 3, 2, 2>& zwzz() { return reinterpret_cast<swizzle_type<2, 3, 2, 2>&>(arr); };
swizzle_type<2, 3, 2, 3>& zwzw() { return reinterpret_cast<swizzle_type<2, 3, 2, 3>&>(arr); };
swizzle_type<2, 3, 3, 0>& zwwx() { return reinterpret_cast<swizzle_type<2, 3, 3, 0>&>(arr); };
swizzle_type<2, 3, 3, 1>& zwwy() { return reinterpret_cast<swizzle_type<2, 3, 3, 1>&>(arr); };
swizzle_type<2, 3, 3, 2>& zwwz() { return reinterpret_cast<swizzle_type<2, 3, 3, 2>&>(arr); };
swizzle_type<2, 3, 3, 3>& zwww() { return reinterpret_cast<swizzle_type<2, 3, 3, 3>&>(arr); };
swizzle_type<3, 0, 0, 0>& wxxx() { return reinterpret_cast<swizzle_type<3, 0, 0, 0>&>(arr); };
swizzle_type<3, 0, 0, 1>& wxxy() { return reinterpret_cast<swizzle_type<3, 0, 0, 1>&>(arr); };
swizzle_type<3, 0, 0, 2>& wxxz() { return reinterpret_cast<swizzle_type<3, 0, 0, 2>&>(arr); };
swizzle_type<3, 0, 0, 3>& wxxw() { return reinterpret_cast<swizzle_type<3, 0, 0, 3>&>(arr); };
swizzle_type<3, 0, 1, 0>& wxyx() { return reinterpret_cast<swizzle_type<3, 0, 1, 0>&>(arr); };
swizzle_type<3, 0, 1, 1>& wxyy() { return reinterpret_cast<swizzle_type<3, 0, 1, 1>&>(arr); };
swizzle_type<3, 0, 1, 2>& wxyz() { return reinterpret_cast<swizzle_type<3, 0, 1, 2>&>(arr); };
swizzle_type<3, 0, 1, 3>& wxyw() { return reinterpret_cast<swizzle_type<3, 0, 1, 3>&>(arr); };
swizzle_type<3, 0, 2, 0>& wxzx() { return reinterpret_cast<swizzle_type<3, 0, 2, 0>&>(arr); };
swizzle_type<3, 0, 2, 1>& wxzy() { return reinterpret_cast<swizzle_type<3, 0, 2, 1>&>(arr); };
swizzle_type<3, 0, 2, 2>& wxzz() { return reinterpret_cast<swizzle_type<3, 0, 2, 2>&>(arr); };
swizzle_type<3, 0, 2, 3>& wxzw() { return reinterpret_cast<swizzle_type<3, 0, 2, 3>&>(arr); };
swizzle_type<3, 0, 3, 0>& wxwx() { return reinterpret_cast<swizzle_type<3, 0, 3, 0>&>(arr); };
swizzle_type<3, 0, 3, 1>& wxwy() { return reinterpret_cast<swizzle_type<3, 0, 3, 1>&>(arr); };
swizzle_type<3, 0, 3, 2>& wxwz() { return reinterpret_cast<swizzle_type<3, 0, 3, 2>&>(arr); };
swizzle_type<3, 0, 3, 3>& wxww() { return reinterpret_cast<swizzle_type<3, 0, 3, 3>&>(arr); };
swizzle_type<3, 1, 0, 0>& wyxx() { return reinterpret_cast<swizzle_type<3, 1, 0, 0>&>(arr); };
swizzle_type<3, 1, 0, 1>& wyxy() { return reinterpret_cast<swizzle_type<3, 1, 0, 1>&>(arr); };
swizzle_type<3, 1, 0, 2>& wyxz() { return reinterpret_cast<swizzle_type<3, 1, 0, 2>&>(arr); };
swizzle_type<3, 1, 0, 3>& wyxw() { return reinterpret_cast<swizzle_type<3, 1, 0, 3>&>(arr); };
swizzle_type<3, 1, 1, 0>& wyyx() { return reinterpret_cast<swizzle_type<3, 1, 1, 0>&>(arr); };
swizzle_type<3, 1, 1, 1>& wyyy() { return reinterpret_cast<swizzle_type<3, 1, 1, 1>&>(arr); };
swizzle_type<3, 1, 1, 2>& wyyz() { return reinterpret_cast<swizzle_type<3, 1, 1, 2>&>(arr); };
swizzle_type<3, 1, 1, 3>& wyyw() { return reinterpret_cast<swizzle_type<3, 1, 1, 3>&>(arr); };
swizzle_type<3, 1, 2, 0>& wyzx() { return reinterpret_cast<swizzle_type<3, 1, 2, 0>&>(arr); };
swizzle_type<3, 1, 2, 1>& wyzy() { return reinterpret_cast<swizzle_type<3, 1, 2, 1>&>(arr); };
swizzle_type<3, 1, 2, 2>& wyzz() { return reinterpret_cast<swizzle_type<3, 1, 2, 2>&>(arr); };
swizzle_type<3, 1, 2, 3>& wyzw() { return reinterpret_cast<swizzle_type<3, 1, 2, 3>&>(arr); };
swizzle_type<3, 1, 3, 0>& wywx() { return reinterpret_cast<swizzle_type<3, 1, 3, 0>&>(arr); };
swizzle_type<3, 1, 3, 1>& wywy() { return reinterpret_cast<swizzle_type<3, 1, 3, 1>&>(arr); };
swizzle_type<3, 1, 3, 2>& wywz() { return reinterpret_cast<swizzle_type<3, 1, 3, 2>&>(arr); };
swizzle_type<3, 1, 3, 3>& wyww() { return reinterpret_cast<swizzle_type<3, 1, 3, 3>&>(arr); };
swizzle_type<3, 2, 0, 0>& wzxx() { return reinterpret_cast<swizzle_type<3, 2, 0, 0>&>(arr); };
swizzle_type<3, 2, 0, 1>& wzxy() { return reinterpret_cast<swizzle_type<3, 2, 0, 1>&>(arr); };
swizzle_type<3, 2, 0, 2>& wzxz() { return reinterpret_cast<swizzle_type<3, 2, 0, 2>&>(arr); };
swizzle_type<3, 2, 0, 3>& wzxw() { return reinterpret_cast<swizzle_type<3, 2, 0, 3>&>(arr); };
swizzle_type<3, 2, 1, 0>& wzyx() { return reinterpret_cast<swizzle_type<3, 2, 1, 0>&>(arr); };
swizzle_type<3, 2, 1, 1>& wzyy() { return reinterpret_cast<swizzle_type<3, 2, 1, 1>&>(arr); };
swizzle_type<3, 2, 1, 2>& wzyz() { return reinterpret_cast<swizzle_type<3, 2, 1, 2>&>(arr); };
swizzle_type<3, 2, 1, 3>& wzyw() { return reinterpret_cast<swizzle_type<3, 2, 1, 3>&>(arr); };
swizzle_type<3, 2, 2, 0>& wzzx() { return reinterpret_cast<swizzle_type<3, 2, 2, 0>&>(arr); };
swizzle_type<3, 2, 2, 1>& wzzy() { return reinterpret_cast<swizzle_type<3, 2, 2, 1>&>(arr); };
swizzle_type<3, 2, 2, 2>& wzzz() { return reinterpret_cast<swizzle_type<3, 2, 2, 2>&>(arr); };
swizzle_type<3, 2, 2, 3>& wzzw() { return reinterpret_cast<swizzle_type<3, 2, 2, 3>&>(arr); };
swizzle_type<3, 2, 3, 0>& wzwx() { return reinterpret_cast<swizzle_type<3, 2, 3, 0>&>(arr); };
swizzle_type<3, 2, 3, 1>& wzwy() { return reinterpret_cast<swizzle_type<3, 2, 3, 1>&>(arr); };
swizzle_type<3, 2, 3, 2>& wzwz() { return reinterpret_cast<swizzle_type<3, 2, 3, 2>&>(arr); };
swizzle_type<3, 2, 3, 3>& wzww() { return reinterpret_cast<swizzle_type<3, 2, 3, 3>&>(arr); };
swizzle_type<3, 3, 0, 0>& wwxx() { return reinterpret_cast<swizzle_type<3, 3, 0, 0>&>(arr); };
swizzle_type<3, 3, 0, 1>& wwxy() { return reinterpret_cast<swizzle_type<3, 3, 0, 1>&>(arr); };
swizzle_type<3, 3, 0, 2>& wwxz() { return reinterpret_cast<swizzle_type<3, 3, 0, 2>&>(arr); };
swizzle_type<3, 3, 0, 3>& wwxw() { return reinterpret_cast<swizzle_type<3, 3, 0, 3>&>(arr); };
swizzle_type<3, 3, 1, 0>& wwyx() { return reinterpret_cast<swizzle_type<3, 3, 1, 0>&>(arr); };
swizzle_type<3, 3, 1, 1>& wwyy() { return reinterpret_cast<swizzle_type<3, 3, 1, 1>&>(arr); };
swizzle_type<3, 3, 1, 2>& wwyz() { return reinterpret_cast<swizzle_type<3, 3, 1, 2>&>(arr); };
swizzle_type<3, 3, 1, 3>& wwyw() { return reinterpret_cast<swizzle_type<3, 3, 1, 3>&>(arr); };
swizzle_type<3, 3, 2, 0>& wwzx() { return reinterpret_cast<swizzle_type<3, 3, 2, 0>&>(arr); };
swizzle_type<3, 3, 2, 1>& wwzy() { return reinterpret_cast<swizzle_type<3, 3, 2, 1>&>(arr); };
swizzle_type<3, 3, 2, 2>& wwzz() { return reinterpret_cast<swizzle_type<3, 3, 2, 2>&>(arr); };
swizzle_type<3, 3, 2, 3>& wwzw() { return reinterpret_cast<swizzle_type<3, 3, 2, 3>&>(arr); };
swizzle_type<3, 3, 3, 0>& wwwx() { return reinterpret_cast<swizzle_type<3, 3, 3, 0>&>(arr); };
swizzle_type<3, 3, 3, 1>& wwwy() { return reinterpret_cast<swizzle_type<3, 3, 3, 1>&>(arr); };
swizzle_type<3, 3, 3, 2>& wwwz() { return reinterpret_cast<swizzle_type<3, 3, 3, 2>&>(arr); };
swizzle_type<3, 3, 3, 3>& wwww() { return reinterpret_cast<swizzle_type<3, 3, 3, 3>&>(arr); };
