swizzle_type<0, 0>& xx() { return reinterpret_cast<swizzle_type<0, 0>&>(arr); };
swizzle_type<0, 1>& xy() { return reinterpret_cast<swizzle_type<0, 1>&>(arr); };
swizzle_type<0, 2>& xz() { return reinterpret_cast<swizzle_type<0, 2>&>(arr); };
swizzle_type<1, 0>& yx() { return reinterpret_cast<swizzle_type<1, 0>&>(arr); };
swizzle_type<1, 1>& yy() { return reinterpret_cast<swizzle_type<1, 1>&>(arr); };
swizzle_type<1, 2>& yz() { return reinterpret_cast<swizzle_type<1, 2>&>(arr); };
swizzle_type<2, 0>& zx() { return reinterpret_cast<swizzle_type<2, 0>&>(arr); };
swizzle_type<2, 1>& zy() { return reinterpret_cast<swizzle_type<2, 1>&>(arr); };
swizzle_type<2, 2>& zz() { return reinterpret_cast<swizzle_type<2, 2>&>(arr); };

swizzle_type<0, 0, 0>& xxx() { return reinterpret_cast<swizzle_type<0, 0, 0>&>(arr); };
swizzle_type<0, 0, 1>& xxy() { return reinterpret_cast<swizzle_type<0, 0, 1>&>(arr); };
swizzle_type<0, 0, 2>& xxz() { return reinterpret_cast<swizzle_type<0, 0, 2>&>(arr); };
swizzle_type<0, 1, 0>& xyx() { return reinterpret_cast<swizzle_type<0, 1, 0>&>(arr); };
swizzle_type<0, 1, 1>& xyy() { return reinterpret_cast<swizzle_type<0, 1, 1>&>(arr); };
swizzle_type<0, 1, 2>& xyz() { return reinterpret_cast<swizzle_type<0, 1, 2>&>(arr); };
swizzle_type<0, 2, 0>& xzx() { return reinterpret_cast<swizzle_type<0, 2, 0>&>(arr); };
swizzle_type<0, 2, 1>& xzy() { return reinterpret_cast<swizzle_type<0, 2, 1>&>(arr); };
swizzle_type<0, 2, 2>& xzz() { return reinterpret_cast<swizzle_type<0, 2, 2>&>(arr); };
swizzle_type<1, 0, 0>& yxx() { return reinterpret_cast<swizzle_type<1, 0, 0>&>(arr); };
swizzle_type<1, 0, 1>& yxy() { return reinterpret_cast<swizzle_type<1, 0, 1>&>(arr); };
swizzle_type<1, 0, 2>& yxz() { return reinterpret_cast<swizzle_type<1, 0, 2>&>(arr); };
swizzle_type<1, 1, 0>& yyx() { return reinterpret_cast<swizzle_type<1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1>& yyy() { return reinterpret_cast<swizzle_type<1, 1, 1>&>(arr); };
swizzle_type<1, 1, 2>& yyz() { return reinterpret_cast<swizzle_type<1, 1, 2>&>(arr); };
swizzle_type<1, 2, 0>& yzx() { return reinterpret_cast<swizzle_type<1, 2, 0>&>(arr); };
swizzle_type<1, 2, 1>& yzy() { return reinterpret_cast<swizzle_type<1, 2, 1>&>(arr); };
swizzle_type<1, 2, 2>& yzz() { return reinterpret_cast<swizzle_type<1, 2, 2>&>(arr); };
swizzle_type<2, 0, 0>& zxx() { return reinterpret_cast<swizzle_type<2, 0, 0>&>(arr); };
swizzle_type<2, 0, 1>& zxy() { return reinterpret_cast<swizzle_type<2, 0, 1>&>(arr); };
swizzle_type<2, 0, 2>& zxz() { return reinterpret_cast<swizzle_type<2, 0, 2>&>(arr); };
swizzle_type<2, 1, 0>& zyx() { return reinterpret_cast<swizzle_type<2, 1, 0>&>(arr); };
swizzle_type<2, 1, 1>& zyy() { return reinterpret_cast<swizzle_type<2, 1, 1>&>(arr); };
swizzle_type<2, 1, 2>& zyz() { return reinterpret_cast<swizzle_type<2, 1, 2>&>(arr); };
swizzle_type<2, 2, 0>& zzx() { return reinterpret_cast<swizzle_type<2, 2, 0>&>(arr); };
swizzle_type<2, 2, 1>& zzy() { return reinterpret_cast<swizzle_type<2, 2, 1>&>(arr); };
swizzle_type<2, 2, 2>& zzz() { return reinterpret_cast<swizzle_type<2, 2, 2>&>(arr); };

swizzle_type<0, 0, 0, 0>& xxxx() { return reinterpret_cast<swizzle_type<0, 0, 0, 0>&>(arr); };
swizzle_type<0, 0, 0, 1>& xxxy() { return reinterpret_cast<swizzle_type<0, 0, 0, 1>&>(arr); };
swizzle_type<0, 0, 0, 2>& xxxz() { return reinterpret_cast<swizzle_type<0, 0, 0, 2>&>(arr); };
swizzle_type<0, 0, 1, 0>& xxyx() { return reinterpret_cast<swizzle_type<0, 0, 1, 0>&>(arr); };
swizzle_type<0, 0, 1, 1>& xxyy() { return reinterpret_cast<swizzle_type<0, 0, 1, 1>&>(arr); };
swizzle_type<0, 0, 1, 2>& xxyz() { return reinterpret_cast<swizzle_type<0, 0, 1, 2>&>(arr); };
swizzle_type<0, 0, 2, 0>& xxzx() { return reinterpret_cast<swizzle_type<0, 0, 2, 0>&>(arr); };
swizzle_type<0, 0, 2, 1>& xxzy() { return reinterpret_cast<swizzle_type<0, 0, 2, 1>&>(arr); };
swizzle_type<0, 0, 2, 2>& xxzz() { return reinterpret_cast<swizzle_type<0, 0, 2, 2>&>(arr); };
swizzle_type<0, 1, 0, 0>& xyxx() { return reinterpret_cast<swizzle_type<0, 1, 0, 0>&>(arr); };
swizzle_type<0, 1, 0, 1>& xyxy() { return reinterpret_cast<swizzle_type<0, 1, 0, 1>&>(arr); };
swizzle_type<0, 1, 0, 2>& xyxz() { return reinterpret_cast<swizzle_type<0, 1, 0, 2>&>(arr); };
swizzle_type<0, 1, 1, 0>& xyyx() { return reinterpret_cast<swizzle_type<0, 1, 1, 0>&>(arr); };
swizzle_type<0, 1, 1, 1>& xyyy() { return reinterpret_cast<swizzle_type<0, 1, 1, 1>&>(arr); };
swizzle_type<0, 1, 1, 2>& xyyz() { return reinterpret_cast<swizzle_type<0, 1, 1, 2>&>(arr); };
swizzle_type<0, 1, 2, 0>& xyzx() { return reinterpret_cast<swizzle_type<0, 1, 2, 0>&>(arr); };
swizzle_type<0, 1, 2, 1>& xyzy() { return reinterpret_cast<swizzle_type<0, 1, 2, 1>&>(arr); };
swizzle_type<0, 1, 2, 2>& xyzz() { return reinterpret_cast<swizzle_type<0, 1, 2, 2>&>(arr); };
swizzle_type<0, 2, 0, 0>& xzxx() { return reinterpret_cast<swizzle_type<0, 2, 0, 0>&>(arr); };
swizzle_type<0, 2, 0, 1>& xzxy() { return reinterpret_cast<swizzle_type<0, 2, 0, 1>&>(arr); };
swizzle_type<0, 2, 0, 2>& xzxz() { return reinterpret_cast<swizzle_type<0, 2, 0, 2>&>(arr); };
swizzle_type<0, 2, 1, 0>& xzyx() { return reinterpret_cast<swizzle_type<0, 2, 1, 0>&>(arr); };
swizzle_type<0, 2, 1, 1>& xzyy() { return reinterpret_cast<swizzle_type<0, 2, 1, 1>&>(arr); };
swizzle_type<0, 2, 1, 2>& xzyz() { return reinterpret_cast<swizzle_type<0, 2, 1, 2>&>(arr); };
swizzle_type<0, 2, 2, 0>& xzzx() { return reinterpret_cast<swizzle_type<0, 2, 2, 0>&>(arr); };
swizzle_type<0, 2, 2, 1>& xzzy() { return reinterpret_cast<swizzle_type<0, 2, 2, 1>&>(arr); };
swizzle_type<0, 2, 2, 2>& xzzz() { return reinterpret_cast<swizzle_type<0, 2, 2, 2>&>(arr); };
swizzle_type<1, 0, 0, 0>& yxxx() { return reinterpret_cast<swizzle_type<1, 0, 0, 0>&>(arr); };
swizzle_type<1, 0, 0, 1>& yxxy() { return reinterpret_cast<swizzle_type<1, 0, 0, 1>&>(arr); };
swizzle_type<1, 0, 0, 2>& yxxz() { return reinterpret_cast<swizzle_type<1, 0, 0, 2>&>(arr); };
swizzle_type<1, 0, 1, 0>& yxyx() { return reinterpret_cast<swizzle_type<1, 0, 1, 0>&>(arr); };
swizzle_type<1, 0, 1, 1>& yxyy() { return reinterpret_cast<swizzle_type<1, 0, 1, 1>&>(arr); };
swizzle_type<1, 0, 1, 2>& yxyz() { return reinterpret_cast<swizzle_type<1, 0, 1, 2>&>(arr); };
swizzle_type<1, 0, 2, 0>& yxzx() { return reinterpret_cast<swizzle_type<1, 0, 2, 0>&>(arr); };
swizzle_type<1, 0, 2, 1>& yxzy() { return reinterpret_cast<swizzle_type<1, 0, 2, 1>&>(arr); };
swizzle_type<1, 0, 2, 2>& yxzz() { return reinterpret_cast<swizzle_type<1, 0, 2, 2>&>(arr); };
swizzle_type<1, 1, 0, 0>& yyxx() { return reinterpret_cast<swizzle_type<1, 1, 0, 0>&>(arr); };
swizzle_type<1, 1, 0, 1>& yyxy() { return reinterpret_cast<swizzle_type<1, 1, 0, 1>&>(arr); };
swizzle_type<1, 1, 0, 2>& yyxz() { return reinterpret_cast<swizzle_type<1, 1, 0, 2>&>(arr); };
swizzle_type<1, 1, 1, 0>& yyyx() { return reinterpret_cast<swizzle_type<1, 1, 1, 0>&>(arr); };
swizzle_type<1, 1, 1, 1>& yyyy() { return reinterpret_cast<swizzle_type<1, 1, 1, 1>&>(arr); };
swizzle_type<1, 1, 1, 2>& yyyz() { return reinterpret_cast<swizzle_type<1, 1, 1, 2>&>(arr); };
swizzle_type<1, 1, 2, 0>& yyzx() { return reinterpret_cast<swizzle_type<1, 1, 2, 0>&>(arr); };
swizzle_type<1, 1, 2, 1>& yyzy() { return reinterpret_cast<swizzle_type<1, 1, 2, 1>&>(arr); };
swizzle_type<1, 1, 2, 2>& yyzz() { return reinterpret_cast<swizzle_type<1, 1, 2, 2>&>(arr); };
swizzle_type<1, 2, 0, 0>& yzxx() { return reinterpret_cast<swizzle_type<1, 2, 0, 0>&>(arr); };
swizzle_type<1, 2, 0, 1>& yzxy() { return reinterpret_cast<swizzle_type<1, 2, 0, 1>&>(arr); };
swizzle_type<1, 2, 0, 2>& yzxz() { return reinterpret_cast<swizzle_type<1, 2, 0, 2>&>(arr); };
swizzle_type<1, 2, 1, 0>& yzyx() { return reinterpret_cast<swizzle_type<1, 2, 1, 0>&>(arr); };
swizzle_type<1, 2, 1, 1>& yzyy() { return reinterpret_cast<swizzle_type<1, 2, 1, 1>&>(arr); };
swizzle_type<1, 2, 1, 2>& yzyz() { return reinterpret_cast<swizzle_type<1, 2, 1, 2>&>(arr); };
swizzle_type<1, 2, 2, 0>& yzzx() { return reinterpret_cast<swizzle_type<1, 2, 2, 0>&>(arr); };
swizzle_type<1, 2, 2, 1>& yzzy() { return reinterpret_cast<swizzle_type<1, 2, 2, 1>&>(arr); };
swizzle_type<1, 2, 2, 2>& yzzz() { return reinterpret_cast<swizzle_type<1, 2, 2, 2>&>(arr); };
swizzle_type<2, 0, 0, 0>& zxxx() { return reinterpret_cast<swizzle_type<2, 0, 0, 0>&>(arr); };
swizzle_type<2, 0, 0, 1>& zxxy() { return reinterpret_cast<swizzle_type<2, 0, 0, 1>&>(arr); };
swizzle_type<2, 0, 0, 2>& zxxz() { return reinterpret_cast<swizzle_type<2, 0, 0, 2>&>(arr); };
swizzle_type<2, 0, 1, 0>& zxyx() { return reinterpret_cast<swizzle_type<2, 0, 1, 0>&>(arr); };
swizzle_type<2, 0, 1, 1>& zxyy() { return reinterpret_cast<swizzle_type<2, 0, 1, 1>&>(arr); };
swizzle_type<2, 0, 1, 2>& zxyz() { return reinterpret_cast<swizzle_type<2, 0, 1, 2>&>(arr); };
swizzle_type<2, 0, 2, 0>& zxzx() { return reinterpret_cast<swizzle_type<2, 0, 2, 0>&>(arr); };
swizzle_type<2, 0, 2, 1>& zxzy() { return reinterpret_cast<swizzle_type<2, 0, 2, 1>&>(arr); };
swizzle_type<2, 0, 2, 2>& zxzz() { return reinterpret_cast<swizzle_type<2, 0, 2, 2>&>(arr); };
swizzle_type<2, 1, 0, 0>& zyxx() { return reinterpret_cast<swizzle_type<2, 1, 0, 0>&>(arr); };
swizzle_type<2, 1, 0, 1>& zyxy() { return reinterpret_cast<swizzle_type<2, 1, 0, 1>&>(arr); };
swizzle_type<2, 1, 0, 2>& zyxz() { return reinterpret_cast<swizzle_type<2, 1, 0, 2>&>(arr); };
swizzle_type<2, 1, 1, 0>& zyyx() { return reinterpret_cast<swizzle_type<2, 1, 1, 0>&>(arr); };
swizzle_type<2, 1, 1, 1>& zyyy() { return reinterpret_cast<swizzle_type<2, 1, 1, 1>&>(arr); };
swizzle_type<2, 1, 1, 2>& zyyz() { return reinterpret_cast<swizzle_type<2, 1, 1, 2>&>(arr); };
swizzle_type<2, 1, 2, 0>& zyzx() { return reinterpret_cast<swizzle_type<2, 1, 2, 0>&>(arr); };
swizzle_type<2, 1, 2, 1>& zyzy() { return reinterpret_cast<swizzle_type<2, 1, 2, 1>&>(arr); };
swizzle_type<2, 1, 2, 2>& zyzz() { return reinterpret_cast<swizzle_type<2, 1, 2, 2>&>(arr); };
swizzle_type<2, 2, 0, 0>& zzxx() { return reinterpret_cast<swizzle_type<2, 2, 0, 0>&>(arr); };
swizzle_type<2, 2, 0, 1>& zzxy() { return reinterpret_cast<swizzle_type<2, 2, 0, 1>&>(arr); };
swizzle_type<2, 2, 0, 2>& zzxz() { return reinterpret_cast<swizzle_type<2, 2, 0, 2>&>(arr); };
swizzle_type<2, 2, 1, 0>& zzyx() { return reinterpret_cast<swizzle_type<2, 2, 1, 0>&>(arr); };
swizzle_type<2, 2, 1, 1>& zzyy() { return reinterpret_cast<swizzle_type<2, 2, 1, 1>&>(arr); };
swizzle_type<2, 2, 1, 2>& zzyz() { return reinterpret_cast<swizzle_type<2, 2, 1, 2>&>(arr); };
swizzle_type<2, 2, 2, 0>& zzzx() { return reinterpret_cast<swizzle_type<2, 2, 2, 0>&>(arr); };
swizzle_type<2, 2, 2, 1>& zzzy() { return reinterpret_cast<swizzle_type<2, 2, 2, 1>&>(arr); };
swizzle_type<2, 2, 2, 2>& zzzz() { return reinterpret_cast<swizzle_type<2, 2, 2, 2>&>(arr); };
