
[[nodiscard]] auto xx_() const { return as_vec2().xx_(); }
[[nodiscard]] auto xy_() const { return as_vec2().xy_(); }
[[nodiscard]] auto xz_() const { return as_vec2().xz_(); }
[[nodiscard]] auto xw_() const { return as_vec2().xw_(); }
[[nodiscard]] auto yx_() const { return as_vec2().yx_(); }
[[nodiscard]] auto yy_() const { return as_vec2().yy_(); }
[[nodiscard]] auto yz_() const { return as_vec2().yz_(); }
[[nodiscard]] auto yw_() const { return as_vec2().yw_(); }
[[nodiscard]] auto zx_() const { return as_vec2().zx_(); }
[[nodiscard]] auto zy_() const { return as_vec2().zy_(); }
[[nodiscard]] auto zz_() const { return as_vec2().zz_(); }
[[nodiscard]] auto zw_() const { return as_vec2().zw_(); }
[[nodiscard]] auto wx_() const { return as_vec2().wx_(); }
[[nodiscard]] auto wy_() const { return as_vec2().wy_(); }
[[nodiscard]] auto wz_() const { return as_vec2().wz_(); }
[[nodiscard]] auto ww_() const { return as_vec2().ww_(); }

[[nodiscard]] auto xxx_() const { return as_vec3().xxx_(); }
[[nodiscard]] auto xxy_() const { return as_vec3().xxy_(); }
[[nodiscard]] auto xxz_() const { return as_vec3().xxz_(); }
[[nodiscard]] auto xxw_() const { return as_vec3().xxw_(); }
[[nodiscard]] auto xyx_() const { return as_vec3().xyx_(); }
[[nodiscard]] auto xyy_() const { return as_vec3().xyy_(); }
[[nodiscard]] auto xyz_() const { return as_vec3().xyz_(); }
[[nodiscard]] auto xyw_() const { return as_vec3().xyw_(); }
[[nodiscard]] auto xzx_() const { return as_vec3().xzx_(); }
[[nodiscard]] auto xzy_() const { return as_vec3().xzy_(); }
[[nodiscard]] auto xzz_() const { return as_vec3().xzz_(); }
[[nodiscard]] auto xzw_() const { return as_vec3().xzw_(); }
[[nodiscard]] auto xwx_() const { return as_vec3().xwx_(); }
[[nodiscard]] auto xwy_() const { return as_vec3().xwy_(); }
[[nodiscard]] auto xwz_() const { return as_vec3().xwz_(); }
[[nodiscard]] auto xww_() const { return as_vec3().xww_(); }
[[nodiscard]] auto yxx_() const { return as_vec3().yxx_(); }
[[nodiscard]] auto yxy_() const { return as_vec3().yxy_(); }
[[nodiscard]] auto yxz_() const { return as_vec3().yxz_(); }
[[nodiscard]] auto yxw_() const { return as_vec3().yxw_(); }
[[nodiscard]] auto yyx_() const { return as_vec3().yyx_(); }
[[nodiscard]] auto yyy_() const { return as_vec3().yyy_(); }
[[nodiscard]] auto yyz_() const { return as_vec3().yyz_(); }
[[nodiscard]] auto yyw_() const { return as_vec3().yyw_(); }
[[nodiscard]] auto yzx_() const { return as_vec3().yzx_(); }
[[nodiscard]] auto yzy_() const { return as_vec3().yzy_(); }
[[nodiscard]] auto yzz_() const { return as_vec3().yzz_(); }
[[nodiscard]] auto yzw_() const { return as_vec3().yzw_(); }
[[nodiscard]] auto ywx_() const { return as_vec3().ywx_(); }
[[nodiscard]] auto ywy_() const { return as_vec3().ywy_(); }
[[nodiscard]] auto ywz_() const { return as_vec3().ywz_(); }
[[nodiscard]] auto yww_() const { return as_vec3().yww_(); }
[[nodiscard]] auto zxx_() const { return as_vec3().zxx_(); }
[[nodiscard]] auto zxy_() const { return as_vec3().zxy_(); }
[[nodiscard]] auto zxz_() const { return as_vec3().zxz_(); }
[[nodiscard]] auto zxw_() const { return as_vec3().zxw_(); }
[[nodiscard]] auto zyx_() const { return as_vec3().zyx_(); }
[[nodiscard]] auto zyy_() const { return as_vec3().zyy_(); }
[[nodiscard]] auto zyz_() const { return as_vec3().zyz_(); }
[[nodiscard]] auto zyw_() const { return as_vec3().zyw_(); }
[[nodiscard]] auto zzx_() const { return as_vec3().zzx_(); }
[[nodiscard]] auto zzy_() const { return as_vec3().zzy_(); }
[[nodiscard]] auto zzz_() const { return as_vec3().zzz_(); }
[[nodiscard]] auto zzw_() const { return as_vec3().zzw_(); }
[[nodiscard]] auto zwx_() const { return as_vec3().zwx_(); }
[[nodiscard]] auto zwy_() const { return as_vec3().zwy_(); }
[[nodiscard]] auto zwz_() const { return as_vec3().zwz_(); }
[[nodiscard]] auto zww_() const { return as_vec3().zww_(); }
[[nodiscard]] auto wxx_() const { return as_vec3().wxx_(); }
[[nodiscard]] auto wxy_() const { return as_vec3().wxy_(); }
[[nodiscard]] auto wxz_() const { return as_vec3().wxz_(); }
[[nodiscard]] auto wxw_() const { return as_vec3().wxw_(); }
[[nodiscard]] auto wyx_() const { return as_vec3().wyx_(); }
[[nodiscard]] auto wyy_() const { return as_vec3().wyy_(); }
[[nodiscard]] auto wyz_() const { return as_vec3().wyz_(); }
[[nodiscard]] auto wyw_() const { return as_vec3().wyw_(); }
[[nodiscard]] auto wzx_() const { return as_vec3().wzx_(); }
[[nodiscard]] auto wzy_() const { return as_vec3().wzy_(); }
[[nodiscard]] auto wzz_() const { return as_vec3().wzz_(); }
[[nodiscard]] auto wzw_() const { return as_vec3().wzw_(); }
[[nodiscard]] auto wwx_() const { return as_vec3().wwx_(); }
[[nodiscard]] auto wwy_() const { return as_vec3().wwy_(); }
[[nodiscard]] auto wwz_() const { return as_vec3().wwz_(); }
[[nodiscard]] auto www_() const { return as_vec3().www_(); }

[[nodiscard]] auto xxxx_() const { return as_vec4().xxxx_(); }
[[nodiscard]] auto xxxy_() const { return as_vec4().xxxy_(); }
[[nodiscard]] auto xxxz_() const { return as_vec4().xxxz_(); }
[[nodiscard]] auto xxxw_() const { return as_vec4().xxxw_(); }
[[nodiscard]] auto xxyx_() const { return as_vec4().xxyx_(); }
[[nodiscard]] auto xxyy_() const { return as_vec4().xxyy_(); }
[[nodiscard]] auto xxyz_() const { return as_vec4().xxyz_(); }
[[nodiscard]] auto xxyw_() const { return as_vec4().xxyw_(); }
[[nodiscard]] auto xxzx_() const { return as_vec4().xxzx_(); }
[[nodiscard]] auto xxzy_() const { return as_vec4().xxzy_(); }
[[nodiscard]] auto xxzz_() const { return as_vec4().xxzz_(); }
[[nodiscard]] auto xxzw_() const { return as_vec4().xxzw_(); }
[[nodiscard]] auto xxwx_() const { return as_vec4().xxwx_(); }
[[nodiscard]] auto xxwy_() const { return as_vec4().xxwy_(); }
[[nodiscard]] auto xxwz_() const { return as_vec4().xxwz_(); }
[[nodiscard]] auto xxww_() const { return as_vec4().xxww_(); }
[[nodiscard]] auto xyxx_() const { return as_vec4().xyxx_(); }
[[nodiscard]] auto xyxy_() const { return as_vec4().xyxy_(); }
[[nodiscard]] auto xyxz_() const { return as_vec4().xyxz_(); }
[[nodiscard]] auto xyxw_() const { return as_vec4().xyxw_(); }
[[nodiscard]] auto xyyx_() const { return as_vec4().xyyx_(); }
[[nodiscard]] auto xyyy_() const { return as_vec4().xyyy_(); }
[[nodiscard]] auto xyyz_() const { return as_vec4().xyyz_(); }
[[nodiscard]] auto xyyw_() const { return as_vec4().xyyw_(); }
[[nodiscard]] auto xyzx_() const { return as_vec4().xyzx_(); }
[[nodiscard]] auto xyzy_() const { return as_vec4().xyzy_(); }
[[nodiscard]] auto xyzz_() const { return as_vec4().xyzz_(); }
[[nodiscard]] auto xyzw_() const { return as_vec4().xyzw_(); }
[[nodiscard]] auto xywx_() const { return as_vec4().xywx_(); }
[[nodiscard]] auto xywy_() const { return as_vec4().xywy_(); }
[[nodiscard]] auto xywz_() const { return as_vec4().xywz_(); }
[[nodiscard]] auto xyww_() const { return as_vec4().xyww_(); }
[[nodiscard]] auto xzxx_() const { return as_vec4().xzxx_(); }
[[nodiscard]] auto xzxy_() const { return as_vec4().xzxy_(); }
[[nodiscard]] auto xzxz_() const { return as_vec4().xzxz_(); }
[[nodiscard]] auto xzxw_() const { return as_vec4().xzxw_(); }
[[nodiscard]] auto xzyx_() const { return as_vec4().xzyx_(); }
[[nodiscard]] auto xzyy_() const { return as_vec4().xzyy_(); }
[[nodiscard]] auto xzyz_() const { return as_vec4().xzyz_(); }
[[nodiscard]] auto xzyw_() const { return as_vec4().xzyw_(); }
[[nodiscard]] auto xzzx_() const { return as_vec4().xzzx_(); }
[[nodiscard]] auto xzzy_() const { return as_vec4().xzzy_(); }
[[nodiscard]] auto xzzz_() const { return as_vec4().xzzz_(); }
[[nodiscard]] auto xzzw_() const { return as_vec4().xzzw_(); }
[[nodiscard]] auto xzwx_() const { return as_vec4().xzwx_(); }
[[nodiscard]] auto xzwy_() const { return as_vec4().xzwy_(); }
[[nodiscard]] auto xzwz_() const { return as_vec4().xzwz_(); }
[[nodiscard]] auto xzww_() const { return as_vec4().xzww_(); }
[[nodiscard]] auto xwxx_() const { return as_vec4().xwxx_(); }
[[nodiscard]] auto xwxy_() const { return as_vec4().xwxy_(); }
[[nodiscard]] auto xwxz_() const { return as_vec4().xwxz_(); }
[[nodiscard]] auto xwxw_() const { return as_vec4().xwxw_(); }
[[nodiscard]] auto xwyx_() const { return as_vec4().xwyx_(); }
[[nodiscard]] auto xwyy_() const { return as_vec4().xwyy_(); }
[[nodiscard]] auto xwyz_() const { return as_vec4().xwyz_(); }
[[nodiscard]] auto xwyw_() const { return as_vec4().xwyw_(); }
[[nodiscard]] auto xwzx_() const { return as_vec4().xwzx_(); }
[[nodiscard]] auto xwzy_() const { return as_vec4().xwzy_(); }
[[nodiscard]] auto xwzz_() const { return as_vec4().xwzz_(); }
[[nodiscard]] auto xwzw_() const { return as_vec4().xwzw_(); }
[[nodiscard]] auto xwwx_() const { return as_vec4().xwwx_(); }
[[nodiscard]] auto xwwy_() const { return as_vec4().xwwy_(); }
[[nodiscard]] auto xwwz_() const { return as_vec4().xwwz_(); }
[[nodiscard]] auto xwww_() const { return as_vec4().xwww_(); }
[[nodiscard]] auto yxxx_() const { return as_vec4().yxxx_(); }
[[nodiscard]] auto yxxy_() const { return as_vec4().yxxy_(); }
[[nodiscard]] auto yxxz_() const { return as_vec4().yxxz_(); }
[[nodiscard]] auto yxxw_() const { return as_vec4().yxxw_(); }
[[nodiscard]] auto yxyx_() const { return as_vec4().yxyx_(); }
[[nodiscard]] auto yxyy_() const { return as_vec4().yxyy_(); }
[[nodiscard]] auto yxyz_() const { return as_vec4().yxyz_(); }
[[nodiscard]] auto yxyw_() const { return as_vec4().yxyw_(); }
[[nodiscard]] auto yxzx_() const { return as_vec4().yxzx_(); }
[[nodiscard]] auto yxzy_() const { return as_vec4().yxzy_(); }
[[nodiscard]] auto yxzz_() const { return as_vec4().yxzz_(); }
[[nodiscard]] auto yxzw_() const { return as_vec4().yxzw_(); }
[[nodiscard]] auto yxwx_() const { return as_vec4().yxwx_(); }
[[nodiscard]] auto yxwy_() const { return as_vec4().yxwy_(); }
[[nodiscard]] auto yxwz_() const { return as_vec4().yxwz_(); }
[[nodiscard]] auto yxww_() const { return as_vec4().yxww_(); }
[[nodiscard]] auto yyxx_() const { return as_vec4().yyxx_(); }
[[nodiscard]] auto yyxy_() const { return as_vec4().yyxy_(); }
[[nodiscard]] auto yyxz_() const { return as_vec4().yyxz_(); }
[[nodiscard]] auto yyxw_() const { return as_vec4().yyxw_(); }
[[nodiscard]] auto yyyx_() const { return as_vec4().yyyx_(); }
[[nodiscard]] auto yyyy_() const { return as_vec4().yyyy_(); }
[[nodiscard]] auto yyyz_() const { return as_vec4().yyyz_(); }
[[nodiscard]] auto yyyw_() const { return as_vec4().yyyw_(); }
[[nodiscard]] auto yyzx_() const { return as_vec4().yyzx_(); }
[[nodiscard]] auto yyzy_() const { return as_vec4().yyzy_(); }
[[nodiscard]] auto yyzz_() const { return as_vec4().yyzz_(); }
[[nodiscard]] auto yyzw_() const { return as_vec4().yyzw_(); }
[[nodiscard]] auto yywx_() const { return as_vec4().yywx_(); }
[[nodiscard]] auto yywy_() const { return as_vec4().yywy_(); }
[[nodiscard]] auto yywz_() const { return as_vec4().yywz_(); }
[[nodiscard]] auto yyww_() const { return as_vec4().yyww_(); }
[[nodiscard]] auto yzxx_() const { return as_vec4().yzxx_(); }
[[nodiscard]] auto yzxy_() const { return as_vec4().yzxy_(); }
[[nodiscard]] auto yzxz_() const { return as_vec4().yzxz_(); }
[[nodiscard]] auto yzxw_() const { return as_vec4().yzxw_(); }
[[nodiscard]] auto yzyx_() const { return as_vec4().yzyx_(); }
[[nodiscard]] auto yzyy_() const { return as_vec4().yzyy_(); }
[[nodiscard]] auto yzyz_() const { return as_vec4().yzyz_(); }
[[nodiscard]] auto yzyw_() const { return as_vec4().yzyw_(); }
[[nodiscard]] auto yzzx_() const { return as_vec4().yzzx_(); }
[[nodiscard]] auto yzzy_() const { return as_vec4().yzzy_(); }
[[nodiscard]] auto yzzz_() const { return as_vec4().yzzz_(); }
[[nodiscard]] auto yzzw_() const { return as_vec4().yzzw_(); }
[[nodiscard]] auto yzwx_() const { return as_vec4().yzwx_(); }
[[nodiscard]] auto yzwy_() const { return as_vec4().yzwy_(); }
[[nodiscard]] auto yzwz_() const { return as_vec4().yzwz_(); }
[[nodiscard]] auto yzww_() const { return as_vec4().yzww_(); }
[[nodiscard]] auto ywxx_() const { return as_vec4().ywxx_(); }
[[nodiscard]] auto ywxy_() const { return as_vec4().ywxy_(); }
[[nodiscard]] auto ywxz_() const { return as_vec4().ywxz_(); }
[[nodiscard]] auto ywxw_() const { return as_vec4().ywxw_(); }
[[nodiscard]] auto ywyx_() const { return as_vec4().ywyx_(); }
[[nodiscard]] auto ywyy_() const { return as_vec4().ywyy_(); }
[[nodiscard]] auto ywyz_() const { return as_vec4().ywyz_(); }
[[nodiscard]] auto ywyw_() const { return as_vec4().ywyw_(); }
[[nodiscard]] auto ywzx_() const { return as_vec4().ywzx_(); }
[[nodiscard]] auto ywzy_() const { return as_vec4().ywzy_(); }
[[nodiscard]] auto ywzz_() const { return as_vec4().ywzz_(); }
[[nodiscard]] auto ywzw_() const { return as_vec4().ywzw_(); }
[[nodiscard]] auto ywwx_() const { return as_vec4().ywwx_(); }
[[nodiscard]] auto ywwy_() const { return as_vec4().ywwy_(); }
[[nodiscard]] auto ywwz_() const { return as_vec4().ywwz_(); }
[[nodiscard]] auto ywww_() const { return as_vec4().ywww_(); }
[[nodiscard]] auto zxxx_() const { return as_vec4().zxxx_(); }
[[nodiscard]] auto zxxy_() const { return as_vec4().zxxy_(); }
[[nodiscard]] auto zxxz_() const { return as_vec4().zxxz_(); }
[[nodiscard]] auto zxxw_() const { return as_vec4().zxxw_(); }
[[nodiscard]] auto zxyx_() const { return as_vec4().zxyx_(); }
[[nodiscard]] auto zxyy_() const { return as_vec4().zxyy_(); }
[[nodiscard]] auto zxyz_() const { return as_vec4().zxyz_(); }
[[nodiscard]] auto zxyw_() const { return as_vec4().zxyw_(); }
[[nodiscard]] auto zxzx_() const { return as_vec4().zxzx_(); }
[[nodiscard]] auto zxzy_() const { return as_vec4().zxzy_(); }
[[nodiscard]] auto zxzz_() const { return as_vec4().zxzz_(); }
[[nodiscard]] auto zxzw_() const { return as_vec4().zxzw_(); }
[[nodiscard]] auto zxwx_() const { return as_vec4().zxwx_(); }
[[nodiscard]] auto zxwy_() const { return as_vec4().zxwy_(); }
[[nodiscard]] auto zxwz_() const { return as_vec4().zxwz_(); }
[[nodiscard]] auto zxww_() const { return as_vec4().zxww_(); }
[[nodiscard]] auto zyxx_() const { return as_vec4().zyxx_(); }
[[nodiscard]] auto zyxy_() const { return as_vec4().zyxy_(); }
[[nodiscard]] auto zyxz_() const { return as_vec4().zyxz_(); }
[[nodiscard]] auto zyxw_() const { return as_vec4().zyxw_(); }
[[nodiscard]] auto zyyx_() const { return as_vec4().zyyx_(); }
[[nodiscard]] auto zyyy_() const { return as_vec4().zyyy_(); }
[[nodiscard]] auto zyyz_() const { return as_vec4().zyyz_(); }
[[nodiscard]] auto zyyw_() const { return as_vec4().zyyw_(); }
[[nodiscard]] auto zyzx_() const { return as_vec4().zyzx_(); }
[[nodiscard]] auto zyzy_() const { return as_vec4().zyzy_(); }
[[nodiscard]] auto zyzz_() const { return as_vec4().zyzz_(); }
[[nodiscard]] auto zyzw_() const { return as_vec4().zyzw_(); }
[[nodiscard]] auto zywx_() const { return as_vec4().zywx_(); }
[[nodiscard]] auto zywy_() const { return as_vec4().zywy_(); }
[[nodiscard]] auto zywz_() const { return as_vec4().zywz_(); }
[[nodiscard]] auto zyww_() const { return as_vec4().zyww_(); }
[[nodiscard]] auto zzxx_() const { return as_vec4().zzxx_(); }
[[nodiscard]] auto zzxy_() const { return as_vec4().zzxy_(); }
[[nodiscard]] auto zzxz_() const { return as_vec4().zzxz_(); }
[[nodiscard]] auto zzxw_() const { return as_vec4().zzxw_(); }
[[nodiscard]] auto zzyx_() const { return as_vec4().zzyx_(); }
[[nodiscard]] auto zzyy_() const { return as_vec4().zzyy_(); }
[[nodiscard]] auto zzyz_() const { return as_vec4().zzyz_(); }
[[nodiscard]] auto zzyw_() const { return as_vec4().zzyw_(); }
[[nodiscard]] auto zzzx_() const { return as_vec4().zzzx_(); }
[[nodiscard]] auto zzzy_() const { return as_vec4().zzzy_(); }
[[nodiscard]] auto zzzz_() const { return as_vec4().zzzz_(); }
[[nodiscard]] auto zzzw_() const { return as_vec4().zzzw_(); }
[[nodiscard]] auto zzwx_() const { return as_vec4().zzwx_(); }
[[nodiscard]] auto zzwy_() const { return as_vec4().zzwy_(); }
[[nodiscard]] auto zzwz_() const { return as_vec4().zzwz_(); }
[[nodiscard]] auto zzww_() const { return as_vec4().zzww_(); }
[[nodiscard]] auto zwxx_() const { return as_vec4().zwxx_(); }
[[nodiscard]] auto zwxy_() const { return as_vec4().zwxy_(); }
[[nodiscard]] auto zwxz_() const { return as_vec4().zwxz_(); }
[[nodiscard]] auto zwxw_() const { return as_vec4().zwxw_(); }
[[nodiscard]] auto zwyx_() const { return as_vec4().zwyx_(); }
[[nodiscard]] auto zwyy_() const { return as_vec4().zwyy_(); }
[[nodiscard]] auto zwyz_() const { return as_vec4().zwyz_(); }
[[nodiscard]] auto zwyw_() const { return as_vec4().zwyw_(); }
[[nodiscard]] auto zwzx_() const { return as_vec4().zwzx_(); }
[[nodiscard]] auto zwzy_() const { return as_vec4().zwzy_(); }
[[nodiscard]] auto zwzz_() const { return as_vec4().zwzz_(); }
[[nodiscard]] auto zwzw_() const { return as_vec4().zwzw_(); }
[[nodiscard]] auto zwwx_() const { return as_vec4().zwwx_(); }
[[nodiscard]] auto zwwy_() const { return as_vec4().zwwy_(); }
[[nodiscard]] auto zwwz_() const { return as_vec4().zwwz_(); }
[[nodiscard]] auto zwww_() const { return as_vec4().zwww_(); }
[[nodiscard]] auto wxxx_() const { return as_vec4().wxxx_(); }
[[nodiscard]] auto wxxy_() const { return as_vec4().wxxy_(); }
[[nodiscard]] auto wxxz_() const { return as_vec4().wxxz_(); }
[[nodiscard]] auto wxxw_() const { return as_vec4().wxxw_(); }
[[nodiscard]] auto wxyx_() const { return as_vec4().wxyx_(); }
[[nodiscard]] auto wxyy_() const { return as_vec4().wxyy_(); }
[[nodiscard]] auto wxyz_() const { return as_vec4().wxyz_(); }
[[nodiscard]] auto wxyw_() const { return as_vec4().wxyw_(); }
[[nodiscard]] auto wxzx_() const { return as_vec4().wxzx_(); }
[[nodiscard]] auto wxzy_() const { return as_vec4().wxzy_(); }
[[nodiscard]] auto wxzz_() const { return as_vec4().wxzz_(); }
[[nodiscard]] auto wxzw_() const { return as_vec4().wxzw_(); }
[[nodiscard]] auto wxwx_() const { return as_vec4().wxwx_(); }
[[nodiscard]] auto wxwy_() const { return as_vec4().wxwy_(); }
[[nodiscard]] auto wxwz_() const { return as_vec4().wxwz_(); }
[[nodiscard]] auto wxww_() const { return as_vec4().wxww_(); }
[[nodiscard]] auto wyxx_() const { return as_vec4().wyxx_(); }
[[nodiscard]] auto wyxy_() const { return as_vec4().wyxy_(); }
[[nodiscard]] auto wyxz_() const { return as_vec4().wyxz_(); }
[[nodiscard]] auto wyxw_() const { return as_vec4().wyxw_(); }
[[nodiscard]] auto wyyx_() const { return as_vec4().wyyx_(); }
[[nodiscard]] auto wyyy_() const { return as_vec4().wyyy_(); }
[[nodiscard]] auto wyyz_() const { return as_vec4().wyyz_(); }
[[nodiscard]] auto wyyw_() const { return as_vec4().wyyw_(); }
[[nodiscard]] auto wyzx_() const { return as_vec4().wyzx_(); }
[[nodiscard]] auto wyzy_() const { return as_vec4().wyzy_(); }
[[nodiscard]] auto wyzz_() const { return as_vec4().wyzz_(); }
[[nodiscard]] auto wyzw_() const { return as_vec4().wyzw_(); }
[[nodiscard]] auto wywx_() const { return as_vec4().wywx_(); }
[[nodiscard]] auto wywy_() const { return as_vec4().wywy_(); }
[[nodiscard]] auto wywz_() const { return as_vec4().wywz_(); }
[[nodiscard]] auto wyww_() const { return as_vec4().wyww_(); }
[[nodiscard]] auto wzxx_() const { return as_vec4().wzxx_(); }
[[nodiscard]] auto wzxy_() const { return as_vec4().wzxy_(); }
[[nodiscard]] auto wzxz_() const { return as_vec4().wzxz_(); }
[[nodiscard]] auto wzxw_() const { return as_vec4().wzxw_(); }
[[nodiscard]] auto wzyx_() const { return as_vec4().wzyx_(); }
[[nodiscard]] auto wzyy_() const { return as_vec4().wzyy_(); }
[[nodiscard]] auto wzyz_() const { return as_vec4().wzyz_(); }
[[nodiscard]] auto wzyw_() const { return as_vec4().wzyw_(); }
[[nodiscard]] auto wzzx_() const { return as_vec4().wzzx_(); }
[[nodiscard]] auto wzzy_() const { return as_vec4().wzzy_(); }
[[nodiscard]] auto wzzz_() const { return as_vec4().wzzz_(); }
[[nodiscard]] auto wzzw_() const { return as_vec4().wzzw_(); }
[[nodiscard]] auto wzwx_() const { return as_vec4().wzwx_(); }
[[nodiscard]] auto wzwy_() const { return as_vec4().wzwy_(); }
[[nodiscard]] auto wzwz_() const { return as_vec4().wzwz_(); }
[[nodiscard]] auto wzww_() const { return as_vec4().wzww_(); }
[[nodiscard]] auto wwxx_() const { return as_vec4().wwxx_(); }
[[nodiscard]] auto wwxy_() const { return as_vec4().wwxy_(); }
[[nodiscard]] auto wwxz_() const { return as_vec4().wwxz_(); }
[[nodiscard]] auto wwxw_() const { return as_vec4().wwxw_(); }
[[nodiscard]] auto wwyx_() const { return as_vec4().wwyx_(); }
[[nodiscard]] auto wwyy_() const { return as_vec4().wwyy_(); }
[[nodiscard]] auto wwyz_() const { return as_vec4().wwyz_(); }
[[nodiscard]] auto wwyw_() const { return as_vec4().wwyw_(); }
[[nodiscard]] auto wwzx_() const { return as_vec4().wwzx_(); }
[[nodiscard]] auto wwzy_() const { return as_vec4().wwzy_(); }
[[nodiscard]] auto wwzz_() const { return as_vec4().wwzz_(); }
[[nodiscard]] auto wwzw_() const { return as_vec4().wwzw_(); }
[[nodiscard]] auto wwwx_() const { return as_vec4().wwwx_(); }
[[nodiscard]] auto wwwy_() const { return as_vec4().wwwy_(); }
[[nodiscard]] auto wwwz_() const { return as_vec4().wwwz_(); }
[[nodiscard]] auto wwww_() const { return as_vec4().wwww_(); }
