[[nodiscard]] auto xx_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x00, 2)); }
[[nodiscard]] auto xy_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x01, 2)); }
[[nodiscard]] auto yx_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x10, 2)); }
[[nodiscard]] auto yy_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x11, 2)); }

[[nodiscard]] auto xxx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x000, 3)); }
[[nodiscard]] auto xxy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x001, 3)); }
[[nodiscard]] auto xyx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x010, 3)); }
[[nodiscard]] auto xyy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x011, 3)); }
[[nodiscard]] auto yxx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x100, 3)); }
[[nodiscard]] auto yxy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x101, 3)); }
[[nodiscard]] auto yyx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x110, 3)); }
[[nodiscard]] auto yyy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x111, 3)); }

[[nodiscard]] auto xxxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0000, 4)); }
[[nodiscard]] auto xxxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0001, 4)); }
[[nodiscard]] auto xxyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0010, 4)); }
[[nodiscard]] auto xxyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0011, 4)); }
[[nodiscard]] auto xyxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0100, 4)); }
[[nodiscard]] auto xyxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0101, 4)); }
[[nodiscard]] auto xyyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0110, 4)); }
[[nodiscard]] auto xyyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0111, 4)); }
[[nodiscard]] auto yxxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1000, 4)); }
[[nodiscard]] auto yxxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1001, 4)); }
[[nodiscard]] auto yxyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1010, 4)); }
[[nodiscard]] auto yxyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1011, 4)); }
[[nodiscard]] auto yyxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1100, 4)); }
[[nodiscard]] auto yyxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1101, 4)); }
[[nodiscard]] auto yyyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1110, 4)); }
[[nodiscard]] auto yyyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1111, 4)); }
