[[nodiscard]] auto xx_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x00, 2)); }
[[nodiscard]] auto xy_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x01, 2)); }
[[nodiscard]] auto xz_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x02, 2)); }
[[nodiscard]] auto xw_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x03, 2)); }
[[nodiscard]] auto yx_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x10, 2)); }
[[nodiscard]] auto yy_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x11, 2)); }
[[nodiscard]] auto yz_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x12, 2)); }
[[nodiscard]] auto yw_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x13, 2)); }
[[nodiscard]] auto zx_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x20, 2)); }
[[nodiscard]] auto zy_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x21, 2)); }
[[nodiscard]] auto zz_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x22, 2)); }
[[nodiscard]] auto zw_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x23, 2)); }
[[nodiscard]] auto wx_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x30, 2)); }
[[nodiscard]] auto wy_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x31, 2)); }
[[nodiscard]] auto wz_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x32, 2)); }
[[nodiscard]] auto ww_() const { return eval<Vector<T, 2>>(Function::current()->swizzle(Type::of<Vector<T, 2>>(), expression(), 0x33, 2)); }

[[nodiscard]] auto xxx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x000, 3)); }
[[nodiscard]] auto xxy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x001, 3)); }
[[nodiscard]] auto xxz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x002, 3)); }
[[nodiscard]] auto xxw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x003, 3)); }
[[nodiscard]] auto xyx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x010, 3)); }
[[nodiscard]] auto xyy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x011, 3)); }
[[nodiscard]] auto xyz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x012, 3)); }
[[nodiscard]] auto xyw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x013, 3)); }
[[nodiscard]] auto xzx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x020, 3)); }
[[nodiscard]] auto xzy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x021, 3)); }
[[nodiscard]] auto xzz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x022, 3)); }
[[nodiscard]] auto xzw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x023, 3)); }
[[nodiscard]] auto xwx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x030, 3)); }
[[nodiscard]] auto xwy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x031, 3)); }
[[nodiscard]] auto xwz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x032, 3)); }
[[nodiscard]] auto xww_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x033, 3)); }
[[nodiscard]] auto yxx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x100, 3)); }
[[nodiscard]] auto yxy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x101, 3)); }
[[nodiscard]] auto yxz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x102, 3)); }
[[nodiscard]] auto yxw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x103, 3)); }
[[nodiscard]] auto yyx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x110, 3)); }
[[nodiscard]] auto yyy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x111, 3)); }
[[nodiscard]] auto yyz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x112, 3)); }
[[nodiscard]] auto yyw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x113, 3)); }
[[nodiscard]] auto yzx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x120, 3)); }
[[nodiscard]] auto yzy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x121, 3)); }
[[nodiscard]] auto yzz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x122, 3)); }
[[nodiscard]] auto yzw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x123, 3)); }
[[nodiscard]] auto ywx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x130, 3)); }
[[nodiscard]] auto ywy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x131, 3)); }
[[nodiscard]] auto ywz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x132, 3)); }
[[nodiscard]] auto yww_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x133, 3)); }
[[nodiscard]] auto zxx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x200, 3)); }
[[nodiscard]] auto zxy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x201, 3)); }
[[nodiscard]] auto zxz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x202, 3)); }
[[nodiscard]] auto zxw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x203, 3)); }
[[nodiscard]] auto zyx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x210, 3)); }
[[nodiscard]] auto zyy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x211, 3)); }
[[nodiscard]] auto zyz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x212, 3)); }
[[nodiscard]] auto zyw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x213, 3)); }
[[nodiscard]] auto zzx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x220, 3)); }
[[nodiscard]] auto zzy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x221, 3)); }
[[nodiscard]] auto zzz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x222, 3)); }
[[nodiscard]] auto zzw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x223, 3)); }
[[nodiscard]] auto zwx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x230, 3)); }
[[nodiscard]] auto zwy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x231, 3)); }
[[nodiscard]] auto zwz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x232, 3)); }
[[nodiscard]] auto zww_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x233, 3)); }
[[nodiscard]] auto wxx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x300, 3)); }
[[nodiscard]] auto wxy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x301, 3)); }
[[nodiscard]] auto wxz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x302, 3)); }
[[nodiscard]] auto wxw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x303, 3)); }
[[nodiscard]] auto wyx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x310, 3)); }
[[nodiscard]] auto wyy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x311, 3)); }
[[nodiscard]] auto wyz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x312, 3)); }
[[nodiscard]] auto wyw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x313, 3)); }
[[nodiscard]] auto wzx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x320, 3)); }
[[nodiscard]] auto wzy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x321, 3)); }
[[nodiscard]] auto wzz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x322, 3)); }
[[nodiscard]] auto wzw_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x323, 3)); }
[[nodiscard]] auto wwx_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x330, 3)); }
[[nodiscard]] auto wwy_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x331, 3)); }
[[nodiscard]] auto wwz_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x332, 3)); }
[[nodiscard]] auto www_() const { return eval<Vector<T, 3>>(Function::current()->swizzle(Type::of<Vector<T, 3>>(), expression(), 0x333, 3)); }

[[nodiscard]] auto xxxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0000, 4)); }
[[nodiscard]] auto xxxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0001, 4)); }
[[nodiscard]] auto xxxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0002, 4)); }
[[nodiscard]] auto xxxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0003, 4)); }
[[nodiscard]] auto xxyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0010, 4)); }
[[nodiscard]] auto xxyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0011, 4)); }
[[nodiscard]] auto xxyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0012, 4)); }
[[nodiscard]] auto xxyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0013, 4)); }
[[nodiscard]] auto xxzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0020, 4)); }
[[nodiscard]] auto xxzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0021, 4)); }
[[nodiscard]] auto xxzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0022, 4)); }
[[nodiscard]] auto xxzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0023, 4)); }
[[nodiscard]] auto xxwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0030, 4)); }
[[nodiscard]] auto xxwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0031, 4)); }
[[nodiscard]] auto xxwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0032, 4)); }
[[nodiscard]] auto xxww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0033, 4)); }
[[nodiscard]] auto xyxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0100, 4)); }
[[nodiscard]] auto xyxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0101, 4)); }
[[nodiscard]] auto xyxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0102, 4)); }
[[nodiscard]] auto xyxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0103, 4)); }
[[nodiscard]] auto xyyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0110, 4)); }
[[nodiscard]] auto xyyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0111, 4)); }
[[nodiscard]] auto xyyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0112, 4)); }
[[nodiscard]] auto xyyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0113, 4)); }
[[nodiscard]] auto xyzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0120, 4)); }
[[nodiscard]] auto xyzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0121, 4)); }
[[nodiscard]] auto xyzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0122, 4)); }
[[nodiscard]] auto xyzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0123, 4)); }
[[nodiscard]] auto xywx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0130, 4)); }
[[nodiscard]] auto xywy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0131, 4)); }
[[nodiscard]] auto xywz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0132, 4)); }
[[nodiscard]] auto xyww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0133, 4)); }
[[nodiscard]] auto xzxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0200, 4)); }
[[nodiscard]] auto xzxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0201, 4)); }
[[nodiscard]] auto xzxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0202, 4)); }
[[nodiscard]] auto xzxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0203, 4)); }
[[nodiscard]] auto xzyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0210, 4)); }
[[nodiscard]] auto xzyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0211, 4)); }
[[nodiscard]] auto xzyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0212, 4)); }
[[nodiscard]] auto xzyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0213, 4)); }
[[nodiscard]] auto xzzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0220, 4)); }
[[nodiscard]] auto xzzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0221, 4)); }
[[nodiscard]] auto xzzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0222, 4)); }
[[nodiscard]] auto xzzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0223, 4)); }
[[nodiscard]] auto xzwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0230, 4)); }
[[nodiscard]] auto xzwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0231, 4)); }
[[nodiscard]] auto xzwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0232, 4)); }
[[nodiscard]] auto xzww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0233, 4)); }
[[nodiscard]] auto xwxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0300, 4)); }
[[nodiscard]] auto xwxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0301, 4)); }
[[nodiscard]] auto xwxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0302, 4)); }
[[nodiscard]] auto xwxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0303, 4)); }
[[nodiscard]] auto xwyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0310, 4)); }
[[nodiscard]] auto xwyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0311, 4)); }
[[nodiscard]] auto xwyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0312, 4)); }
[[nodiscard]] auto xwyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0313, 4)); }
[[nodiscard]] auto xwzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0320, 4)); }
[[nodiscard]] auto xwzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0321, 4)); }
[[nodiscard]] auto xwzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0322, 4)); }
[[nodiscard]] auto xwzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0323, 4)); }
[[nodiscard]] auto xwwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0330, 4)); }
[[nodiscard]] auto xwwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0331, 4)); }
[[nodiscard]] auto xwwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0332, 4)); }
[[nodiscard]] auto xwww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x0333, 4)); }
[[nodiscard]] auto yxxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1000, 4)); }
[[nodiscard]] auto yxxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1001, 4)); }
[[nodiscard]] auto yxxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1002, 4)); }
[[nodiscard]] auto yxxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1003, 4)); }
[[nodiscard]] auto yxyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1010, 4)); }
[[nodiscard]] auto yxyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1011, 4)); }
[[nodiscard]] auto yxyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1012, 4)); }
[[nodiscard]] auto yxyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1013, 4)); }
[[nodiscard]] auto yxzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1020, 4)); }
[[nodiscard]] auto yxzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1021, 4)); }
[[nodiscard]] auto yxzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1022, 4)); }
[[nodiscard]] auto yxzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1023, 4)); }
[[nodiscard]] auto yxwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1030, 4)); }
[[nodiscard]] auto yxwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1031, 4)); }
[[nodiscard]] auto yxwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1032, 4)); }
[[nodiscard]] auto yxww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1033, 4)); }
[[nodiscard]] auto yyxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1100, 4)); }
[[nodiscard]] auto yyxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1101, 4)); }
[[nodiscard]] auto yyxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1102, 4)); }
[[nodiscard]] auto yyxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1103, 4)); }
[[nodiscard]] auto yyyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1110, 4)); }
[[nodiscard]] auto yyyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1111, 4)); }
[[nodiscard]] auto yyyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1112, 4)); }
[[nodiscard]] auto yyyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1113, 4)); }
[[nodiscard]] auto yyzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1120, 4)); }
[[nodiscard]] auto yyzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1121, 4)); }
[[nodiscard]] auto yyzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1122, 4)); }
[[nodiscard]] auto yyzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1123, 4)); }
[[nodiscard]] auto yywx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1130, 4)); }
[[nodiscard]] auto yywy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1131, 4)); }
[[nodiscard]] auto yywz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1132, 4)); }
[[nodiscard]] auto yyww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1133, 4)); }
[[nodiscard]] auto yzxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1200, 4)); }
[[nodiscard]] auto yzxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1201, 4)); }
[[nodiscard]] auto yzxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1202, 4)); }
[[nodiscard]] auto yzxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1203, 4)); }
[[nodiscard]] auto yzyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1210, 4)); }
[[nodiscard]] auto yzyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1211, 4)); }
[[nodiscard]] auto yzyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1212, 4)); }
[[nodiscard]] auto yzyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1213, 4)); }
[[nodiscard]] auto yzzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1220, 4)); }
[[nodiscard]] auto yzzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1221, 4)); }
[[nodiscard]] auto yzzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1222, 4)); }
[[nodiscard]] auto yzzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1223, 4)); }
[[nodiscard]] auto yzwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1230, 4)); }
[[nodiscard]] auto yzwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1231, 4)); }
[[nodiscard]] auto yzwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1232, 4)); }
[[nodiscard]] auto yzww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1233, 4)); }
[[nodiscard]] auto ywxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1300, 4)); }
[[nodiscard]] auto ywxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1301, 4)); }
[[nodiscard]] auto ywxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1302, 4)); }
[[nodiscard]] auto ywxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1303, 4)); }
[[nodiscard]] auto ywyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1310, 4)); }
[[nodiscard]] auto ywyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1311, 4)); }
[[nodiscard]] auto ywyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1312, 4)); }
[[nodiscard]] auto ywyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1313, 4)); }
[[nodiscard]] auto ywzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1320, 4)); }
[[nodiscard]] auto ywzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1321, 4)); }
[[nodiscard]] auto ywzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1322, 4)); }
[[nodiscard]] auto ywzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1323, 4)); }
[[nodiscard]] auto ywwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1330, 4)); }
[[nodiscard]] auto ywwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1331, 4)); }
[[nodiscard]] auto ywwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1332, 4)); }
[[nodiscard]] auto ywww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x1333, 4)); }
[[nodiscard]] auto zxxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2000, 4)); }
[[nodiscard]] auto zxxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2001, 4)); }
[[nodiscard]] auto zxxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2002, 4)); }
[[nodiscard]] auto zxxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2003, 4)); }
[[nodiscard]] auto zxyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2010, 4)); }
[[nodiscard]] auto zxyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2011, 4)); }
[[nodiscard]] auto zxyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2012, 4)); }
[[nodiscard]] auto zxyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2013, 4)); }
[[nodiscard]] auto zxzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2020, 4)); }
[[nodiscard]] auto zxzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2021, 4)); }
[[nodiscard]] auto zxzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2022, 4)); }
[[nodiscard]] auto zxzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2023, 4)); }
[[nodiscard]] auto zxwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2030, 4)); }
[[nodiscard]] auto zxwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2031, 4)); }
[[nodiscard]] auto zxwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2032, 4)); }
[[nodiscard]] auto zxww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2033, 4)); }
[[nodiscard]] auto zyxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2100, 4)); }
[[nodiscard]] auto zyxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2101, 4)); }
[[nodiscard]] auto zyxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2102, 4)); }
[[nodiscard]] auto zyxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2103, 4)); }
[[nodiscard]] auto zyyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2110, 4)); }
[[nodiscard]] auto zyyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2111, 4)); }
[[nodiscard]] auto zyyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2112, 4)); }
[[nodiscard]] auto zyyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2113, 4)); }
[[nodiscard]] auto zyzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2120, 4)); }
[[nodiscard]] auto zyzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2121, 4)); }
[[nodiscard]] auto zyzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2122, 4)); }
[[nodiscard]] auto zyzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2123, 4)); }
[[nodiscard]] auto zywx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2130, 4)); }
[[nodiscard]] auto zywy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2131, 4)); }
[[nodiscard]] auto zywz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2132, 4)); }
[[nodiscard]] auto zyww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2133, 4)); }
[[nodiscard]] auto zzxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2200, 4)); }
[[nodiscard]] auto zzxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2201, 4)); }
[[nodiscard]] auto zzxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2202, 4)); }
[[nodiscard]] auto zzxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2203, 4)); }
[[nodiscard]] auto zzyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2210, 4)); }
[[nodiscard]] auto zzyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2211, 4)); }
[[nodiscard]] auto zzyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2212, 4)); }
[[nodiscard]] auto zzyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2213, 4)); }
[[nodiscard]] auto zzzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2220, 4)); }
[[nodiscard]] auto zzzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2221, 4)); }
[[nodiscard]] auto zzzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2222, 4)); }
[[nodiscard]] auto zzzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2223, 4)); }
[[nodiscard]] auto zzwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2230, 4)); }
[[nodiscard]] auto zzwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2231, 4)); }
[[nodiscard]] auto zzwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2232, 4)); }
[[nodiscard]] auto zzww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2233, 4)); }
[[nodiscard]] auto zwxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2300, 4)); }
[[nodiscard]] auto zwxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2301, 4)); }
[[nodiscard]] auto zwxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2302, 4)); }
[[nodiscard]] auto zwxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2303, 4)); }
[[nodiscard]] auto zwyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2310, 4)); }
[[nodiscard]] auto zwyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2311, 4)); }
[[nodiscard]] auto zwyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2312, 4)); }
[[nodiscard]] auto zwyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2313, 4)); }
[[nodiscard]] auto zwzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2320, 4)); }
[[nodiscard]] auto zwzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2321, 4)); }
[[nodiscard]] auto zwzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2322, 4)); }
[[nodiscard]] auto zwzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2323, 4)); }
[[nodiscard]] auto zwwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2330, 4)); }
[[nodiscard]] auto zwwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2331, 4)); }
[[nodiscard]] auto zwwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2332, 4)); }
[[nodiscard]] auto zwww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x2333, 4)); }
[[nodiscard]] auto wxxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3000, 4)); }
[[nodiscard]] auto wxxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3001, 4)); }
[[nodiscard]] auto wxxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3002, 4)); }
[[nodiscard]] auto wxxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3003, 4)); }
[[nodiscard]] auto wxyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3010, 4)); }
[[nodiscard]] auto wxyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3011, 4)); }
[[nodiscard]] auto wxyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3012, 4)); }
[[nodiscard]] auto wxyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3013, 4)); }
[[nodiscard]] auto wxzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3020, 4)); }
[[nodiscard]] auto wxzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3021, 4)); }
[[nodiscard]] auto wxzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3022, 4)); }
[[nodiscard]] auto wxzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3023, 4)); }
[[nodiscard]] auto wxwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3030, 4)); }
[[nodiscard]] auto wxwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3031, 4)); }
[[nodiscard]] auto wxwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3032, 4)); }
[[nodiscard]] auto wxww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3033, 4)); }
[[nodiscard]] auto wyxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3100, 4)); }
[[nodiscard]] auto wyxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3101, 4)); }
[[nodiscard]] auto wyxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3102, 4)); }
[[nodiscard]] auto wyxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3103, 4)); }
[[nodiscard]] auto wyyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3110, 4)); }
[[nodiscard]] auto wyyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3111, 4)); }
[[nodiscard]] auto wyyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3112, 4)); }
[[nodiscard]] auto wyyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3113, 4)); }
[[nodiscard]] auto wyzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3120, 4)); }
[[nodiscard]] auto wyzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3121, 4)); }
[[nodiscard]] auto wyzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3122, 4)); }
[[nodiscard]] auto wyzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3123, 4)); }
[[nodiscard]] auto wywx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3130, 4)); }
[[nodiscard]] auto wywy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3131, 4)); }
[[nodiscard]] auto wywz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3132, 4)); }
[[nodiscard]] auto wyww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3133, 4)); }
[[nodiscard]] auto wzxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3200, 4)); }
[[nodiscard]] auto wzxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3201, 4)); }
[[nodiscard]] auto wzxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3202, 4)); }
[[nodiscard]] auto wzxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3203, 4)); }
[[nodiscard]] auto wzyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3210, 4)); }
[[nodiscard]] auto wzyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3211, 4)); }
[[nodiscard]] auto wzyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3212, 4)); }
[[nodiscard]] auto wzyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3213, 4)); }
[[nodiscard]] auto wzzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3220, 4)); }
[[nodiscard]] auto wzzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3221, 4)); }
[[nodiscard]] auto wzzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3222, 4)); }
[[nodiscard]] auto wzzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3223, 4)); }
[[nodiscard]] auto wzwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3230, 4)); }
[[nodiscard]] auto wzwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3231, 4)); }
[[nodiscard]] auto wzwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3232, 4)); }
[[nodiscard]] auto wzww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3233, 4)); }
[[nodiscard]] auto wwxx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3300, 4)); }
[[nodiscard]] auto wwxy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3301, 4)); }
[[nodiscard]] auto wwxz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3302, 4)); }
[[nodiscard]] auto wwxw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3303, 4)); }
[[nodiscard]] auto wwyx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3310, 4)); }
[[nodiscard]] auto wwyy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3311, 4)); }
[[nodiscard]] auto wwyz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3312, 4)); }
[[nodiscard]] auto wwyw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3313, 4)); }
[[nodiscard]] auto wwzx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3320, 4)); }
[[nodiscard]] auto wwzy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3321, 4)); }
[[nodiscard]] auto wwzz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3322, 4)); }
[[nodiscard]] auto wwzw_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3323, 4)); }
[[nodiscard]] auto wwwx_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3330, 4)); }
[[nodiscard]] auto wwwy_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3331, 4)); }
[[nodiscard]] auto wwwz_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3332, 4)); }
[[nodiscard]] auto wwww_() const { return eval<Vector<T, 4>>(Function::current()->swizzle(Type::of<Vector<T, 4>>(), expression(), 0x3333, 4)); }
